### ISSUE TITLE
Icons only displayed in cards, not in lovelance menus

### ISSUE THREAD

**Issue by MarcelKie** [elax46/custom-brand-icons#1]
Hi,
really lov this frontend extension for HA!

I currently have the issue that all of the icons are only shown correctly in the cards I use in lovelance dahsboards but not in the lovelance menus.

I already tried reinstalling but still have this issue - would be nice to have those icons in the menus as well.

Here's a screenshot of the issue:
![image](https://user-images.githubusercontent.com/23638275/118401164-d61ad680-b664-11eb-9bdb-9137e2b5744a.png)

After I click on "Edit" in the lovelance menu, the icons are shown. But as soon as I reload the page, the icons won't show up again until I manually click edit in the menu.

Is there a way to fix this issue?

**Comment by elax46** [comment]
I have already specified it here
https://github.com/elax46/custom-brand-icons#dont-see-the-icon
However, if you do not see the icon follow the second point
https://github.com/elax46/custom-brand-icons#hacs

**Comment by MarcelKie** [comment]
Okay - works now. Thanks for the quick help!

**Comment by elax46** [comment]
😁😁
