### ISSUE TITLE
Custom Icon request [name icon]

### ISSUE THREAD

**Issue by jrspowers** [elax46/custom-brand-icons#101]
hallo 

can you make icons or videoland & streamz ?
[icons](https://mega.nz/folder/2owkDJZA#xrkB98-bJwZ_oNVO54-11g)

**Comment by rchiileea** [comment]
working on a few as we speak
![image](https://user-images.githubusercontent.com/87599807/146338469-775118d8-e715-4463-9035-599f2a83ee7d.png)
![image](https://user-images.githubusercontent.com/87599807/146338498-1fdb896d-7a56-4d38-b131-0be2ae454a7e.png)
![image](https://user-images.githubusercontent.com/87599807/146338542-d24fea47-fe89-4ab7-bf47-3f35846ca387.png)
![image](https://user-images.githubusercontent.com/87599807/146338573-91670474-21cb-45d0-9910-453d84ec856a.png)
![image](https://user-images.githubusercontent.com/87599807/146338623-72ab5c3f-89c1-4146-81ed-3ab537fd23c8.png)
![image](https://user-images.githubusercontent.com/87599807/146338652-34e624bf-c394-46e4-9fc4-45c7a344df64.png)

**Comment by jrspowers** [comment]
@rchiileea thanks man 
@elax46 you thanks to make tis nice icons integration for home assistant

**Comment by elax46** [comment]
> @rchiileea thanks man @elax46 you thanks to make tis nice icons integration for home assistant

there is only to thank @rchiileea

**Comment by jrspowers** [comment]
@rchiileea hey can you also make the vrtnu icon for me ?

[icons](https://mega.nz/folder/2owkDJZA#xrkB98-bJwZ_oNVO54-11g)

**Comment by rchiileea** [comment]
> > @rchiileea thanks man @elax46 you thanks to make tis nice icons integration for home assistant
> 
> there is only to thank @rchiileea

I draw you made the plugin, its not one individual but a team :P


> @rchiileea hey can you also make the vrtnu icon for me ?
> 
> [icons](https://mega.nz/folder/2owkDJZA#xrkB98-bJwZ_oNVO54-11g)

this will be added to the to do list and put in next round of icons

**Comment by elax46** [comment]
the icons will be available in the next update
