### ISSUE TITLE
Telenet TV Box

### ISSUE THREAD

**Issue by jrspowers** [elax46/custom-brand-icons#103]
hey can you make the telenet tv box icon for me ? thanks in advance!

[Telenettvbox](https://mega.nz/folder/2owkDJZA#xrkB98-bJwZ_oNVO54-11g)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/147654011-61c33c97-b2ad-48ef-9b80-7d9b13324e2c.png)

will be added soon

**Comment by jrspowers** [comment]
Nice man thanks@rchiileea
