### ISSUE TITLE
Custom Icon request - Rituals diffuser

### ISSUE THREAD

**Issue by labaland** [elax46/custom-brand-icons#105]
Can someone make a Rituals diffuser icon? :D 
i dont know how to do it :( 

img: https://rituals.scene7.com/is/image/rituals/1103780_WirelessperfumeDiffuserPROA?resMode=sharp2&fmt=png-alpha&wid=1000

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/147653937-fdc99ee4-977f-4f68-b97c-ba6ff5ed6322.png)
will be added soon

**Comment by labaland** [comment]
@elax46 
Icon has wrong name in HA.  t should be: phu:riturals    (( riturals ))

**Comment by elax46** [comment]
Thanks for letting me know, correct name in next version will be updated
