### ISSUE TITLE
Tried contributing, getting weird results

### ISSUE THREAD

**Issue by ultimate-tester** [elax46/custom-brand-icons#107]
**Describe the bug**
I have just finished drawing my first vector image in Illustrator (ever) and managed to get it all in a oneliner for the js file.
Unfortunately in Home Assistant the "fill" and "stroke" attributes are unset, defaulting them to some unexpected color. This is the result in home assistant:

![image](https://user-images.githubusercontent.com/580758/147421178-89918ff4-cb32-493f-be45-d898de2957a9.png)

If I force the fill and stroke attributes in the developer console it looks fine:

![image](https://user-images.githubusercontent.com/580758/147421188-c8d831a7-cdcf-4ee4-9f01-d82b015eb3f1.png)

And here is the original image:

![image](https://user-images.githubusercontent.com/580758/147421203-d6f35cd9-9543-4eaf-abe5-9369c22b3bb1.png)

Am I doing something wrong? How can I draw the vector images in such a way that the fill and stroke attributes are properly kept or how can I prevent the shape from automatically filling the wrong color?

**Comment by rchiileea** [comment]
lines are too thin for a start, but you need to do a stroke trace if its only the stroke you want to see

**Comment by rchiileea** [comment]
Ultimate post the oringinal svg you made, if code is not messed up I can fix it quickly
