### ISSUE TITLE
Dont see custom icons

### ISSUE THREAD

**Issue by MrThiemann** [elax46/custom-brand-icons#108]
**Describe the bug**

I tried to insert a custom icon.

unfortunately it is not displayed to me.
in order to be able to rule out that it is due to my icon, I duplicated an existing one and only changed the name.
Unfortunately, this is not displayed either.

## Don't see the icon?

HA restarted, cache taught, also deactivated in the inspector from the browser cache ...

problem persists: no new icon is displayed

**Comment by elax46** [comment]
could you post some screenshots where you show me how you integrated your icon?

**Comment by rchiileea** [comment]
you can also check something before showing screen shots, if addon is installed, please go to config, devices and services, click any device then under controls section in device page click one entity showing a icon. then under icon type phu: do they show for you here?

**Comment by MrThiemann** [comment]
<img width="1390" alt="Bildschirmfoto 2021-12-28 um 09 30 51" src="https://user-images.githubusercontent.com/54147030/147566315-e09d538c-afcb-4f43-836e-aee9e9e1bf4a.png">


> you can also check something before showing screen shots, if addon is installed, please go to config, devices and services, click any device then under controls section in device page click one entity showing a icon. then under icon type phu: do they show for you here?

i only installed it this morning. So I think I have the latest version =)
The other icons (phu :) are shown to me.
So I can't quite understand the whole thing yet.
<img width="469" alt="Bildschirmfoto 2021-12-28 um 13 32 03" src="https://user-images.githubusercontent.com/54147030/147566612-d6bbcb3b-9d33-4e94-be5a-e0e9e87c7d3f.png">
<img width="472" alt="Bildschirmfoto 2021-12-28 um 13 43 31" src="https://user-images.githubusercontent.com/54147030/147567548-648cfe18-169c-4a4d-96c7-965c73237edd.png">


at first i thought that it was because of my picture (because i also have difficulties integrating the code properly here) but if so then I tried to duplicate the "bulb candle" and call it for me: "bulb test", 
Unfortunately, it is not displayed to me either.
<img width="461" alt="Bildschirmfoto 2021-12-28 um 13 43 24" src="https://user-images.githubusercontent.com/54147030/147567535-142b36fd-39c5-42f7-a0bc-558ad1e7a0c4.png">



`<svg id="Ebene_1" data-name="Ebene 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 590.58 458.76"><defs><style>.cls-1,.cls-2,.cls-5{fill:none;stroke:#000;}.cls-1{stroke-width:6.13px;}.cls-2{stroke-width:5.36px;}.cls-3{fill:#050505;}.cls-4{fill:#1d1d1b;}.cls-5{stroke-width:4.26px;}</style></defs><title>house-5</title><rect class="cls-1" x="288.68" y="231.65" width="76.28" height="59.45"/><line class="cls-2" x1="326.82" y1="231.65" x2="326.82" y2="290.21"/><path d="M39.65,227.32H199.34c.74,0,1.35.84,1.35,1.88s-.61,1.89-1.35,1.89h-7.42v37a.82.82,0,0,1-1.64,0v-37h-8.22v37a.82.82,0,0,1-1.64,0v-37H172.2v37a.78.78,0,0,1-.81.75.79.79,0,0,1-.83-.75v-37h-8.21v37a.82.82,0,0,1-1.64,0v-37h-8.22v37a.82.82,0,0,1-1.64,0v-37h-8.22v37a.82.82,0,0,1-1.64,0v-37h-8.21v37a.83.83,0,0,1-1.65,0v-37h-8.21v37a.82.82,0,0,1-1.64,0v-37h-8.22v37a.82.82,0,0,1-1.64,0v-37H103.2v37a.82.82,0,0,1-1.64,0v-37H93.35v37a.83.83,0,0,1-1.65,0v-37H83.49v37a.83.83,0,0,1-1.65,0v-37H73.63v37a.82.82,0,0,1-1.64,0v-37H63.77v37a.82.82,0,0,1-1.64,0v-37H53.91v37a.82.82,0,0,1-1.64,0v-37H44.05v37a.78.78,0,0,1-.81.75.79.79,0,0,1-.83-.75v-37H39.65c-.74,0-1.34-.85-1.34-1.89S38.91,227.32,39.65,227.32Z" transform="translate(-35.38 -68.37)"/><rect class="cls-3" x="564.6" y="121.41" width="8.79" height="337.34"/><polygon points="564.55 454.02 564.55 458.75 307.21 458.75 307.21 455.61 310.3 455.61 310.3 454.02 564.55 454.02"/><polygon points="568.99 200.23 568.99 204.59 0 204.59 0 201.69 6.84 201.69 6.84 200.23 568.99 200.23"/><rect x="307.21" y="454.02" width="3.09" height="1.58"/><rect x="307.21" y="343.17" width="3.09" height="111.31"/><polygon points="307.21 455.61 307.21 458.75 163.71 458.75 163.71 455.61 172.51 455.61 172.51 454.02 307.21 454.02 307.21 455.61"/><rect x="4.82" y="343.17" width="560.75" height="16.58"/><rect x="163.71" y="454.02" width="8.79" height="1.58"/><rect class="cls-4" x="237.66" y="71.27" width="243.73" height="6.65"/><rect class="cls-3" x="163.76" y="114.65" width="8.79" height="344.11"/><rect class="cls-3" y="201.85" width="8.79" height="157.87"/><rect class="cls-3" x="307.03" y="72.22" width="2.85" height="129.03"/><rect class="cls-3" x="455.6" y="202.36" width="2.85" height="143.9"/><path d="M599.47,194.44,397,82.34,194.46,194.44H168L394.79,68.89a3.49,3.49,0,0,1,2.15-.52,4.63,4.63,0,0,1,2.19.51L626,194.44Z" transform="translate(-35.38 -68.37)"/><rect class="cls-1" x="435.11" y="100.21" width="76.28" height="59.45"/><line class="cls-2" x1="473.25" y1="100.21" x2="473.25" y2="158.77"/><rect class="cls-5" x="220.65" y="100.21" width="42.31" height="51.8"/><polygon points="413.78 450.51 413.78 442.98 405.28 442.98 405.28 438.85 405.31 438.85 405.31 435.42 396.83 435.42 396.83 427.89 388.34 427.89 388.34 420.35 388.32 420.35 388.32 420.33 379.85 420.33 379.85 412.79 371.35 412.79 371.35 405.26 362.86 405.26 362.86 397.8 354.37 397.8 354.37 393.65 354.38 393.65 354.38 390.21 345.89 390.21 345.89 382.68 337.4 382.68 337.4 375.14 337.37 375.14 337.37 375.06 328.89 375.06 328.89 367.53 320.4 367.53 320.4 359.99 310.84 359.99 310.84 363.42 317.57 363.42 317.57 370.96 326.06 370.96 326.06 378.49 327.84 378.49 327.84 378.57 334.57 378.57 334.57 386.11 343.06 386.11 343.06 393.65 344.81 393.65 344.81 393.7 351.53 393.7 351.53 401.23 360.03 401.23 360.03 408.77 368.52 408.77 368.52 416.22 377.01 416.22 377.01 423.76 378.78 423.76 378.78 423.78 385.5 423.78 385.5 431.32 394 431.32 394 438.85 395.72 438.85 395.72 438.88 402.45 438.88 402.45 446.41 410.94 446.41 410.94 453.95 422.26 453.95 422.26 450.51 413.78 450.51"/></svg>`

**Comment by rchiileea** [comment]
code is wrong you need to create a single path like netflix logo has (M 7.538,3.593 V 3.591 3.593 H 7.5 Z M 18.24,2 H 5.76 A 3.759,3.759 0 0 0 2,5.76 V 18.24 A 3.759,3.759 0 0 0 5.76,22 H 18.24 A 3.759,3.759 0 0 0 22,18.24 V 5.76 A 3.759,3.759 0 0 0 18.24,2 Z m -7.51,14.209 a 27.582,27.582 0 0 1 -0.043,3.457 c -0.121,0 -1.178,0.069 -1.53,0.1 -0.23,0.019 -0.692,0.067 -1.027,0.1 C 7.795,19.899 7.517,19.931 7.511,19.924 7.505,19.917 7.5,16.243 7.5,11.754 V 4.588 l 3.234,9.287 z m 5.727,3.718 h -0.014 c -0.057,0 -0.166,-0.011 -0.285,-0.027 -0.742,-0.092 -1.717,-0.176 -2.5,-0.215 -0.26,-0.012 -0.475,-0.025 -0.477,-0.027 -0.002,-0.002 -0.384,-1.081 -1.109,-3.13 L 10.99,13.475 10.736,12.759 v -0.006 0 L 7.5,3.593 v 0 h 3.223 l 0.022,0.06 c 0.007,0.025 0.146,0.415 0.339,0.961 l 0.252,0.711 c 0.092,0.262 0.049,0.142 0.131,0.371 V 5.7 c 1.048,2.959 1.237,3.5 1.516,4.281 v 0 0 l 0.3,0.838 v 0 l 3.206,9.1 a 0.064,0.064 0 0 1 -0.032,0.008 z m 0.04,-1.244 -3.217,-8.97 0.005,-2.5 0.006,-3.61 h 3.2 l 0.006,8.152 c 0.003,2.911 0.003,5.48 0.003,6.928 z)

**Comment by MrThiemann** [comment]
I want to try your code =)
does HA have to be restarted every time I add an icon?

**Comment by rchiileea** [comment]
nope as its front end
but the icon is in the addon anyway that is just the netflix one as an example, it has to be all a single path

**Comment by elax46** [comment]
@MrThiemann  if you have solved the problem I close your request if you have icons to propose they are always welcome you can also open integration requests on the dev version.
