### ISSUE TITLE
Jellyfin Icon request

### ISSUE THREAD

**Issue by juvenalandres** [elax46/custom-brand-icons#109]
https://gist.github.com/LeoVerto/23604847d13fb8fa39733248bf4be12f

Credit to @LeoVerto

**Comment by elax46** [comment]
images with multiple paths are not compatible

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/147812185-c56e212d-94d0-4d27-a9f9-36a8c9000d1a.png)
done this quickly

**Comment by juvenalandres** [comment]
> ![image](https://user-images.githubusercontent.com/87599807/147812185-c56e212d-94d0-4d27-a9f9-36a8c9000d1a.png) done this quickly

Awesome, thanks you
