### ISSUE TITLE
Custom Icon request - Litterbox and Petflap

### ISSUE THREAD

**Issue by DevilsAdjutant** [elax46/custom-brand-icons#110]
Litterbox: https://www.dropbox.com/s/dbqdgbbz2bpq9wq/litterbox.svg?dl=0
Petflap: https://www.dropbox.com/s/8f6gsn3h4ccbk1k/catflap.svg?dl=0

Used for a petflap and a litterbox

**Comment by rchiileea** [comment]
these will be a while as I would like to create a pet flap open and close icon (my one is smart)

**Comment by DevilsAdjutant** [comment]
An open flap or one with a lock on it?

**Comment by rchiileea** [comment]
nope same icon, but one with flap open (and one with flap closed) to indicate lock or unlocked

**Comment by DevilsAdjutant** [comment]
I can do that. Will be later today

**Comment by rchiileea** [comment]
> I can do that. Will be later today

work on your curves and lines, the catflap is all wiggly lines, if using illustrator dont save as, use export as svg, save as does some weird stuff to svg in illustrator

**Comment by DevilsAdjutant** [comment]
Open: https://www.dropbox.com/s/8f6gsn3h4ccbk1k/catflap-open.svg?dl=0
Closed: https://www.dropbox.com/s/hia69e06fm71xnw/catflap-closed.svg?dl=0

**Comment by elax46** [comment]
> Open: https://www.dropbox.com/s/8f6gsn3h4ccbk1k/catflap-open.svg?dl=0 Closed: https://www.dropbox.com/s/hia69e06fm71xnw/catflap-closed.svg?dl=0

the closed version is not compatible the code integrates unsolicited elements and the `path` is multiple

**Comment by DevilsAdjutant** [comment]
Edited the closed version. Please check again.

**Comment by elax46** [comment]
Litterbox is not compatible with `transform` and `scale`

**Comment by DevilsAdjutant** [comment]
Litterbox is corrected

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/147918153-b88bf339-f8d1-44b4-8f36-66eaf07c0ca8.png)
![image](https://user-images.githubusercontent.com/87599807/147918188-4531e7ae-68d4-4657-9734-2150d4047642.png)

**Comment by elax46** [comment]
> Litterbox is corrected

Sorry I got confused with another request

**Comment by elax46** [comment]
> ![image](https://user-images.githubusercontent.com/87599807/147918153-b88bf339-f8d1-44b4-8f36-66eaf07c0ca8.png) ![image](https://user-images.githubusercontent.com/87599807/147918188-4531e7ae-68d4-4657-9734-2150d4047642.png)

oops  @rchiileea I just integrated the icons he had provided us, okay when they are ready we will replace them.

**Comment by rchiileea** [comment]
np @elax46 I just wanted to replace them as the lines were a bit wavy and would not scale up well, I wanted to ensure that is some crazy person was using the icons from package on a larger scale with a magic mirror or something they would look good too.

**Comment by elax46** [comment]
> np @elax46 I just wanted to replace them as the lines were a bit wavy and would not scale up well, I wanted to ensure that is some crazy person was using the icons from package on a larger scale with a magic mirror or something they would look good too.

ok also because in my opinion the most suitable name is pet flap

**Comment by rchiileea** [comment]
no problem with rename at all:)

**Comment by DevilsAdjutant** [comment]
Thanks for integrating, but the litterbox icon appears very small... 
![image](https://user-images.githubusercontent.com/88609445/148226451-c4d98921-24d1-4230-8989-deac54f30519.png)

**Comment by elax46** [comment]
fixed the bug released a pre-release fix
