### ISSUE TITLE
Custom Icon request Laptop and Tablet

### ISSUE THREAD

**Issue by pierinho** [elax46/custom-brand-icons#111]
Laptop: [https://www.dropbox.com/s/pn3vyftv9bk99ax/Laptop.svg?dl=0](https://www.dropbox.com/s/pn3vyftv9bk99ax/Laptop.svg?dl=0)
Laptop-Win: [https://www.dropbox.com/s/tmplmtp3l1qjlm0/Win-Laptop.svg?dl=0](https://www.dropbox.com/s/tmplmtp3l1qjlm0/Win-Laptop.svg?dl=0)
Tablet: [https://www.dropbox.com/s/ckzpzzt65v8lvrt/Tablet.svg?dl=0](https://www.dropbox.com/s/ckzpzzt65v8lvrt/Tablet.svg?dl=0)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/147848614-fb4eb375-0cf7-46b2-aefa-f2e562065a22.png)
![image](https://user-images.githubusercontent.com/87599807/147848618-779a8e33-8c96-43af-a790-5d245332c191.png)
![image](https://user-images.githubusercontent.com/87599807/147848622-191b54d2-49f5-4414-acb9-6ba723d0a45b.png)
![image](https://user-images.githubusercontent.com/87599807/147848638-f39dd918-2a18-4f09-a0cf-b5c181e15f13.png)

**Comment by pierinho** [comment]
Nice work, but , for me, for windows laptop the front view would be nice, as for the normal laptop, but with the windows logo
