### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by mfabiani53** [elax46/custom-brand-icons#115]
Could be useful for smart plug or sockets to have also the "off" icon as actually we have only the "on" icon...

**Comment by elax46** [comment]
how does the icon differ for on or off? the difference can be made by the color rather than by the type of icon an example can be [found here](https://github.com/elax46/custom-brand-icons/issues/107)

**Comment by rchiileea** [comment]
at the end of your card you create, edit in yaml mode

put
state:
  - value: 'on'
  - color <what ever you like here>

this will set color for the icon when on

**Comment by mfabiani53** [comment]
> how does the icon differ for on or off? the difference can be made by the color rather than by the type of icon an example can be [found here](https://github.com/elax46/custom-brand-icons/issues/107)

I mean to have two different icons just as many in the default HA icons. For example smart-plug-on and smart-plug-off or lightbulb-on and lightbulb-off...
Hope to be enough clean....

**Comment by elax46** [comment]
> > how does the icon differ for on or off? the difference can be made by the color rather than by the type of icon an example can be [found here](https://github.com/elax46/custom-brand-icons/issues/107)
> 
> I mean to have two different icons just as many in the default HA icons. For example smart-plug-on and smart-plug-off or lightbulb-on and lightbulb-off... Hope to be enough clean....

It doesn't make sense to have two icons the on / off status is given by the color but not by a different icon @rchiileea  gave you an example on how to do it in yaml

**Comment by rchiileea** [comment]
@elax46  is right on this and I agree, the same could be said for lights too, I agree certain icons need 2 icons, doors, windows, locks etc to show open and closed but on an off  item such as plug sockets, switches and lights just does not make productive sense.
