### ISSUE TITLE
Custom Icon request Underfloor Heating

### ISSUE THREAD

**Issue by olympia** [elax46/custom-brand-icons#116]
[https://www.svgrepo.com/svg/149187/underfloor-heating](url)

Icon for Underfloor Heating

**Comment by elax46** [comment]
[the icon is not compatible](https://github.com/elax46/custom-brand-icons#help-me-insert-more-icons) and[ this](https://github.com/elax46/custom-brand-icons#make-icon)

**Comment by olympia** [comment]
I am confused. The linked icon is downloadable in svg format:
I[https://www.svgrepo.com/download/149187/underfloor-heating.svg](url)

**Comment by elax46** [comment]
however the icon is not compatible it has a multiple and not a single `path`

**Comment by olympia** [comment]
Ah, ok; It looks like I need to dive into this more.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/147915424-f1f81216-a21c-4de4-aabf-ba015b6f25b7.png)
will be added next round

**Comment by olympia** [comment]
This is looking awesome! Many thanks!
