### ISSUE TITLE
Custom Icon request [name icon]

### ISSUE THREAD

**Issue by pierinho** [elax46/custom-brand-icons#117]
Asus RP 68U: [https://www.dropbox.com/s/1orkkwsebi5vmsc/ASUS_RP_68U_1641132752473.svg?dl=0](https://www.dropbox.com/s/1orkkwsebi5vmsc/ASUS_RP_68U_1641132752473.svg?dl=0)
Ubiquiti USG-3P: [https://www.dropbox.com/s/iarkkq86unqim2x/UNIFI-USG-3P_1641132614952.svg?dl=0](https://www.dropbox.com/s/iarkkq86unqim2x/UNIFI-USG-3P_1641132614952.svg?dl=0)
Ubiquiti AP: [https://www.dropbox.com/s/tvsd9p8iaivkk9c/UNIFI_Access_Point_1641132752473.svg?dl=0](https://www.dropbox.com/s/tvsd9p8iaivkk9c/UNIFI_Access_Point_1641132752473.svg?dl=0)
Fritz 7530: [https://www.dropbox.com/s/jgp8ow14bxz4t0c/AVM_Fritz_7530_1641132752473.svg?dl=0](https://www.dropbox.com/s/jgp8ow14bxz4t0c/AVM_Fritz_7530_1641132752473.svg?dl=0)
Fritz Repeater 1200: [https://www.dropbox.com/s/3u8mgw3qf3h8dok/AVM_RP_1200_1641132752473.svg?dl=0](https://www.dropbox.com/s/3u8mgw3qf3h8dok/AVM_RP_1200_1641132752473.svg?dl=0)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/148032030-5af28961-0964-4b14-bebc-3b718000b0ec.png)
![image](https://user-images.githubusercontent.com/87599807/148032090-46169395-7a38-464a-bafe-d4c946dba620.png)
![image](https://user-images.githubusercontent.com/87599807/148032119-820eb3d3-7d0b-4db1-8180-80a24c8ac4d1.png)
![image](https://user-images.githubusercontent.com/87599807/148032138-9dfc7f0f-aeef-4ef2-8ea7-cabe4ee1043f.png)
![image](https://user-images.githubusercontent.com/87599807/148032388-4ea22a44-2255-4cf1-8aa5-404fe68e567b.png)
