### ISSUE TITLE
Custom Icon request-temp outside

### ISSUE THREAD

**Issue by pepsonEL** [elax46/custom-brand-icons#119]
Hi
Is any chance to add to repo icon converted from this URL image ?
https://pl.dreamstime.com/temperaturowa-outside-linii-ikona-image100433538?fbclid=IwAR3FEIoPWcB38KmpAXabVu_aIHgCL0Dx_z9nZFymuhhLOOAtmOPCtBCOFp4

Thanks

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/148115828-c9c3db5b-fcad-44c8-8921-3e1f0da10389.png)
will be done in the next update I am still away on buisness, but @elax46 is still doing the adding

**Comment by elax46** [comment]
> ![image](https://user-images.githubusercontent.com/87599807/148115828-c9c3db5b-fcad-44c8-8921-3e1f0da10389.png) will be done in the next update I am still away on buisness, but @elax46 is still doing the adding

when you can post all the icons in the discussions, I also wrote you a little note

**Comment by pepsonEL** [comment]
It was very very good. I am waiting for it..... Good if it will comming fast.

**Comment by pepsonEL** [comment]
But this PNG you can transorm ?
![NicePng_temperature-icon-png_2975832](https://user-images.githubusercontent.com/71824185/148133885-4c3b892f-b003-45ae-9f04-f4e631040c36.png)
