### ISSUE TITLE
Lovelace main card icon issue(?)

### ISSUE THREAD

**Issue by SAOPP** [elax46/custom-brand-icons#12]
Btw, I faced with issue with display icons in title of card, here is the example of my issue:

![image](https://user-images.githubusercontent.com/5647009/121751817-95a16200-cb17-11eb-90f0-f0db5a379095.png)

As u can see, two icons is missed. it's `rooms-bathroom` and `rooms-living`, time to time this icons is display, but for example at mobile app is never happens, and I had trying incognito in chrome, trying firefox with incognito too, in all modes the same.

I'am more inclined to believe now, after a few days of testing, that this is probably the HA/Lovelace bug, maybe I'm wrong.

For example, now I can try to put 'icon_name' to one of the icons, and probably 99% that they will be displayed again, but then they will disappear after any changes in lovelace... This behavior is strange.

Any suggestions?

**Comment by elax46** [comment]
I verified by doing some tests on the desktop interface the icons you indicated work as an application also to me it was your identical problem but by deleting the application cache the icons are visible again. I don't know if it's a HA issue but I don't think it's always a cache issue

**Comment by elax46** [comment]
unfortunately the icon cannot be integrated as it is made up of several vector segments unfortunately the icon is not integrable as it is composed of several vector segments, to be clearer in your svg file there must be only one string of the type '<path d = "icon" />'

**Comment by umutcelebi** [comment]
I have almost the same issue on mobile. On start i dont see the icons but when i click configure ui they appear and will stay there till i restart the app. So close the app and open the icons are gone again. No issue on pc yet.

**Comment by elax46** [comment]
> I have almost the same issue on mobile. On start i dont see the icons but when i click configure ui they appear and will stay there till i restart the app. So close the app and open the icons are gone again. No issue on pc yet.

clear the application cache

**Comment by elax46** [comment]
Maybe you have some battery saver settings that limit HA

**Comment by umutcelebi** [comment]
Unfortunately already checked that. It seems cache does not help either. I have a samsung galaxy s20 plus. Any idea?

**Comment by elax46** [comment]
I can't tell you it seems strange to me

**Comment by SAOPP** [comment]
Btw, I haven't tested this issue lately, I will to check it, maybe it is "gone"... for me. :)

**Comment by umutcelebi** [comment]
> Btw, I haven't tested this issue lately, I will to check it, maybe it is "gone"... for me. :)

Any update? Cant get it to work on my mobile..

**Comment by SAOPP** [comment]
Just checked, in mobile app I saw empty icon too. :(
