### ISSUE TITLE
Cannot see icons in the interface bar

### ISSUE THREAD

**Issue by chemelli74** [elax46/custom-brand-icons#121]
**Describe the bug**
Cannot see icons in the interface bar.
During configuration:

![image](https://user-images.githubusercontent.com/57354320/148217711-4cae3025-3bc0-4b93-8811-91635b5996a6.png)

After saving:

![image](https://user-images.githubusercontent.com/57354320/148217790-48049e5f-7a14-4f12-98c3-b2d448299605.png)

Already did a "Empty cache and hard refresh" from F12 menu of my Microsoft Edge browser

Non sure if it's related to this package or is a Frontend issue.

## Don't see the icon?

It probably depends on the cache. Open Home assistant from an incognito window and check that the icon loads if yes then it depends on the cache, otherwise double check the installation

**Comment by elax46** [comment]
Have you taken a look at the Pinned issues?  Did you follow the[ instructions](https://github.com/elax46/custom-brand-icons#hacs)? It is essential to include this piece of code

  ```yaml
frontend:
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
```
After the change it is necessary to clear the browser cache

**Comment by chemelli74** [comment]
I'm ashamed not to have noticed :-( 

Thx a lot !!!

Simone
