### ISSUE TITLE
Custom Icon request [Sonos Play:1 and Sonos Arc]

### ISSUE THREAD

**Issue by ND1988** [elax46/custom-brand-icons#122]
Sonos Play:1 --> https://www.dropbox.com/s/nynt6g2rwten4il/Play1.svg?dl=0
Sonos Arc --> https://www.dropbox.com/s/6kjjfnmrlom6tse/Arc.svg?dl=0

Not sure if these templates work out well, I am not into graphic design and used https://picsvg.com/ to convert.
Originals:
Sonos Play:1 --> https://www.dropbox.com/s/nmvuwhdliuq27vf/Play1.jpg?dl=0
Sonos Arc --> https://www.dropbox.com/s/om0m2g9yzzqmdr5/Arc.jpg?dl=0

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/148828846-8ba39737-2ecc-43cd-940f-f35747c060af.png)
tried to recreate the speaker grill, but it does not look right in full size but ok in med and small needs more work

**Comment by elax46** [comment]
@rchiileea Very Cool

**Comment by elax46** [comment]
@rchiileea 👍🏻

**Comment by ND1988** [comment]
@rchiileea wow far better then my approach.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/148901317-d63cbc53-2e16-472a-b7b9-c9bba23a69ca.png)
![image](https://user-images.githubusercontent.com/87599807/148898437-2cbe1454-649d-4be0-b4d1-b0d520b69c52.png)
![image](https://user-images.githubusercontent.com/87599807/148900421-9d032f05-cbfe-45b4-a316-d852533ac34d.png)

we are going to need to beta test this on a beta both versions as one looks messed, up, it might also cause some type of issue as doing a grill like this turns a svg that would normally be about 4000 bytes into and 2 are 1mb plus and one  2mb plus one lol eeek

c looks the best in browser, but I have a feeling b will look the best in home assistant

[sonos-one.zip](https://github.com/elax46/custom-brand-icons/files/7844591/sonos-one.zip)

**Comment by elax46** [comment]
i just released a new beta i haven't updated the documentation but you have sonos-one-a, sonos-one-b, sonos-one-c available 

> ![image](https://user-images.githubusercontent.com/87599807/148898437-2cbe1454-649d-4be0-b4d1-b0d520b69c52.png) ![image](https://user-images.githubusercontent.com/87599807/148900421-9d032f05-cbfe-45b4-a316-d852533ac34d.png) ![image](https://user-images.githubusercontent.com/87599807/148901317-d63cbc53-2e16-472a-b7b9-c9bba23a69ca.png)
> 
> we are going to need to beta test this on a beta both versions as one looks messed, up, it might also cause some type of issue as doing a grill like this turns a svg that would normally be about 4000 bytes into and 2 are 1mb plus and one 2mb plus one lol eeek
> 
> c looks the best in browser, but I have a feeling b will look the best in home assistant
> 
> [sonos-one.zip](https://github.com/elax46/custom-brand-icons/files/7844591/sonos-one.zip)
> 
> lol these also have the single most longest single path I have ever seen in a svg

i just released a new beta i haven't updated the documentation but you have sonos-one-a, sonos-one-b, sonos-one-c available

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/148916063-d873887e-a6f2-41d1-9053-319b2028e49e.png)
zoomed 200%
![image](https://user-images.githubusercontent.com/87599807/148916155-1359da69-ab14-48d7-9d71-87a4f60b3ff4.png)
normal 1280x1080

nnot sure now which one looks best lol

**Comment by elax46** [comment]
actually me too, at first glance I would say better c

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/148916727-9424ee97-965e-4901-a43c-8acaf85c450e.png)
 think b as ion black it looks like this

**Comment by elax46** [comment]
well yes with the color the b is much better

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/148916963-2ea7e263-8695-44fd-907a-d01a925abfe6.png)

**Comment by rchiileea** [comment]
I think b is probaly best choice as it covers plain icons and people who use shaddows on icons

**Comment by elax46** [comment]
> I think b is probaly best choice as it covers plain icons and people who use shaddows on icons

i updated the dev version with only version b

**Comment by ND1988** [comment]
Also I think B is the best suiting one 👍🏻

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/149080915-124427b9-aeda-44c5-ba95-7197760f5c3e.png)
WIP

**Comment by rchiileea** [comment]
above one was hard to do for me, the grill just would not work with same pattern as the sonos one I did not like it, so I had to go down a different route to give it that light bounce effect on the grill
![image](https://user-images.githubusercontent.com/87599807/149215394-a0dd1165-96e4-437d-8ec9-42389dfe4e0e.png)

**Comment by ND1988** [comment]
looks better :) what about if you keep the oval front surface in black, and just try to do a slim white line for the edge of this oval front surface to give the 3D touch?

**Comment by rchiileea** [comment]
> looks better :) what about if you keep the oval front surface in black, and just try to do a slim white line for the edge of this oval front surface to give the 3D touch?

the oval is recieving the same treatmeant as main grill 
![image](https://user-images.githubusercontent.com/87599807/149314044-ccc3f908-770d-4ef6-9d14-5bcc5efe71ee.png)

**Comment by rchiileea** [comment]
right so I am uploading these @elax46  but also uploading these lg ones I have done too

![image](https://user-images.githubusercontent.com/87599807/149325025-b4ff4122-4976-4c31-a2c3-2923d5475b85.png)
![image](https://user-images.githubusercontent.com/87599807/149325072-acc8f9f2-ae43-4603-b226-c2ad49c5e575.png)
![image](https://user-images.githubusercontent.com/87599807/149325100-d62b603a-40d0-442d-9f57-b341cc77ca81.png)
![image](https://user-images.githubusercontent.com/87599807/149325137-90c4a560-2ecf-40e6-a1ae-d8e960b5d09d.png)
![image](https://user-images.githubusercontent.com/87599807/149325175-f4364684-abb5-40d3-98bb-e77491dd8a76.png)
![image](https://user-images.githubusercontent.com/87599807/149325204-ed02e442-c02f-483f-9f24-76624a0e2702.png)
![image](https://user-images.githubusercontent.com/87599807/149325240-d1fca6cc-6a8a-43ae-b631-5fd5d4ad41dd.png)
![image](https://user-images.githubusercontent.com/87599807/149325410-d91a571e-4457-430c-a0a8-0509c119e49c.png)
[sonos-lg-update.zip](https://github.com/elax46/custom-brand-icons/files/7862484/sonos-lg-update.zip)

**Comment by elax46** [comment]
> Collaborator

incredible job

**Comment by rchiileea** [comment]
> > Collaborator
> 
> incredible job

thank you, just wish I had the signiture tv to use the icon :P

**Comment by elax46** [comment]
> > > Collaborator
> > 
> > 
> > incredible job
> 
> thank you, just wish I had the signiture tv to use the icon :P

hahah very expensive

**Comment by rchiileea** [comment]
> > > > Collaborator
> > > 
> > > 
> > > incredible job
> > 
> > 
> > thank you, just wish I had the signiture tv to use the icon :P
> 
> hahah very expensive

you telling me, I thought my oled was pricey lol, but I spent more on my two ultrawides in my office at home tbh.

**Comment by elax46** [comment]
> > > > > Collaborator
> > > > 
> > > > 
> > > > incredible job
> > > 
> > > 
> > > thank you, just wish I had the signiture tv to use the icon :P
> > 
> > 
> > hahah very expensive
> 
> you telling me, I thought my oled was pricey lol, but I spent more than my oled on my two ultrawides in my office at home tbh.

I don't know exactly how much the lg signature costs but I know they cost a lot but qualitatively they are the best oled

**Comment by ND1988** [comment]
> right so I am uploading these @elax46 but also uploading these lg ones I have done too
> 
> ![image](https://user-images.githubusercontent.com/87599807/149325025-b4ff4122-4976-4c31-a2c3-2923d5475b85.png) ![image](https://user-images.githubusercontent.com/87599807/149325072-acc8f9f2-ae43-4603-b226-c2ad49c5e575.png) ![image](https://user-images.githubusercontent.com/87599807/149325100-d62b603a-40d0-442d-9f57-b341cc77ca81.png) ![image](https://user-images.githubusercontent.com/87599807/149325137-90c4a560-2ecf-40e6-a1ae-d8e960b5d09d.png) ![image](https://user-images.githubusercontent.com/87599807/149325175-f4364684-abb5-40d3-98bb-e77491dd8a76.png) ![image](https://user-images.githubusercontent.com/87599807/149325204-ed02e442-c02f-483f-9f24-76624a0e2702.png) ![image](https://user-images.githubusercontent.com/87599807/149325240-d1fca6cc-6a8a-43ae-b631-5fd5d4ad41dd.png) ![image](https://user-images.githubusercontent.com/87599807/149325410-d91a571e-4457-430c-a0a8-0509c119e49c.png) [sonos-lg-update.zip](https://github.com/elax46/custom-brand-icons/files/7862484/sonos-lg-update.zip)

Great job! Thanks!
