### ISSUE TITLE
Custom Icon request [VRT]

### ISSUE THREAD

**Issue by AndyVRD** [elax46/custom-brand-icons#123]
Hi,

Is it possible to create a icon for the Belgium TV channel "VRT"?

[ICON/LOGO](https://www.google.com/search?q=vrt+logo&rlz=1C1GCEB_enBE959BE959&tbm=isch&source=iu&ictx=1&vet=1&fir=ASN5bSsOEs5AjM%252ChIdzVQwdh7x9cM%252C_%253BH-jyV7OKL-1w2M%252CUoHVuBIlvMwo0M%252C_%253BnY5NW1oAKCGj9M%252CuCuFbwtM45XUnM%252C_%253BmKQGSymwnS0rcM%252CyxwTBw0aNGPgYM%252C_%253BfurWvUYtdIWb_M%252Cg7jzaA1xNrBKEM%252C_%253B5yJkPoNEuq679M%252CoA0MKO7iu6j4bM%252C_%253BXis_XFZk4N_WzM%252CyRl8G17-raFHXM%252C_%253BIUn8ctlTEJEV-M%252C3Y5yFq67kF-QfM%252C_%253B8C4dgdSBuiGCDM%252CtzEOuAiIQajxqM%252C_%253BjUyG6ws0TIdNFM%252C2aKYysp9W4fRkM%252C_%253BPBqzujYBZkfe5M%252CosqRNkP-QUAwQM%252C_%253BfKjAtB_RnSI_7M%252C3fKmGGHx8vfp7M%252C_&usg=AI4_-kTs7IWemhfsnH2Oj1e_lIkshn6TYA&sa=X&ved=2ahUKEwizrauv8qn1AhWRjKQKHXIJD1AQ9QF6BAgQEAE&biw=1280&bih=577&dpr=1.5&safe=active&ssui=on)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/149475033-d6375120-189a-49ba-a3c2-6be8a7d5d1d2.png)
`m 11.940707,3.8277836 c -4.4591494,0 -8.0853001,3.5980012 -8.0853001,8.0224574 0,4.424456 3.6261507,8.022457 8.0853001,8.022457 4.456016,0 8.08536,-3.598001 8.08536,-8.022457 V 3.8277836 Z m 2.557019,4.7722382 h 0.911238 c 0.05512,0 0.09961,0.044093 0.09961,0.098467 v 1.0563809 h 1.399721 c 0.0548,0 0.09961,0.044155 0.09961,0.098529 v 0.7394853 c 0,0.05437 -0.04481,0.09847 -0.09961,0.09847 h -1.399721 c 0,0 9.13e-4,1.626863 9.13e-4,1.680926 l -3.16e-4,0.04195 c 0,0.363215 0.208506,0.590375 0.507244,0.590375 0.280262,0 0.480673,-0.198856 0.504158,-0.525098 l 3.78e-4,-0.0038 c 0.01033,-0.09073 0.0698,-0.137352 0.145897,-0.137352 l 0.782868,-3.14e-4 c 0.05417,0 0.09892,0.04289 0.09955,0.09632 3.16e-4,0.0071 3.16e-4,0.01429 3.16e-4,0.02144 0,0.876192 -0.670084,1.587725 -1.553146,1.587725 l -0.0016,-0.0025 c -0.939428,0 -1.596401,-0.683549 -1.597028,-1.702665 V 8.7000812 c 6.26e-4,-0.055927 0.04512,-0.1000594 0.09992,-0.1000594 z m -1.165692,1.1253324 c 0.138271,-0.011015 0.276069,-0.00909 0.410719,0 0.05793,0.00372 0.103005,0.051274 0.103005,0.108755 V 10.57984 c 0,0.06183 -0.05198,0.110624 -0.11399,0.108449 -0.01472,-6.21e-4 -0.0288,-6.3e-5 -0.0432,-3.67e-4 -0.867404,-0.03729 -1.469572,0.652484 -1.499946,1.51314 v 1.388892 l 9.12e-4,-0.0062 v 0.280278 c 0,0.06059 -0.04947,0.109672 -0.110534,0.109672 h -0.889328 c -0.06075,0 -0.110225,-0.0494 -0.110225,-0.109672 V 9.8620941 c 0,-0.060588 0.04947,-0.1096733 0.110225,-0.1096733 h 0.84551 c 0.06106,0 0.110533,0.049086 0.110533,0.1096733 v 0.4722519 c 0.352286,-0.4259787 0.771491,-0.5759451 1.186307,-0.6089918 z m -3.8426904,0.030496 h 0.9268514 v 6.114e-4 c 0.07453,0 0.127773,0.072088 0.105227,0.1426185 L 9.1342296,13.90097 c -0.01441,0.04567 -0.057,0.07642 -0.105226,0.07642 h -1.067812 c -0.04822,0 -0.09051,-0.03075 -0.105226,-0.07642 L 6.4687739,9.8990807 c -0.022546,-0.07053 0.030636,-0.1426186 0.1051642,-0.1426186 h 0.9269135 c 0.04885,0 0.09175,0.031658 0.105843,0.077953 l 0.889329,2.7591069 h 0.01691 l 0.870567,-2.7591069 c 0.01378,-0.046606 0.05699,-0.078566 0.105843,-0.078566 z`

not even my design, just pulled straight from their media logos
