### ISSUE TITLE
Icons not showing - Google Cast

### ISSUE THREAD

**Issue by henlagt** [elax46/custom-brand-icons#124]
When views with custom icons are casted with Google Cast, the icons are not displayed. If I refresh the view, or navigate to another view and then back again the icons are displayed. If the cast is reset the same thing happends again.
Before refresh:
![IMG_0590](https://user-images.githubusercontent.com/30823445/149177297-f21cf108-1703-4bfd-aad1-a22d6d1cdf9a.jpeg)

After refresh:
![IMG_0591](https://user-images.githubusercontent.com/30823445/149177280-109af9ad-106c-47b6-b700-990f08b2a78b.jpeg)

**Comment by elax46** [comment]
Unfortunately it depends on the system cache

**Comment by rchiileea** [comment]
> Unfortunately it depends on the system cache

I think with cast Its just a case of deleteting and re adding the addon for it in home assistant as I had issue with my morgan freeman mp3 files playing until i deleted google cast addon and then re added it.
