### ISSUE TITLE
Custom Icon request Tim Logo and Windows Laptop

### ISSUE THREAD

**Issue by pierinho** [elax46/custom-brand-icons#127]
It's possible to replace the tim-logo, with this one:
[https://www.dropbox.com/s/bazflyhue0gm4ch/tim.svg?dl=0](https://www.dropbox.com/s/bazflyhue0gm4ch/tim.svg?dl=0)
And it's possible to add this another version of windows laptop:
[https://www.dropbox.com/s/j6vhp1xj2nwwlql/winlaptop.svg?dl=0](https://www.dropbox.com/s/j6vhp1xj2nwwlql/winlaptop.svg?dl=0)
Thanks

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/150509180-61c9bbe7-e365-4b89-85dc-7a708ab97642.png)
![image](https://user-images.githubusercontent.com/87599807/150509259-24bf478e-80d4-40b1-9c34-aa3fc838d6b0.png)

will upload when I am back at hotel, I altered the windows one to look more realistic why keeping the direct on approach as I dont think having simular icons with only branding the difference is good

**Comment by rchiileea** [comment]
[winlapandtim.zip](https://github.com/elax46/custom-brand-icons/files/7915426/winlapandtim.zip)
there you go
