### ISSUE TITLE
Custom Icon request: Network Switch

### ISSUE THREAD

**Issue by pierinho** [elax46/custom-brand-icons#129]
Hi, can you make a network switch icon?
Unfortunately I didn't find any svg files to attach to you
Thanks

**Comment by rchiileea** [comment]
havew you not tried the
 ubiquiti-usg-p3 one, or are you thinking something more generic or rack style

**Comment by rchiileea** [comment]
have you tried the phu:ubiquiti-usg-p3

**Comment by rchiileea** [comment]
or just thinking solid with ports no branding

**Comment by pierinho** [comment]
Ubiquiti is not a ethern switch, it's a Gateway. Solid with ports no branding is ok, for me.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/152116431-0bb30673-6169-48ac-bd6b-9b52fc38faca.png)
made it netgear so it can go under netgear brand
