### ISSUE TITLE
Fronius Inverter Gen24

### ISSUE THREAD

**Issue by thecem** [elax46/custom-brand-icons#13]
What icons would you like to see in Custom brand icons?

Fronius

I tried to convert it but don't know how to translate since the svg is a bit complex:

Invert Gen24 modified to black:
```

<svg width="70" height="70" xmlns="http://www.w3.org/2000/svg" data-name="Ebene 1">

 <g>
  <title>Layer 1</title>
  <g id="svg_8">
   <rect id="svg_1" stroke-width="2px" stroke-miterlimit="10" stroke="#000000" fill="none" rx="6.8" height="64" width="58.7" y="3" x="5.65" class="cls-1"/>
   <circle id="svg_2" stroke-miterlimit="10" stroke="#000000" fill="none" r="11" cy="29.61" cx="35.03" class="cls-2"/>
   <circle id="svg_3" stroke-miterlimit="10" stroke="#000000" fill="none" r="4" cy="40" cx="15" class="cls-2"/>
   <path id="svg_4" fill-rule="evenodd" stroke-miterlimit="10" stroke="#000000" fill="none" d="m40.19,52l-3.46,0a2,2 0 0 0 -3.46,0l-3.46,0a1.08,1.08 0 1 0 0,2.15l3.46,0a2,2 0 0 0 3.46,0l3.46,0a1.08,1.08 0 1 0 0,-2.15z" class="cls-3"/>
   <path stroke="#000000" id="svg_5" fill="#000000" fill-rule="evenodd" d="m34.89,61.87c-3.24,0 -5.87,-0.73 -5.87,-1.62s2.63,-1.64 5.87,-1.64s5.87,0.74 5.87,1.64s-2.63,1.62 -5.87,1.62z" class="cls-4"/>
   <line id="svg_6" stroke-miterlimit="10" stroke="#000000" fill="none" y2="53.08" x2="28.73" y1="53.08" x1="5.07" class="cls-2"/>
   <line id="svg_7" stroke-miterlimit="10" stroke="#000000" fill="none" y2="53.08" x2="64.93" y1="53.08" x1="41.27" class="cls-2"/>
  </g>
 </g>
</svg>
```

Original inverter-gen24.svg:
```
<svg id="Ebene_1" data-name="Ebene 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 70 70"><defs><style>.cls-1,.cls-2,.cls-3{fill:none;stroke:#666;stroke-miterlimit:10;}.cls-1{stroke-width:2px;}.cls-3,.cls-4{fill-rule:evenodd;}.cls-4{fill:#e2001a;}</style></defs><rect class="cls-1" x="5.65" y="3" width="58.7" height="64" rx="6.8"/><circle class="cls-2" cx="35.03" cy="29.61" r="11"/><circle class="cls-2" cx="15" cy="40" r="4"/><path class="cls-3" d="M40.19,52H36.73a2,2,0,0,0-3.46,0H29.81a1.08,1.08,0,1,0,0,2.15h3.46a2,2,0,0,0,3.46,0h3.46a1.08,1.08,0,1,0,0-2.15Z"/><path class="cls-4" d="M34.89,61.87c-3.24,0-5.87-.73-5.87-1.62s2.63-1.64,5.87-1.64,5.87.74,5.87,1.64S38.13,61.87,34.89,61.87Z"/><line class="cls-2" x1="5.07" y1="53.08" x2="28.73" y2="53.08"/><line class="cls-2" x1="41.27" y1="53.08" x2="64.93" y2="53.08"/></svg>
```

Which app do you recommend?

THANKS A LOT!

**Comment by elax46** [comment]
if you give me a link of the icon, let's see if I can integrate it!

**Comment by elax46** [comment]
I have saved the original, as soon as it is ready I complete it!

**Comment by elax46** [comment]
unfortunately the icon is not integrable as it is composed of several vector segments, to be clearer in your svg file there must be only one string of the type '<path d = "icon" />'

**Comment by thecem** [comment]
yes this is the problem, i don't know how to fix this. Could you give me some information with which tool I could generate icons that meet the requirements?

**Comment by elax46** [comment]
There is little you can do very much depends on the creator of the vector
you can only find an alternate icon or recreate it from scratch

Il Sab 12 Giu 2021, 16:41 thecem ***@***.***> ha scritto:

**Comment by thecem** [comment]
tried a icon, but nothing appears.
tried to copy a icon out of the file to a one with a new name:

```
,
        "bulbs-test":[0,0,24.0,24.0,"M22 22v-2H2v2zm-2-4a-8-8 0 0 0-4-6.927V9c0-1.108-.892-2-2-2h-4c-1.108 0-2 .892-2 2v2.072A-8-8 0 0 0 4 18h8zM15 5V2h-2v3zm-4 0V2H9v3z"]
      };
```

not working, what should i do?

**Comment by thecem** [comment]
I had to shange in lovelace resources /hacsfile/* to /local/community/* to load the js not the gz.

**Comment by elax46** [comment]
is specified [README](https://github.com/elax46/custom-brand-icons#hacs) if you integrate new icons it creates a pull request by pasting the svg icon code as well so we make it available to everyone, thanks

**Comment by labaland** [comment]
> is specified [README](https://github.com/elax46/custom-brand-icons#hacs) if you integrate new icons it creates a pull request by pasting the svg icon code as well so we make it available to everyone, thanks. please pay attention to the dimensions if not correct the icon will not be well centered on the card

Noob here, I have ok skillz in illustrator. Is that the program to create svg icons? If yes, can u share a template?

**Comment by elax46** [comment]
Si illustrator is the right program. I believe google can be of help to you. I'll point out some resources that seem useful to me.

- [How to Create Great SVG Icons & a Checklist for Success](https://medium.com/yext-design/how-to-create-great-svg-icons-a-checklist-for-success-f255bd7f1344)
- [Creating an SVG Icon](https://www.bitovi.com/blog/creating-an-svg-icon-typeface)
- [How to create SVG](https://uxdesign.cc/how-to-create-an-svg-ready-icon-library-in-sketch-a95e1a163a27)

**Comment by elax46** [comment]
I have integrated the icon!
