### ISSUE TITLE
Official Icon request Missing Hue icons

### ISSUE THREAD

**Issue by francois-pasquier** [elax46/custom-brand-icons#133]
From the [official hue icon pack](https://developers.meethue.com/develop/application-design-guidance/icon-pack), some icons are missing.

Could you include those?

- otherReading
- otherWatchingMovie
- roomsFrontdoor
- tabbarHome
- zoneAreasFirstfloor
- zoneAreasGroundfloor
- zoneAreasSecondfloor

Please note that despite their name, all of these icons are available for rooms in the official philips hue app.

**Comment by elax46** [comment]
Thanks for this request I just updated the icons, philips updated the icon pack to 2019 recently. If you notice any other icons missing it opened other requests
