### ISSUE TITLE
Custom Icon request [stove-vent]

### ISSUE THREAD

**Issue by bcutter** [elax46/custom-brand-icons#135]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
Please provide the following files (named PNG but they are SVGs):
- https://cdn2.iconfinder.com/data/icons/electronic-devices-43/512/Hood_kitchen_range_hood_rangehood-512.png
as "stove-vent"
- https://cdn2.iconfinder.com/data/icons/kitchen-utensils-25/64/123-512.png
as "stove-vent-2" or whatever the "alternative icon" naming convention is
- https://cdn0.iconfinder.com/data/icons/home-and-garden/64/kitchen-stove-appliance-hood-1024.png
as another alternative

**Additional context**
Icons should be free, no copyright listed (found using picture search for "stove vent")

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/152523656-e5ac28d8-2e90-4938-a7bd-c498ca2b5ebe.png)
![image](https://user-images.githubusercontent.com/87599807/152523710-5d62c100-4cf3-472c-91ee-2844f18983f2.png)
