### ISSUE TITLE
Custom Icon request [Open/Closed Sign]

### ISSUE THREAD

**Issue by Firerouge** [elax46/custom-brand-icons#136]
[Example open sign svg](https://www.iconspng.com/clipart/neon-open-sign-from-glitch/neon-open-sign-from-glitch.svg)
![neon-open-sign-from-glitch](https://user-images.githubusercontent.com/9072079/152484325-1ecf566b-9a49-4d70-be0a-0478f2b1a70b.svg)

Lots of creative freedom available here. Quite a few [font](https://neonsign.com/wp-content/uploads/2020/02/Closed-with-pink-border-Neon-Sign_13x32-Black-Backing.jpg), [style](https://centurion-inc.com/wp-content/uploads/2016/07/7060110.png), and [designs](https://ae01.alicdn.com/kf/HTB1MKpBXu6sK1RjSsrbq6xbDXXaQ/CHENXI-Open-Closed-2-in-1-LED-Sign-Store-Neon-Business-Shop-Open-Closed-Advertising-Light.jpg) around to model after, as well potentially the [hanging flip over type](https://slm-assets.secondlife.com/assets/18324905/view_large/OPEN_CLOSED_WINDOW_SIGN.jpg?1505153710) signs.

Could potentially use both a turned on (illuminated) and turned off variant of both

**Comment by rchiileea** [comment]
how about like a proper neon sign not a turnable one
![image](https://user-images.githubusercontent.com/87599807/152528333-e6ed8fce-9570-45e1-aace-426c7d9fa006.png)
![image](https://user-images.githubusercontent.com/87599807/152528455-15a1ed39-2a16-420f-94ba-1c01fbb4f077.png)

**Comment by Firerouge** [comment]
Generic and generally applicable in one design, nice @rchiileea 👍

**Comment by rchiileea** [comment]
I thought as a sign neon style would work better due to the nature of them having both closed and open on the same side.

**Comment by Firerouge** [comment]
> I thought as a sign neon style would work better due to the nature of them having both closed and open on the same side.

Good thought, it also opens up the potential for a neon category, I imagine that others might desire '(NO) VACCANCY', as well as SALE, CLEARANCE, 24/7, and other common restaurant/retail ones that could be put on a smart outlet.

**Comment by rchiileea** [comment]
Well that was not final, that was just the general idea, here is the final one
![image](https://user-images.githubusercontent.com/87599807/152632648-6551c6e7-28f8-4eed-a513-89f485de75b4.png)
![image](https://user-images.githubusercontent.com/87599807/152632662-5f00468a-f573-4e44-806f-52458dbf5e90.png)

with true neon effect

**Comment by Firerouge** [comment]
> Well that was not final, that was just the general idea, here is the final one ![image](https://user-images.githubusercontent.com/87599807/152632648-6551c6e7-28f8-4eed-a513-89f485de75b4.png) ![image](https://user-images.githubusercontent.com/87599807/152632662-5f00468a-f573-4e44-806f-52458dbf5e90.png)
> 
> with true neon effect once they are added, ill make a code for them to use with custom button card so they truely do look neon like on dashboard.

Very cool, taking it to the next level, this'll definitely need it's own neon category to highlight that and expand upon

**Comment by Firerouge** [comment]
Already looking pretty great by default in my theme @rchiileea 
![neon-open](https://user-images.githubusercontent.com/9072079/152926287-8a1bbe2c-2ce8-4f1c-ae1c-db15a70ceae8.png)

**Comment by rchiileea** [comment]
![neon](https://user-images.githubusercontent.com/87599807/152937839-6c343328-1da3-45bc-bd4b-59c972524200.gif)
```
entity:  (your entity here)
icon: phu:neon-closed
color: '#FFFF8A'
name: test

# adjust bellow for glow colors

extra_styles: |
  @keyframes pulse {
    0% {
       -moz-filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF00);
       filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF00);
    }
    10% {
        -moz-filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF8A);
        filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF8A);
    }
    20% {
       -moz-filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF00);
       filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF00);
    }
    30% {
        -moz-filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF8A);
        filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF8A);
    }
    40% {
        -moz-filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF00);
        filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF00);
    }
    50% {
      -moz-filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF8A);
      filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF8A);
    }
    60% {
      -moz-filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF00);
      filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF00);
    }
    70% {
      -moz-filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF8A);
      filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF8A);
    }
    80% {
      -moz-filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF00);
      filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF00);
    }
    90% {
      -moz-filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF8A);
      filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF8A);
    }
    100% {
      -moz-filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF00);
      filter: contrast(96%) drop-shadow(3px 3px 10px #FFFF00);
    }
  }
size: 70%
tap_action:
  action: toggle
  haptic: light
hold_action:
  action: more-info
  haptic: medium

# adjust bellow for styling

styles:
  img_cell:
    - padding-left: 44px
    - justify-content: start
  card:
    - width: min(25vw, 240px)
    - height: min(25vw, 240px)
    - border-style: solid
    - border-width: 0px
    - border-color: '#0060FF'
    - border-radius: 20px
  icon:
    - color: '#FFFF8A'
    - '-webkit-filter': contrast(96%) drop-shadow(3px 3px 3px rgba(0,0,0,0.95)
state:
  - value: 'on'
    icon: phu:neon-open
    color: '#FFFF8A'
    styles:
      icon:
        - animation: pulse 10s infinite
      card:
        - box-shadow: var(--soft-ui-pressed)
show_state: true
card_mod:
  class: null
type: custom:button-card

```
