### ISSUE TITLE
Custom Icon request for window tilt

### ISSUE THREAD

**Issue by RoYaL69** [elax46/custom-brand-icons#142]
Can you add a tilt please? my windows got 3 states, open, closed, and tilted.

**Comment by rchiileea** [comment]
image of window please

**Comment by elax46** [comment]
If you do not give us a reference image it is not possible to make the icon @RoYaL69

**Comment by RoYaL69** [comment]
Sorry, I do not have the exact Icons and I am not familiar with the creation of Icons but I mean something like this.
![image](https://user-images.githubusercontent.com/10222781/157874030-cd7b08c6-45a5-45a3-bbc7-af615c997fcc.png)

I hope this helps to explain what I mean or did you want the Icons from me?

**Comment by rchiileea** [comment]
cheers give me a week

**Comment by rchiileea** [comment]
sorry about the late reply been so busy with work

![image](https://user-images.githubusercontent.com/87599807/159155386-98c08829-6df7-410c-8fe5-54dd07fda27c.png)
![image](https://user-images.githubusercontent.com/87599807/159155391-91d6c3fd-c0bb-420b-9ef8-291e163b0fea.png)
![image](https://user-images.githubusercontent.com/87599807/159155402-15d350b8-3d80-4e74-ac0a-947b4a0524dc.png)

**Comment by rchiileea** [comment]
[lift-in.zip](https://github.com/elax46/custom-brand-icons/files/8310899/lift-in.zip)
