### ISSUE TITLE
Custom Icon request Bitwarden icon

### ISSUE THREAD

**Issue by marcis92** [elax46/custom-brand-icons#144]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://github.com/bitwarden/brand/blob/master/icons/icon.svg

**Additional context**
Hi, could you please add the mentioned bitwarden logo to the repo?
If the linked icon does not fit, there are more in the official bitwarden repo: https://github.com/bitwarden/brand/tree/master/icons

Thanks in advance!

**Comment by elax46** [comment]
The icon will be available in the next update
