### ISSUE TITLE
Custom Icon request [NetApp Logo]

### ISSUE THREAD

**Issue by samuelmcconnell** [elax46/custom-brand-icons#145]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://www.dropbox.com/s/9nabfk4xvaprkrm/netapp.svg?dl=1

**Additional context**
About as simple an SVG as you get, only 145 bytes.

**Comment by rchiileea** [comment]
will do but maybe 2 weeks as I am working on a project for show.

**Comment by elax46** [comment]
> will do but maybe 2 weeks as I am working on a project for show.

already done this!
