### ISSUE TITLE
Custom Icon request Movistar

### ISSUE THREAD

**Issue by ciltocruz** [elax46/custom-brand-icons#146]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Movistar_Plus%2B_2022_logo.svg/640px-Movistar_Plus%2B_2022_logo.svg.png

**Additional context**
Movistar is a Spanish television application (like Netflix, HBO, Amazon Prime Video...)

**Comment by elax46** [comment]
> **Insert a link to an SVG icon the integrable icons are ONLY in SVG format** https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Movistar_Plus%2B_2022_logo.svg/640px-Movistar_Plus%2B_2022_logo.svg.png
> 
> **Additional context** Movistar is a Spanish television application (like Netflix, HBO, Amazon Prime Video...)

You have entered the Movistar plus non Movistar logo as a reference, whichever you mean

**Comment by rchiileea** [comment]
be clear, but I am 2 weeks off being able to do any icons personally as working on a show pc.

**Comment by ciltocruz** [comment]
Movistar has had many names in its history. Now it is called "Movistar Plus+". The logo is the one I indicated.
https://en.wikipedia.org/wiki/Movistar_Plus%2B

**Comment by rchiileea** [comment]
will be back home at editing pc next week

**Comment by myde2001** [comment]
This is the new official logo of movistar: [https://upload.wikimedia.org/wikipedia/commons/3/3d/Movistar_2020_logo.svg](https://upload.wikimedia.org/wikipedia/commons/3/3d/Movistar_2020_logo.svg)

Movistar+ is a separate brand from Movistar that offers paid television channels

**Comment by ciltocruz** [comment]
`Movistar is a spanish carrier` --> Correct.
But my request is about Movistar's paid streaming service (such as Netflix, Amazon Prime), which is called `Movistar +`

Perhaps the name of the issue is not the best, but in my first message I made it clear that I was referring to the television channel service.

If you want to add the 2, for me there is no problem.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/165457015-be1097b0-ba77-4cfa-861d-a0bfbba17dee.png)
![MOVIESTAR PLUS](https://user-images.githubusercontent.com/87599807/165457031-9100f05d-b071-4bf6-8672-726d09842c5c.svg)
