### ISSUE TITLE
Custom Icon request [vtm go & telenet tv app ]

### ISSUE THREAD

**Issue by jrspowers** [elax46/custom-brand-icons#147]
hallo 

can you make icons or vtm go & telenet tv app?
[icons](https://mega.nz/folder/2owkDJZA#xrkB98-bJwZ_oNVO54-11g)

**Comment by rchiileea** [comment]
will be done some time next week I will be back at pc at home by then

**Comment by jrspowers** [comment]
good no problem thanks in advance!

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/165456655-103fa7dd-32bc-4df5-a652-03ea2cea5706.png)
![VTM](https://user-images.githubusercontent.com/87599807/165456772-572c2b36-a726-46a2-9153-b1cc7b1ed6e7.svg)
![image](https://user-images.githubusercontent.com/87599807/165456848-c715d6b8-be34-465d-b37b-25abc81caa74.png)
![TELNET](https://user-images.githubusercontent.com/87599807/165456859-07530497-d93a-4b00-8d02-51ec5a9400f5.svg)

**Comment by jrspowers** [comment]
very nicely done man
