### ISSUE TITLE
Icons not shown, Error in console

### ISSUE THREAD

**Issue by mutzl** [elax46/custom-brand-icons#15]
All of a sudden the phu:* icons don't work anymore for my configuration.
Same for Edge, Chrome, Fire Tablets.

F12 Dev Tools show me an error: 
```
Uncaught (in promise) TypeError: Cannot read property '4' of undefined
    at getIcon (custom-brand-icons.js:87)
```
![image](https://user-images.githubusercontent.com/2855185/121884901-c5b55480-cd13-11eb-9fdd-90f84d84d5db.png)

Custom brand icons: V 1.0.3 (installed via HACS)
HA core-2021.6.4

**Comment by elax46** [comment]
it's a problem with your home assistant setup. I recommend you uninstall and reinstall the compose. Everything works fine on the HA core-2021.6.4 version

**Comment by mutzl** [comment]
Posting _Everything works fine_ and closing the issue after 2 hours is for sure a valid possibility. 

Responding _did you upgrade the library recently? Have you noticed, that there is a change in the naming convention of the icon names, causing almost all the names to become invalid?_ would be even more helpful... 


For all the others searching for the same error message: most likely you have a typo in the icon name caused by a change in the library.

**Comment by elax46** [comment]
It is not about closing the request after two hours dear. The variation of the icon names has been included in the release notes referring to README.md. If you don't see the changes when you update, it's certainly not up to me. Having said this peace and love

**Comment by mutzl** [comment]
created PR to log wrong icon names.
