### ISSUE TITLE
Custom Icon request [HBO/HBO MAX]

### ISSUE THREAD

**Issue by Dilergore** [elax46/custom-brand-icons#151]
Hi,

Would be great to have icons for HBO / HBO Max like:

- https://logotyp.us/logo/hbo-max/ | https://commons.wikimedia.org/wiki/File:HBO_Max_Logo.svg
- https://upload.wikimedia.org/wikipedia/commons/d/de/HBO_logo.svg

Thanks!

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/165692787-21af75b6-39dd-42bb-818a-62739c3a928b.png)
![image](https://user-images.githubusercontent.com/87599807/165692843-329d316e-7372-49fd-92b5-aa0d3c43e179.png)
[hbo.zip](https://github.com/elax46/custom-brand-icons/files/8580178/hbo.zip)

combined the max to bottom, why it sort of brings it like older logo it would look very small stretched out as one word

**Comment by Dilergore** [comment]
thanks :) This was very fast :)
