### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by GunterAv** [elax46/custom-brand-icons#153]
Hello,

I have created three icons, if you want you can install them:

![Sideboard](https://user-images.githubusercontent.com/87611027/166096958-327fc533-95e4-425b-9938-11488bf86436.jpg)

![Sideboard](https://user-images.githubusercontent.com/87611027/166096981-bc8e9e0f-cd18-4b76-b3d2-793232b21999.svg)

![Deckenfluter](https://user-images.githubusercontent.com/87611027/166096988-9c9e0787-d9f2-4b65-977a-5285bc3d6e6a.jpg)

![deckenfluter](https://user-images.githubusercontent.com/87611027/166096993-71b46c50-08b9-4544-82dc-655e92c6c2e3.svg)

![leselampe-wz](https://user-images.githubusercontent.com/87611027/166096999-4ebc648b-102f-4d48-a305-1fd2780489c4.svg)

Best regards
Gunter

**Comment by elax46** [comment]
what name should we give to the three lamps?

**Comment by GunterAv** [comment]
Hello 

1. Sideboardlamp
2. Floor uplighter 
3. Floor uplighte with reading lamp

[GA-lamps.zip](https://github.com/elax46/custom-brand-icons/files/8597112/GA-lamps.zip)

Best regards
Gunter

**Comment by rchiileea** [comment]
table-cylinder-lamp
uplighter
2-way-uplighter
