### ISSUE TITLE
Custom Icon request [Familie-vtm & Lisa-vtm ]

### ISSUE THREAD

**Issue by jrspowers** [elax46/custom-brand-icons#156]
hallo 

can you make icons or Familie-vtm & Lisa-vtm?
[icons](https://mega.nz/folder/2owkDJZA#xrkB98-bJwZ_oNVO54-11g)

**Comment by rchiileea** [comment]
I am confused by these vtm requests, just wondering how you need so many icons  with vtm, they are not hard to do, but I am just thinking overal so many vtm ones.

**Comment by jrspowers** [comment]
I am making dashboard map for me telenet tv box and hence the vtm family and vtm lisa but this will be the last request from vtm?

**Comment by rchiileea** [comment]
you need to supply better versions, these are not complete, down load them and open them, they look very off

**Comment by jrspowers** [comment]
I have added new icons with number 1 are the new ?

**Comment by rchiileea** [comment]
Hey Jrs Powers I am sorry but having looked for better icons, I am not sure we should intergrate these icons as they are not even a brand, item or app but rather tv shows and that would be branching off too far from the project.

**Comment by jrspowers** [comment]
ok good very sorry but understand
