### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by techies1400** [elax46/custom-brand-icons#159]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://appimage.github.io/database/Moonlight/icons/scalable/moonlight.svg
https://upload.wikimedia.org/wikipedia/commons/d/db/Deezer_logo.svg
https://www.justwatch.com/appassets/img/home/logo.svg

**Additional context**

**Comment by techies1400** [comment]
And if you can put a icon like the "pendant-long" but without the ceiling cord it could be great for LED surface linear lights

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/167888703-20cd3779-ec78-46a8-8708-f9902f973e5c.png)
![image](https://user-images.githubusercontent.com/87599807/167888761-f1e1fc53-f651-498c-bcf4-8ec8a5dd3dc7.png)
![image](https://user-images.githubusercontent.com/87599807/167888839-e6c73a2d-8121-45c9-9d16-ed7f696ddf93.png)

**Comment by techies1400** [comment]
Hi, they look fine! how I configure they on my haos? I have to modify the files?

**Comment by rchiileea** [comment]
no, once the update has been pushed to custom brand icons, just in icon selector put phu: then browse the list

**Comment by elax46** [comment]
> Hi, they look fine! how I configure they on my haos? I have to modify the files?

the update is [now available](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.57)
