### ISSUE TITLE
New icon request

### ISSUE THREAD

**Issue by MCHellspawn** [elax46/custom-brand-icons#160]
Requesting an icon for Paramount+ please.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/167888985-1c1e735e-b294-4784-9794-9356964a3c6b.png)

**Comment by rchiileea** [comment]
[paramount.zip](https://github.com/elax46/custom-brand-icons/files/8671365/paramount.zip)
