### ISSUE TITLE
Infuse Pro

### ISSUE THREAD

**Issue by danielclindsay** [elax46/custom-brand-icons#162]
[[[**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
](https://www.figma.com/file/kW1VsOIct7yUjR9GmNrAt6/Infuse_Pro?node-id=0%3A1)
**Additional context**
Media player for AppleTV

**Comment by rchiileea** [comment]
![Infuse-Pro](https://user-images.githubusercontent.com/87599807/168110233-e5f521ba-51c5-4be1-bc13-cbdac0b976cf.svg)
[Infuse-Pro.zip](https://github.com/elax46/custom-brand-icons/files/8680476/Infuse-Pro.zip)
