### ISSUE TITLE
 TV Gen 2 Siri Remote

### ISSUE THREAD

**Issue by danielclindsay** [elax46/custom-brand-icons#171]
https://www.figma.com/file/kW1VsOIct7yUjR9GmNrAt6/HA_Icons?node-id=0%3A1

I couldn't find one in your current pack, feel free to pull this apart if you need to. 

Thanks

**Comment by danielclindsay** [comment]
@rchiileea I use it on HA as my navigation, source switcher, audio switcher, basically everything in a singular media panel, but its base is the Apple TV remote, so want the icon instead of the standard mdi remote icon.

**Comment by rchiileea** [comment]
I was going to do this, but the link your provided is to read only, so they cant be saved and adapted, they litrally save as 0kb files due to being read only.

**Comment by danielclindsay** [comment]
@rchiileea Hey hey,
Figma will be read-only unless I pay for you to be an editor. You should be able to export though or duplicate if you have Figma yourself :D I have also attached my version but feel free to change and update as you need to my dude. 

Thanks 
![ATV-Siri-Remote](https://user-images.githubusercontent.com/65338509/172550550-95194783-0583-4470-9c07-ae9dd3a3b363.svg)

**Comment by danielclindsay** [comment]
@elax46 @rchiileea do you need anything more from me on this one? Happy to help where I can 👍

**Comment by elax46** [comment]
@elax46  takes care of the icon but apart from this the icon is not downloadable even when accessing Figma the icon cannot be exported

**Comment by danielclindsay** [comment]
@elax46 Thanks for the clarification

I have retoggled this sharing setting to see if it kicks in and the link is shared below for your convenience. 

https://www.figma.com/file/kW1VsOIct7yUjR9GmNrAt6/HA_Icons?node-id=0%3A1


![Uploading CleanShot 2022-06-10 at 16.04.27@2x.jpg…]()

**Comment by danielclindsay** [comment]
![CleanShot 2022-06-10 at 18 19 52@2x](https://user-images.githubusercontent.com/65338509/173118614-5ee58eef-c8fe-401b-b3f4-ad3e6bbb3fd6.jpg)
@elax46 Thanks for checking but all the icons are a single path no? 

I had exported it and included it in a comment above too as an icon?

Here is the link to that comment too. It is at the bottom of the message. 
https://github.com/elax46/custom-brand-icons/issues/171#issuecomment-1152382719

**Comment by elax46** [comment]
@rchiileea for yoy
![24 x 24](https://user-images.githubusercontent.com/55278049/173122486-9ef6f5da-dc7d-4023-bf66-c68dbe3ee377.svg)

**Comment by rchiileea** [comment]
i can get them now, will be done by end of the week

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/173766939-ff10d610-5892-427b-86b0-b12d22c2a4fb.png)
