### ISSUE TITLE
Custom Icon request: Emby

### ISSUE THREAD

**Issue by gthrift** [elax46/custom-brand-icons#172]
Request for Emby Icon

![Emby Logo](https://user-images.githubusercontent.com/4450552/170149402-b40c8555-63bd-4fad-bd69-fe6606b0b35f.svg)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/172305535-91e125e9-dd94-43f7-8ceb-66e4df6b5e4a.png)
