### ISSUE TITLE
Custom Icon request ESPN, YouTube TV, 

### ISSUE THREAD

**Issue by gthrift** [elax46/custom-brand-icons#173]
ESPN - 
![ESPN_E_icon](https://user-images.githubusercontent.com/4450552/170550262-a031f179-b614-4bfa-902c-a3a2ced73be7.svg)

YouTube TV -
![youtube-tv](https://user-images.githubusercontent.com/4450552/170550053-e06d336b-c764-466d-b7df-f9bbd8ca5f31.svg)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/172303797-716725fd-c3e7-4e38-85d8-c33dc2834997.png)
![image](https://user-images.githubusercontent.com/87599807/172303900-ab14b9d3-3fe5-4d55-bc0f-22a0bb3aa012.png)
