### ISSUE TITLE
Custom Icon requests: TiVo, Peacock, VUDU

### ISSUE THREAD

**Issue by brandoningli** [elax46/custom-brand-icons#174]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
**TiVo**
![TiVo_logo_2011_RGB](https://user-images.githubusercontent.com/6826623/171771800-2ccb71fb-ad27-4c45-95ae-5afcc52eeb15.svg)

**Peacock**
![Peacockicon](https://user-images.githubusercontent.com/6826623/171771809-e5c4e178-497e-43f3-8876-ff230aa14f7e.svg)

**VUDU**
![Vudu_2014_logo](https://user-images.githubusercontent.com/6826623/171771816-0b6f13fc-10da-4809-98b6-45d771ce6e3b.svg)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/172304070-93aa505b-58e9-4bed-a3c6-23f14945575f.png)
![image](https://user-images.githubusercontent.com/87599807/172304115-185e4951-0f1e-468c-afa7-1ca6f153368d.png)
![image](https://user-images.githubusercontent.com/87599807/172304825-cbaf54a7-c9dc-416c-87d7-426d0b3d7995.png)
