### ISSUE TITLE
Custom Icon request Nuki

### ISSUE THREAD

**Issue by Sim0cYz** [elax46/custom-brand-icons#179]
Hello! I just purchased a Nuki Smart Lock 3.0, I noticed that an icon for this item is missing :)

**Comment by elax46** [comment]
> Nuki Smart Lock 3.0

you can post a svg picture thank you

**Comment by Sim0cYz** [comment]
![nuki](https://user-images.githubusercontent.com/102484565/172708921-2c912e40-ac15-406a-bc34-8aa3b6a82eff.svg)

something like this?

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/173766786-32242ca7-85eb-4a6c-872e-32321c608866.png)
