### ISSUE TITLE
Custom Icon request "sultan group alt"

### ISSUE THREAD

**Issue by HunterX86** [elax46/custom-brand-icons#187]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
[bulb-group-sultan-3-alt.zip](https://github.com/elax46/custom-brand-icons/files/8917383/bulb-group-sultan-3-alt.zip)

**Additional context**
Can you please use my custom made icons to make it a svg icon and add it to your repository?

**Comment by elax46** [comment]
> **Insert a link to an SVG icon the integrable icons are ONLY in SVG format** [bulb-group-sultan-3-alt.zip](https://github.com/elax46/custom-brand-icons/files/8917383/bulb-group-sultan-3-alt.zip)
> 
> **Additional context** Can you please use my custom made icons to make it a svg icon and add it to your repository?

could you post in svg format?

**Comment by HunterX86** [comment]
Sorry but that's not possible because my adobe illustrator is crashing when i try to save it to svg

**Comment by danielclindsay** [comment]
@elax46 thank you and the team for your help with the ATV remote. Hopefully these help save some time. 

Cheers

[bulb-group-sultan-3-alt.zip](https://github.com/elax46/custom-brand-icons/files/8917553/bulb-group-sultan-3-alt.zip)

**Comment by HunterX86** [comment]
@danielclindsay thnx for convert it into svg format

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/174321031-d8006b30-42ef-4e24-a23d-abeb151157d3.png)
![image](https://user-images.githubusercontent.com/87599807/174321063-c4b5abc3-a4df-4a74-ba82-99b063bcb8f1.png)

I am not sure about Elax64 stance on this but I dont think we should get into the adding of lines through icons for on off as home assistant lights icons up that are on, if we did that have you seen how many plugs and icons and over stuff we would have to end up doing and adding lines through.

I have done these two though 
[sultan-group.zip](https://github.com/elax46/custom-brand-icons/files/8928553/sultan-group.zip)

**Comment by HunterX86** [comment]
That's true. Then it's not necessary. It's ok if you add the other two.

**Comment by rchiileea** [comment]
there already set for next commit :)

**Comment by HunterX86** [comment]
Great and thnx.

**Comment by elax46** [comment]
> ![image](https://user-images.githubusercontent.com/87599807/174321031-d8006b30-42ef-4e24-a23d-abeb151157d3.png) ![image](https://user-images.githubusercontent.com/87599807/174321063-c4b5abc3-a4df-4a74-ba82-99b063bcb8f1.png)
> 
> I am not sure about Elax64 stance on this but I dont think we should get into the adding of lines through icons for on off as home assistant lights icons up that are on, if we did that have you seen how many plugs and icons and over stuff we would have to end up doing and adding lines through.
> 
> I have done these two though [sultan-group.zip](https://github.com/elax46/custom-brand-icons/files/8928553/sultan-group.zip)

completely agree the off icons will not be inserted!
