### ISSUE TITLE
Icon Disappears

### ISSUE THREAD

**Issue by GitHubGoody** [elax46/custom-brand-icons#189]
I am using phu:tesla-icon in my header. On most of my devices (iOS app, Fire Tablets running FKB, and Tesla browser), it appears after clearing the cache and reloading, but later disappears requiring me to reset my cache again and the cycle repeats. This is the only icon that seems to be a problem. I'm using other brand icons and font awesome icons, but this one seems to be the problem. Could it be something with using brand icons in the header specifically?

**Comment by elax46** [comment]
Thank you for raising the issue unfortunately the issue is already known and depends on the Home Assistant cache management policy. I will investigate further to see if it is possible to resolve the issue I remind you that you still need to enter your configuration.yaml this additional code
```
frontend:
extra_module_url:
   - /local/community/custom-brand-icons/custom-brand-icons.js
```

**Comment by GitHubGoody** [comment]
@elax46 Thank you for looking into it.

Is that code still required if I've already added the path to my Dashboard Resources (my understanding is that it is not):
![image](https://user-images.githubusercontent.com/46235745/174506594-25b5724a-c497-4c54-a58f-2338dc053271.png)

**Comment by elax46** [comment]
> @elax46 Thank you for looking into it.
> 
> Is that code still required if I've already added the path to my Dashboard Resources (my understanding is that it is not): ![image](https://user-images.githubusercontent.com/46235745/174506594-25b5724a-c497-4c54-a58f-2338dc053271.png)

no it's the same thing! that's okay

**Comment by rchiileea** [comment]
I think you should just leave it for a week and see if returns back, if not ill redo the icon again to check, can you refer exactly which tesla one it is (peugeot one when applied dissapears only in ios app, but is not permently there after about 5 to 7 days) its a strange bug indeed.

**Comment by GitHubGoody** [comment]
@rchiileea It's been a couple months and it comes and goes routinely from the dashboard tabs where I'm currently using it. It's the Tesla T logo.

**Comment by rchiileea** [comment]
@GitHubGoody I have investigated this and can say 98% sure this is on ios devices right?

**Comment by GitHubGoody** [comment]
No, iOS app, Fire Tablets running FKB, and Tesla browser.

**Comment by rchiileea** [comment]
Is it just the Tesla icon? Or others, as I have no issues on my fire tablets with my ones from repository and I run fkb too.. if it is just Tesla one I’ll update it tomorrow

**Comment by GitHubGoody** [comment]
Random Echo icons used to be an issue, but they all seem stable now. So, yes, I think it's just the Tesla icon for the ones I'm using anyways. Thank you.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/179208070-fdd668f4-9fac-44f2-87d2-a880ea4c81ae.png)
tried a differnet way to do it, lets see if its better

**Comment by GitHubGoody** [comment]
Cool. I just updated, but didn't see it in that update. Waiting for the next merge and push?

**Comment by elax46** [comment]
> Cool. I just updated, but didn't see it in that update. Waiting for the next merge and push?

The new version has just been released if the problem is no longer present write it so I will close the request

**Comment by elax46** [comment]
> The problem persists. So far, I've tested it on the iOS app (iPhone 11 Pro and iPad Pro) and my Laptop (Windows 10/Edge). Initially, the icon loads in the header tab, but any reload and it goes blank. A refresh does not recover it. I've also tried to clear the cache (iOS app and Edge), then reload and refresh. The icon still does not return.

I still don't understand the question, is the icon that is not displayed always the same? have you tried to restart HA? The iOS cache management problem is partly known but with Windows there is no problem I recommend that you check your HA installation well at this point or also check the error log because there is something in your installation that does not work or that it conflicts in some way

**Comment by GitHubGoody** [comment]
Yes, it's always the same icon.

**Comment by rchiileea** [comment]
i have this icon in my dash as a replacement to test, lets see what happens

**Comment by elax46** [comment]
> i have this icon in my dash as a replacement to test, lets see what happens

After twenty days of testing how is the situation?

**Comment by rchiileea** [comment]
iits still there so I am a bit confused, after a restart some of my icons are missing but a quick reload fixes this (its the same for any custom icon).

**Comment by elax46** [comment]
> iits still there so I am a bit confused, after a restart some of my icons are missing but a quick reload fixes this (its the same for any custom icon).

Well if it always appears at this point I think I can close the request

**Comment by GitHubGoody** [comment]
@elax46 It's still the only icon I have problems with. There should be a Tesla icon in the space indicated by the the red square.

![image](https://user-images.githubusercontent.com/46235745/186653239-fbd8e979-020f-42f8-8961-2271b80490b9.jpeg)

**Comment by GitHubGoody** [comment]
@elax46 I just started using the new HEOS icon in the header bar similar to how I was using a Tesla logo. It seems to be acting flaky as well - sometimes displaying, sometimes not.

The same custom brand icons (Tesla and HEOS) seem to work fine elsewhere in the UI and mdi: icons do not disappear in the header.

Any chance Home Assistant has some sort of sporadic issue with phu: icons in the header bar specifically?

**Comment by rchiileea** [comment]
Try this as when I used a older Samsung tablet I had a issue. Clear cache on browser without opening home assistant,

Download the latest custom brand icons js file from git hub, upload it to www/community folder.

then add this to your configuration.yaml

frontend:
   extra_module_url
   -/local/community/custom-brand-icons/custom-brand-icons.js

then go to hardware 3 dots and shutdown system then Reboot.  Let me know how that works out

**Comment by GitHubGoody** [comment]
I'm trying this on an old iPad mini and my Laptop's Edge browser. I had to have the HA iOS app open on the iPad to clear the frontend cache, but otherwise followed your instructions.

To be sure, here's what I have in my configuration.yaml:

```
frontend:
  extra_module_url:
    -/local/community/custom-brand-icons/custom-brand-icons.js
```
After a reboot, what I observed was that on both devices a browser refresh and/or HA three dot>refresh would sometimes cause the phu: icon to disappear, but refreshing using the same refresh method that made it disappear could either return the icon or not. It did not seem that either method produced more consistent results than the other.

Also, I already had this configured in the UI Dashboard Resources:

![image](https://user-images.githubusercontent.com/46235745/210893791-cfe5ce95-677e-432d-ae59-2dc75794b257.png)

**Comment by GitHubGoody** [comment]
@rchiileea @elax46

I'm starting to learn CSS a little more for card-mod, so I've been using the inspector. I noticed I get an error that seems like it may be the cause of this. When I click the error, it brings me to the Console tab and displays this message:

![image](https://user-images.githubusercontent.com/46235745/220632255-42dc8f2a-da75-4465-b637-fbdb4b5bf8fe.png)

When I click either of the Overview links, it brings me to the Sources tab and displays this line with the red x next to it:

![image](https://user-images.githubusercontent.com/46235745/220632848-5d5af200-b3ba-4be2-a1b7-614498e99f9d.png)

Here's the entry I have under Dashboards > Resources:

![image](https://user-images.githubusercontent.com/46235745/220633384-82365f7f-fc1e-401c-8647-03c25cbf75f6.png)

Do you think that extra '-' in front of the path is causing these issues?

**Comment by elax46** [comment]
There seems to be a formatting typo one space is missing

```
frontend:
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
```

**Comment by GitHubGoody** [comment]
Thanks. I think we may have finally just solved this issue (my misconfiguration). After multiple page reloads/refreshes the custom brand icons no longer disappear. I also realized I have it configured via both methods (frontend: and resources). Which one should I remove or does it matter?

**Comment by rchiileea** [comment]
leave them both, the adding to config, keeps the icons in menu, for some reason on some browsers.

**Comment by InfoSecured** [comment]
@GitHubGoody How did you end up resolving this? I'm having the exact same issue.

**Comment by GitHubGoody** [comment]
@InfoSecured I don't recall exactly, but it looks like it's documented above.
