### ISSUE TITLE
No more icons are shown

### ISSUE THREAD

**Issue by naamah75** [elax46/custom-brand-icons#19]
Since updated to core-2021.6.4 no more icon are shown. 
Obviously before report this issue I already cleaned the cache twice and tried with the incognito mode
This problem is reported on all my PCs and smartphones.
Also tried to reinstall the component.

**Comment by elax46** [comment]
I recommend that you try to clear the cache several times. Do you have all the libraries updated? Have you noticed that there has been a variation on the nomenclature of icon names?

**Comment by naamah75** [comment]
@elax46 , thanks for you reply, the problem was the changing of the nomenclature.

**Comment by elax46** [comment]
Thanks to you for nothing
