### ISSUE TITLE
Custom Icon request - Shudder, NeonTV (NZ Streaming Service),

### ISSUE THREAD

**Issue by DoubtfulTurnip** [elax46/custom-brand-icons#190]
I have made an attempt at a couple of SVG icons

Neon (NZ Streaming Service)
![neontvnz](https://user-images.githubusercontent.com/23531986/174476067-ab01c899-7605-445a-bb6f-cffe4c7730fd.svg)

Shudder
![Shudder](https://user-images.githubusercontent.com/23531986/174475744-33052c29-441e-4981-a6fd-9b6d77355d0b.svg)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/174568963-065c91e3-99cd-4945-9b3b-8b30aaf8866c.png)
![image](https://user-images.githubusercontent.com/87599807/174568986-db71e93e-ef65-4c7d-9f73-dcdd2854ea98.png)
[Shudder.zip](https://github.com/elax46/custom-brand-icons/files/8939228/Shudder.zip)
