### ISSUE TITLE
Custom Icon request Pluto TV

### ISSUE THREAD

**Issue by hitnrun30** [elax46/custom-brand-icons#193]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
Pluto TV - https://commons.wikimedia.org/wiki/File:Pluto_TV_logo.svg

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/175764245-52d0dded-4a89-467b-baf2-a9e86df0006d.png)
