### ISSUE TITLE
Custom Icon request [Toyota]

### ISSUE THREAD

**Issue by jlmaners** [elax46/custom-brand-icons#197]
Icon is attached - include Toyota icon in the vehicle/car logos

![toyota-icon](https://user-images.githubusercontent.com/582807/176332491-cb51c1e4-4f7e-4573-9f92-38dbe2dbeb7f.svg)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/178139484-6b91e78b-a642-4c8d-b7e8-50d2205d1f06.png)
![image](https://user-images.githubusercontent.com/87599807/178139488-3cbf828f-e9e6-4c02-921b-70e7caf2a4ae.png)
![image](https://user-images.githubusercontent.com/87599807/178139494-f7a7fbf6-eabb-4169-99e6-71880c1dd076.png)
![image](https://user-images.githubusercontent.com/87599807/178139499-4d0d9add-a7fd-437a-b160-889fceb854b8.png)
![image](https://user-images.githubusercontent.com/87599807/178139510-a078509a-03c6-4ecb-adef-bb517bd26849.png)
![image](https://user-images.githubusercontent.com/87599807/178139513-1f4262c9-51b8-47e8-87dc-e98c0c5b3dd7.png)
![image](https://user-images.githubusercontent.com/87599807/178139516-c73c959b-9f7c-4156-b9cb-f6941a4f5382.png)
![image](https://user-images.githubusercontent.com/87599807/178139521-313e92ab-6f98-474b-a3a3-50181b840066.png)
![image](https://user-images.githubusercontent.com/87599807/178139525-04cb51d7-93f1-4e3c-8c39-7cc6fe128ad9.png)
