### ISSUE TITLE
Custom Icon request Crunchyroll

### ISSUE THREAD

**Issue by peppy6582** [elax46/custom-brand-icons#198]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://upload.wikimedia.org/wikipedia/en/f/f6/Crunchyroll_Logo.svg
**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
Just the icon I presume as text would be very small

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: peppy6582 ***@***.***>
Sent: Sunday, July 3, 2022 7:54:13 PM
To: elax46/custom-brand-icons ***@***.***>
Cc: Richard Bowzer ***@***.***>; Assign ***@***.***>
Subject: [elax46/custom-brand-icons] Custom Icon request Crunchyroll (Issue #198)


Insert a link to an SVG icon the integrable icons are ONLY in SVG format
https://upload.wikimedia.org/wikipedia/en/f/f6/Crunchyroll_Logo.svg<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fen%2Ff%2Ff6%2FCrunchyroll_Logo.svg&data=05%7C01%7C%7C0675e7af4070486a7dd208da5d256c94%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637924712559866169%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=s5PfdVQZPWsO9rO%2Fbh2VuwdYG7hhDQP3vavlSx1Hskc%3D&reserved=0>
off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/178139471-7ca4d650-ddc0-49cc-96a9-35e39569ca2d.png)
