### ISSUE TITLE
Custom Icon request SONNEN

### ISSUE THREAD

**Issue by skyx3** [elax46/custom-brand-icons#199]
I have a Sonnerbatterie (https://sonnen.de  ) and I created a new Icon for that. I would be happy if this could be added.:

**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://s30.aconvert.com/convert/p3r68-cdx67/ajjsi-fhyd9.svg

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/178139460-1062a234-00ad-4f64-a393-ed5ff1e74ac8.png)
