### ISSUE TITLE
Icons not visible inside the HA app

### ISSUE THREAD

**Issue by mfabiani53** [elax46/custom-brand-icons#2]
As the subject, icons are not shown inside the HA android companion app. Also after clearing cache not visible. They are perfectly visible inside Chrome browser.

**Comment by elax46** [comment]
The problem of loading, even in the HA application always depends on the cache. Try ending the process and reopening.

**Comment by mfabiani53** [comment]
Yes, i did it several times and finally i got the icons... Thanks!

**Comment by elax46** [comment]
Do not mention it
