### ISSUE TITLE
Custom brand icons will not load in lovelace 

### ISSUE THREAD

**Issue by checkdivers** [elax46/custom-brand-icons#20]
Hi,
2 weeks ago in installed under HACS “Custom band icons” and his work perfect. Today i can’t see the icons. Ich check the status and i see this addon is not loaded or active. I deinstall and reinstall the addon and the same result.

What is my problem or my issue.

Sorry for my bad english, but i’m german user

Kind regards,

Andreaas

**Comment by elax46** [comment]
I remind you to clear the cache by following the instructions indicated above [README.md](https://github.com/elax46/custom-brand-icons#dont-see-the-icon)  Do you have all the libraries updated? Have you noticed that there has been a variation on the nomenclature of icon names?

**Comment by greghesp** [comment]
I also have this issue.  Its not a cache issue, as i've had them working, restarted home assistant and then they no longer show

**Comment by checkdivers** [comment]
Hi,
Here my steps in the install process:
- I install the Addon under Hacs
- In insert the code in config
frontend:
extra_module_url:
  - /local/community/custom-brand-icons/custom-brand-icons.js
  
After this I restart HA

Not work

**Comment by elax46** [comment]
sorry for the late reply did you enter the icon names correctly? the names have changed since version [1.0.1](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.1)

**Comment by checkdivers** [comment]
Hi, 
no problem and thanks for your time. I reinstall your addon and check the names in the cards. I see the icons now, but not all. Example: phu:rooms-kinds-bedroom will not work.

kind regards,
Andreas

**Comment by elax46** [comment]
thanks for your contribution there was a bug with that icon that I have already fixed in the next version will be visible

**Comment by greghesp** [comment]
> have you updated the name of the icons? the names have changed since version [1.0.1](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.1)

Yep.  They seem to work sometimes and not others.  
I can have them working, restart HA and then they don't show up

![image](https://user-images.githubusercontent.com/768908/122795605-66c48200-d2b5-11eb-875c-ddb536b7a0f0.png)

**Comment by elax46** [comment]
> I can have them working, restart HA and then they don't show up

I believe it is a problem with your Home Assistant setup

**Comment by checkdivers** [comment]
> thanks for your contribution there was a bug with that icon that I have already fixed in the next version will be visible

Perfect, which date you upload the next version?
Kind regards, Andreas

**Comment by elax46** [comment]
> > thanks for your contribution there was a bug with that icon that I have already fixed in the next version will be visible
> 
> Perfect, which date you upload the next version?
> Kind regards, Andreas

the new version is already available [1.0.6](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.6)

**Comment by checkdivers** [comment]
> > > thanks for your contribution there was a bug with that icon that I have already fixed in the next version will be visible
> > 
> > 
> > Perfect, which date you upload the next version?
> > Kind regards, Andreas
> 
> the new version is already available [1.0.6](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.6)

For you information:
in custom-brand-icons.js is the name for kids bedroom = rooms-**kinds**-bedroom in  the repository = rooms-kids-bedroom.

Kind regards,
Andreas

**Comment by elax46** [comment]
> > > > thanks for your contribution there was a bug with that icon that I have already fixed in the next version will be visible
> > > 
> > > 
> > > Perfect, which date you upload the next version?
> > > Kind regards, Andreas
> > 
> > 
> > the new version is already available [1.0.6](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.6)
> 
> For you information:
> in custom-brand-icons.js is the name for kids bedroom = rooms-**kinds**-bedroom in the repository = rooms-kids-bedroom.
> 
> Kind regards,
> Andreas

thanks for your report I have corrected the problem in custom-brand-icons.js
