### ISSUE TITLE
Custom Icon request Window and Roller Shutter - marquee

### ISSUE THREAD

**Issue by skyx3** [elax46/custom-brand-icons#200]
I would be happy about the following icon. It is still missing from the collection.

**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
![markise](https://user-images.githubusercontent.com/58375274/177313616-03ab7333-7674-428e-a970-9f74189f8226.png)

![markiseb](https://user-images.githubusercontent.com/58375274/177352235-30bf411c-06f5-4f44-8fff-b072b198e27b.png)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/178139444-dec59486-068d-4562-8b5f-9a1e94eda70b.png)
