### ISSUE TITLE
Custom Icon request [Sonos Move]

### ISSUE THREAD

**Issue by legovaer** [elax46/custom-brand-icons#201]
Is it possible to add icons for Sonos speakers:

Sonos Move

https://www.dimensions.com/element/sonos-move-smart-speaker might help?

https://sonos.ng/web/image/product.image/130/image_1024/SONOS%20MOVE?unique=53ef2a2

**Comment by rchiileea** [comment]
had to do the speaker grill with larger holes to cut down on size

![image](https://user-images.githubusercontent.com/87599807/178139289-0ace3276-4f20-4753-866d-f9caed8780a2.png)
