### ISSUE TITLE
Paramount+ Icon Too Small

### ISSUE THREAD

**Issue by j6s33m** [elax46/custom-brand-icons#206]
The Paramount + icon is too small to be discernible in Home Assistant buttons and isn't scaled to be similar sized to any of the other TV apps. I posted an issue for as a bug a month or so ago and I believe you said it was fixed, but it has not been corrected. 

Any chance you could get to this would be greatly appreciated.

Thank you in advance!

**Comment by elax46** [comment]
In your previous request you talked about visibility in the README.md file as the screenshort you published also demonstrates, Not surprisingly it is now more visible. Here you talk about the dashboard of HA @rchiileea  do you think the question can be improved?

**Comment by rchiileea** [comment]
Caught me right at pc, I actually went to edit original and its has a error that forces it to top left corner in illustrator, so the file has some sort of issue, I done this from scratch and morthed logo and text to fit the width of restriction in icon size

![image](https://user-images.githubusercontent.com/87599807/178325704-11b0e2c3-b62a-46eb-92bc-da9a7b7d726e.png)
[paramount.zip](https://github.com/elax46/custom-brand-icons/files/9086420/paramount.zip)

**Comment by rchiileea** [comment]
yep for some reason the icon code did not change, I have updated the dev branch and should see it moved to main some time today.

**Comment by elax46** [comment]
> yep for some reason the icon code did not change, I have updated the dev branch and should see it moved to main some time today.

Update!
