### ISSUE TITLE
Bollard Groupe

### ISSUE THREAD

**Issue by checkdivers** [elax46/custom-brand-icons#21]
Hi,
i has been create a new icon bollard-groupe in Photoshop.
![Bollard-group Kopie](https://user-images.githubusercontent.com/50680195/123494520-69f69f80-d620-11eb-83ef-dda2b4a1ff18.png)

What you mean?

Kind regards,
Andreas

**Comment by elax46** [comment]
once you have created the image you have to export it to svg but pay attention that the path d must be single and not multiple if the icon is not integrable

**Comment by checkdivers** [comment]
Ok, i will try later today.

Mit freundlichen Grüßen/ Best regards

Von meinem iPhone gesendet/ Send from my IPhone

Andreas Voigt

> Am 26.06.2021 um 09:43 schrieb Emanuele ***@***.***>:
> 
> once you have created the image you have to export it to svg but pay attention that the path d must be single and not multiple if the icon is not integrable

**Comment by elax46** [comment]
I did some tests on the icon you posted by exporting it to svg it is made up of multiple paths and is too big in size

**Comment by checkdivers** [comment]
Hi, after my job, I will work on this

Mit freundlichen Grüßen/ Best regards

Von meinem iPhone gesendet/ Send from my IPhone

Andreas Voigt

**Comment by checkdivers** [comment]
Hi,

 

ist this better? 

 

Kind regards,

 

Andreas

 

Von: Emanuele ***@***.*** 
Gesendet: Montag, 28. Juni 2021 10:40
An: elax46/custom-brand-icons ***@***.***>
Cc: checkdivers ***@***.***>; Author ***@***.***>
Betreff: Re: [elax46/custom-brand-icons] Bollard Groupe (#21)

 

I did some tests on the icon you posted by exporting it to svg it is made up of multiple paths and is too big in size

**Comment by elax46** [comment]
I do not understand what you mean

**Comment by elax46** [comment]
if you have a more defined icon with a larger size, I will integrate it
