### ISSUE TITLE
Motorised Desk Icons

### ISSUE THREAD

**Issue by sumur1au** [elax46/custom-brand-icons#211]
Hi, 

Can someone create a standing and sitting desk icon, preferable the ikea idasen desk. Sorry I can't find an svg link for desk.

Many thanks

**Comment by elax46** [comment]
could you post at least a reference photo? also to understand in what angle to make the thank you icon

**Comment by rchiileea** [comment]
credit to @Gtt1229 for these too, ill tell him to upload in our discussion
![image](https://user-images.githubusercontent.com/87599807/178565211-a755671d-d467-4ddc-afb3-7fe53ee5cca6.png)
![image](https://user-images.githubusercontent.com/87599807/178565236-5c536f3d-eb98-40cf-8a4b-98e89f67aec4.png)
and another choice
![image](https://user-images.githubusercontent.com/87599807/178565288-86cd8799-7836-4e91-8521-4ea34ffa48b8.png)
![image](https://user-images.githubusercontent.com/87599807/178565375-a8144890-b6d6-4d7c-90d8-5858ddca8937.png)
