### ISSUE TITLE
Custom Icon request for Frigate

### ISSUE THREAD

**Issue by CeeWeasel** [elax46/custom-brand-icons#218]
I'd like to request adding an icon for the HomeAssistant addon Frigate. I got a copy of the logo from their repo, converted it to SVG in InkScape, and have attached it to this request. If that's not kosher, that's fine... I just figured I'd make the suggestion. If you have any issues getting to the file, let me know and I will find another way of getting it to you.

![frigate-logo](https://user-images.githubusercontent.com/6403938/180271860-4d5712d2-86d7-46c1-822a-27c22e0fd98d.svg)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/180641486-de3c31a1-7464-4b85-ba80-4c9a9b8760b8.png)
[frigate.zip](https://github.com/elax46/custom-brand-icons/files/9175514/frigate.zip)
will be added soon
