### ISSUE TITLE
Custom Icon request [door icon lock]

### ISSUE THREAD

**Issue by ChillZwix** [elax46/custom-brand-icons#220]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

Im using your door icons, but I missing doors type with a lock, like my front door auto look, like to see it locked, not just closed. like mdi:door-sliding-lock

**Comment by rchiileea** [comment]
a better way to do this would be to click on show code editor and either put show state or

![image](https://user-images.githubusercontent.com/87599807/180640324-11bda592-2dbd-45cc-87e0-fc7c142afe25.png)
![image](https://user-images.githubusercontent.com/87599807/180640348-7bf73d2b-ad67-4d66-8013-a741b3833d61.png)

to do this use custom button card and add

```
styles:
  grid:
    - grid-template-areas: '"l" "i" "n" "s"'
    - grid-template-rows: min-content 1fr min-content min-content
    - grid-template-columns: 1fr
  label:
    - justify-self: start
    - font-weight: bold
    - font-size: 15px
    - opacity: 0.6
    - padding: 0 15px 5px
show_label: true
label: |
  [[[
     if (states['put your lock entity here'].state == 'on') 
      return "Locked"; 
     if (states['put your lock entity here'].state == 'off')
      return "Unlocked"
  ]]]
```
adjust code acordingly to your device and layout font size ect

**Comment by ChillZwix** [comment]
*Thank you for that, but that will not work for me or what I want. I using a tablet with icons only for easy use and easy quick look setup , so thats why I want a door with a lock on to easy see that it locked.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/181044567-ce79a478-aca5-4c77-8dc1-e0f3f9bb2939.png)
![image](https://user-images.githubusercontent.com/87599807/181044512-906b4bfc-5234-4c9d-be3f-6a3e09dd727d.png)
![image](https://user-images.githubusercontent.com/87599807/181044646-3025beb2-8ac7-4aca-830f-ba5fae3f2928.png)
![image](https://user-images.githubusercontent.com/87599807/181044685-563811b0-d5b8-4506-95df-cac802f74997.png)
![image](https://user-images.githubusercontent.com/87599807/181044714-6b493b98-f665-451b-9c94-ab5ab55c750e.png)
![image](https://user-images.githubusercontent.com/87599807/181044753-47328f73-20ea-4ad8-afba-2b576b0daeeb.png)
![image](https://user-images.githubusercontent.com/87599807/181045183-b2835ee8-8f2b-416e-92d2-c84611726fd6.png)
