### ISSUE TITLE
New Icon: Sprinkler Stopped

### ISSUE THREAD

**Issue by clau-bucur** [elax46/custom-brand-icons#221]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

Not really an off-type :) but you decide. It would be useful to me to indicate sprinkler states at a glance.
![sprinkler-stopped](https://user-images.githubusercontent.com/47672949/180742937-393e7024-5066-44b6-bc6c-d7bd7733ddd1.svg)

**Comment by elax46** [comment]
As already indicated for a duplication issue we do not insert icons that represent the state as it is possible to assign the colors to represent the state I suggest you take a look at the request #136 where @rchiileea  has inserted an example
