### ISSUE TITLE
Custom Icon request [Chicken]

### ISSUE THREAD

**Issue by Tillsy** [elax46/custom-brand-icons#222]
Any chance of a chicken icon? I current use a turkey for my various chicken coop devices but it annoys me it's not really right ;)

Maybe something like this...
![chicken-silhouette-svg-6](https://user-images.githubusercontent.com/103569790/180993663-bdb128a7-ba94-446d-b10d-309bcdfa59eb.png)

**Comment by rchiileea** [comment]
I am sorry I am not doing a chicken :P  joking of course, would you prefer somthing like this, because lets face it the chicken is not smart the coup is :)

![image](https://user-images.githubusercontent.com/87599807/181040167-3b8813b4-d926-4afe-98c6-9d752d2dfa59.png)

**Comment by Tillsy** [comment]
> I am sorry I am not doing a chicken :P joking of course, would you prefer somthing like this, because lets face it the chicken is not smart the coup is :)

LOL!!!  Oh my gosh that is so freaking cool!  Do you think that detail would render okay in HS tiny icon size?

Looks fantastic - the gotcha would be I have an icon indicating the chicken coop overall, which is currently a turkey!, but then have a bed to control the door for the coop and an egg to control the door for the nest.  So this new icon would be perfect for the coop door, but totally happy to leave as a bed and use this coop image for the overall chicken coop.

Not sure that makes sense, here's a quick crop from my kitchen's dashboard to show that area currently looks like...
![Coop](https://user-images.githubusercontent.com/103569790/181120115-28edbb7f-a697-49e2-9fc5-e5b253a2ed57.jpg)

**Comment by rchiileea** [comment]
coup with chicken door open you could use that as, then chicken coup with lock as door closed
![image](https://user-images.githubusercontent.com/87599807/181763110-0c0eb9ab-7914-4f9c-9a0b-9377c730a2e1.png)
then chicken
![image](https://user-images.githubusercontent.com/87599807/181763160-b82338f8-1512-4017-9697-5f4673bc2735.png)
Then egg tray
![image](https://user-images.githubusercontent.com/87599807/181763256-39227942-c900-45f8-81c0-4e7539615b7f.png)

**Comment by Tillsy** [comment]
Oh wow... that icons are **STUNNING!!!**. Thank you that would be perfect!
