### ISSUE TITLE
Custom Icon request [Stage DMX Lights]

### ISSUE THREAD

**Issue by BenJamesAndo** [elax46/custom-brand-icons#224]
I'd love to have some studio or concert light icons as I use DMX lighting through Home Assistant. They could be fresnel or LED based. Some examples below.
Spotlight: https://cdn.onlinewebfonts.com/svg/download_494676.svg
Stage light: https://www.pngwing.com/en/free-png-hlryl or https://icon-library.com/icon/stage-light-icon-2.html
Back light: https://www.pngwing.com/en/free-png-ydpbs
Stage LED up lights: https://cdn.shopify.com/s/files/1/0216/9754/products/led-uplight-effect_a2b04193-08c6-4e3b-8bfb-c7ac6a4a65e9_large.jpg?v=1571268247

It would be nice to have grouped icons as well to demonstrate controlling multiple lights at once.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/181762331-c35abb56-4016-46eb-9ab4-f1b9c69c2bb3.png)

**Comment by BenJamesAndo** [comment]
Wow these are really nice! Thanks so much. Can't wait to load them up.
If it's not too much more to ask, it would be nice to have the stage-light as a group icon. Essentially 2 of the stage-lights in the one icon.
And finally the stage-uplight looks awesome. Would it be possible to have it as a downlight also? Basically how it is but rotated down with the handle adjusted accordingly. Kinda like this: https://www.chauvetdj.com/wp-content/uploads/2016/12/wsi-imageoptim-SlimPAR-Pro-W-USB-RIGHT-White.jpg

**Comment by elax46** [comment]
> Wow these are really nice! Thanks so much. Can't wait to load them up. If it's not too much more to ask, it would be nice to have the stage-light as a group icon. Essentially 2 of the stage-lights in the one icon. And finally the stage-uplight looks awesome. Would it be possible to have it as a downlight also? Basically how it is but rotated down with the handle adjusted accordingly. Kinda like this: https://www.chauvetdj.com/wp-content/uploads/2016/12/wsi-imageoptim-SlimPAR-Pro-W-USB-RIGHT-White.jpg

Now I have released the new version, open a new request for the other icon
