### ISSUE TITLE
Custom Icon requests [Reolink E1, Bitfocus Companion, Portainer, Duplicati, ProPresenter & FFAStrans]

### ISSUE THREAD

**Issue by BenJamesAndo** [elax46/custom-brand-icons#225]
This is a great project. Thanks for all the hard work. Below are some icons that I'd like to have in Home Assistant.

Reolink E1 - https://home-cdn.reolink.us/wp-content/assets/2019/10/e1-zoom-400.png
Bitfocus Companion - https://github.com/bitfocus/companion/tree/master/assets or https://bitfocus.io/images/brand/companion.png
Portainer - https://icon-sets.iconify.design/simple-icons/portainer/
Duplicati: https://www.duplicati.com/images/duplicati-fb-share-v1.png
ProPresenter: https://image.pngaaa.com/487/5068487-middle.png
FFAStrans: https://upload.wikimedia.org/wikipedia/commons/b/be/FFAStrans_Logo.png

**Comment by rchiileea** [comment]
I get some of these, but the last 2 are basically something you would not need a button for in HA or smart home inmho

**Comment by rchiileea** [comment]
would good to see a donation with such a large list of icons btw

![image](https://user-images.githubusercontent.com/87599807/181761811-f21222b0-0eae-400e-a1d4-99281ceaba45.png)
![image](https://user-images.githubusercontent.com/87599807/181761903-9f99075e-871e-45f6-80a8-2ac1dccf0a62.png)
![image](https://user-images.githubusercontent.com/87599807/181761993-b6e1ca8a-9435-415b-9e3f-d9e034b4c400.png)

**Comment by BenJamesAndo** [comment]
These are wonderful, thank you. Yeah that makes sense. I think you're right in only making icons that would make sense alongside HA. I understand these are fairly niche icon requests. Basically I'm putting iframes into HA of all the other services I run, hence the desire for these icons.

Thanks for the prompt. I'll definitely send through a donation to help this project now.
