### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by myopenflixr** [elax46/custom-brand-icons#226]
Hello,

I have a custom icon request for the TIDAL music service logo.

Link to svg file below

[https://raw.githubusercontent.com/myopenflixr/images/main/tidal.svg](https://raw.githubusercontent.com/myopenflixr/images/main/tidal.svg)

**Comment by myopenflixr** [comment]
Hello,

I just wanted to be sure that you look over the svg file that I linked to in my original post/request. I grabbed the svg file online and it might not meet the requirements to be used as it is. I personally tried to add it to my config and could not get it to work. I assume that the svg file will need some editing/tweaking before it can be added.

**Comment by myopenflixr** [comment]
Decided to give this a try on my own. Pull Request #230

**Comment by rchiileea** [comment]
I am back tomorrow i will check or elax will today, mums birthday weekend, hence lack of action  here

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by elax46** [comment]
it is not the case that you open a new pull request I have added the time to your icon
