### ISSUE TITLE
Custom Icon request - grouped stage DMX light and Stage wash light

### ISSUE THREAD

**Issue by BenJamesAndo** [elax46/custom-brand-icons#228]
Thanks so much for the work on the stage DMX lights. If I may request, I'd love to have two additional ones added.
First one would be the stage-light but as a group of two or three. To represent that it's a group of lights.

I'd also like the stage-uplight icon facing down. Essentially the same icon, but rotated down with the handle adjusted accordingly. I think their official names are stage wash lights. Kinda like this: https://www.chauvetdj.com/wp-content/uploads/2016/12/wsi-imageoptim-SlimPAR-Pro-W-USB-RIGHT-White.jpg

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/183704759-14f75cae-5495-4b8d-8207-9054b732ee1a.png)
![image](https://user-images.githubusercontent.com/87599807/183705952-c0a44e75-5845-4823-9c2f-0ca5fe22791e.png)

**Comment by BenJamesAndo** [comment]
Hey @rchiileea thanks or these. They look great. The group icon you made will be useful, but I did mean a grouped icon of the below icon. 

![181762451-6a2d7955-f9bd-4d09-919d-f58a8eceb5f8](https://user-images.githubusercontent.com/44917135/183743730-2b411b11-0a9a-4840-9c64-bb895febe004.png)

**Comment by elax46** [comment]
> Hey @rchiileea thanks or these. They look great. The group icon you made will be useful, but I did mean a grouped icon of the below icon.
> 
> ![181762451-6a2d7955-f9bd-4d09-919d-f58a8eceb5f8](https://user-images.githubusercontent.com/44917135/183743730-2b411b11-0a9a-4840-9c64-bb895febe004.png)

@rchiileea meant this icon here

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/184138531-6e437d01-dc85-4251-b13e-62ba5aee4c2e.png)
