### ISSUE TITLE
Revamp: essential-oil-diffuser

### ISSUE THREAD

**Issue by cooper645** [elax46/custom-brand-icons#229]
Icon already in the library, however I feel like the line thickness needs increasing, or a bolder version of the essential-oil-diffuser from meross please.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/183706064-d16e40d2-7de2-4ce0-9365-515426cae484.png)

**Comment by cooper645** [comment]
Wow, excellent work and great turn around time. Thanks
