### ISSUE TITLE
Reolink E1 Outdoor

### ISSUE THREAD

**Issue by cloudbr34k84** [elax46/custom-brand-icons#236]
Hey im hoping this is correct.
Can we make some variations of this that support the entities it supports? PLease :)
Person Motion
Vehicle Motion
SpotLight

![Reolink-E1-Outdoor-e1617209214912](https://user-images.githubusercontent.com/58960644/186787529-768027ac-005b-4594-b0f6-499c3e0ab142.svg)

**Comment by cloudbr34k84** [comment]
Can

**Comment by elax46** [comment]
why did you close the request? @cloudbr34k84

**Comment by cloudbr34k84** [comment]
> why did you close the request? @cloudbr34k84

Crap, I didn't mean to!! Lol

**Comment by rchiileea** [comment]
I will get this done some time next week

**Comment by cloudbr34k84** [comment]
> I will get this done some time next week

Sweet as no hurry, appreciate it

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/188502084-e13898fa-018c-43be-b157-c41714790b7d.png)
