### ISSUE TITLE
Custom Icon request: Ikea Symfonisk Lampe

### ISSUE THREAD

**Issue by hesspoint** [elax46/custom-brand-icons#240]
Hi,
I was wondering if it would be possible to create an icon for the Ikea Symfonisk Lamp (1st. Gen)?

![image](https://user-images.githubusercontent.com/67288231/188001411-251ccb3c-e283-46a3-929b-d0ed3d47a22b.jpeg)

**Comment by rchiileea** [comment]
I will get this done some time next week

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/188502025-1b141c8d-2a37-481a-a0f6-926e58aad8ed.png)
