### ISSUE TITLE
Custom Icon request Ikea Regolit Arc Lamp

### ISSUE THREAD

**Issue by hesspoint** [elax46/custom-brand-icons#241]
Hi,
I have an Arc Lamp from Ikea and there is no icons for Arc Lamps either in the MDI icons nor in PHU. Would it be possible to create an Arc Lamp icon (does not have to be exactly the Ikea one of course)

![image](https://user-images.githubusercontent.com/67288231/188001675-da735942-69ac-48bf-8665-bfae78a67904.jpeg)

**Comment by rchiileea** [comment]
I will get this done some time next week

**Comment by hesspoint** [comment]
Awesome thanks :)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/188501991-574bdb8b-2ac5-4ae3-b6eb-7dc2c3b3a648.png)

**Comment by hesspoint** [comment]
I integrated the icon now in my setup. And I think it is beautiful. The only thing is that the icon is very light (thin lines) which makes it stick out to the other icons and does not match the overall design language.

![image](https://user-images.githubusercontent.com/67288231/188614917-077bff58-24fc-409d-a814-13d50710df3f.jpeg)

Would it be an option to make the lines thicker as in all the other icons and then make the lampshade filled instead of outlined?

Thanks a lot!

**Comment by elax46** [comment]
> I integrated the icon now in my setup. And I think it is beautiful. The only thing is that the icon is very light (thin lines) which makes it stick out to the other icons and does not match the overall design language.
> 
> ![image](https://user-images.githubusercontent.com/67288231/188614917-077bff58-24fc-409d-a814-13d50710df3f.jpeg)
> 
> Would it be an option to make the lines thicker as in all the other icons and then make the lampshade filled instead of outlined?
> 
> Thanks a lot!

@rchiileea

**Comment by hesspoint** [comment]
Awesome much better :) Thanks a lot!!

**Comment by elax46** [comment]
Icon revisited in the appen [version](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.77)
