### ISSUE TITLE
ZwaveJS icon request

### ISSUE THREAD

**Issue by j6s33m** [elax46/custom-brand-icons#244]
Would love for this to be turned into an icon. Hopefully this file makes it easy

![zwavejs](https://user-images.githubusercontent.com/17929290/188214299-f0d208bb-7095-48b9-bd88-dbdea302c033.png)

**Comment by rchiileea** [comment]
I will get this done some time next week

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/188502108-f92891b4-f551-45f8-b3c9-61eb38de1e59.png)

**Comment by j6s33m** [comment]
This looks awesome. Thank you!

**Comment by j6s33m** [comment]
Thanks!
