### ISSUE TITLE
Custom Icon request - Hubitat

### ISSUE THREAD

**Issue by Andrewpaps** [elax46/custom-brand-icons#248]
https://play-lh.googleusercontent.com/TZAPkGzEl1eg3n71HfPR2yTDXTEatrHTdW_7SNKzTUE4bHh7aYJBg1_-Vlu78JVw_g

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/188867957-423d8720-c5aa-4ab7-8b5b-6a5df8bdde0f.png)
[hubitat.zip](https://github.com/elax46/custom-brand-icons/files/9505736/hubitat.zip)
