### ISSUE TITLE
Custom Icon request (PM2.5).

### ISSUE THREAD

**Issue by masterfish1** [elax46/custom-brand-icons#249]
Not strictly a brand icon but I thought one for air quality (PM2.5) in general would be useful.

I've made this one, hopefully it is in the right format as I don't really know what I'm doing.

![pm25](https://user-images.githubusercontent.com/7001305/188872854-44d0a501-1e18-403d-95e8-1526d38a61a5.svg)

**Comment by rchiileea** [comment]
would help to have the icon to show us :P

**Comment by elax46** [comment]
> would help to have the icon to show us :P
https://user-images.githubusercontent.com/7001305/188872854-44d0a501-1e18-403d-95e8-1526d38a61a5.svg

**Comment by masterfish1** [comment]
I mean no disrespect but I don't like that one. I don't see the relevance of the cartoon virus-like images. They take up more space than the "PM2.5" text, which I see as being the most important element.

**Comment by elax46** [comment]
@rchiileea

**Comment by rchiileea** [comment]
if you had the life I have had you would understand it would take a lot more than that to make me fill disrespected, ok give me some time on this one to play, I just feel PM 2.5 is a bit blah on its own,  I will figure something more proffesional

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/189430587-679579ee-13ea-4f08-a497-9a338d1afd75.png)
[pm2.5.zip](https://github.com/elax46/custom-brand-icons/files/9538209/pm2.5.zip)

**Comment by masterfish1** [comment]
Now that I like. The 'warning' triangle seems much more appropriate. Many thanks for your time.

**Comment by elax46** [comment]
> ![image](https://user-images.githubusercontent.com/87599807/189430587-679579ee-13ea-4f08-a497-9a338d1afd75.png) [pm2.5.zip](https://github.com/elax46/custom-brand-icons/files/9538209/pm2.5.zip)

The path of the icon is not unique @rchiileea

**Comment by rchiileea** [comment]
[PM2.5-fixed.zip](https://github.com/elax46/custom-brand-icons/files/9539719/PM2.5-fixed.zip)
