### ISSUE TITLE
Can't see icons in version update card

### ISSUE THREAD

**Issue by Sholofly** [elax46/custom-brand-icons#250]
**Describe the bug**
Small but annoying :)
When I get an update notification of this wonderfull component the new icons are listed with an image in a table. Unfortunately they always show as an broken image. When I use them in cards or dashboards they show up fine. Cleared the cache opened an incognito window, added the frontend URL but all without any luck

![image](https://user-images.githubusercontent.com/901632/188903108-aef49217-b7aa-43c1-98a4-ca7c3ed6ef11.png)

## Don't see the icon?

It probably depends on the cache. Open Home assistant from an incognito window and check that the icon loads if yes then it depends on the cache, otherwise double check the installation

**Comment by elax46** [comment]
In all honesty I do not know if I were you I would check with other browsers, in the next few days a new version will be released we will see if the thing comes up again

**Comment by elax46** [comment]
![Immagine 2022-09-10 153705](https://user-images.githubusercontent.com/55278049/189485895-7ad8b623-38ac-4dbb-a3f5-2f800a3f5ca7.png)

Could you also check the issue with different browsers before updating ?, as you can see the display is correct

**Comment by Sholofly** [comment]
None of the browser show the images:

tried:

- Chrome, edge, firefox
- Enable and disable adguard
- Add js file to frontend-url in config

**Comment by Sholofly** [comment]
Yup!

**Comment by elax46** [comment]
Have you tried from another device? just not from the same where you tried the various browsers?

**Comment by Sholofly** [comment]
Yup been there :) Two laptops and a mobile device.

**Comment by elax46** [comment]
This thing is really weird, if I were you I would open a problem on [HACS ](https://github.com/hacs/frontend)also mentioning this one you opened here

**Comment by Sholofly** [comment]
Maybe another lead: When I look in your installed repository in HACS the images appear to be broken too.
The src of the images = ./icon-svg/bulb-filament-alt.svg wich translates to: http://homeassistant.local:8123/hacs/repository/icon-svg/bulb-spot-off.svg

Is that the correct location?

**Comment by Sholofly** [comment]
Even stranger. Left column does work right column has other src urls and doesn't

![image](https://user-images.githubusercontent.com/901632/189942767-09cc92cb-4ccb-4688-8b3d-1837f8645bd2.png)
****

**Comment by Sholofly** [comment]
Unfortunately size doesnt matter in this case...

**Comment by elax46** [comment]
Well yes

**Comment by Sholofly** [comment]
> Well yes

Why?

**Comment by elax46** [comment]
changing the page size does not change the display of icons is a very strange thing

**Comment by rchiileea** [comment]
have you cleared the cache?

**Comment by Sholofly** [comment]
Yup, was one of the first steps..

**Comment by Sholofly** [comment]
@elax46 
Can you do something with this comment?

https://github.com/hacs/integration/issues/2850#issuecomment-1246412852

**Comment by elax46** [comment]
Already read I will try to settle the matter but it will take some time

**Comment by Sholofly** [comment]
NP m8. The problem isn't urgent. Thanks for taking action anyway. Love your work!

**Comment by elax46** [comment]
In the [newly released version](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.80) I entered the static urls let me know if the icons are visible @Sholofly

**Comment by Sholofly** [comment]
Brilliant. Thanks!
![image](https://user-images.githubusercontent.com/901632/190144419-60dc80d7-e10d-42aa-8238-18424c582232.png)

**Comment by Sholofly** [comment]
Too quick. The update card works, the repo (after clearing cache and resinstall) doesn't.

**Comment by elax46** [comment]
At the moment I did a test with the release-only suggestion, the rest will be updated later

**Comment by elax46** [comment]
I have released a [pre-release](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.81b1) with the changes if I then install it and let me know if there are any problems thanks

**Comment by elax46** [comment]
@Sholofly Update on the issue?

**Comment by Sholofly** [comment]
Hi @elax46 Sorry for the delayed reply, I've been ill the past week.
Updating to 1.0.81b1 doesn't make any difference, still the second column in every table doesn't show the icons.

![image](https://user-images.githubusercontent.com/901632/192999621-ed83c5d5-9e8c-4e49-bdd0-fb2056211cb8.png)

**Comment by elax46** [comment]
did you clear the cache? with inspect element what do you see? @Sholofly

**Comment by Sholofly** [comment]
> did you clear the cache

Of course :)

![image](https://user-images.githubusercontent.com/901632/193333590-52852a37-75c8-48d6-b91a-c3fb8cdaa416.png)

**Comment by elax46** [comment]
If you look at the file in the dev [branch ](https://github.com/elax46/custom-brand-icons/blob/dev/README.md)you can verify for yourself that all links are up to date

**Comment by Sholofly** [comment]
Yeah I have seen that. I really don't know why it happens. It's a strange
bug. I've disabled all my other frontend plugins but it makes no
difference... But thanks for your help anyway!

Op vr 30 sep. 2022 22:54 schreef Emanuele ***@***.***>:

**Comment by elax46** [comment]
I close the request as the implemented solution is now available to everyone
