### ISSUE TITLE
Home Humidity Icon

### ISSUE THREAD

**Issue by cloudbr34k84** [elax46/custom-brand-icons#251]
Would it be possible to get a Home Humidity icon in the same style as the mdi:home-thermometer?

**Comment by rchiileea** [comment]
you got any rough idea as humidity is in general a % icon with a water drop

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/189430391-41d823e3-b30f-4fd6-828c-138e9f62efac.png)
[humidity1.zip](https://github.com/elax46/custom-brand-icons/files/9538202/humidity1.zip)

**Comment by cloudbr34k84** [comment]
I was thinking that house icon the with water % icon on the side like that house temperature icon.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/189472721-b688a0f4-5918-4429-9c59-ad3fe42fd443.png)
[humidity.zip](https://github.com/elax46/custom-brand-icons/files/9539726/humidity.zip)
