### ISSUE TITLE
Custom Icon request [Starbucks]

### ISSUE THREAD

**Issue by samuelmcconnell** [elax46/custom-brand-icons#257]
https://upload.wikimedia.org/wikipedia/sco/d/d3/Starbucks_Corporation_Logo_2011.svg

**Comment by rchiileea** [comment]
Sorry to be a pain, but why would you need this in your smart home?

**Comment by samuelmcconnell** [comment]
My roommate works at Starbucks, and I'd like to use it as a location icon for her location card.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/190113687-e016dd19-47bd-4a2d-b518-5d7179173e02.png)
