### ISSUE TITLE
Custom Icon request [IKEA HEKTAR 3-spot lamp]

### ISSUE THREAD

**Issue by YodahJimah** [elax46/custom-brand-icons#259]
Hi,

Would it be possible to get an icon for the IKEA HEKTAR 3-spot floor lamp ?

![hektar-floor-lamp-with-3-spot-dark-grey__0879891_pe676995_s5](https://user-images.githubusercontent.com/19324148/190707692-991155d7-87e0-43b1-b915-998abdd6d735.jpg)

More pictures at
https://www.ikea.com/om/en/p/hektar-floor-lamp-with-3-spot-dark-grey-60393603/

It could be very symbolic, maybe based on floor-lamp-dual

Many thanks

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/190989950-b26b533f-6030-4332-b38e-fd09bc4500dd.png)
[ikeaa-hektar3.zip](https://github.com/elax46/custom-brand-icons/files/9597752/ikeaa-hektar3.zip)

**Comment by YodahJimah** [comment]
This looks great, except the lamps seem to be floating around the stand.
Any chance you could have them closer so they look attached to it?

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/191184814-1eb625f0-7f0f-4911-8778-4ebc76d5f317.png)
[ikeaa-hektar3.zip](https://github.com/elax46/custom-brand-icons/files/9604724/ikeaa-hektar3.zip)

**Comment by YodahJimah** [comment]
This is awesome thanks! Have a beer on me, sponsoring you right away ;)

**Comment by rchiileea** [comment]
Why thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
