### ISSUE TITLE
Custom Icon request - dome-light

### ISSUE THREAD

**Issue by Spirituss** [elax46/custom-brand-icons#26]
Hello!

Please, add this icon:
dome-light
https://github.com/hulkhaugen/hass-bha-icons/blob/master/svg/dome-light.svg

**Comment by elax46** [comment]
What do you mean by consistent angle?

**Comment by Spirituss** [comment]
> What do you mean by consistent angle?

It was initial message template. I have corrected.

**Comment by elax46** [comment]
Addition! will be available in the next update

**Comment by Spirituss** [comment]
Thanks a lot!
