### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by andrey170183** [elax46/custom-brand-icons#260]
Hi.
I am sending you my creation, please add it.

![audio-reciever](https://user-images.githubusercontent.com/42129962/194003304-41730ee5-ce00-486b-a9bc-819cca1ba06c.svg)

**Comment by rchiileea** [comment]
you can not just submit a icon for us to guess what it is, also this is of incorrect format, please read the guidelines on make the correct format, or wait for next batch to be done for it to be corrected.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/194480009-0ce3afea-c68e-4f95-b4af-ecd90b327b63.png)
[stereo-alt.zip](https://github.com/elax46/custom-brand-icons/files/9731141/stereo-alt.zip)

**Comment by andrey170183** [comment]
Cool! 
I tried to make it so that it was on and off
![image](https://user-images.githubusercontent.com/42129962/194499639-aae1c00b-a826-4f06-a4db-d1a05ec519dd.png)
![image](https://user-images.githubusercontent.com/42129962/194499715-b9dced0e-9452-4ef8-aed7-1193d5d84f9c.png)

**Comment by andrey170183** [comment]
> ![image](https://user-images.githubusercontent.com/87599807/194480009-0ce3afea-c68e-4f95-b4af-ecd90b327b63.png) [stereo-alt.zip](https://github.com/elax46/custom-brand-icons/files/9731141/stereo-alt.zip)

Cool!
I tried to make it so that it was on and off
![image](https://user-images.githubusercontent.com/42129962/194500097-b2f19f69-b703-4a1e-8cd9-35ee2d2773c6.png)
![image](https://user-images.githubusercontent.com/42129962/194500148-027062c9-cba8-48e3-b777-c9b14c337e23.png)
