### ISSUE TITLE
Custom Icon request [new VRT Max logo] 

### ISSUE THREAD

**Issue by jrspowers** [elax46/custom-brand-icons#261]
hello i have a question is it possible to make this icon it is the new from the previous vrt logo ?

[logo](https://www.google.com/search?q=vrt+max+logo&tbm=isch&ved=2ahUKEwjhv96yqsz6AhWPG-wKHa0NDAsQ2-cCegQIABAA&oq=vrt+max+logo&gs_lcp=CgNpbWcQARgAMgcIABCABBAYOgQIABBDOgUIABCABDoGCAAQHhAHOgYIABAeEAg6BggAEB4QBToECAAQHlCYGFiNO2C2RGgAcAB4AIABhwmIAf8ZkgELOC4xLjQtMS43LTKYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=jis_Y-FAj7ewB62bsFg&bih=577&biw=1280&rlz=1C1GCEB_enBE959BE959&safe=active)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/194479865-147a8577-b59c-49a4-bc46-90742400e959.png)
[vrt-max.zip](https://github.com/elax46/custom-brand-icons/files/9731139/vrt-max.zip)

**Comment by jrspowers** [comment]
thanks man
