### ISSUE TITLE
Dyson fans

### ISSUE THREAD

**Issue by jchhenderson** [elax46/custom-brand-icons#263]
Hi - can you add these please?

**Dyson desk fan**
https://free-icon-rainbow.com/dyson-style-fan-heater-icon-1/

**Dyson tower fan**
https://free-icon-rainbow.com/dyson-style-fan-heater-icon-2/

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/197981742-d01e6764-6c99-4191-877f-24d836587fb0.png)
![image](https://user-images.githubusercontent.com/87599807/197981773-02430a0f-077e-4349-a860-81bf040f36c9.png)
