### ISSUE TITLE
Zattoo Logo

### ISSUE THREAD

**Issue by ND1988** [elax46/custom-brand-icons#264]
Hi,
can you add an icon for the streaming service Zattoo:

https://theme.zdassets.com/theme_assets/10911/da108065e12d4ab2e30571c46418a0e39f8eb4ba.svg

Thanks!

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/197981625-141841c3-b3da-4017-ba11-0a74cdd588be.png)
