### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by rchiileea** [elax46/custom-brand-icons#27]
Hi bud I was wondering if you could add a icon for the moes brand of switches (p.s I did donate from rchiileea@msn.com a few days ago) not for this request but because I think this is a nice little addon really. I just saw this request when looking at last update I thought I have just ordered the whole house full of moes  light switches so why not :)

**Comment by elax46** [comment]
If you tell me which icon it is and you give me references, let's try

**Comment by rchiileea** [comment]
![moes-switches](https://user-images.githubusercontent.com/87599807/129354260-fb9d2541-43ea-4ef3-b5a9-d31045dfce0d.png)
i knocked this up in photoshop, but never been good at smoothing the edges :(

**Comment by elax46** [comment]
could you give me the source of these images?

**Comment by elax46** [comment]
Available [v1.0.16](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.16) now. Thank you for your contribution

**Comment by rchiileea** [comment]
No thank you for the awesome icons, I have an idea I might want to talk to about as well but need to test my theory out with custom card first.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by elax46** [comment]
when you want
