### ISSUE TITLE
Apache Guacamole Icon

### ISSUE THREAD

**Issue by Roemer** [elax46/custom-brand-icons#271]
Hello
Would be gread if you could add the Apache Guacamole Icon (https://www.dove.io/static/media/guac.4b7f0930426ff89e75ab.png).
Many thanks

**Comment by rchiileea** [comment]
request done, if possible next time can you do the same in all one thread :)

![image](https://user-images.githubusercontent.com/87599807/198955107-a64df91e-c7d6-4aec-879f-6cc519a604a8.png)
![image](https://user-images.githubusercontent.com/87599807/198955255-3db32312-d8ed-49c1-b1c6-43f5397a0155.png)
![image](https://user-images.githubusercontent.com/87599807/198955280-6e3cd51a-bbfd-4701-94de-a598f10a8d20.png)
![image](https://user-images.githubusercontent.com/87599807/198955303-6410c6cd-3f28-4a11-99c5-6005aaf92027.png)
![image](https://user-images.githubusercontent.com/87599807/198955327-0e0b10ce-f1a0-45c4-b1cd-e0e7a32a19a8.png)

**Comment by Roemer** [comment]
> request done, if possible next time can you do the same in all one thread :)
Will do. Many thanks!
