### ISSUE TITLE
Duco ventilation icon

### ISSUE THREAD

**Issue by JDunnio** [elax46/custom-brand-icons#273]
Hi,

Is it possible to create an icon pack for the duco ventilation?

I would like to create something like in the attachment which is the control unit for my ventilation system.
duco-speed-1
duco-speed-2
duco-speed-3
duco-speed-auto (for font and theming?)
duco-logo

The attached logo is the nearest and best logo I could find.
Original (google duco icon waves): 
https://apps.apple.com/us/app/duco-ventilation/id1245700076

https://is5-ssl.mzstatic.com/image/thumb/Purple124/v4/aa/41/73/aa4173a8-f6f0-d319-faef-4e4a72602730/AppIcons-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1200x600wa.png

For the logo:
https://is4-ssl.mzstatic.com/image/thumb/Purple122/v4/96/88/e0/9688e0e4-b28e-8dd4-f687-0bf3a804d656/AppIcon-0-1x_U007emarketing-0-7-0-85-220.png/246x0w.webp

![200164914-20c91482-9522-4ae5-bb14-577055609182](https://user-images.githubusercontent.com/44028885/201508155-7a8d96a9-1840-4c32-8127-3319f7f9dba0.png)
![duco logo waves](https://user-images.githubusercontent.com/44028885/201508161-1fdba3f0-6000-4c27-b82a-8a19bc1b4087.png)

Help is greatly appreciated!

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/201607310-01b69371-1276-4e87-b6a8-1d7401e63598.png)
![image](https://user-images.githubusercontent.com/87599807/201607348-1d4498fc-ad31-4f73-93c9-093625ec6712.png)
![image](https://user-images.githubusercontent.com/87599807/201607380-1766d70c-491c-4dbe-a1fa-89e18357cd85.png)
![image](https://user-images.githubusercontent.com/87599807/201607402-f96fccf1-85c5-4228-b7ae-3a9e2951b348.png)
![image](https://user-images.githubusercontent.com/87599807/201607432-4e940222-0771-44e3-8fef-ef8edd0e0985.png)

**Comment by JDunnio** [comment]
Thanks a lot! 🙏
