### ISSUE TITLE
Icon won't show up 

### ISSUE THREAD

**Issue by sandrybridge** [elax46/custom-brand-icons#278]
I've updated the .js adding a new icon named cloudflare, however it doesn't show up no matter what. I've tried to empty the cache on windows and mobile device and I restarted the HA OS and the host but it still won't show up. I've created a fork under sandrybridge repos in wich i've putted the svg files and the .js. (the icon I'd like to render is the cloudflare one) Could you help me find out what's wrong please?

All the other custom icon are showing up correctly, it is only the icon i've added that won't, I've tried to substitute the string part of my custom svg with one of other svg already present  (and rendered) in the javascript but I've obtained the same result.

It's definitely my fault, however I wasn't able to open this issue with the lable "help wanted" wich is probably more appropriate

Thank you

**Comment by sandrybridge** [comment]
it seems to be a cache issue, I've tried to rename the .js and changed the name of it in lovelace resources and now I can see the icons I've added. i'm still wondering why it doesn't work with the proper name even if I clear the cache and restart the HA machine

**Comment by elax46** [comment]
I checked all the icons you have added to your fork and the related js file seems all correct, I believe that as you yourself said it is a matter of cache however the icons are ok so you can open a pull request to integrate them to the maximum release one version official test and let's see if the same problem arises.

**Comment by sandrybridge** [comment]
Ok, once I've added all the remaining icons in my fork I'll perform the pull request. 
The issue is definetly related to the cache, but it seems not resolvable, at least not by myself. 
One last question, for the README file, do you want the links to svg files to be set as your repository or will you change them once the tests will be completed? actually they are pointing to my fork, otherwise I wouldn't be able to see if everything is fine...
Thank you

**Comment by elax46** [comment]
change the path of the icons pointing to the original dev branch

**Comment by elax46** [comment]
The icons that are not visible are:

- openwrt-logo
- pfsense-logo
- ssd
- hdd
- truenas-logo

Furthermore, these icons are already available in mdi so it is useless to add them and they will be removed

- docker
- gdrive
- hdd

**Comment by sandrybridge** [comment]
![icons](https://user-images.githubusercontent.com/83014475/202225055-1437c1c8-2fcd-45ff-9677-a9bb133763b4.PNG)
Actually, I can see all of them.

**Comment by elax46** [comment]
Icons already present in `mdi ` are not added it is just a duplication

**Comment by elax46** [comment]
Icons added to the new version, thanks for your contribution

**Comment by sandrybridge** [comment]
it was a pleasure, see you next time
