### ISSUE TITLE
Shutter icons with percentage of opening

### ISSUE THREAD

**Issue by Scarpetta3** [elax46/custom-brand-icons#282]
Hello,
I want to ask you if it's possibile to add icons that represents the state of the shutter from 0% to 100% opened (10% interval).
I am refering to mdi:window-shutter.

Thank You very much: great work and great addition to the mdi icons!

**Comment by rchiileea** [comment]
I would say this is a bit crazy as 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100 a bit of work involved for this

**Comment by rchiileea** [comment]
![shutter-0](https://user-images.githubusercontent.com/87599807/203746731-930ad1c2-5560-426f-826a-fb75b2a0c610.gif)
this is what I presume you mean your after 11 icons to do this

**Comment by Scarpetta3** [comment]
First of all thank you for the answer.
this is what i was referring to, but if an overlapping number could be added upon the icon as well it would be perfect. I know it's a lot of work, sorry for that request. What I can say is that at the moment, for my needs, I should only use four: 10%, 25%, 50% and 75%.

Even if I don't know if you would do that: thank you in any case in advance.

**Comment by rchiileea** [comment]
I have created a full set from 0 to 100 in 10 percent spaces, but I have not added percentage, the reasoning behind this is that you can add this number by using a custom button card.
![shutter-0](https://user-images.githubusercontent.com/87599807/204125625-2b4dec17-e7b6-4941-be0a-0d456edc1fa4.svg)
![shutter-100](https://user-images.githubusercontent.com/87599807/204125626-eb20ef31-c9eb-4f8b-af76-a2b198e5576c.svg)
![shutter-90](https://user-images.githubusercontent.com/87599807/204125627-8014661f-3f57-4211-9e93-197c5c9cbd98.svg)
![shutter-80](https://user-images.githubusercontent.com/87599807/204125628-1ad2ff99-f89d-4e5c-b2a8-e8fd48136710.svg)
![shutter-70](https://user-images.githubusercontent.com/87599807/204125629-13f1051c-5ea6-4588-8907-2130e1c5d7c1.svg)
![shutter-60](https://user-images.githubusercontent.com/87599807/204125630-bcdaf62b-7e19-4492-84ed-c5c41691dbc5.svg)
![shutter-50](https://user-images.githubusercontent.com/87599807/204125631-a1967556-da54-4483-8fd1-89fbe7b7d707.svg)
![shutter-40](https://user-images.githubusercontent.com/87599807/204125632-a6705011-a49d-40ad-a80c-760ba84d7080.svg)
![shutter-30](https://user-images.githubusercontent.com/87599807/204125633-6e34da73-53df-4bf9-b8d2-1a718111e126.svg)
![shutter-20](https://user-images.githubusercontent.com/87599807/204125634-3258491d-0e94-4b94-9a8f-1cbeb7a6aa9a.svg)
![shutter-10](https://user-images.githubusercontent.com/87599807/204125635-865324dd-ec13-44bb-b272-2aa5757fc81c.svg)

[shutter.zip](https://github.com/elax46/custom-brand-icons/files/10097813/shutter.zip)
