### ISSUE TITLE
Custom Icon request ESPHome

### ISSUE THREAD

**Issue by bcutter** [elax46/custom-brand-icons#283]
ESPHome icon as `phu:esphome`
- https://raw.githubusercontent.com/esphome/home-assistant-addon/main/esphome-dev/icon.png
or (higher res):
- https://esphome.io/_images/logo.png

**Comment by elax46** [comment]
thanks for your report I fixed the problem in the dev branch

**Comment by elax46** [comment]
> > thanks for your report I fixed the problem in the dev branch
> 
> The "fix" is to list it on the https://github.com/elax46/custom-brand-icons page, right?

No will be available in the next merge is present in the [dev branch](https://github.com/elax46/custom-brand-icons/tree/dev#ha-addons)
