### ISSUE TITLE
Custom Icon request Umage Lamps

### ISSUE THREAD

**Issue by Rawet** [elax46/custom-brand-icons#285]
Umage make beautiful lamps, unfortunately i dont have any Illustrator skills.

Here are a few i would like to see
![](https://cdn.shopify.com/s/files/1/0342/2425/products/UMAGE_packshot_2041_Eosxx-large_white_d3003023-5851-4e6d-bc97-e89b30e8c547_600x.png?v=1649332828)
![](https://cdn.shopify.com/s/files/1/0342/2425/products/UMAGE_packshot_2031_Silviamini_copper_lowres_600x.png?v=1653909738)
![](https://cdn.shopify.com/s/files/1/0342/2425/products/UMAGE_packshot_2056_Carminamedium_white_f1914453-f4a0-40b0-8108-2fd6523f512a_600x.png?v=1635318635)
![](https://cdn.shopify.com/s/files/1/0342/2425/products/UMAGE_packshot_2105_Acorn_white_polishedbrass_2_600x.png?v=1619527693)
Please also add PH5
![](https://louispoulsen.azureedge.net/images/catalog-images/29684_29866_PH-5-All-White-22-2-5-90293.png?width=600&format=webp)

// Danish Lamp lover

**Comment by rchiileea** [comment]
those all would take some time, the top one though would be a no no, with all them points that one svg would be twice the size of the sonos ones which are probably are largest.

**Comment by elax46** [comment]
You consider these icons uninsertable if you close the request @rchiileea

**Comment by rchiileea** [comment]
@elax46 a couple of them will be fine @elax46 but with work commitments to insure I have christmas and new year off I be suprised if I get them done before the new year

**Comment by rchiileea** [comment]
am working on these have 2 done so far, just one more before uploaded

![image](https://user-images.githubusercontent.com/87599807/207292755-78a04e11-3c63-418d-9df2-d402750353e2.png)
![image](https://user-images.githubusercontent.com/87599807/207292824-136d8e55-865b-4dff-8ca7-baa0264ac23c.png)
