### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by ramodub9** [elax46/custom-brand-icons#29]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**
Philips White Ambiance EXPLORE Suspension

**Provide a URL that points to an image of this fixture/bulb**
https://www.amazon.fr/Philips-White-Ambiance-EXPLORE-Suspension/dp/B07D1JYYYL

Preferably icon photography, as they use a consistent angle.

**Additional context**

Add any other context for your icon request here.
Please if possible

**Comment by elax46** [comment]
Thanks for your request, the icon is available in the new version just released [1.0.17](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.17)

**Comment by ramodub9** [comment]
Surprise! It was fast. Thank you very much. I can send to paypalme/emanueleladaga?

**Comment by elax46** [comment]
Yes, if you want to support the project, thank you

**Comment by arallsopp** [comment]
No need to send any payment, @ramodub9. These original works were offered by their actual author under a creative commons non-commercial license and have always been free to use. In fact, you're free to do anything you want with the icons that were created, except for distribute them under your own license, fail to attribute their actual author, or collect any form of payment for them. 

Broadly, use them as you fancy, but don't steal them, pass them off as your own, and try to make money from it. That would be disingenuous, fraudulent, and a very real threat to the nature of the open source.
