### ISSUE TITLE
ZIDOO Custom Icon request

### ISSUE THREAD

**Issue by twitch86** [elax46/custom-brand-icons#290]
A Zidoo ICON for Misc would be great but im to stupid to get a proper .SVG

Here is a link to PNG
https://devicedb.roonlabs.net/1/images/43bf5aa6217b02340d3d1f54b17a6a1c5262d522.png

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/207299914-42074be5-14a7-4999-ba87-a4048e00151e.png)
[zidooo.zip](https://github.com/elax46/custom-brand-icons/files/10217138/zidooo.zip)

**Comment by twitch86** [comment]
Thank you so much!

**Comment by elax46** [comment]
> Thank you so much!

Thank you for support! @twitch86
