### ISSUE TITLE
My own custom icon does not appear

### ISSUE THREAD

**Issue by Mischa1975** [elax46/custom-brand-icons#292]
Hi,

I've successfully installed the CUSTOM BRANDS ICON and I am able to use the custom icons in HA. However I would like to add an additional icon for the BMW brand. This icon is available in SVG format online (https://www.svgviewer.dev/s/58022/bmw).

I have followed the steps ("Bollard": [0, 0, 24.0, 24.0, "string"]) as described in the README file and whilst it doesn't appear to show any errors, it doesn't appear as a usable icon.... I have tried so many things, can't figure it out myself.

I have added the path from (https://www.svgviewer.dev/s/58022/bmw) as the string in the custom-brand-icons.js file. However it doesn't seem to work. What am I doing wrong?

`"bmw":[0,0,24,24,"M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0zm0 .78C18.196.78 23.219 5.803 23.219 12c0 6.196-5.022 11.219-11.219 11.219C5.803 23.219.781 18.196.781 12S5.804.78 12 .78zm-.678.63c-.33.014-.66.042-.992.078l-.107 2.944a9.95 9.95 0 0 1 .71-.094l.07-1.988-.013-.137.043.13.664 1.489h.606l.664-1.488.04-.131-.01.137.07 1.988c.232.022.473.054.71.094l-.109-2.944a14.746 14.746 0 0 0-.992-.078l-.653 1.625-.023.12-.023-.12-.655-1.625zm6.696 1.824-1.543 2.428c.195.15.452.371.617.522l1.453-.754.092-.069-.069.094-.752 1.453c.163.175.398.458.53.63l2.43-1.544a16.135 16.135 0 0 0-.46-.568L18.777 6.44l-.105.092.078-.115.68-1.356-.48-.48-1.356.68-.115.078.091-.106 1.018-1.539c-.18-.152-.351-.291-.57-.46zM5.5 3.785c-.36.037-.638.283-1.393 1.125a18.97 18.97 0 0 0-.757.914l2.074 1.967c.687-.76.966-1.042 1.508-1.613.383-.405.6-.87.216-1.317-.208-.242-.558-.295-.85-.175l-.028.01.01-.026a.7.7 0 0 0-.243-.734.724.724 0 0 0-.537-.15zm.006.615c.136-.037.277.06.308.2.032.14-.056.272-.154.382-.22.25-1.031 1.098-1.031 1.098l-.402-.383c.417-.51.861-.974 1.062-1.158a.55.55 0 0 1 .217-.139zM12 4.883a7.114 7.114 0 0 0-7.08 6.388v.002a7.122 7.122 0 0 0 8.516 7.697 7.112 7.112 0 0 0 5.68-6.97A7.122 7.122 0 0 0 12 4.885v-.002zm-5.537.242c.047 0 .096.013.14.043.088.059.128.16.106.26-.026.119-.125.231-.205.318l-1.045 1.12-.42-.4s.787-.832 1.045-1.099c.102-.106.168-.17.238-.205a.331.331 0 0 1 .14-.037zM12 5.818A6.175 6.175 0 0 1 18.182 12H12v6.182A6.175 6.175 0 0 1 5.818 12H12V5.818z"],`

the above is just the starting line of the file (after  "var icons = {") - the rest is left untouched.

Even when I replicate existing (original) lines and give it my own name - they don't appear either as icons. So not sure whether the above string is even wrong. In all cases I have fully restarted HA.

thanks,
mischa

**Comment by elax46** [comment]
i think it's a cache problem however i checked that your icon is ok and i put it now in the dev branch

**Comment by Mischa1975** [comment]
Thanks Emanuele – it’s working now!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/207293434-96184469-c1ba-4d60-b174-920b16736757.png)
[bmw.zip](https://github.com/elax46/custom-brand-icons/files/10216917/bmw.zip)
alternate color version
