### ISSUE TITLE
Custom Icon request [Volvo]

### ISSUE THREAD

**Issue by andynash** [elax46/custom-brand-icons#295]
Great work on these icons! I see that Volvo is not yet included, hope this is what you need?

[This is the official download](https://pickitmedialive.blob.core.windows.net/lw65e30301zj76m-main/muAXxV49?sv=2020-10-02&st=2022-12-14T16%3A41%3A59Z&se=2022-12-14T17%3A11%3A59Z&sr=c&sp=r&sig=Kxr87S%2BtXhwRf8Lh3%2FaGvS5jYc1oaLfZ4CjSraWf5Jk%3D), linked to from [this Volvo Group website](https://www.volvogroup.com/experiencesystem/en/#/brand/615bfcc428c818001105b4e3/61652f5f8ea937001135220e/619518c01e4b9100128772a3?section=627a673a2c699016fc67ff25).

In the Artworks folder are two versions:

Volvo Iron Mark - Black.svg (for light background)

![Volvo Iron Mark - Black](https://user-images.githubusercontent.com/1126073/207662644-07b34edc-c7df-40ac-904c-8146091b7f45.svg)

Volvo Iron Mark - White.svg (for dark background, I guess the "-alt" version, as you've done for BMW? Obvs you won't be able to see this)

![Volvo Iron Mark - White](https://user-images.githubusercontent.com/1126073/207662635-f1b9faf4-70e0-4b95-9b81-248a2c71921c.svg)

**Comment by rchiileea** [comment]
funny enough white and black is taken care of by ha, if you choose a light theme it will be black, if you choose a dark theme it willl be white, the BMW is two different viersions due to a outline of logo instead so its more a normal and hollow version offered.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/207810676-bd5f8ca9-82dc-4dd5-a236-a70aa6640d66.png)
![image](https://user-images.githubusercontent.com/87599807/207810747-2a72f5bb-5427-42d6-81e5-822151e9b42d.png)
[volvo.zip](https://github.com/elax46/custom-brand-icons/files/10235179/volvo.zip)

**Comment by rchiileea** [comment]
the outline version I would advise using card mod with in a drop shaddow style under icon to make it pop.

**Comment by andynash** [comment]
Perfect, super-fast response and nicely done!

**Comment by andynash** [comment]
I've noticed this hasn't made it into the integration yet, perhaps closing it myself took it off your radar, sorry!

**Comment by elax46** [comment]
I'm sorry but having closed the request I missed the insertion of the icons

**Comment by andynash** [comment]
Hi @elax46, I'm still not seeing the Volvo icon in the integration, has it definitely been added?

Thanks!

**Comment by elax46** [comment]
> Hi @elax46, I'm still not seeing the Volvo icon in the integration, has it definitely been added?
> 
> Thanks!

the icon is available and it was added quite some time ago I remind you that you have to update the integration to the latest available version

**Comment by andynash** [comment]
Apologies, you are right! I had been looking at the changelog each time but had not seen it added, I must have missed it.
