### ISSUE TITLE
Custom Icon request [Electric Blanket]

### ISSUE THREAD

**Issue by oneseventhree** [elax46/custom-brand-icons#296]
Two versions of an electric blanket

Electric Blanket:
![electric-blanket](https://user-images.githubusercontent.com/15043282/207767712-add5a628-f3f4-4e93-b6eb-2cf5a07f2968.svg)

Electric Blanket - Person:
![electric-blanket-person](https://user-images.githubusercontent.com/15043282/207767729-3241aea4-ff70-4eda-a0f2-4ad8a6703206.svg)

Edit: Unsure why it didn't work so I zipped it:
[ElectricBlanket.zip](https://github.com/elax46/custom-brand-icons/files/10233564/ElectricBlanket.zip)

**Comment by rchiileea** [comment]
yep it still does not work because, all you have really done is place a jpg and save it to a svg, svg files dont work like that they are lines and points, not just a svg copied or saved from a jpg. better to upload the jpg's to seeif they are doable or even try to draw using inscape what your after

**Comment by oneseventhree** [comment]
> to

Thanks for that. I've used Inkscape - let me know if these work:

White:
![Electric-Blanket-White](https://user-images.githubusercontent.com/15043282/209253982-e1d606b1-0393-4e4c-8151-ca3afa7d2697.svg)


Black:
![Electric-Blanket-Black](https://user-images.githubusercontent.com/15043282/209254000-52c31a6d-9462-4a08-8d8c-419da8d43821.svg)

**Comment by oneseventhree** [comment]
> yep it still does not work because, all you have really done is place a jpg and save it to a svg, svg files dont work like that they are lines and points, not just a svg copied or saved from a jpg. better to upload the jpg's to seeif they are doable or even try to draw using inscape what your after

Thanks for that - I did them in Inkscape. Let me know if it works:

White:
![Electric-Blanket-White](https://user-images.githubusercontent.com/15043282/209254125-d83a4bc2-1557-49b0-8887-645f0759a9fb.svg)


Black:
![Electric-Blanket-Black](https://user-images.githubusercontent.com/15043282/209254141-76151792-d1ac-4fa8-83f7-666c9e51ae83.svg)

**Comment by rchiileea** [comment]
these icons are not proper SVG icons, just png's added into a svg file no draw lines, plus the one you have given us is copyrighted, so I made one from scratch 

![image](https://user-images.githubusercontent.com/87599807/210336844-1edf308d-b6ad-4000-b3c0-1aa5dd8936b7.png)

**Comment by oneseventhree** [comment]
> these icons are not proper SVG icons, just png's added into a svg file no draw lines, plus the one you have given us is copyrighted, so I made one from scratch
> 
> ![image](https://user-images.githubusercontent.com/87599807/210336844-1edf308d-b6ad-4000-b3c0-1aa5dd8936b7.png)

thats even BETTER! thank you so much :)

**Comment by rchiileea** [comment]
re opened we will close once we intergrate it :)
