### ISSUE TITLE
Custom Icon request [Radio stations Logo's]

### ISSUE THREAD

**Issue by jrspowers** [elax46/custom-brand-icons#298]
hello 

would it be possible to make this 3 radio transmitter icon out of this so very useful for my dashboard? thanks in advance! 

1.Radio MNM
2.Radio Qmusic
3.Radio TopRadio

[radio icons](https://mega.nz/folder/i1xylACR#ONEwpJiOMM5_W5WpYCczdw)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/210336420-a910f07e-b0e0-466f-90bc-b62bcd744416.png)
![image](https://user-images.githubusercontent.com/87599807/210336451-9c80b81a-b90b-4981-ab87-c6ce557dce1f.png)
![image](https://user-images.githubusercontent.com/87599807/210336485-faa98349-ce47-4cae-9fea-9f94a443a13e.png)

**Comment by jrspowers** [comment]
Thanks man !
