### ISSUE TITLE
Custom Icon request [Robot Vacuum Replacement Parts]

### ISSUE THREAD

**Issue by jonathanathe** [elax46/custom-brand-icons#299]
Hello, I tell you my idea, more and more people I know that I have as I include myself have a robot vacuum cleaner. The robots that we have can be connected to Home Assistant, the entities that are included in many occasions are the remaining time left to be able to change the parts ( Main Brush, Left Brush...) I include a picture of the items that I would like to have and in the future you could always create more if you see that it is necessary for this great project.

![Screenshot_2022-12-25-18-46-24-591_com.alibaba.aliexpresshd-edit.jpg](https://user-images.githubusercontent.com/34164094/209478063-c0a40915-348c-40d0-a562-b38dc7607beb.jpg)

Thank you very much for this project and everyone's dedication!

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/210335891-dfad834a-e261-4344-82a0-7fccbcbb2b5e.png)
![image](https://user-images.githubusercontent.com/87599807/210335916-9b23239c-ae91-46fa-836d-843ba6f0b783.png)
![image](https://user-images.githubusercontent.com/87599807/210335939-81410e1e-da1c-4e9a-8937-4ed608de394f.png)
![image](https://user-images.githubusercontent.com/87599807/210335960-eb934f72-0684-489a-9d15-047ff6adf94a.png)

**Comment by jonathanathe** [comment]
> ![image](https://user-images.githubusercontent.com/87599807/210335891-dfad834a-e261-4344-82a0-7fccbcbb2b5e.png) ![image](https://user-images.githubusercontent.com/87599807/210335916-9b23239c-ae91-46fa-836d-843ba6f0b783.png) ![image](https://user-images.githubusercontent.com/87599807/210335939-81410e1e-da1c-4e9a-8937-4ed608de394f.png) ![image](https://user-images.githubusercontent.com/87599807/210335960-eb934f72-0684-489a-9d15-047ff6adf94a.png)

That would be perfect! Thank you again for your dedication.
