### ISSUE TITLE
roomsOutdoor (Garden) not listed in list of options

### ISSUE THREAD

**Issue by sjikkervisje** [elax46/custom-brand-icons#3]
I could not find the garding icon in the list of names you can use to get the icon. I tried some variations and then "phu:roomsOutdoor" seems to work as the icon does show. Please update the information so others can find this. Perhaps also check if any other icon names have not been posted in this repository.

**Comment by elax46** [comment]
I used the names entered by the philips developer channel, corrected the documentation
