### ISSUE TITLE
Custom Icon request [WP Pilot]

### ISSUE THREAD

**Issue by ArekKubacki** [elax46/custom-brand-icons#301]
![logo_wp-pilot](https://user-images.githubusercontent.com/5568263/210079883-add83aa9-b109-45ee-b066-c7c77d78dfaf.svg)

Polish streaming platform logo. Please add to the library.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/210336377-e4ca2599-6ee4-4975-8edb-e86af49cc0ee.png)

**Comment by ArekKubacki** [comment]
Thank you.
