### ISSUE TITLE
Custom Icon request [Radio stations Logo's]

### ISSUE THREAD

**Issue by jrspowers** [elax46/custom-brand-icons#311]
hello 

would it be possible to make this 3 radio transmitter icon out of this so very useful for my dashboard? thanks in advance! 

1.Topradio Techno
2.Topradio Versuz
3.Topradio Retroarena

[radio icons](https://mega.nz/folder/i1xylACR#ONEwpJiOMM5_W5WpYCczdw)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/212954883-7c77f21a-8bbf-423b-b4a0-7629eb8b3627.png)
![image](https://user-images.githubusercontent.com/87599807/212954922-105bb4ce-4221-4235-a3f0-7059550ad4dd.png)
![image](https://user-images.githubusercontent.com/87599807/212954955-7e5fcec5-d21c-4c26-aec9-733e62041753.png)
