### ISSUE TITLE
Delivery Service Icons

### ISSUE THREAD

**Issue by tj335** [elax46/custom-brand-icons#313]
Request icons for FedEx, UPS, and USPS to help support the creation of a custom card to use with the Mail and Packages integration.

**Comment by rchiileea** [comment]
please provide examples

**Comment by elax46** [comment]
If you do not add the images I will be forced to consider your request void and proceed with the closure @tj335

**Comment by tj335** [comment]
![AE490D32-9C04-45E1-ABA5-9F92DFD72A4D](https://user-images.githubusercontent.com/105184198/213830920-f447a637-37c6-491c-b2a7-0854e5e2c85e.png)
![8B819246-786F-440C-B7D0-0CFF13CE5F6C](https://user-images.githubusercontent.com/105184198/213830921-43d7989a-e0e7-4350-aef7-36a0897ea832.png)
![38DD0414-370D-4C65-A0DB-B6F64B1B3D6F](https://user-images.githubusercontent.com/105184198/213830922-f945bb43-48b1-4bc2-910a-73f5a1320e1d.jpeg)
![97E3FEE3-2353-41B6-9D7B-180A746CDC21](https://user-images.githubusercontent.com/105184198/213830924-dd71ef74-4462-44b9-90d7-e1db51d7dd78.jpeg)
![F4E070C0-9873-47FF-ACAC-4448CD0A48E0](https://user-images.githubusercontent.com/105184198/213830925-3535d308-9051-4c84-be2f-4b02a3a00faa.png)

**Comment by tj335** [comment]
Added the images with two variations for the USPS, not sure if either of those could be used.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/214830803-0ad29b3f-d43c-49f6-8ba7-e785d89e5611.png)
![image](https://user-images.githubusercontent.com/87599807/214830834-a742ecae-39ba-47aa-9f2e-fcf0ce3bbb3d.png)
![image](https://user-images.githubusercontent.com/87599807/214830855-2ad1d491-4c40-47cb-8d7e-09852da91ddc.png)
![image](https://user-images.githubusercontent.com/87599807/214830876-aacbd149-880e-4afe-b60e-f9d46f5d4cb0.png)
![image](https://user-images.githubusercontent.com/87599807/214830942-89706cb4-a35f-4fde-8e56-27bf4966af26.png)

there is already a amazon icon its the A with the smile tick under it.
