### ISSUE TITLE
Custom Icon request [MolotovTV]

### ISSUE THREAD

**Issue by HydrelioxGitHub** [elax46/custom-brand-icons#316]
**https://upload.wikimedia.org/wikipedia/fr/3/3d/Molotov.svg**

I don't know if it can be accepted as an icon. 

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/212954731-dca64834-4042-4859-b2e9-f5c33895b34c.png)
