### ISSUE TITLE
Custom Icon request [Remote Control Ikea]

### ISSUE THREAD

**Issue by jonathanathe** [elax46/custom-brand-icons#317]
Hello, continuing with the Ikea devices already included, I would like if it is possible for you to create two remote controls that are very cheap and useful for many automations. Here are 2 photos of the two remote controls.

Thank you very much for your help and for this project.

![image](https://user-images.githubusercontent.com/34164094/211169525-34ded8d2-6692-4ec2-8bce-d5d515b2d5c9.jpeg)

![image](https://user-images.githubusercontent.com/34164094/211169537-a48c12cf-3803-4932-b13e-4afc2ad56541.jpeg)

**Comment by rchiileea** [comment]
I think doing these would be a bit crazy as it might start adding requests for more stuff like this in future, but dont worry ill get them done still in the not to distant future @elax46 can you leave this request open so I can get these done some time this week

**Comment by jonathanathe** [comment]
> I think doing these would be a bit crazy as it might start adding requests for more stuff like this in future, but dont worry ill get them done still in the not to distant future @elax46 can you leave this request open so I can get these done some time this week

Thank you very much! I wanted to tell you to be careful with the size that the icon will have when it is seen in small to avoid problems as indicated in [this request] (https://github.com/elax46/custom-brand-icons/issues/319). I will also take into account your comment for my future requests and not open certain icons. Thank you again for your great work!

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/214830604-9101dc0e-993a-471a-99c4-2d25c4880619.png)
![image](https://user-images.githubusercontent.com/87599807/214830660-849da0e1-af98-4bcf-a832-48efdfae68e4.png)

**Comment by jonathanathe** [comment]
It's perfect! Thank you @rchiileea
