### ISSUE TITLE
Custom Icon request [IKEA PS 2014]

### ISSUE THREAD

**Issue by adamlc** [elax46/custom-brand-icons#318]
Thanks for this great project.

If possible I'd love to see the Ikea "Deathstar" pendant light added! Because of the crazy geometric shapes this could be a tricky one!

![image](https://user-images.githubusercontent.com/809944/211805182-122067d2-87d9-40da-bfaf-5e0f0bf86e60.png)

![image](https://user-images.githubusercontent.com/809944/211805229-97a15881-be0d-4221-84da-63c71b60217f.png)

![image](https://user-images.githubusercontent.com/809944/211805262-67114a01-8d44-4b37-8359-73939da51e75.png)

**Comment by rchiileea** [comment]
lol thats a challange, ill take a look next week when i am back from trip

**Comment by rchiileea** [comment]
only 2 icons one for open and close
![image](https://user-images.githubusercontent.com/87599807/212954087-6fa3d5e6-eae0-4742-9cec-131c4ec7bf35.png)
![image](https://user-images.githubusercontent.com/87599807/212954126-a6cfcbf1-8fde-4369-841d-29d0903a1417.png)

**Comment by adamlc** [comment]
These are awesome! Thanks for taking the time to do this! 👍
