### ISSUE TITLE
Bug Report - Icons too small

### ISSUE THREAD

**Issue by jonathanathe** [elax46/custom-brand-icons#319]
Hello!

I wanted to comment that I don't know if I'm the only one but I see that many times the icon appears very small, if you compare them with other people's icon packs. It even causes that some icons you can't see exactly what it is.

Here is a comparison:

![image](https://user-images.githubusercontent.com/34164094/211854400-eaee55f5-ad7f-42f6-a572-0105be2dbcb5.png)
![image](https://user-images.githubusercontent.com/34164094/211854627-30ace448-35dd-46ab-ad05-100553a459d8.png)

*Custom-Brand-Icons icon is always the second one shown in the picture*.
Some of these are: 

- The new "Vacuum Parts" pack
- phu:chicken-coup-door-shut
- Alexa icon could be bigger.
- phu:bbc - I think if it's made a bit bigger it would be clearer.
- phu:stage-light-group
- phu:umage

This only happens on cards where the icon appears small like on the automation page, scripts and also when choosing the type: entities.

Thanks in advance for your great work in this community!

**Comment by elax46** [comment]
Icon sizes are all fixed at 24x24. There are some icons that were added at the beginning of the project and therefore the size needs to be rearranged. For this I ask the help of @rchiileea  to update the size of the `alexa-logo` icon. All other icons you indicate have the default size. I let @rchiileea  evaluate whether it is appropriate to make them larger since he is the author

**Comment by jonathanathe** [comment]
Good morning,

Thank you very much for your reply and I am waiting for @rchiileea to indicate if in the end he considers that the icons should be made bigger.

Thank you. Regards.

**Comment by rchiileea** [comment]
the only way of doing this was enlarging some items, and have to distort a few things, for vac spares It was a case of stacking them up.

I stretched it up as its at full width so stretched upwards to enlarge
![image](https://user-images.githubusercontent.com/87599807/212964208-620bfa06-5686-4342-ae0f-ca0b7264a063.png)

this is full width so made the padlock really large
![image](https://user-images.githubusercontent.com/87599807/212964287-8e1e8887-42db-46c5-8f32-5dc99013ae45.png)

I stretched it up as its at full width so stretched upwards to enlarge
![image](https://user-images.githubusercontent.com/87599807/212964615-7b885842-22fa-4b2b-abe9-94d1ff3ad2bc.png)

I stretched it up as its at full width so stretched upwards to enlarge
![image](https://user-images.githubusercontent.com/87599807/212964722-db98dfe7-ac05-499b-98b5-785eae09c43b.png)

I added stroke to the alexa to thicken it up 
![image](https://user-images.githubusercontent.com/87599807/212964858-039d52dd-598c-4c32-81e6-65fabb25c0b4.png)

combined 3 vac main brush to thicken logo up 
![image](https://user-images.githubusercontent.com/87599807/212965017-8f9b826d-9b3c-4ce6-bf1a-e64bea377364.png)

rotated the mops to and stretched them
![image](https://user-images.githubusercontent.com/87599807/212965111-a9c6c32e-504f-4229-8380-daa3c71db512.png)

stroked the side brush
![image](https://user-images.githubusercontent.com/87599807/212965206-4beb3b47-7df3-414b-a172-fc5d4b06916a.png)

**Comment by jonathanathe** [comment]
> the only way of doing this was enlarging some items, and have to distort a few things, for vac spares It was a case of stacking them up.
> 
> I stretched it up as its at full width so stretched upwards to enlarge
> ![image](https://user-images.githubusercontent.com/87599807/212964208-620bfa06-5686-4342-ae0f-ca0b7264a063.png)
> 
> this is full width so made the padlock really large
> ![image](https://user-images.githubusercontent.com/87599807/212964287-8e1e8887-42db-46c5-8f32-5dc99013ae45.png)
> 
> I stretched it up as its at full width so stretched upwards to enlarge
> ![image](https://user-images.githubusercontent.com/87599807/212964615-7b885842-22fa-4b2b-abe9-94d1ff3ad2bc.png)
> 
> I stretched it up as its at full width so stretched upwards to enlarge
> ![image](https://user-images.githubusercontent.com/87599807/212964722-db98dfe7-ac05-499b-98b5-785eae09c43b.png)
> 
> I added stroke to the alexa to thicken it up 
> ![image](https://user-images.githubusercontent.com/87599807/212964858-039d52dd-598c-4c32-81e6-65fabb25c0b4.png)
> 
> combined 3 vac main brush to thicken logo up 
> ![image](https://user-images.githubusercontent.com/87599807/212965017-8f9b826d-9b3c-4ce6-bf1a-e64bea377364.png)
> 
> rotated the mops to and stretched them
> ![image](https://user-images.githubusercontent.com/87599807/212965111-a9c6c32e-504f-4229-8380-daa3c71db512.png)
> 
> stroked the side brush
> ![image](https://user-images.githubusercontent.com/87599807/212965206-4beb3b47-7df3-414b-a172-fc5d4b06916a.png)
> 

Sounds good to me, thank you very much and I'm waiting for it to appear published!
