### ISSUE TITLE
Custom Icon request [TV Networks: ABC, NBC]

### ISSUE THREAD

**Issue by JustApu** [elax46/custom-brand-icons#321]
ABC: https://worldvectorlogo.com/logo/abc-broadcast

NBC: https://worldvectorlogo.com/logo/nbc

**Comment by JustApu** [comment]
MeTV: https://commons.wikimedia.org/wiki/File:MeTV_Logo.svg

PBS: https://www.vectorlogo.zone/logos/pbs/index.html

P.S. I see the instructions on how to contribute more icons myself but I'm not completely sure how to create the string from the SVG file. If you could perhaps create a short tutorial on all the steps, I'm happy to try to contribute more icons.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/212953541-d0f0ce0d-7dd4-47bd-81ed-1eafba9e142c.png)
![image](https://user-images.githubusercontent.com/87599807/212953601-5092b8a5-3119-41f9-8368-a795fdfd8de5.png)

**Comment by JustApu** [comment]
@rchiileea @elax46 Thank you.

FYI, "plus.svg" should probably be named "pbs.svg" ("Public Broadcasting Service")
