### ISSUE TITLE
Custom Icon request [Pedestal Fan]

### ISSUE THREAD

**Issue by oneseventhree** [elax46/custom-brand-icons#322]
![pedestal-fan](https://user-images.githubusercontent.com/15043282/212320966-128ced36-31ca-4390-9d40-9557557f4a8f.svg)

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by sumur1au** [comment]
@rchiileea @elax46 . Thanks a lot for making the custom icon. The icon is quite small when rendered in Lovelace, as a suggestion we could crop the icon at a (1/3) or (1/2) of the current height and enlarge it.

**Comment by rchiileea** [comment]
square: true
columns: 1
type: grid
cards:
  - type: picture-elements
    image: /local/blank1.png
    elements:
      - type: custom:button-card
        entity: light.hue_iris_1
        icon: phu:pedastal-fan-hollow
        show_name: false
        style:
          top: 80%
          left: 50%
          width: 240%
      - type: custom:button-card
        entity: light.hue_iris_1
        icon: phu:fan-blade
        tap_action:
          action: toggle
          haptic: medium
        hold_action:
          action: more-info
          haptic: medium
        styles:
          card:
            - background-color: transparent
            - box-shadow: none
          grid:
            - grid-template-areas: '"i" "n"'
            - grid-template-columns: 1fr
          name:
            - color: white
        state:
          - value: 'on'
            styles:
              icon:
                - animation: rotating 1s linear infinite
                - filter: drop-shadow(0px 0px 4px teal) drop-shadow(0px 0px 4px teal)
        style:
          top: 37.9%
          left: 49.4%
          width: 90%
    style: |
      ha-card {
        box-shadow: none;
      }
but then you wont be able to make a button that resizes like this  code does 
![CPT2301200845-535x500](https://user-images.githubusercontent.com/87599807/213653570-6bad4c72-647f-4c29-928a-95498803f01e.gif)

although i need to fix the fan blade

but i could redo the solid one

**Comment by rchiileea** [comment]
[pedastal replacements.zip](https://github.com/elax46/custom-brand-icons/files/10464942/pedastal.replacements.zip)
