### ISSUE TITLE
Custom Icon request [intel-nuc]

### ISSUE THREAD

**Issue by ingeniumdesign** [elax46/custom-brand-icons#333]
The 3D Icon from the Intel NUC is not so good.

Can you create a INTEL NUC Frontside?

this is a webp File: 141287958_intel-nuclight.webp
https://forums.unraid.net/uploads/monthly_2020_11/141287958_intel-nuclight.png.902fca46fb1eacc575e96c55ea42182a.png

**Comment by elax46** [comment]
The requested icon is already present

**Comment by ingeniumdesign** [comment]
a second icon would be perfect.
The icons are partly too small and have too many details

**Comment by rchiileea** [comment]
> a second icon would be perfect. The icons are partly too small and have too many details

we are keeping the 3D one but I have made it more solid

![image](https://user-images.githubusercontent.com/87599807/214830351-3daad290-8af2-4ca9-bd78-f40cdc98e2c8.png)
