### ISSUE TITLE
Custom Icon request ceiling fan from below

### ISSUE THREAD

**Issue by mattbruman** [elax46/custom-brand-icons#336]
https://www.castleresorts.com/images/icons/Ceiling-Fan.svg

Can we get a icon kinda like this for ceiling fans so when its animated it looks like a ceiling fan and not a other kind of fan?

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/214830226-3a25b59b-b2c4-4960-9a98-216574057c45.png)
