### ISSUE TITLE
Custom Icon request Formula1

### ISSUE THREAD

**Issue by Dominic-070** [elax46/custom-brand-icons#337]
It would be very nice to have the Formula 1 logo.

https://upload.wikimedia.org/wikipedia/commons/3/33/F1.svg

![F1](https://user-images.githubusercontent.com/62623885/214809341-28adcd4a-5e03-44aa-9689-9989cd259c82.svg)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/214831950-aaa82bf7-0218-4de6-a121-f62277895746.png)
