### ISSUE TITLE
Proxmox icon removed on 2023.1.5

### ISSUE THREAD

**Issue by myopenflixr** [elax46/custom-brand-icons#339]
Hello,

It appears that the `Proxmox` icon might have accidentally been deleted on the last Release.

And looking over the changes/diff, it looks like the `raspberry-pi` icon was also deleted as well.

Not sure if this was intentional or accidental but any chance of having these added back in during the next release?

Thanks!

**Comment by elax46** [comment]
the deletion is completely accidental I have already fixed the thing
