### ISSUE TITLE
Change log display in HA

### ISSUE THREAD

**Issue by SinnoTech** [elax46/custom-brand-icons#341]
Hej! Great work!

Would love to see in HA when updating what is being done without looking at the issues in github. 
Similar to what hass hue icons does?

![image](https://user-images.githubusercontent.com/74432416/215177284-a9abe28f-485a-4c49-9fd9-4d26647f359e.png)

**Comment by elax46** [comment]
In previous versions it was done but lately we are releasing versions with 40/60 new icons icons so it is difficult to insert them all I will soon try to return to the same pattern [v1.0.87](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.87)
