### ISSUE TITLE
Custom Icon request [Sonos Play:3]

### ISSUE THREAD

**Issue by CasparTheBridge** [elax46/custom-brand-icons#342]
Would you like to add an icon for the Sonos Play:3 speaker?

I've created an svg from a picture:
https://github.com/CasparTheBridge/SVG-Icons/blob/main/Sonos%20Play3.svg

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/216974622-27d585f4-5e27-4258-af2e-95b9db7f4b60.png)

**Comment by CasparTheBridge** [comment]
Nice!
