### ISSUE TITLE
Custom Icon request [Sonos Port]

### ISSUE THREAD

**Issue by CasparTheBridge** [elax46/custom-brand-icons#343]
Would you like to add an icon for the Sonos Port media player?

I've created an svg from a picture:
https://github.com/CasparTheBridge/SVG-Icons/blob/main/Sonos%20Port.svg

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/216974566-e84818b6-2fa8-43e8-8976-3171172e6dfe.png)

**Comment by CasparTheBridge** [comment]
Thank you!
