### ISSUE TITLE
Custom Icon request [VictoriaMetrics]

### ISSUE THREAD

**Issue by Roemer** [elax46/custom-brand-icons#344]
Would be great to have VictoriaMetrics added as well.

https://upload.wikimedia.org/wikipedia/commons/c/c6/VictoriaMetrics_logo.svg

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/216974492-2e5d1f61-6f20-41c5-9282-d3b45426d153.png)
