### ISSUE TITLE
Custom Icon request [Voron] 

### ISSUE THREAD

**Issue by Mosher23** [elax46/custom-brand-icons#350]
Hello could you please add this icon? 

It is a logo for Voron 3D printers

https://github.com/VoronDesign/Voron-Extras/blob/main/Images/Logo/Hex_Logo.svg

Thank you

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/220402530-8d6cb99e-8698-4fed-8299-ac4c27453565.png)
I had to widen it to fit right otherwise it would be invisible

**Comment by Mosher23** [comment]
> ![image](https://user-images.githubusercontent.com/87599807/220402530-8d6cb99e-8698-4fed-8299-ac4c27453565.png) 
I had to widen it to fit right otherwise it would be invisible

Hello, could you please fix it, the logo should be filled, like on image below.
Thank you
<img width="118" alt="Screenshot 2023-02-22 at 16 40 12" src="https://user-images.githubusercontent.com/8256425/220674509-8d375088-2f6b-43b2-a145-d714128e837c.png">

**Comment by elax46** [comment]
> > ![image](https://user-images.githubusercontent.com/87599807/220402530-8d6cb99e-8698-4fed-8299-ac4c27453565.png)
> > I had to widen it to fit right otherwise it would be invisible
> 
> Hello, could you please fix it, the logo should be filled, like on image below. Thank you <img alt="Screenshot 2023-02-22 at 16 40 12" width="118" src="https://user-images.githubusercontent.com/8256425/220674509-8d375088-2f6b-43b2-a145-d714128e837c.png">

@rchiileea

**Comment by rchiileea** [comment]
That’s not the least go you uploaded?? I got the logo as just skinny black out lines

**Comment by rchiileea** [comment]
![9CF3291F-5B73-4854-9D84-AA4187E29D73](https://user-images.githubusercontent.com/87599807/220893039-900eea53-42ea-445f-8d43-c67baab57557.jpeg)

That’s what you uplaoded

**Comment by Mosher23** [comment]
Hi,
I am sorry for confusion. The logo I have share is from official Github of Voron community. I do not know why it doesn't have filled inner space.
Here is the official website. https://vorondesign.com/
You can see that the logo is filled.

Again, sorry for misunderstanding

**Comment by Mosher23** [comment]
First time dealing with SVG.
Please check if it is correctly done.

![Voron_Logo filled](https://user-images.githubusercontent.com/8256425/222674650-a8854ac0-9931-4f68-b810-cde0eaf60f6e.svg)
<img width="824" alt="Screenshot 2023-03-03 at 09 52 52" src="https://user-images.githubusercontent.com/8256425/222675657-739e898f-3e5e-4b77-8711-25464804d239.png">

**Comment by elax46** [comment]
I close the request given the evaluation of @rchiileea

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/224971248-b9e93d4a-084b-4177-bc57-4bfe2ece9b7e.png)
