### ISSUE TITLE
Custom Icon request [Mainsail]

### ISSUE THREAD

**Issue by Mosher23** [elax46/custom-brand-icons#351]
Hello,

could you please add this icon?
Its a front end for 3D-Printers

https://github.com/mainsail-crew/mainsail/blob/develop/public/img/logo.svg

Thank you

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/220402470-e1781f20-2b3f-4f76-8083-58c24f009db7.png)
