### ISSUE TITLE
Custom Icon request [Atresplayer, Orange Tv]

### ISSUE THREAD

**Issue by jonathanathe** [elax46/custom-brand-icons#352]
Hello, I would like to ask you for the following TV icons. Both belong to Fire Tv applications.

Atresplayer: Popular Spanish TV Channels

![ Image](https://user-images.githubusercontent.com/34164094/218268636-ab7dcd3b-3b8a-49a1-9022-c499b57f163f.jpeg)

Orange Tv: Application belonging to Orange.

![ Image](https://user-images.githubusercontent.com/34164094/218268670-f422382a-86aa-4895-b906-563fb702374c.png)

Thank you very much for your help!

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/220402310-738ba9c2-3249-4b41-aea4-4385ea729b3b.png)
![image](https://user-images.githubusercontent.com/87599807/220402356-530ee73f-61b1-46d6-a6b4-466e87e1e571.png)

**Comment by jonathanathe** [comment]
It’s perfect, thank you very much as always!
