### ISSUE TITLE
Custom Icon request [MG]

### ISSUE THREAD

**Issue by JasSmiths** [elax46/custom-brand-icons#353]
![clipart3547474](https://user-images.githubusercontent.com/34107308/218316389-f9355420-ed2c-423b-8cc5-9000997d2370.png)

Car Manufacturer MG.

Any further info required let me know.

Thanks

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/220402772-8c6d3161-971f-484e-84d7-ec0a68b5ecbb.png)
