### ISSUE TITLE
Hyundai  Logo

### ISSUE THREAD

**Issue by RASBR** [elax46/custom-brand-icons#355]
Hi,
May I ask to have Hyundai logo variant showing the Logo only without the brand?

Thank you
R.S.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/220403009-77e17374-9eeb-4cbd-910d-768cfeab8851.png)

**Comment by RASBR** [comment]
This is great. has it been added to the package? or will it be in the next update?
