### ISSUE TITLE
Custom Icon request [DirectTV Stream]

### ISSUE THREAD

**Issue by mdb17** [elax46/custom-brand-icons#356]
(https://commons.wikimedia.org/wiki/File:DIRECTV_STREAM_2021_logo.svg)

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/220402861-68ed3c22-94cb-44a2-9412-ec6a2fdb4ed5.png)
I enlarged the stream text so it would be more visible on a button

**Comment by mdb17** [comment]
That’s awesome! Their iOS app just uses the “D” part if you think that works better
