### ISSUE TITLE
Custom Icon request: Echo Show 5 & 8

### ISSUE THREAD

**Issue by govido** [elax46/custom-brand-icons#36]
Hi,

I just created Echo Show 5 & 8 icons since they are missing right now.
If you want you can use them to add to the collection.
Created from the Amazon images and edited via Inkscape.

![path1133](https://user-images.githubusercontent.com/12106056/131370593-4dd99aa7-3cf5-4b8e-8035-2ddc521356fd.png)
![path572](https://user-images.githubusercontent.com/12106056/131370595-561cc1fe-ba34-4713-98a3-2a0f238a6971.png)
[Echo Show 5 & 8 SVG.zip](https://github.com/elax46/custom-brand-icons/files/7078024/Echo.Show.5.8.SVG.zip)

**Comment by elax46** [comment]
Thanks for providing the icons. Already available in the new version [1.0.21](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.21)
