### ISSUE TITLE
Icon for Magenta TV

### ISSUE THREAD

**Issue by GunterAv** [elax46/custom-brand-icons#362]
Hello,

here is my icon for the German Magenta TV for [https://github.com/elax46/custom-brand-icons#television](url)
If you want you can add it.

![magentatv](https://user-images.githubusercontent.com/87611027/221417107-ed1d9ab3-457c-478f-bf2a-7aabad311621.svg)

Best regards
Gunter

**Comment by GunterAv** [comment]
Hello,

I have adjusted the icon again.
![magentatv](https://user-images.githubusercontent.com/87611027/221585878-a72fe718-5aa6-4b0d-96eb-12ebbd4ef4e3.svg)

Best regards
Gunter

**Comment by rchiileea** [comment]
choose two of these you would like?

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/224971044-a757478a-2ff8-4551-8231-65ef511622c9.png)
![image](https://user-images.githubusercontent.com/87599807/224971086-e3697e87-4f79-44a2-a316-38b357ed0a4e.png)
