### ISSUE TITLE
Custom Icon request [Formula 1]

### ISSUE THREAD

**Issue by Art3mis0940** [elax46/custom-brand-icons#364]
Hi!
Could you add this icons?

![simple-icons_f1](https://user-images.githubusercontent.com/98536934/222669088-91f762dc-27e5-4b2f-8bb9-2b4b18eecbfe.svg)
![arcticons_f1-tv](https://user-images.githubusercontent.com/98536934/222669092-b80180d2-d697-413a-9cf3-f42a3f99bc4f.svg)

Thanks!

**Comment by elax46** [comment]
the icon is already present `phu:f1`

**Comment by Art3mis0940** [comment]
Oh. I see. How about second one?

**Comment by rchiileea** [comment]
second one wont look good once added to a card, thin lines never work well

**Comment by elax46** [comment]
I close the request given the evaluation of @rchiileea
