### ISSUE TITLE
Icon for Bose Devices

### ISSUE THREAD

**Issue by GunterAv** [elax46/custom-brand-icons#365]
Hello,

I have created the following icons for Bose devices:

Bose Wave:
![bose-wave](https://user-images.githubusercontent.com/87611027/222773016-4037b912-ca6e-4327-b28c-43cef279437e.svg)

Bose Soundtouch10:
![bose-soundtouch](https://user-images.githubusercontent.com/87611027/222772988-1faf53bb-8eff-45c9-a498-7e1d2a41c317.svg)

You can add them if you want.

Best regrard
Gunter

**Comment by rchiileea** [comment]
These are not going to look great bud especially the first one I’ll re edit on Tuesday or Wednesday

**Comment by rchiileea** [comment]
hey bud can you respoond to this today, I can make these icons work or looking at the products I can make nicer ones, but these will take a little longer. let me know

**Comment by GunterAv** [comment]
Hello,

do it, I find them so ok.
But if you can do better, then do it.

Best regards
Gunter

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/224406980-b4cd6f16-20e5-4b6d-bd75-81b71909811a.png)

**Comment by GunterAv** [comment]
better ;-)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/224970920-0950a5a0-a7e2-48a4-be2e-aa8db34222cd.png)

**Comment by GunterAv** [comment]
Name: bose-soundwave
