### ISSUE TITLE
happens to me too

### ISSUE THREAD

**Issue by Vansmak** [elax46/custom-brand-icons#366]
I have 4 button cards all setup the same 1 of them has an mdi icon and 3 of them use phu icons and those 3 don't show, they're blank unless I goto another dashboard and return. so seems like a cache but I don't want to always do that so  i solved the issue by only using mdi icons.

**Comment by rchiileea** [comment]
either your browser is behaving strange or something else, I never have a issue on updates of icons, not showing, the only place with custom icons from any hacks repo you might get a cache error is in the top, but defo not buttons,  or you actually previously assigned mdi icons to the device in the device page under setings.

![image](https://user-images.githubusercontent.com/87599807/224153395-5f362a27-f401-4ec9-81b4-28cc9f2a3df3.png)

if you have previously assigned a icon here then its causing the conflict.

**Comment by elax46** [comment]
Add the folowing to the frontend section of your `configuration.yaml`

```
frontend:
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
```
