### ISSUE TITLE
Custom Icon request Homey

### ISSUE THREAD

**Issue by LRvdLinden** [elax46/custom-brand-icons#367]
Link SVG: https://drive.google.com/file/d/1Zs2ZC6xeP86JxwfQ_pdwUnj979qGZ5f0/view?usp=share_link

**Comment by rchiileea** [comment]
best i could do as its a black and white conversion of what is just a rgb circle 
![image](https://user-images.githubusercontent.com/87599807/224970761-3a73ddb7-03e4-46fc-a927-7ea1ab608836.png)

**Comment by LRvdLinden** [comment]
This is perfect!
