### ISSUE TITLE
Custom Icon request - Sabnzbd

### ISSUE THREAD

**Issue by nickrout** [elax46/custom-brand-icons#368]
**[Insert a link to an SVG icon the integrable icons are ONLY in SVG format]**(https://github.com/sabnzbd/sabnzbd/blob/cd3ed40ff31a814ecf7cad3cd387722d9e5ab3aa/interfaces/Config/templates/staticcfg/images/logo-small.svg)

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by nickrout** [comment]
Cheers.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/224970566-fa7c35bd-8616-4f23-b6a3-1c9b51e45b95.png)
