### ISSUE TITLE
Custom Icon request - openmediavault

### ISSUE THREAD

**Issue by nickrout** [elax46/custom-brand-icons#369]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

https://github.com/openmediavault/openmediavault/blob/f1f74399fd64a9ccc6a1d1eb8c554e856eaef124/deb/openmediavault/workbench/src/favicon.svg

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/224970492-78a5699e-064c-4446-9750-e380c31ea13c.png)

**Comment by nickrout** [comment]
Really impressed by the speed this and my other request got handled! Thanks.
