### ISSUE TITLE
Custom Icon request: Sonos

### ISSUE THREAD

**Issue by monstrek** [elax46/custom-brand-icons#37]
Is it possible to add icons for Sonos speakers:

- Sonos One
- Sonos Playbar
- Sonos Beam
- Sonos Move
- Sonos Arc
- Sonos Connect
- Sonos Connect:amp

**Comment by elax46** [comment]
hi, thanks for your request if you have the icons in svg I can insert them. Alternatively stylized icons in png to convert to svg.

**Comment by monstrek** [comment]
Here are the icons [(svg):](url)
https://we.tl/t-0pvuRSDEmS

**Comment by monstrek** [comment]
Here are the icons (svg):
https://we.tl/t-0pvuRSDEmS

**Comment by elax46** [comment]
These icons cannot be included as they consist of multiple vector elements. the vector path must be single

**Comment by elax46** [comment]
I have integrated only three icons. If you can find the others I will insert them
