### ISSUE TITLE
Custom Icon request [go_play & big_brother & vtm_go]

### ISSUE THREAD

**Issue by jrspowers** [elax46/custom-brand-icons#370]
hello do you want to add these 2 logo go_play & big_brother ? thanks in advance!

[logo](https://mega.nz/folder/T4JDhYKQ#5l8RU906EqTSLRRkzvDnaQ)

then I have a question about the vtm go logo, as you can see, it is now only vtm & should go under it, so would you like to adjust it, otherwise there will be confusion with vtm & vtm go? thanks in advance

[logo vtm go on you github](https://github.com/elax46/custom-brand-icons/blob/main/icon-svg/vtm.svg)

**Comment by rchiileea** [comment]
cant find any font to match the go play logo bud.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/227510054-7ed1506e-ac84-48c4-97f9-e9bd0449bc63.png)

the go ones dissapeared vtm go one I have done but cant find it on my nas so it must be on home pc, ill add the next round

**Comment by jrspowers** [comment]
will you also replace the vtm go logo as indicated & the go play will still come?

**Comment by rchiileea** [comment]
yes I will be, the go play wil come when I get a font simular the vtm go was done, but I must of left it on my desktop pc, I thought I had loaded it to the nas

**Comment by jrspowers** [comment]
okay good

**Comment by jrspowers** [comment]
hello I would like to ask if you could fix this from above?

hello do you want to add these 2 logo go_play & big_brother ? thanks in advance!

[logo](https://mega.nz/folder/T4JDhYKQ#5l8RU906EqTSLRRkzvDnaQ)

then I have a question about the vtm go logo, as you can see, it is now only vtm & should go under it, so would you like to adjust it, otherwise there will be confusion with vtm & vtm go? thanks in advance

[logo vtm go on you github](https://github.com/elax46/custom-brand-icons/blob/main/icon-svg/vtm.svg)
