### ISSUE TITLE
Custom Icon request [huawei solar icons]

### ISSUE THREAD

**Issue by jrspowers** [elax46/custom-brand-icons#376]
hello is it possible to make the following icons ?

[1.huawei_solar_inverter](https://mega.nz/file/LlAiERDa#Rcm_X_CynD5g4CTC7LsebbiwC0LArkvGodLY-KRKOHc)
[2.huawei_solar_homebattery_5kw](https://mega.nz/file/nkoHHahC#m9LbYdaTeCrzuiGFnU7RqmLwZMUE5Nnu1_EkRRgDgCg)
[3.huawei_solar_homebattery_10kw](https://mega.nz/file/ah51gLQS#zZETkmyB6oLfMg13071tH17QhwFk7-wcPHSu1hNnc2s)

merci alvast!

**Comment by rchiileea** [comment]
no huawei branding (although left inverter simular, again the issue if we do one specific brand for each solar brand moving forward we could end up with 1000s of batteries lol :P although I think you will like these, more universal

![image](https://user-images.githubusercontent.com/87599807/227509866-b377b147-2f51-47cf-9181-67942e053659.png)
![image](https://user-images.githubusercontent.com/87599807/227509893-acf92562-9638-41c8-8630-cd4c4efd71b6.png)
![image](https://user-images.githubusercontent.com/87599807/227509918-39b7c5ba-489a-4d71-8499-de3fb4bfbfcd.png)
![image](https://user-images.githubusercontent.com/87599807/227509945-e0abe27f-1616-44f0-90cc-06734241f790.png)

**Comment by jrspowers** [comment]
thanks for making this & indeed true !
