### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by Bazzo85** [elax46/custom-brand-icons#38]
Ciao,
come ti avevo accennato qualche giorno fa ho qualche altra icona. Grazie mille per il tuo lavoro.

[Garden irrigation.svg.zip](https://github.com/elax46/custom-brand-icons/files/7079770/Garden.irrigation.svg.zip)
[Thermostat.svg.zip](https://github.com/elax46/custom-brand-icons/files/7079771/Thermostat.svg.zip)
[Charging_station.svg.zip](https://github.com/elax46/custom-brand-icons/files/7079772/Charging_station.svg.zip)
[Air_conditioner.svg.zip](https://github.com/elax46/custom-brand-icons/files/7079773/Air_conditioner.svg.zip)

Ciao

**Comment by elax46** [comment]
Ciao grazie per la tua richiesta nel prossimo aggiornamento saranno inserite.

**Comment by Bazzo85** [comment]
Grazie mille
