### ISSUE TITLE
Wrong icons Solar Battery

### ISSUE THREAD

**Issue by trisplay** [elax46/custom-brand-icons#380]
Thanks for delivery of Huawei Solar icons!
The battery icons of Huawei are not matching their naming.
The 10kWh does in total have 3 modules (like it's shown in huawei-solar-battery-15). The 5kWh 2 and the huawei-solar-battery-5 is just the system Modul without any battery.

**Comment by elax46** [comment]
![image](https://user-images.githubusercontent.com/87599807/227509866-b377b147-2f51-47cf-9181-67942e053659.png)
![image](https://user-images.githubusercontent.com/87599807/227509893-acf92562-9638-41c8-8630-cd4c4efd71b6.png)
![image](https://user-images.githubusercontent.com/87599807/227509918-39b7c5ba-489a-4d71-8499-de3fb4bfbfcd.png)
![image](https://user-images.githubusercontent.com/87599807/227509945-e0abe27f-1616-44f0-90cc-06734241f790.png)

Summarizing like this:
5kW (1 module)
10kW (2 modules)
15kW (3 modules)

@rchiileea  then add the 15kW form icon

**Comment by elax46** [comment]
For the moment I correct by eliminating the icon 15 is leaving only 5 is 10

**Comment by rchiileea** [comment]
this was done purpously to be more universal, my battery is 15kw and 3 stack, we have to be more universal with the battery, if your 10 is 3 segments use the 15 icon for it :)

**Comment by elax46** [comment]
I agree with your reasoning but if we have to respect the huawei icon then it must be done the same

**Comment by rchiileea** [comment]
ill drop the circle whole from the upper one if needed on them all, as I was just trying to make something more universal for all.

**Comment by elax46** [comment]
> ill drop the circle whole from the upper one if needed on them all, as I was just trying to make something more universal for all.

OK then let's replace the huawei icons with more universal battery modules of size 5kw 10kw 15kw
