### ISSUE TITLE
Custom Icon request - Remeha eTwist Thermostat

### ISSUE THREAD

**Issue by vhardono** [elax46/custom-brand-icons#388]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://drive.google.com/file/d/1GYhclWAxc_oH1x0k8vV9__R5aPbncLRK/view?usp=sharing
**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/231424666-84555913-0a80-4c46-85f1-83d7c0f46d09.png)

**Comment by vhardono** [comment]
thank you! really appreciate your effort accommodating the request
