### ISSUE TITLE
CB-Icon not showing up as expected

### ISSUE THREAD

**Issue by bcutter** [elax46/custom-brand-icons#39]
**Describe the bug**
Icon not showing up in title of a view. Switching to GUI edit mode makes it appear.

Checked several devices/browsers, already reset frontend cache.

CBI is installed using HACS.

Missing "phu:apple-iphone" icon in title
![image](https://user-images.githubusercontent.com/13799156/132767500-cc06e765-b405-43e5-acd1-27851846ea3a.jpeg)

In edit mode there it is
![image](https://user-images.githubusercontent.com/13799156/132767581-d8aafad5-9ef7-44bf-8f35-2873e2cccfc3.jpeg)

**Comment by elax46** [comment]
Unfortunately it is not a problem that depends on CBI but on the browser cache and HA. It is no coincidence that the icon works in the rest of the interface

**Comment by bcutter** [comment]
So what would you recommend to get this fixed? Post it to the HA Core repo?

**Comment by elax46** [comment]
no it's a cache issue there isn't much to solve i just tried it and the icon is displayed
![Immagine 2021-09-10 213601](https://user-images.githubusercontent.com/55278049/132908049-81e30aec-811d-4584-b29f-930c3be910b6.png)

**Comment by bcutter** [comment]
Refresh your browser once you left edit mode. Still showing up?

**Comment by elax46** [comment]
Yes, I just noticed

**Comment by elax46** [comment]
@bcutter   Maybe it is the case of opening a request on HA Core or Frontend from my point of view the icon works in the rest of the interface maybe due to some cache mechanism it is not displayed when updating the browser

**Comment by bcutter** [comment]
OK. You´re right, it´s not CBI specific. I tried with "bha:nas" from https://github.com/hulkhaugen/hass-bha-icons (integrated also using HACS) and it´s the same issue. I´ll try to find the right place to put this at, will probably link this issue here.

**Comment by elax46** [comment]
@bcutter Sure keep me updated on the matter. However, I leave the request open for your updates

**Comment by elax46** [comment]
@bcutter if you have icon to suggest i appreciate it

**Comment by bcutter** [comment]
See https://github.com/home-assistant/frontend/issues/10011

**Comment by bcutter** [comment]
That "fixed" it for me after a quick test. Snippet in frontend section of configuration.yaml seems to be absolutely necessary.
Should have read the install instructions correctly, really thought HACS installation is enough (HACS takes care of all necessary steps).
