### ISSUE TITLE
Icon preview in documentation not showing

### ISSUE THREAD

**Issue by xteaun** [elax46/custom-brand-icons#391]
Hi!

On the github page where all the available icons are listed, many icons do not show. There is only a broken image icon and a link to a preview version visible.

**Comment by rchiileea** [comment]
I can see all preview images in github have you tried another browser

**Comment by xteaun** [comment]
This was apparently a problem with the database version. I deleted nextcloud on Strato and moved it to my NAS and now it works. Thanks!
