### ISSUE TITLE
New Panel Sliding Door icons

### ISSUE THREAD

**Issue by mitzu2250** [elax46/custom-brand-icons#392]
Hello,

I would like to request two new icons similar to the ones already added in the Doors section added by @rchiileea.

One of my sliding doors look like this:
![image](https://user-images.githubusercontent.com/99750119/230336188-19226bb2-b5f2-470e-aa2b-9b7aaf263ceb.png)

Currently there is no panel door icon that looks similar.
As I understand these icons are custom made so unfortunately I don't have links for the .svg files.

Appreciate your work!

**Comment by mitzu2250** [comment]
Hello,

I managed to create some .svg files with the help of an online site of what I imagine these should look like.
But the issue is that the source of the .svg files do not look like the ones in the .js file used in this repository.

CLOSED:
![close](https://user-images.githubusercontent.com/99750119/230375154-49f36681-d0dc-41a9-8ac9-249eb9325c81.svg)

OPEN:
![open](https://user-images.githubusercontent.com/99750119/230375184-fc120abf-7967-43c3-b4e5-6e5e85b0d472.svg)

**Comment by rchiileea** [comment]
great attempt buddy, my advice would be a lot thicker slats and less of them, if you put this into home assistant onces shrunk the slats will become un even and some will dissapear.

**Comment by mitzu2250** [comment]
Do you recommend a software that I can use to create these?
The online tool I used was very limited and I was not able to zoom out that much to get the svg at a smaller size like the ones used in HA.

**Comment by rchiileea** [comment]
adobe illustrator is best really, I made a template too to keep the boundries of size for ha

**Comment by mitzu2250** [comment]
Tried to play around with Illustrator but I get a .svg with <rect> nodes instead of <path>.
Maybe I'm missing something, tried to join the paths but it didn't worked for me.

![test2222](https://user-images.githubusercontent.com/99750119/230578505-677c05e4-ad4b-4a1a-8051-05716508cd63.svg)

**Comment by mitzu2250** [comment]
I figured it out, somehow, I think I'm still doing something wrong because this isn't displayed when I try to use it in HA.

> 		"panel-door-open-mtz":[0,0,24,24,"M2,2.5h20v1H2V2.5z M11 2.5h1v20H11Z M3 2.5h1v20H3Z M3,21.5h9v1H3V21.5z M3,20h9v1H3V20z M3,18.5h9v1H3V18.5z M3,17h9v1H3V17z M3,15.5h9v1H3V15.5z M3,14h9v1H3V14z M3,4h9v1H3V4z M3,5.5h9v1H3V5.5z M3,7h9v1H3V7z M3,8.6h9v1H3V8.6z M3,10h9v3.5H3V10z M11,21.5h11v1H11V21.5z M21 2.5h1v20H21Z"],
> 		"panel-door-close-mtz":[0,0,24,24,"M2,2.5h20v1H2V2.5z M21 2.5h1v20H21Z M13 2.5h1v20H13Z M13,21.5h9v1h-9V21.5z M13,20h9v1h-9V20z M13,18.5h9v1h-9V18.5z M13,17h9v1h-9V17z M13,15.5h9v1h-9V15.5z M13,14h9v1h-9V14z M13,4h9v1h-9V4z M13,5.5h9v1h-9V5.5z M13,7h9v1h-9V7z M13,8.6h9v1h-9V8.6z M13,10h9v3.5h-9V10z"],

I created the vectors :
`<?xml version="1.0" encoding="utf-8"?>

<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 24 24" style="enable-background:new 0 0 24 24;" xml:space="preserve">
<g>
	<path d="M2,2.5h20v1H2V2.5z"/>
	<rect x="11" y="2.5" width="1" height="20"/>
	<rect x="3" y="2.5" width="1" height="20"/>
	<path d="M3,21.5h9v1H3V21.5z"/>
	<path d="M3,20h9v1H3V20z"/>
	<path d="M3,18.5h9v1H3V18.5z"/>
	<path d="M3,17h9v1H3V17z"/>
	<path d="M3,15.5h9v1H3V15.5z"/>
	<path d="M3,14h9v1H3V14z"/>
	<path d="M3,4h9v1H3V4z"/>
	<path d="M3,5.5h9v1H3V5.5z"/>
	<path d="M3,7h9v1H3V7z"/>
	<path d="M3,8.6h9v1H3V8.6z"/>
	<path d="M3,10.2h9v3.2H3V10.2z"/>
	<path d="M11,21.5h11v1H11V21.5z"/>
	<rect x="21" y="2.5" width="1" height="20"/>
</g>
</svg>
`
and
`<?xml version="1.0" encoding="utf-8"?>

<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 24 24" style="enable-background:new 0 0 24 24;" xml:space="preserve">
<g>
	<path d="M2,2.5h20v1H2V2.5z"/>
	<rect x="21" y="2.5" width="1" height="20"/>
	<rect x="13" y="2.5" width="1" height="20"/>
	<path d="M13,21.5h9v1h-9V21.5z"/>
	<path d="M13,20h9v1h-9V20z"/>
	<path d="M13,18.5h9v1h-9V18.5z"/>
	<path d="M13,17h9v1h-9V17z"/>
	<path d="M13,15.5h9v1h-9V15.5z"/>
	<path d="M13,14h9v1h-9V14z"/>
	<path d="M13,4h9v1h-9V4z"/>
	<path d="M13,5.5h9v1h-9V5.5z"/>
	<path d="M13,7h9v1h-9V7z"/>
	<path d="M13,8.6h9v1h-9V8.6z"/>
	<path d="M13,10.2h9v3.2h-9V10.2z"/>
</g>
</svg>
`

used some online tool to remove the <rect> nodes, and then merged all the d's.

**Comment by rchiileea** [comment]
You have to save a specific way then open in Inkscape to finalise

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mitzu2250** [comment]
I have managed to make them work using this codes (the same as above):

> "panel-wood-door-open":[0,0,24,24,"M 2,2.5 h 20 v 1 H 2 V 2.5 z M 11 2.5 h 1 v 20 H 11 Z M 3 2.5 h 1 v 20 H 3 Z M 3,21.5 h 9 v 1 H 3 V 21.5 z M 3,20 h 9 v 1 H 3 V 20 z M 3,18.5 h 9 v 1 H 3 V 18.5 z M 3,17 h 9 v 1 H 3 V 17 z M 3,15.5 h 9 v 1 H 3 V 15.5 z M 3,14 h 9 v 1 H 3 V 14 z M 3,4 h 9 v 1 H 3 V 4 z M 3,5.5 h 9 v 1 H 3 V 5.5 z M 3,7 h 9 v 1 H 3 V 7 z M 3,8.6 h 9 v 1 H 3 V 8.6 z M 3,10.2 h 9 v 3.2 H 3 V 10.2 z M 11,21.5 h 11 v 1 H 11 V 21.5 z M 21 2.5 h 1 v 20 H 21 Z"],
> "panel-wood-door-close":[0,0,24,24,"M 2,2.5 h 20 v 1 H 2 V 2.5 z M 21 2.5 h 1 v 20 H 21 Z M 13 2.5 h 1 v 20 H 13 Z M 13,21.5 h 9 v 1 h -9 V 21.5 z M 13,20 h 9 v 1 h -9 V 20 z M 13,18.5 h 9 v 1 h -9 V 18.5 z M 13,17 h 9 v 1 h -9 V 17 z M 13,15.5 h 9 v 1 h -9 V 15.5 z M 13,14 h 9 v 1 h -9 V 14 z M 13,4 h 9 v 1 h -9 V 4 z M 13,5.5 h 9 v 1 h -9 V 5.5 z M 13,7 h 9 v 1 h -9 V 7 z M 13,8.6 h 9 v 1 h -9 V 8.6 z M 13,10.2 h 9 v 3.2 h -9 V 10.2 z"],

The issue was that my frontend wasn't updating.

I had to delete the .gz file from \config\www\community\custom-brand-icons\ and then navigate to http://homeassistant.local:8123/config/lovelace/resources and increment the ending of the hacstag for /hacsfiles/custom-brand-icons/custom-brand-icons.js in order to get the file reloaded.

![image](https://user-images.githubusercontent.com/99750119/230731516-de7c4c47-600b-407b-a8bc-f5587403ce84.png)

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/231423629-5990e7c1-cd6f-4304-b1b1-0e5b28a3d8be.png)
![image](https://user-images.githubusercontent.com/87599807/231424436-db1a453d-f842-42fd-a82c-c37049596eac.png)
