### ISSUE TITLE
Custom Icon request: Hive (without the name)

### ISSUE THREAD

**Issue by RedNo7** [elax46/custom-brand-icons#399]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://images.ctfassets.net/mijf9lz5yt3u/1wEODJe9KOlmw7j0rEu5Xs/eb38f1783bec4c777062280b7c4e32e7/hive-primary-logo.svg

Thank you!

**Comment by rchiileea** [comment]
done ill upload tomorrow as I have to leave for work

**Comment by RedNo7** [comment]
Thank you!

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/235066830-ad7c91da-5e38-4f31-be43-0f2e675de3e1.png)
