### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by EvertJob** [elax46/custom-brand-icons#400]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://upload.wikimedia.org/wikipedia/commons/0/02/Simple_sine_wave.svg

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by EvertJob** [comment]
No, not much effort. Just forgot is.Is sinus-wave used for measure amperage :)Sent from my iPhoneOn 27 Apr 2023, at 20:46, Richard Bowzer ***@***.***> wrote:﻿
Come on bud is it to much effort to mention what it is for? so we can give it an apporiate name.

**Comment by rchiileea** [comment]
done ill upload tomorrow as I have to leave for work

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/235066718-53257abd-c62c-4bd3-aec2-183e79f1c8ff.png)
adjusted to make more ha friendly
