### ISSUE TITLE
Custom Icon request Kitchen

### ISSUE THREAD

**Issue by EvertJob** [elax46/custom-brand-icons#401]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://www.svgrepo.com/show/76384/kitchen.svg
**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
done ill upload tomorrow as I have to leave for work

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/235066666-01a503a2-1c9b-4a22-9a25-4f6fad9f4625.png)
