### ISSUE TITLE
Would it be possible to get Icons for the following video game systems?

### ISSUE THREAD

**Issue by smarthomeaf** [elax46/custom-brand-icons#403]
GameCube - https://www.svgrepo.com/svg/342066/nintendo-gamecube
Genesis - https://www.svgrepo.com/svg/176006/genesis-control
Sega - https://www.svgrepo.com/svg/342198/sega
Dreamcast - https://www.svgrepo.com/svg/139811/dreamcast-control-for-games
N64 - https://logos.fandom.com/wiki/File:Nintendo-64-(monochrome).svg
Sega Saturn - https://logos.fandom.com/wiki/File:Sega_Saturn_(Symbol).svg

**Comment by rchiileea** [comment]
done ill upload tomorrow as I have to leave for work

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/235066438-767ec291-8e00-4338-aefd-b9f3268d3bf2.png)
![image](https://user-images.githubusercontent.com/87599807/235066470-8dbd6721-fa18-4f30-be82-5211253c91db.png)
![image](https://user-images.githubusercontent.com/87599807/235066500-9aaf2c81-3eff-4ae8-aa13-9850f0db9452.png)
![image](https://user-images.githubusercontent.com/87599807/235066522-48695741-0eaf-4cfd-abc1-aac8fea10733.png)
![image](https://user-images.githubusercontent.com/87599807/235066552-8b78132b-5caf-4ac7-b6f2-099bdc0c624a.png)
![image](https://user-images.githubusercontent.com/87599807/235066603-8b2c99b3-4fa5-429e-94a5-c33b818c6115.png)

**Comment by smarthomeaf** [comment]
thank you!
