### ISSUE TITLE
Custom Icon request Ring Logo Only

### ISSUE THREAD

**Issue by GitHubGoody** [elax46/custom-brand-icons#405]
https://commons.wikimedia.org/wiki/File:Ring_logo.svg

**Comment by GitHubGoody** [comment]
I couldn't find a good .svg, but I could also use the Ring hexagonal sign, but straight on. Thank you!

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/b508451f-49ef-491d-808e-95b74f6eb68d)
