### ISSUE TITLE
Custom Brand icons occasionally don't Display on Lovelace dashboard

### ISSUE THREAD

**Issue by smarthomeaf** [elax46/custom-brand-icons#407]
Custom Brand icons don't always show up.   Hitting refresh on browser will sometimes display them again, but not always.  In incognito browser exhibits the same behavior.   (as well as the iphone app)

Firefox seems to be better, but again it behaves the same.  

I am including a .har file for both when it loads and when it doesn't to better help you.    ( i had to rename them as .log and .har files are not allowed on github)
[working.log](https://github.com/elax46/custom-brand-icons/files/11360309/working.log)
[non working.log](https://github.com/elax46/custom-brand-icons/files/11360310/non.working.log)

**Comment by elax46** [comment]
Add the folowing to the `frontend `section of your `configuration.yaml`

```
frontend:
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
```

**Comment by GitHubGoody** [comment]
@smarthomeaf More [here](https://github.com/elax46/custom-brand-icons/issues/189)

**Comment by smarthomeaf** [comment]
That worked for browsers, needed to change the path to "/hacsfiles/custom-brand-icons/custom-brand-icons.js".  However, for iphone app, they are still not displaying.

**Comment by smarthomeaf** [comment]
Seems like I fixed it.  went into debugging tools on the ios app and cleared the frontend  cache and cleared it.  now it all seems fine.  Thank you and you can close this.
