### ISSUE TITLE
Custom Icon request for Roon Media Service

### ISSUE THREAD

**Issue by LordVoodoo** [elax46/custom-brand-icons#408]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

The Icons are available in the forum of Roon: https://community.roonlabs.com/t/custom-dark-mode-roon-1-8-icons/140973

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/dc057390-5813-49c8-807f-ad653928c725)
