### ISSUE TITLE
Custom Icon request Carrier Home

### ISSUE THREAD

**Issue by GitHubGoody** [elax46/custom-brand-icons#409]
![CarrierHome](https://user-images.githubusercontent.com/46235745/235354485-2d96e98c-76f1-44fb-82fa-ad6dd466ddc1.svg)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/dc00f944-2b50-438e-be50-1535046522cd)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/cd1065a2-789e-46de-86df-e67f028ebba6)

**Comment by GitHubGoody** [comment]
Awesome, thank you!
