### ISSUE TITLE
Custom Icon request for Nextcloud

### ISSUE THREAD

**Issue by bcutter** [elax46/custom-brand-icons#41]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**

Nextcloud (collaboration service, not a device)

**Provide a URL that points to an image of this fixture/bulb**

- https://nextcloud-italia.it/wp-content/uploads/2019/07/Nextcloud_Logo.svg_-e1562924758414.png
(all other being found with https://duckduckgo.com/?t=ffsb&q=nextcloud+svg&atb=v154-1&iax=images&ia=images&iaf=type%3Atransparent are with the text included unfortunately)
- Update: maybe better (app icon)? https://img.apksum.com/06/com.nextcloud.client/3.11.1/icon.png

**Additional context**

- Much better than the general "mdi:cloud".
- Not sure if the aspect of the logo (quite wide) fits or is a problem.

**Comment by elax46** [comment]
just the icon or even the brand name?

**Comment by elax46** [comment]
- integrated in the new version [1.0.24](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.24)

**Comment by bcutter** [comment]
> 
> 
> just the icon or even the brand name?

"Just" the icon should be enough because text is hard to read in such small size.

Thanks, that was very fast! 👍
