### ISSUE TITLE
Custom Icon request: Locked & Unlocked Door

### ISSUE THREAD

**Issue by raddacle** [elax46/custom-brand-icons#414]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**
![noun-locked-2926006](https://user-images.githubusercontent.com/50691489/236676776-7ec522f2-4032-44dd-b460-c07da29f09f5.svg)
![noun-unlock-2926011](https://user-images.githubusercontent.com/50691489/236676777-9cb65b44-5d06-47ef-9a12-36eb0f90b1a3.svg)

**Comment by rchiileea** [comment]
We do have door icons for indicating open closed and locked or unlocked

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: raddacle ***@***.***>
Sent: Sunday, May 7, 2023 1:14:23 PM
To: elax46/custom-brand-icons ***@***.***>
Cc: Richard Bowzer ***@***.***>; Assign ***@***.***>
Subject: [elax46/custom-brand-icons] Custom Icon request: Locked & Unlocked Door (Issue #414)


Insert a link to an SVG icon the integrable icons are ONLY in SVG format

off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library
[noun-locked-2926006]<https://user-images.githubusercontent.com/50691489/236676776-7ec522f2-4032-44dd-b460-c07da29f09f5.svg>
[noun-unlock-2926011]<https://user-images.githubusercontent.com/50691489/236676777-9cb65b44-5d06-47ef-9a12-36eb0f90b1a3.svg>

**Comment by rchiileea** [comment]
https://github.com/elax46/custom-brand-icons/discussions/245 See here for description on how to utilize them

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by elax46** [comment]
As indicated by @rchiileea  you can use the code indicated #245 for so I close the request

**Comment by raddacle** [comment]
There aren't any that indicate that the door is unlocked- only locked, opened, or closed. To me, a closed door with the lack of a lock icon is not same as 'unlocked', it only indicates that the door is closed.

**Comment by rchiileea** [comment]
Would you not know it’s not locked by the fact there is not a lock icon and it’s like caked by the fact there is a locked icon?


Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by raddacle** [comment]
In my current dashboard, I'm using a lot of "chips" to have it be more minimal, and with the current icon set there would be no way to differentiate a contact sensor showing a closed door vs a lock showing that it's closed but unlocked; in other words, a door can be opened or closed when unlocked. I considered adding a matching third icon for unlocked and open, but I didn't want to clutter the icon library, as there are already door opened icons even though they don't match.

**Comment by rchiileea** [comment]
I get what your trying to say, but to be more minimal you would just no, there is no lock icon next to door so its not locked, just  try out the code bellow with your current door contact sensors and lock, you will see what I mean the door shut with no lock showing means the door is closed and unlocked, with a lock showing it is closed and locked. the lock icon will only show up if your door is lock (obviously chage the lock state from on to locked if thats what your door reports.

icon: |
  [[[
     if (states['your-lock-here'].state == 'on)
      return "phu:panel-front-door-locked" 
     if (states['your-door-contact-sensor-here'].state == 'on') 
      return "phu:panel-frontdoor-open"; 
     if (states['your-door-contact-sensor-here'].state == 'off') 
      return "phu:panel-frontdoor-close"
  ]]]

the door obviously does not need a lock icon when open and doesnt really need one when unlock, I will add a more basic style like yours if you wish, but door closed, door open and then one with a lock on it ?
