### ISSUE TITLE
Custom Icon request Yeelight Lamps

### ISSUE THREAD

**Issue by TheZoker** [elax46/custom-brand-icons#415]
Yeelight Beside Lamp v1:
![bedside_lamp](https://user-images.githubusercontent.com/1368405/236685036-406412d4-d562-4613-b5c0-b0173a9c0546.svg)

Yeelight Smart Bulb:
![bulb](https://user-images.githubusercontent.com/1368405/236685227-a290000e-ffa6-4bcd-bcc0-ac7a852bac2e.svg)

Yeelight Desk Lamp:
![desk_lamp](https://user-images.githubusercontent.com/1368405/236685253-f6c96922-d065-40a1-bba2-929c5f5186de.svg)

Yeelight Ceiling Light:
![ceiling_350](https://user-images.githubusercontent.com/1368405/236685374-d15f8cc9-6a2a-437c-b324-fea4887c5787.svg)

Yeelight Light Strip:
![strip](https://user-images.githubusercontent.com/1368405/236685321-9917f741-2737-42b4-a7ef-e63c19be535e.svg)

**Comment by rchiileea** [comment]
changed them up a bit to be a bit more eligable in HA buttons and added a light group of the bulb
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/c50e69fa-891c-46e7-b6d4-592e52aec47e)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/80b78e4b-027b-4ae6-8fda-5d22de975c06)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/ac50eab3-16ac-4901-8472-8d186adb23df)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/c8aa5bb7-41f8-43d4-9ffa-201562622f69)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/38fe8eee-ef03-443e-89df-3ba9969d8b61)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/401e5089-5272-4ace-8784-f5e91539b039)

**Comment by TheZoker** [comment]
Ah very nice, thanks!
My only comment would be to maybe remove the top line in the ceiling light, since I think it will look nicer/cleaner that way. 
When looking at the light, you can't not really see the top part anyway:
![image](https://github.com/elax46/custom-brand-icons/assets/1368405/a5482912-533e-47d6-9fc1-dcff41bab53a)

**Comment by rchiileea** [comment]
Lol you submitted the icons with the top part?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TheZoker** [comment]
Yes and after I saw you proposal, I realized, that maybe it looks better without the top part. This was not meant as a criticism or something, just a discussion :)
