### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by AshGSmith** [elax46/custom-brand-icons#416]
[**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**]
https://upload.wikimedia.org/wikipedia/commons/7/7b/Plex_logo_2022.svg

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/ae5b675e-76e3-490a-be34-cbc0bd6911f8)
