### ISSUE TITLE
Custom Icon request Kettle Grill

### ISSUE THREAD

**Issue by LunkwillAndFook** [elax46/custom-brand-icons#417]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://www.svgrepo.com/download/300374/barbecue-grill.svg

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![grill-charcoal](https://github.com/elax46/custom-brand-icons/assets/87599807/ca63d7d6-fe53-4765-926c-ac6128bd46e6)
