### ISSUE TITLE
Custom Icon request Gas Grill

### ISSUE THREAD

**Issue by LunkwillAndFook** [elax46/custom-brand-icons#418]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://www.svgrepo.com/download/126871/gas-grill.svg

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![grill-gas](https://github.com/elax46/custom-brand-icons/assets/87599807/d37659a1-063e-4ec2-a49f-3b1e3b774f54)

for future referance can you put all requests into one post when requesting multiple icons
