### ISSUE TITLE
Custom Icon request Ceramic Grill

### ISSUE THREAD

**Issue by LunkwillAndFook** [elax46/custom-brand-icons#419]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://www.svgrepo.com/download/47469/ceramic-grill.svg

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![grill-ceramic](https://github.com/elax46/custom-brand-icons/assets/87599807/26b44165-25c6-470c-a5d6-37b0284025e4)

please see note in gas grilll request
