### ISSUE TITLE
Custom Icon request for Shelly

### ISSUE THREAD

**Issue by bcutter** [elax46/custom-brand-icons#42]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**

It´s a device manufacturer (company and product name).

**Provide a URL that points to an image of this fixture/bulb**

- https://brands.home-assistant.io/shelly/icon.png
(https://github.com/home-assistant/brands/blob/master/core_integrations/shelly/icon.png)

**Additional context**

Nothing else to add :-)

**Comment by elax46** [comment]
will be available in the next released version
