### ISSUE TITLE
Custom Icon request [MyCanal]

### ISSUE THREAD

**Issue by Wendigogo** [elax46/custom-brand-icons#420]
Could you please add the MyCanal icon in Television section please?

I edited it to make it easier to integrate in js file (one "path" with one line).
![mycanal](https://github.com/elax46/custom-brand-icons/assets/1914251/cabbf215-f3c8-4f5e-bd15-019093112bf9)

Thanks

EDIT : I let you change it to the appropriate color.

**Comment by Wendigogo** [comment]
Could you make e preview of it this way (with correct sze)?
It think it will be good like this.

Thanks

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/32c05298-0005-46fc-920a-ec67d33e4487)
in a large 2 card row

**Comment by rchiileea** [comment]
I wont add a icon like this personally as on a tablet size it will be too small for a icon

**Comment by Wendigogo** [comment]
I totally agree with you: this second version is way better!

**Comment by rchiileea** [comment]
having done hundreds of icons I sort of understand what will and wont look good, I still some times make one that might look good until its in ha and realise it looks crap, but thats rare these days

**Comment by rchiileea** [comment]
done and ready to update the repo 
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/435bbcf1-35c6-467d-9740-77491f793514)
