### ISSUE TITLE
Custom Icon request: Pocket Casts

### ISSUE THREAD

**Issue by j6s33m** [elax46/custom-brand-icons#421]
Pocket Casts

https://www.svgrepo.com/download/349480/pocketcasts.svg

Please and thank you!

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/5fbd7daf-0562-4f97-ad1d-abaf042f9809)

**Comment by j6s33m** [comment]
Thank you!
