### ISSUE TITLE
Tado thermostat

### ISSUE THREAD

**Issue by rijsab** [elax46/custom-brand-icons#423]
Hi again, 

Many thanks for including Tado as a brand. A gentle request to include a Tado Thermostat as well please. 

Thanks again.

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/11f0c2d0-1fc7-47b9-b92c-f75c8a71e3b9)

**Comment by rijsab** [comment]
This is also great! Apologies for the confusion. What I meant is the square main thermostat of Tado to controle this newly designed thermostat valve. So basicaly the main Tado unit. Cheers and many thanks!!
