### ISSUE TITLE
Custom Icon request: [ Aqara Button Switch ]

### ISSUE THREAD

**Issue by WarC0zes** [elax46/custom-brand-icons#424]
Hi,
Can you add the icon for the Aqara wireless switch (lumi.remote.b1acn01) in the Aqara category?

https://raw.githubusercontent.com/TedTolboom/com.xiaomi-mi-zigbee/master/drivers/remote.b1acn01/assets/icon.svg

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/50deecaf-e9e8-4070-805e-266340185ef6)

**Comment by WarC0zes** [comment]
Nice job, thanks.
