### ISSUE TITLE
Custom Icon request [max]

### ISSUE THREAD

**Issue by brandoningli** [elax46/custom-brand-icons#425]
[SVG Link](https://upload.wikimedia.org/wikipedia/commons/c/ce/Max_logo.svg)

This is the new streaming service set to replace HBO Max on May 23.

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/e3d5bfcc-6d88-4137-a75b-1e42cdde1fec)
to replace hbo max
