### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by gdreelin** [elax46/custom-brand-icons#43]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for** Blink Cameras

**Provide a URL that points to an image of this fixture/bulb** 

XT2 Camera (https://support.blinkforhome.com/en_US/setting-up-first-generation-indoor/start-2-add-a-system)
Mini Camera (https://support.blinkforhome.com/mini)
Sync Module (https://media.flixcar.com/delivery/minisite/show/2348/en/1904857) icon at bottom. 

Preferably icon photography, as they use a consistent angle.

**Additional context**

Add any other context for your icon request here.

Front view would work. I found one icon version for the XT2 but not the mini.

**Comment by elax46** [comment]
what do you mean by "icon photographs" the icons are in svg not png or jpeg

**Comment by gdreelin** [comment]
That was part of the pre-text that was on the request when you click Icon Request link. I did not put that in I was just answering the questions asked. So if I took out all that pre-text it would look like this:

Blink Cameras

XT2 Camera (https://support.blinkforhome.com/en_US/setting-up-first-generation-indoor/start-2-add-a-system)
Mini Camera (https://support.blinkforhome.com/mini)
Sync Module (https://media.flixcar.com/delivery/minisite/show/2348/en/1904857) icon at bottom.

Front view would work. I found one icon version for the XT2 but not the mini.

**Comment by elax46** [comment]
Do you have references of the mini camera? from the link there is not much. The other two icons are ready

**Comment by gdreelin** [comment]
The best I could find is this picture. Could not find any drawings of it.
![blink_banner](https://user-images.githubusercontent.com/802649/133265455-9499917b-c370-4fed-ad78-97fdefa33df3.png)

**Comment by elax46** [comment]
at the moment I was unable to integrate the mini icon if you find better references please post them here thanks

**Comment by gdreelin** [comment]
No worries thanks for trying at least.
