### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by HolmbomDK** [elax46/custom-brand-icons#431]
Please ad the 2 icons in next update.
THX Kim

![Ikea-JAKOBSBYN](https://github.com/elax46/custom-brand-icons/assets/60605847/e914f66d-e19d-49bd-9681-2cd55c3d0ce5)

![Paperlamp](https://github.com/elax46/custom-brand-icons/assets/60605847/244bf8a0-3a49-48f9-a526-7b991ed7ef01)

**Comment by romanr** [comment]
What are the brand/product names of those icons? This repo is called brand icons.

**Comment by HolmbomDK** [comment]
![Ikea-JAKOBSBYN](https://github.com/elax46/custom-brand-icons/assets/60605847/ad7b434c-5395-4f30-8ea5-ca6f9f5a036d) = IKEA - Jakobsbyn

![Paperlamp](https://github.com/elax46/custom-brand-icons/assets/60605847/2f528d2d-4866-4983-aae8-9c768ff20a4e) = IKEA - Paparlamp 

It is old and i don't have / can't find the name so name can be :
IKEA - Paparlamp  or Generic - Paparlamp or High Floorlamp

Home this helps :-)

**Comment by HolmbomDK** [comment]
A better version of Paperlamp
![Paperlamp](https://github.com/elax46/custom-brand-icons/assets/60605847/47f99e20-96e5-48b8-95d2-f859520554ac)
