### ISSUE TITLE
Icon not showing when used for iframe_panel

### ISSUE THREAD

**Issue by duanemck** [elax46/custom-brand-icons#432]
**Describe the bug**
I have a number of iFrame panels setup that show in the side bar of HA.
I'm using the node-red custom brand icon but it doesn't seem to load consistently. Sometimes it's there and sometimes it's not.
I've tested it in an incognito window to confirm if it was a caching issue but the problem exists there too.

![image](https://github.com/elax46/custom-brand-icons/assets/429394/8e68389a-9c89-4587-b131-672cefb39716)

![image](https://github.com/elax46/custom-brand-icons/assets/429394/9a6a9781-760d-432d-8a85-f6ea54d151a6)

Using: https://www.home-assistant.io/integrations/panel_iframe/

**Comment by elax46** [comment]
Add the folowing to the `frontend `section of your `configuration.yaml`

```
frontend:
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
```

**Comment by duanemck** [comment]
Thanks, that's done the trick!
