### ISSUE TITLE
Custom Icon request for Phoscon/deCONZ

### ISSUE THREAD

**Issue by bcutter** [elax46/custom-brand-icons#44]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**

Official Phoscon/deCONZ icon

**Provide a URL that points to an image of this fixture/bulb**

- Officially from website: https://phoscon.de/img/phoscon-logo128x.svg
- From forum: https://forum.phoscon.de/uploads/default/original/1X/c61b1a04d0bb3c2fb4cc9ca1b1194f8f50ce0a84.png
- From another custom frontend integration: https://github.com/hulkhaugen/hass-bha-icons/blob/master/svg/phoscon.svg

**Additional context**

Name should be "phoscon" (or "phoscon-logo") as deCONZ name doesn´t really match the logo.

**Comment by elax46** [comment]
will be available in the next released
