### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by krisshomeassistant** [elax46/custom-brand-icons#447]
Hi,

Thanks for the great work it is hugely appreciated.

Iv attached the SVG file for a LG logo.

If you could add this or give me some advice on how to create these myself it would really be appreciated.

BR

Kris
![LG_logo_(2015)](https://github.com/elax46/custom-brand-icons/assets/94012767/f3c7e378-0446-4375-9858-df13ce0eda73)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/6cb6b689-4221-4172-8184-322c86ea3785)

**Comment by elax46** [comment]
Icon will be avalable in the next update
