### ISSUE TITLE
Custom Icon request - KNX

### ISSUE THREAD

**Issue by jensihnow** [elax46/custom-brand-icons#448]
Since Home Assistant recently announced the collaboration with KNX, I believe adding the KNX icon is a nice addition.

Example: https://de.wikipedia.org/wiki/Datei:KNX_logo.svg

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/fa034b4c-64dd-4615-a0b7-e5e6b0e8dc96)
