### ISSUE TITLE
Custom Icon request [Fortinet]

### ISSUE THREAD

**Issue by sherkan-666** [elax46/custom-brand-icons#449]
Hello,
Thank you for your work.
I isolated my private network behind a Fortinet firewall and am monitoring it in HA, is it possible to have the Forti logo?
Thanks
Link to .svg of Fortinet : https://commons.wikimedia.org/wiki/File:Fortinet_logo.svg

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/0b28c1da-52b1-4408-9740-f9c0521277c7)

**Comment by sherkan-666** [comment]
> ![image](https://user-images.githubusercontent.com/87599807/254356677-0b28c1da-52b1-4408-9740-f9c0521277c7.png)

Really nice, thank you !
