### ISSUE TITLE
Custom Icon request for thermostat (alternative)

### ISSUE THREAD

**Issue by bcutter** [elax46/custom-brand-icons#45]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**

Alternative thermostat icon (analog look)

**Provide a URL that points to an image of this fixture/bulb**

- https://github.com/hulkhaugen/hass-bha-icons/blob/master/svg/thermostat.svg

**Additional context**

Name could be "thermostat-alt" as alternative to existing "digital look" thermostat icon.

**Comment by elax46** [comment]
iona integrated, will be available in the next release
