### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by chester512** [elax46/custom-brand-icons#450]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

Target
https://upload.wikimedia.org/wikipedia/commons/c/c5/Target_Corporation_logo_%28vector%29.svg
Starbucks
https://upload.wikimedia.org/wikipedia/sco/d/d3/Starbucks_Corporation_Logo_2011.svg
HEB
https://upload.wikimedia.org/wikipedia/en/a/a1/H-E-B_logo.svg

**Comment by rchiileea** [comment]
You realise Starbucks is already there.

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/dc810d0c-dd6e-4fb3-825a-a5a13315ec3b)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/1dc62510-a97c-4bee-8813-7bbec4d5f393)
