### ISSUE TITLE
Custom Icon request: Battery Temperature

### ISSUE THREAD

**Issue by AshGSmith** [elax46/custom-brand-icons#452]
[Image Link](https://svgshare.com/i/vtZ.svg) 

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/7615bec7-09f1-476c-9eb0-2b25720421ae)
changed to this to be more eligable on wall mounted dashboards
