### ISSUE TITLE
Custom Icon request [IKEA 5 button remote]

### ISSUE THREAD

**Issue by michelbalzer** [elax46/custom-brand-icons#456]
I don't have a svg, but is it possible to add the 5 button remote from IKEA? see https://community.home-assistant.io/t/zha-ikea-five-button-remote-for-lights/253804 for a photo

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/359f19df-bfbc-4006-b6d8-d0621f6dccd7)
went for a more universal type with included filters before the softener

**Comment by michelbalzer** [comment]
Nicely done
