### ISSUE TITLE
Custom Icon request [air sensor icons]

### ISSUE THREAD

**Issue by jrspowers** [elax46/custom-brand-icons#457]
Hello, could you please add these icons? This would help me display my new DIY sensor. Thanks in advance! 
![IMG_4746](https://github.com/elax46/custom-brand-icons/assets/60328474/8bccef0a-eb78-4459-bd2d-6b5781b0cf7b)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/cb33d661-c096-4c3e-b6fd-4dea09675c72)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/dfd10de5-4220-44d3-94dc-9b2922a01926)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/a1f3ad8e-0ee8-4a5d-8fe8-a6ff6692a4b5)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/c0d5b6bd-3bd7-44a2-89b0-bc0a23f14631)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/dc949798-6080-49f6-a60e-f48b72ad46f2)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/9728b890-3314-45cb-82c5-e1483daf50dd)
I left temp out as there are plenty of temp icons

**Comment by jrspowers** [comment]
Thanks 😊

**Comment by jrspowers** [comment]
> ![image](https://github.com/elax46/custom-brand-icons/assets/87599807/cb33d661-c096-4c3e-b6fd-4dea09675c72)
> 
> ![image](https://github.com/elax46/custom-brand-icons/assets/87599807/dfd10de5-4220-44d3-94dc-9b2922a01926)
> 
> ![image](https://github.com/elax46/custom-brand-icons/assets/87599807/a1f3ad8e-0ee8-4a5d-8fe8-a6ff6692a4b5)
> 
> ![image](https://github.com/elax46/custom-brand-icons/assets/87599807/c0d5b6bd-3bd7-44a2-89b0-bc0a23f14631)
> 
> ![image](https://github.com/elax46/custom-brand-icons/assets/87599807/dc949798-6080-49f6-a60e-f48b72ad46f2)
> 
> ![image](https://github.com/elax46/custom-brand-icons/assets/87599807/9728b890-3314-45cb-82c5-e1483daf50dd)
> 
> I left temp out as there are plenty of temp icons

"Hey, I don't see the CO2 icon. Can you also add this one?"

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/7455b938-07a0-4791-a6f0-d06249efe253)

**Comment by jrspowers** [comment]
> ![image](https://github.com/elax46/custom-brand-icons/assets/87599807/7455b938-07a0-4791-a6f0-d06249efe253)
> 
> 

Thanks nice color how you do this ?

**Comment by elax46** [comment]
> > ![image](https://user-images.githubusercontent.com/87599807/264989939-cb33d661-c096-4c3e-b6fd-4dea09675c72.png)
> > ![image](https://user-images.githubusercontent.com/87599807/264989973-dfd10de5-4220-44d3-94dc-9b2922a01926.png)
> > ![image](https://user-images.githubusercontent.com/87599807/264990007-a1f3ad8e-0ee8-4a5d-8fe8-a6ff6692a4b5.png)
> > ![image](https://user-images.githubusercontent.com/87599807/264990057-c0d5b6bd-3bd7-44a2-89b0-bc0a23f14631.png)
> > ![image](https://user-images.githubusercontent.com/87599807/264990117-dc949798-6080-49f6-a60e-f48b72ad46f2.png)
> > ![image](https://user-images.githubusercontent.com/87599807/264990160-9728b890-3314-45cb-82c5-e1483daf50dd.png)
> > I left temp out as there are plenty of temp icons
> 
> "Hey, I don't see the CO2 icon. Can you also add this one?"

The CO2  icon is not visible here but it is available

**Comment by rchiileea** [comment]
> > ![image](https://user-images.githubusercontent.com/87599807/265100414-7455b938-07a0-4791-a6f0-d06249efe253.png)
> 
> Thanks nice color how you do this ?

Custom button card,

under styles do 
 styles:
     icon:
         - color: |
            [[[ 
               if (entity.state <= 50) return 'red';
               else if (entity.state <= 75) return 'orange';
               else if (entity.state <= 100) return 'green';
               else return 'red';
            ]]
     state:
         - color: |
            [[[ 
               if (entity.state <= 50) return 'red';
               else if (entity.state <= 75) return 'orange';
               else if (entity.state <= 100) return 'green';
               else return 'red';
            ]]

     state:
         - color: |
            [[[ 
               if (entity.state <= 50) return 'red';
               else if (entity.state <= 75) return 'orange';
               else if (entity.state <= 100) return 'green';
               else return 'red';
            ]]

    name:
         - color: |
            [[[ 
               if (entity.state <= 50) return 'red';
               else if (entity.state <= 75) return 'orange';
               else if (entity.state <= 100) return 'green';
               else return 'red';
            ]]

     state:
         - color: |
            [[[ 
               if (entity.state <= 50) return 'red';
               else if (entity.state <= 75) return 'orange';
               else if (entity.state <= 100) return 'green';
               else return 'red';
            ]]

change numbers to co2 levels you want to reflect the state of the items you can the use this scheme under the name, icon ect under the styles line so that icon and name and state change  to match each other.

**Comment by jrspowers** [comment]
Thanks
