### ISSUE TITLE
The icon doesn't show in the top bar

### ISSUE THREAD

**Issue by eduardokabello** [elax46/custom-brand-icons#459]
When I open HA (desktop), the customs icons (alexa-logo) don't appear in the top bar, but the others are ok. The alexa-logo icon only shows when I click "Edit Dashboard" and after I clicked "DONE", the icon appears normally while the browser staying open.

I tried to open HA from an incognito windows also, but I got the same issue. I'm sure that installation is ok.

This issue occurs only in top bar, in all other places, the icons are showing ok.

By the way, the same issue occurs on the iOS app.

Thanks

![image](https://github.com/elax46/custom-brand-icons/assets/90769476/e873e6f5-2e86-447d-ab37-4b8b03f05b12)

![image](https://github.com/elax46/custom-brand-icons/assets/90769476/b742ca08-919c-4665-a35c-79f8bba8d3e3)

![image](https://github.com/elax46/custom-brand-icons/assets/90769476/90928c84-c5b1-4bfe-97e1-c124709b4992)

**Comment by elax46** [comment]
The problem is the same as others already opened and pinned at the top #1 #287 #432 

Add the folowing to the `frontend `section of your `configuration.yaml`

```
frontend:
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
```

https://github.com/elax46/custom-brand-icons#hacs

**Comment by elax46** [comment]
@eduardokabello If you solved the problem please close the request thanks
