### ISSUE TITLE
Custom Icon request - Solar Battery

### ISSUE THREAD

**Issue by AshGSmith** [elax46/custom-brand-icons#460]
![IMG_2458](https://github.com/elax46/custom-brand-icons/assets/68118872/9f87277f-77b4-47c6-bf56-35ea615db39a)

**Comment by rchiileea** [comment]
I made a more universal one I hope you like it

![image](https://github.com/elax46/custom-brand-icons/assets/87599807/0917f8eb-9ad3-43b1-8df2-2674e8b9c5a7)
