### ISSUE TITLE
Custom Icon request [softening system]

### ISSUE THREAD

**Issue by MelleD** [elax46/custom-brand-icons#461]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
Unfortunately I couldn't find any SVG for softening system.
But an icon in this direction would be great. Maybe someone has a good idea :)

https://www.bwt.com/de-de/shop/BWT-Perla-Home/011431x
https://www.selfio.de/wasseraufbereitung/enthaertungsanlagen/

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/359f19df-bfbc-4006-b6d8-d0621f6dccd7)
went for a more universal type with included filters before the softener

**Comment by MelleD** [comment]
@elax46 thanks a bunch. Could also make a single icon without drink water?

Normally, you need a softener for other devices such as a coffee machine, washing machine, etc. not for drink water.

Due to the osmosis conversion, many households even have 2 water lines. One for softening and one line directly for drinking water WITHOUT softening :)

**Comment by elax46** [comment]
> @elax46 and @rchiileea thanks a bunch. Could also make a single icon without drink water?
> 
> Normally, you need a softener for other devices such as a coffee machine, washing machine, etc. not for drink water.
> 
> Due to the osmosis conversion, many households even have 2 water lines. One for softening and one line directly for drinking water WITHOUT softening :)

if you can post examples at least we try to understand what you mean and implement it accordingly

**Comment by MelleD** [comment]
> if you can post examples at least we try to understand what you mean and implement it accordingly

My links are the examples :). It's a Ion exchanger, which use salt to reduce lime and normally it's not for trink water. So it's no a h2o softener.
Example:
https://www.bwt.com/de-de/shop/BWT-Perla-Home/011431x

Here:
"Diese Art der Wassertechnik, ein Ionentauscher, ist eine chemische Wasseraufbereitung, die in die Wasserleitung eingebaut werden muss.

Sie ersetzt die Härte bildenden Stoffe Kalzium und Magnesium durch das Natrium aus dem Kochsalz, mit dem die Anlage regeneriert wird. Das bedeutet, dass der Natriumgehalt des Trinkwassers erhöht wird und über den Grenzwert von 200 mg/l steigen kann. Dann erfüllt das Leitungswasser nicht mehr die Anforderungen der Trinkwasserverordnung, ist also kein zugelassenes Trinkwasser mehr.
"

**Comment by rchiileea** [comment]
The problem with your device option request, is its a square box really, I mean I can edd another icon like this, but with bath and shower etc, I just am thinking long term, boxes upon boxes for devices like these wont make for a pretty ui.  Let me know your thoughts.

**Comment by MelleD** [comment]
Yes, good question.

I think the problem is needed for all devices that have problems with lime: washing machine, bathroom, coffee machine, dishwasher, etc.
In addition, the entrance is the house water connection. Maybe a pipe as a connection and then a few example which machines are connected?
Or the softener in the middle like a star?
Softener in the middle and around the outside a few devices?

Or if it should be one symbol, maybe something like air filter from mdi?
Maybe drip water instead of air waves?

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/4235cc1a-41c5-4740-ba8b-db8ddca017b7)

**Comment by MelleD** [comment]
@rchiileea hey again. I reopen it, because I think the water-softener is missing in the distrubtion:
https://github.com/elax46/custom-brand-icons/blob/main/dist/custom-brand-icons.js

Cannot find and also did try to it in HA and get a empty icon.

Thanks
