### ISSUE TITLE
Custom Icon request [Daikin Altherma 3]

### ISSUE THREAD

**Issue by EvertJob** [elax46/custom-brand-icons#462]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://drive.google.com/drive/folders/17xOnVcCPJlAQXvJ_LThXEzQq9FEfXLza?usp=share_link

I would request a icon for the Daikin Altherma 3. All ready convert it from jpg to SVG but because the unit is white where is a lot of white space.

Maybe an idea to make it universal blue?

**Comment by rchiileea** [comment]
this is a awkward one as its the other side of a airsource system, would the air source outer unit not cover this?

**Comment by EvertJob** [comment]
Not for me. As I understand that this is a difficult one. Got no solution for it so far.

**Comment by rchiileea** [comment]
what I mean is rather than it look like a tall retangular tower (which will basically make it look like a home battery) would not a Icon of the outer part (the pump it self)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/cd4623e6-a360-4ec7-b36d-041be8fc20cf)
 a comprimise to suit all

**Comment by EvertJob** [comment]
> ![image](https://user-images.githubusercontent.com/87599807/270150854-cd4623e6-a360-4ec7-b36d-041be8fc20cf.png) a comprimise to suit all

Yeah! That’s a solution that could work for me!
