### ISSUE TITLE
Custom Icon request: Uptime Kuma

### ISSUE THREAD

**Issue by nicholaswilde** [elax46/custom-brand-icons#464]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://github.com/louislam/uptime-kuma/blob/283d52a8619396f6d4da776ff3ef30ec35c4660b/public/icon.svg

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/3f63a122-8e4a-4fec-8ec9-71f6cbedd4ad)
