### ISSUE TITLE
Custom Icon request [table 2 chairs]

### ISSUE THREAD

**Issue by KobeNuyts** [elax46/custom-brand-icons#465]
This is a remix of the table-chair, the difference is that it has 2 chairs.
I will use this icon for my lamp above my dining table in Home Assistant.

**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://drive.google.com/file/d/1sfPQKCGLPrt0cap2vcon9xWwcUrRlGXD/view?usp=sharing
![table2chair](https://github.com/elax46/custom-brand-icons/assets/102762606/ae79c84c-d2fd-4137-9d56-1798b4ac52b3)

**Comment by rchiileea** [comment]
I made two for this to have a better look

![image](https://github.com/elax46/custom-brand-icons/assets/87599807/492e8fa9-8809-44fd-b575-53ea37a78ab8)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/712e95fa-d903-4c70-bf26-ca599df864c0)
