### ISSUE TITLE
custom-brand-icons.js missing from release assets

### ISSUE THREAD

**Issue by lmendezr** [elax46/custom-brand-icons#466]
**Describe the bug**

Not sure if I'm missing something, but I've been unable to install the latest version (or any version) of `custom-brand-icons` via HACS for about a week. I thought it was a problem with my HA instance, but after looking at the repo I can't find the generated `custom-brand-icons.js` from any of the released versions. Was this always this way, or was it due to some cleanup on Github's end?

**Comment by elax46** [comment]
the js file can be found [here ](https://github.com/elax46/custom-brand-icons/blob/main/dist/custom-brand-icons.js)for installation via HACS you can also use the direct [link](https://github.com/elax46/custom-brand-icons/tree/main#hacs)

**Comment by lmendezr** [comment]
Oh! I found the issue - it was on my end. My router's IPv6 config was messed up, thus I was having issues accessing packages from Github. False alert, totally my bad. Thanks for the icon pack, @elax46!!
