### ISSUE TITLE
Custom Icon request [OQEE]

### ISSUE THREAD

**Issue by Lotharion** [elax46/custom-brand-icons#467]
Hello,

I want to add an icon for my Android TV for an application call OQEE.

Please find below as you request the information on the Icon:

`"OQEE": [0, 0, 32.0, 32.0, <path d="m 4.944 9.168 c -0.5136 0.0624 -0.912 0.1872 -1.3632 0.4224 c -0.7536 0.3984 -1.3584 1.1664 -1.536 1.9632 c -0.12 0.5424 -0.1008 1.2384 0.0432 1.68 c 0.408 1.2144 1.536 1.9344 3.0192 1.9344 c 0.8784 0 1.5696 -0.2112 2.1936 -0.6576 l 0.2352 -0.168 l 0.1776 0.144 c 0.4896 0.384 1.176 0.624 1.944 0.6672 l 0.4656 0.0288 l 0.3504 0.3408 c 0.192 0.1872 0.4128 0.3936 0.4896 0.456 c 0.2256 0.1824 0.7104 0.4848 0.7824 0.4848 c 0.0768 0 1.1664 -0.9024 1.1664 -0.9648 c 0 -0.024 -0.0864 -0.0864 -0.1968 -0.1392 c -0.1056 -0.0576 -0.3456 -0.2448 -0.5328 -0.4224 l -0.336 -0.3216 l 0.216 -0.1536 l 0.2112 -0.1536 l 0.1104 0.1152 c 0.1632 0.1776 0.8112 0.4944 1.2336 0.6048 c 0.7728 0.2064 1.8 0.1152 2.5632 -0.2256 c 0.4176 -0.1872 0.432 -0.2256 0.2016 -0.4656 c -0.2496 -0.2592 -0.504 -0.6384 -0.6192 -0.9168 c -0.0528 -0.12 -0.1104 -0.2208 -0.1296 -0.2208 c -0.024 0 -0.1008 0.0432 -0.1728 0.0912 c -0.2208 0.1584 -0.6624 0.2592 -0.9792 0.2256 c -0.504 -0.0528 -0.8688 -0.264 -1.0464 -0.6192 l -0.0912 -0.1776 l 1.3584 0 l 1.3632 0 l 0.0672 0.2256 c 0.3744 1.3584 1.5456 2.1744 3.1152 2.1744 c 0.3408 0 0.6336 -0.0336 0.912 -0.096 c 0.4512 -0.1104 1.104 -0.4032 1.104 -0.4944 c 0 -0.0336 -0.1104 -0.168 -0.2448 -0.2976 c -0.24 -0.2304 -0.6672 -0.8304 -0.6672 -0.9312 c 0 -0.1008 -0.1056 -0.1056 -0.2592 -0.0096 c -0.2496 0.1536 -0.72 0.2592 -1.0032 0.2208 c -0.2736 -0.0384 -0.6288 -0.1728 -0.768 -0.3024 c -0.0912 -0.0816 -0.3216 -0.4128 -0.3216 -0.4656 c 0 -0.0144 0.9168 -0.024 2.0352 -0.024 l 2.04 0 l 0.0384 -0.2304 c 0.072 -0.432 0.0288 -1.0128 -0.1056 -1.4352 c -0.1536 -0.4944 -0.5184 -1.0512 -0.8352 -1.2816 c -0.7152 -0.528 -1.6896 -0.72 -2.6736 -0.5328 c -0.408 0.0768 -1.1472 0.4128 -1.3728 0.6192 l -0.1248 0.12 l -0.2208 -0.168 c -0.3024 -0.2304 -0.7056 -0.4224 -1.1088 -0.528 c -0.4608 -0.1248 -1.5024 -0.1248 -1.944 -0.0048 c -0.4848 0.1344 -1.0368 0.408 -1.2864 0.6432 c -0.048 0.048 -0.1104 0.0192 -0.312 -0.1296 c -0.5424 -0.4128 -1.2384 -0.6192 -2.0832 -0.624 c -0.8016 0 -1.512 0.2016 -2.0592 0.5808 l -0.2688 0.192 l -0.2448 -0.1776 c -0.6528 -0.4704 -1.6464 -0.7056 -2.5296 -0.5952 z m 1.1328 1.7472 c 0.3984 0.216 0.5952 0.5904 0.5952 1.1136 c 0 0.6576 -0.4032 1.2528 -0.9792 1.4304 c -0.3696 0.1152 -0.8784 0.0864 -1.1808 -0.0672 c -0.2112 -0.1056 -0.432 -0.3024 -0.456 -0.4032 c -0.0048 -0.0288 -0.0384 -0.12 -0.0768 -0.1968 c -0.0384 -0.0864 -0.0624 -0.3168 -0.0624 -0.576 c -0.0048 -0.3984 0.0096 -0.456 0.1584 -0.7344 c 0.0912 -0.168 0.2256 -0.336 0.3024 -0.384 c 0.072 -0.0432 0.1344 -0.0912 0.1344 -0.1104 c 0 -0.1008 0.6624 -0.2352 1.0368 -0.216 c 0.2064 0.0144 0.3648 0.0576 0.528 0.144 z m 4.5024 -0.0672 c 1.056 0.3984 1.0512 2.0928 -0.0096 2.5488 c -0.3552 0.1536 -0.84 0.1728 -1.1808 0.0432 c -0.5328 -0.2016 -0.7968 -0.6192 -0.7968 -1.2528 c 0 -0.8736 0.5472 -1.4208 1.4256 -1.4304 c 0.192 -0.0048 0.3936 0.0288 0.5616 0.0912 z m 4.5648 -0.0432 c 0.2784 0.0768 0.5616 0.2928 0.6864 0.5184 l 0.1104 0.1968 l -1.272 0 c -0.7008 0 -1.2768 -0.0192 -1.2768 -0.0432 c 0 -0.0768 0.3936 -0.4896 0.5472 -0.5664 c 0.3024 -0.1584 0.8448 -0.2064 1.2048 -0.1056 z m 4.848 0.096 c 0.216 0.1104 0.552 0.4608 0.552 0.576 c 0 0.024 -0.528 0.0432 -1.272 0.0432 l -1.2768 0 l 0.0576 -0.1104 c 0.0816 -0.1584 0.336 -0.4176 0.4992 -0.4992 c 0.2496 -0.1344 0.3744 -0.1536 0.792 -0.144 c 0.3312 0.0096 0.456 0.0336 0.648 0.1344 z" ]`

Thank you in advance for your help.

**Comment by Lotharion** [comment]
The [link ](https://drive.google.com/file/d/1qBQY_3sRbBFkQsACvLjuj8pSZPFZ_Vtp/view?usp=sharing)to the svg file on Google Drive if is more simple.

Have a nice day.

**Comment by rchiileea** [comment]
this was rough, @elax46 dont put this in, its full of cube lines on the edges not smooth at all, I have fixed it, use this instead

![image](https://github.com/elax46/custom-brand-icons/assets/87599807/7e645ae2-b45d-48d8-a1ca-76d577c59b00)
