### ISSUE TITLE
Icon missing after Refresh in Dashboard-Header

### ISSUE THREAD

**Issue by MickLesk** [elax46/custom-brand-icons#468]
**Describe the bug**
Hey! :-)

I wanted to use the custom icon (Cupra) in my dashboard header. I had mdi:car before and this worked without problems.

As a test I took the Fontawesome extension and used fas:car. This worked. Even after refresh.

Here the problem is that (as you can see from my picture), I can select the icon correctly, save this, but after page refresh the icon disappears.

I can exclude cache, the icon is not displayed on several devices and several browsers (also incognito). 

![image](https://github.com/elax46/custom-brand-icons/assets/47820557/14924556-63e3-4fd1-9ecc-14932565d66e)

## Don't see the icon?

It probably depends on the cache. Open Home assistant from an incognito window and check that the icon loads if yes then it depends on the cache, otherwise double check the installation

**Comment by elax46** [comment]
Add the folowing to the `frontend `section of your `configuration.yaml`

```
frontend:
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
```

https://github.com/elax46/custom-brand-icons#hacs

**Comment by MickLesk** [comment]
Hi,

thats already in there :-)
<img width="396" alt="image" src="https://github.com/elax46/custom-brand-icons/assets/47820557/e8df4c09-c2a6-4422-8bdf-67eaef81f5b2">

ive removed this, restart the ha server, add this & restart again, nothing change.

Home Assistant 2023.9.0
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230906.1 - latest

**Comment by MickLesk** [comment]
okay, after update to Release: HA 2023.9.0 it works 👍🏻
