### ISSUE TITLE
Custom Icon request [Ezviz logo]

### ISSUE THREAD

**Issue by adidash** [elax46/custom-brand-icons#469]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

Hi can you integrate this Ezviz icon
![ezviz](https://github.com/elax46/custom-brand-icons/assets/10267727/c4537bb8-a779-4eab-a249-2c08fa606f0c)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/edc86ba0-611e-4ad1-b0d6-c144c9e5ca45)
