### ISSUE TITLE
Custom Icon request [Eero]

### ISSUE THREAD

**Issue by c3p0vsr2d2** [elax46/custom-brand-icons#470]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://www.vectorlogo.zone/logos/eero/eero-ar21.svg
https://www.svgrepo.com/download/516095/eero.svg

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/600500d2-edb4-400a-b45b-bd33b0f7927d)

**Comment by c3p0vsr2d2** [comment]
many thanks for creating the eero logo, but it seems like the new eero logo is:
https://www.vectorlogo.zone/util/preview.html?image=/logos/eero/eero-ar21.svg

(this is the one seen at eero.com)
could we perhaps update the logo?

**Comment by rchiileea** [comment]
that was ripped from there ios app which is current with slightly stretched text as it was too small to be eligible
