### ISSUE TITLE
Custom Icon request [Picnic]

### ISSUE THREAD

**Issue by KentuckyMC** [elax46/custom-brand-icons#471]
Is there an option to add the dutch grocery delivery company: Picnic?

**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://upload.wikimedia.org/wikipedia/commons/0/01/Picnic_logo.svg

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/de9504c4-5526-420e-bca5-48ece7fc2e23)
