### ISSUE TITLE
Custom Pool & Chemical Icons Pack PLs

### ISSUE THREAD

**Issue by cloudbr34k84** [elax46/custom-brand-icons#474]
Hey do you need these icons in SVG or can you do it?

Pool Filter - https://www.flaticon.com/free-icon/filter_3126663?related_id=3126663&origin=pack
Pool Depth - https://www.flaticon.com/free-icon/pool-depth_3126643?related_id=3126643&origin=pack
Salinity - https://www.flaticon.com/free-icon/salt-water_7225259
Chlorine - https://www.flaticon.com/free-icon/chlorine_8406002?term=chlorine&page=1&position=2&origin=search&related_id=8406002
Water Electric Conductivity - https://www.flaticon.com/free-icon/electric_2623901?term=electrical+water&page=1&position=3&origin=search&related_id=2623901
total dissolved solids - https://www.flaticon.com/free-icon/drop_11590021?term=water&page=1&position=44&origin=search&related_id=11590021

**Comment by rchiileea** [comment]
Thats a lot for one request :O

**Comment by cloudbr34k84** [comment]
> Thats a lot for one request :O

Whats the best way for me to help??

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/8f6e9e51-77ec-469a-99a9-84aa619b90da)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/84252228-35c7-481e-903f-871996acbe60)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/46b088cd-db54-44e1-8642-757563147171)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/98644425-9ac7-4cae-b826-fcee2c6a915e)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/11f49386-8bc9-41db-9ad0-cd5a68cbbded)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/0f5fc171-5b59-406f-9c83-4c91a6cac41e)

like this :P cchanged the icons a bit to have a bit more originality (cut open filter to have visible filter inside).

**Comment by cloudbr34k84** [comment]
Man how good are these!!! ill make sure to share this on a few facebook posts and HA community posts as lots of ppl have pool sensors that track all of these!
