### ISSUE TITLE
Custom Icon request [water reservoir]

### ISSUE THREAD

**Issue by EvertJob** [elax46/custom-brand-icons#476]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

https://www.flaticon.com/free-icon/reservoir_4947130?term=water+reservoir&page=1&position=43&origin=search&related_id=4947130

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/7c48bfb3-d203-474b-ae54-820634ec798e)

**Comment by EvertJob** [comment]
Great!

**Comment by rchiileea** [comment]
done and finalised file now :( dont worry just add a drop shaddown to it and it will change your opinion :P
