### ISSUE TITLE
Ring Icons

### ISSUE THREAD

**Issue by broyuken** [elax46/custom-brand-icons#48]
Requesting some icons for Ring devices to be added. Specifically the Ring Floodlight Cam and the Ring Floodlight Wired. I don't seem to be able to find any icons existing for them, but nobody seems to have anything even remotely close. 

If possible, this would be a good list to be created for many members of the community, but the 2 above would be the most useful for me personally.
Ring Floodlight Cam
Ring Floodlight Wired
Ring Doorbell Pro
Ring Alarm
Ring Keypad
Ring Spotlight Cam
Ring Indoor Cam

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/140657650-3e5b5f6f-955e-4df2-a59f-a50ccf992718.png)
[ring doorbell.zip](https://github.com/elax46/custom-brand-icons/files/7492878/ring.doorbell.zip)

**Comment by elax46** [comment]
@rchiileea When you have time, could you also do the others indicated? thanks for your valuable contribution

**Comment by rchiileea** [comment]
will do but have a few others to work through in the free time between work (its my lunch hours etc  I do these things it helps me wind down a bit)

**Comment by elax46** [comment]
Ok thanks, when you can! @rchiileea

**Comment by rchiileea** [comment]
I will get round to doing 

floodlight cam = (but not pro as well as they are both basically the same thing apart from the shape of lights)
alarm  = is possible,
keypad = makes no sense as the buttons would have to be super tiny to fit them all in, which could mess up the appearance,
Indoor Cam = possible
doorbell pro = a possible too

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/141293451-401c2e1b-733a-4910-9427-c6f4b78750c3.png)
![image](https://user-images.githubusercontent.com/87599807/141293533-447d5309-d90f-4e1b-8661-72aa165edf15.png)
![image](https://user-images.githubusercontent.com/87599807/141293601-3a0a12d2-dd48-40dc-a709-8548758227a8.png)

**Comment by elax46** [comment]
> Work in progress
> 
> ![image](https://user-images.githubusercontent.com/87599807/141293451-401c2e1b-733a-4910-9427-c6f4b78750c3.png) ![image](https://user-images.githubusercontent.com/87599807/141293533-447d5309-d90f-4e1b-8661-72aa165edf15.png) ![image](https://user-images.githubusercontent.com/87599807/141293601-3a0a12d2-dd48-40dc-a709-8548758227a8.png)

wow amazing icon

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/141466927-71405715-e264-4853-81fb-49de1b81f802.png)
Door bell pro
![image](https://user-images.githubusercontent.com/87599807/141468619-189a023d-cbed-4dbc-a467-9f62c5afa011.png)
Ring Alarm panel Best I could do
![image](https://user-images.githubusercontent.com/87599807/141467287-4a7c68e6-d7bd-4385-b2cd-a50c0757d110.png)
Ring alarm
![image](https://user-images.githubusercontent.com/87599807/141467444-f5350889-c243-4440-8494-b242c0ebf82f.png)
Ring flood light
![image](https://user-images.githubusercontent.com/87599807/141468690-0ee63f29-cee8-444f-99f6-877997146f5a.png)
Ring spotlight
![image](https://user-images.githubusercontent.com/87599807/141468797-711a2dcf-3271-411b-bb13-4638a62bbd4d.png)
Ring Stick up cam
[ring-icon svg.zip](https://github.com/elax46/custom-brand-icons/files/7527608/ring-icon.svg.zip)

**Comment by elax46** [comment]
> > Work in progress
> > ![image](https://user-images.githubusercontent.com/87599807/141293451-401c2e1b-733a-4910-9427-c6f4b78750c3.png) ![image](https://user-images.githubusercontent.com/87599807/141293533-447d5309-d90f-4e1b-8661-72aa165edf15.png) ![image](https://user-images.githubusercontent.com/87599807/141293601-3a0a12d2-dd48-40dc-a709-8548758227a8.png)
> 
> wow amazing icon

Thanks for your amazing work

**Comment by broyuken** [comment]
wow these are incredible! Thank you! Any chance I could bother you for one more? The floodlight wired, without a camera.

https://ring.com/products/smart-lighting-floodlight-wired

**Comment by elax46** [comment]
do not thank me thanks @rchiileea he made the icons, create a new request and see later

**Comment by rchiileea** [comment]
I’ll do it but it will be quick, but you could buy relax a coffee for the coding side :) will be a carbon copy of the floodlight cam just without cam and only sensor

**Comment by broyuken** [comment]
absolutely, thanks for all your hard work!

**Comment by rchiileea** [comment]
> absolutely, thanks for all your hard work!

take a look in the update
