### ISSUE TITLE
Custom Icon request: Soil Moisture Icons

### ISSUE THREAD

**Issue by cloudbr34k84** [elax46/custom-brand-icons#481]
Hey Again mate

Any chance you can make these
![soil-moisture](https://github.com/elax46/custom-brand-icons/assets/58960644/ab8f89e0-9eb6-494f-89ca-ebbd19130ad4)
![istockphoto-1309912166-612x612](https://github.com/elax46/custom-brand-icons/assets/58960644/e9f04c51-99bc-442d-8b9c-b6b287c5cf98)

**Comment by rchiileea** [comment]
done my own take on these as i did not want copy and paste icons
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/e8e1fd0a-5e0c-4f81-9153-76795a218f0a)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/3c448d39-a151-4907-b82c-4a9096c9ad0f)
