### ISSUE TITLE
Custom Icon request for WPS (Wi-Fi Protected Setup)

### ISSUE THREAD

**Issue by MelleD** [elax46/custom-brand-icons#483]
I currently know WPS signs with the Wi-Fi sign and a label “WPS”.
e.g. this sign https://play.google.com/store/apps/details?id=com.themausoft.wpsapp&hl=de

Better ideas are welcome :)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/b7e955b1-d7c0-4c04-bdbf-4f08cbfd9804)
