### ISSUE TITLE
Water softener is not included in the distribution

### ISSUE THREAD

**Issue by MelleD** [elax46/custom-brand-icons#484]
I think the water-softener is missing in the distribution:
https://github.com/elax46/custom-brand-icons/blob/main/dist/custom-brand-icons.js

Cannot find it and also did try to add it in HA and get an empty icon.

Thanks

Could not reopen the orginal post :)
_Originally posted by @MelleD in https://github.com/elax46/custom-brand-icons/issues/461#issuecomment-1768877453_

**Comment by rchiileea** [comment]
@elax46 can you check, as it does not show for me either

**Comment by MelleD** [comment]
Thanks
