### ISSUE TITLE
TV Channel [Rede Bandeirantes]

### ISSUE THREAD

**Issue by rodolfomachado** [elax46/custom-brand-icons#486]
Hi,

Please, add the following tv channel Rede Bandeirantes 

https://pt.wikipedia.org/wiki/Rede_Bandeirantes#/media/Ficheiro:Rede_Bandeirantes_logo_2018.svg

**Comment by rchiileea** [comment]
you can have the Rede logo, but we wont go into doing indivdual channels no more due to the fact we dont want to weigh the libary down with 10,000,000+ global channels.

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/d2226c0b-0c29-49f2-9e5c-2e5826619a9a)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/811854d1-73e8-4464-af41-64662ccda64d)
