### ISSUE TITLE
Custom Icon request: Oura Ring "O"

### ISSUE THREAD

**Issue by aetchells55** [elax46/custom-brand-icons#488]
(https://drive.google.com/file/d/18SCkeMNL92UTobjeifsNOhZOtsQLj_cg/view?usp=drive_link)

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/5a9f9af3-55e7-40e1-a254-558ad93c65d6)
