### ISSUE TITLE
Custom Icon request: Peloton "P"

### ISSUE THREAD

**Issue by aetchells55** [elax46/custom-brand-icons#489]
[Peloton P](https://drive.google.com/file/d/1YEjcnrni3Ft-TpRh37AB1hB3Xm0arcU4/view?usp=drive_link)

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
sorry please dont upload blocky stuff like this it is of no use, please read updated rules as well for requesting icons for next time and put multiple requests into one post. 
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/8f55aee4-465a-4c9f-81b5-d2f929fced54)
