### ISSUE TITLE
Custom Icon request - OctoPrint

### ISSUE THREAD

**Issue by sym0nd0** [elax46/custom-brand-icons#49]
**Provide a URL that points to an image of this fixture/bulb**

https://octoprint.org/assets/img/logo.png

**Additional context**

I know there would be a lot of people that would have a use for this. Material Design aren't interested, as it's a brand... 

Outline or silhouette would be great!

**Comment by elax46** [comment]
integrated icon!

**Comment by sym0nd0** [comment]
@elax46 You're awesome, thank you!
