### ISSUE TITLE
Icons are invisible only in the HA App

### ISSUE THREAD

**Issue by oliver073** [elax46/custom-brand-icons#493]
Icons are invisible every time I open the home assistant app.
It helps to open and close the raw configuration editor - without changing or saving anything. Then all icons are visible.
Unfortunately only until the next time I open the app.
This error only occurs in the app.
Clearing the cache or reinstalling the app didn't help either.

Thank you,
Oliver

**Comment by elax46** [comment]
laws #287 #432 #1

**Comment by rchiileea** [comment]
closed as 1 month has passed

**Comment by ctournayre** [comment]
Same problem here. All work great in browsers but in the app all custom brand icons doesn't appear. If I edit in app the configuration of a card using custom icon and just press save all icon reappears.

**Comment by elax46** [comment]
you could specify what changes you made and on this card so we can integrate it into Redme, if you like you can make a pull request by writing a paragraph on the measures taken

**Comment by rchiileea** [comment]
do you have frontend:
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
in your config?
