### ISSUE TITLE
Update 2023.10.1 to 2023.10.3 Breaks all cards in HA with custom-brand-icons

### ISSUE THREAD

**Issue by Tekonsite** [elax46/custom-brand-icons#496]
After the update the card that uses the icon no longer is displayed.

Since I use custom-brand-icons in most of my cards my HA is no longer functional and I had to refer back to a backup before the recent update

**Comment by elax46** [comment]
Could you be more specific in stating the problem? Have you tried installing and uninstalling the component? do you have errors in the log? 

Add the folowing to the `frontend `section of your `configuration.yaml`

```
frontend:
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
```

https://github.com/elax46/custom-brand-icons#hacs

**Comment by Tekonsite** [comment]
Issue resolved
An update to Mushroom cards in HACs was the fix before update to custom-brand-icons

Thanks
Tekonsite



Sent from my Galaxy



-------- Original message --------
From: Emanuele ***@***.***>
Date: 2023-11-01 2:37 p.m. (GMT-05:00)
To: elax46/custom-brand-icons ***@***.***>
Cc: Tekonsite ***@***.***>, Author ***@***.***>
Subject: Re: [elax46/custom-brand-icons] Update 2023.10.1 to 2023.10.3 Breaks all cards in HA with custom-brand-icons (Issue #496)


Could you be more specific in stating the problem? Have you tried installing and uninstalling the component? do you have errors in the log?

Add the folowing to the frontend section of your configuration.yaml

frontend:
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js


https://github.com/elax46/custom-brand-icons#hacs
