### ISSUE TITLE
Custom Icon request [Clock with euro symbol]

### ISSUE THREAD

**Issue by EvertJob** [elax46/custom-brand-icons#498]
Usable for the sensors that holds the cheapest energy prices.
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
![image](https://github.com/elax46/custom-brand-icons/assets/58138839/be6a7eb8-25d6-4d76-b373-b90a3a974222)

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/64d19dbb-4ac3-48f9-b356-1fd65bc1cf57)

**Comment by EvertJob** [comment]
Looks perfect!

**Comment by EvertJob** [comment]
Maybe better to rename to icon from `euro` to `clock-euro` so I've someone requests another clock in the future that name is still available?

**Comment by elax46** [comment]
> Maybe better to rename to icon from `euro` to `clock-euro` so I've someone requests another clock in the future that name is still available?

in the next update i fix the name
