### ISSUE TITLE
Custom Icon request [Easee charge lite]

### ISSUE THREAD

**Issue by Corsw** [elax46/custom-brand-icons#499]
![cvVx4X01](https://github.com/elax46/custom-brand-icons/assets/108132302/b32b263e-352a-465b-b434-eb4d2e8a83c7)
![easee-Charge-Core-Charging-Robot](https://github.com/elax46/custom-brand-icons/assets/108132302/165d1661-8639-4975-9067-c8058afb103d)

Can we add the easee charger lite wallbox icon?

**Comment by rchiileea** [comment]
illl make this solid as the lines are thin in my opinion.

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/7fbc21ea-a9c8-4f0a-a96d-daff090c6a4a)

**Comment by Corsw** [comment]
Looks very nice, thanks for the effort!
