### ISSUE TITLE
Custom Icon request, Centris 4

### ISSUE THREAD

**Issue by rvdlinden** [elax46/custom-brand-icons#500]
In the Philips Hue list of lights are various Centris icons, but there is no icon for the centris 4 light. Only Centris, two and three. 

Could an icon for Centris 4 be added too?

Kind regards,
Rene

**Comment by rchiileea** [comment]
if you buy me one for my kitchen ill make the icon  🤣 

on a serious not ill add it to the list, november is a busy month for me, birthdays, family visits and a family wedding at the weekend, will get done some time in the next two weeks.

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/7e375a78-5a4e-4afd-a6ab-23d4b42103e7)
