### ISSUE TITLE
Custom Icon request [IKEA PILSKOTT]

### ISSUE THREAD

**Issue by EvertJob** [elax46/custom-brand-icons#503]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
I cannot find a suitable SVG file for it:
![image](https://github.com/elax46/custom-brand-icons/assets/58138839/f3463f8f-a6fc-4bd2-9ecc-611170e91acc)

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
ouch thats going to be a hard icon due to it will just look like a thin line, maybe a comprimise of making it a bit stubby (shorter) so its at least visible in all sizes.

**Comment by EvertJob** [comment]
Sounds great 👍

**Comment by EvertJob** [comment]
Nice!Sent from my iPhoneOn 29 Nov 2023, at 17:03, Richard Bowzer ***@***.***> wrote:﻿
image.png (view on web)
