### ISSUE TITLE
Icons not visible

### ISSUE THREAD

**Issue by Marko298** [elax46/custom-brand-icons#504]
Hello, I have problem with icons. I don't think it is related to the cache as it works if I switch dashboards or just navigate to another tab. I tried to clean caches in all possible ways. Same thing in incognito mode. Take a look on the video
https://share.cleanshot.com/kW2nGQwL

**Comment by elax46** [comment]
laws https://github.com/elax46/custom-brand-icons/issues/287 https://github.com/elax46/custom-brand-icons/issues/432 https://github.com/elax46/custom-brand-icons/issues/1

**Comment by rchiileea** [comment]
closed as no response
