### ISSUE TITLE
Custom Icon request: Brother Printer Icon

### ISSUE THREAD

**Issue by chintito4ever** [elax46/custom-brand-icons#505]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

Please add brother printer icon

**Comment by rchiileea** [comment]
I would like to see a sample of this please! this could be one of 100s of icons

**Comment by rchiileea** [comment]
closing as no response
