### ISSUE TITLE
Custom Icon request [Bluetooth Mesh Gateway]

### ISSUE THREAD

**Issue by BenJamesAndo** [elax46/custom-brand-icons#506]
https://greenhse.com/pub/media/catalog/product/cache/99248b4c629e9c0324d4392eebe4008a/b/t/bt_mesh_gateway04_2.png

https://m.media-amazon.com/images/I/51gk45jCMkL._AC_SL1500_.jpg

Plenty of companies sell these branded Tuya devices. They all look very similar. Can sometimes be referred to online as a Smart Wireless Bluetooth Gateway Mesh SIG.

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/391535e8-208b-41fb-a371-f33ec1dacf12)

**Comment by BenJamesAndo** [comment]
Looks great, thank you :)
