### ISSUE TITLE
Custom Icon request [Sonoff SNZB-01P]

### ISSUE THREAD

**Issue by BenJamesAndo** [elax46/custom-brand-icons#509]
[Sonoff SNZB-01P SVG](https://sonoff.tech/wp-content/uploads/2023/05/SNZB-01P_15.png)

[With Packaging](https://i.ebayimg.com/images/g/QG0AAOSwpidk1z7q/s-l1600.jpg)

Would probably very similar to `phu:aqara-wirelessbutton` except fully circular.

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/b6e72e91-7c7b-4577-8f16-db1e48132f99)
