### ISSUE TITLE
Custom Icon request for Amazon logo

### ISSUE THREAD

**Issue by bcutter** [elax46/custom-brand-icons#51]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**

Amazon logo, as it´s being removed by MDI and HA Core 2021.12 (announced with HA Core 2021.10)

**Provide a URL that points to an image of this fixture/bulb**

https://icon-sets.iconify.design/ant-design/amazon-outlined/

**Additional context**

Logo name proposal: `amazon-logo`

**Comment by elax46** [comment]
integrated! in the newly released version
