### ISSUE TITLE
Multiple Sockets

### ISSUE THREAD

**Issue by Doom666DE** [elax46/custom-brand-icons#511]
I would like an icon like that. 
https://static.vecteezy.com/system/resources/thumbnails/004/650/925/small/power-strip-glyph-icon-vector.jpg

Because I have a few multiple sockets where I can switch the 3 individual ACs on/off and can also switch 3 USB ports on/off in a group.

**Comment by Doom666DE** [comment]
Thanks for the quick add and update. Unfortunately I don't see the new icons even though the extension is recognized and the older icons work, just not the new ones.


https://github.com/elax46/custom-brand-icons/assets/98554600/a4d1bb8e-cc81-4435-81de-8efeb6b50657

**Comment by elax46** [comment]
> Thanks for the quick add and update. Unfortunately I don't see the new icons even though the extension is recognized and the older icons work, just not the new ones.
> 
>  Aufzeichnung.2023-12-09.182519.mp4

![Screenshot 2023-12-10 220555](https://github.com/elax46/custom-brand-icons/assets/55278049/247fade7-6c77-4a69-b80f-6bac17095bea)
clear cache
