### ISSUE TITLE
Custom Icon request [Grogu]

### ISSUE THREAD

**Issue by soloam** [elax46/custom-brand-icons#514]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

https://wannacraft.com/uploads/3/4/5/8/34583508/baby_yoda_head.svg

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/a239732f-0dc4-44e8-8ede-c57136e39052)

**Comment by soloam** [comment]
That's perfect 😱😀

**Comment by elax46** [comment]
> That's perfect, but now that I use it, it looks very small, can it be made bigger? Probably taking it to the limit of the canvas?

sizes are standard for all icons

**Comment by soloam** [comment]
I know that it's standard, but it looks like the canvas has empty space around the icon, the drawing could be increased to fill the canvas

**Comment by elax46** [comment]
> I know that it's standard, but it looks like the canvas has empty space around the icon, the drawing could be increased to fill the canvas

he takes care of it @rchiileea

**Comment by rchiileea** [comment]
the empty space only shows on preview above no icon can ever go in that space, if you look at the others in closed you will see the same preview for all others with space around...  if I protrude into it home assistant will freak out and not accept the icon, we are constrained.
