### ISSUE TITLE
Custom+Icon+request

### ISSUE THREAD

**Issue by Paul-M-Alderson** [elax46/custom-brand-icons#515]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

https://upload.wikimedia.org/wikipedia/en/thumb/a/a6/Sky_Group_logo_2020.svg/512px-Sky_Group_logo_2020.svg.png

**Comment by rchiileea** [comment]
we have sky icons

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/d30651d1-cf46-42c3-86cf-7fa1095efa04)

**Comment by Paul-M-Alderson** [comment]
Where is the sky-alt logo located? I can only see; sky-q-logo
________________________________
