### ISSUE TITLE
bifurcation

### ISSUE THREAD

**Issue by iturbay** [elax46/custom-brand-icons#516]
Good day! When adding icons to HA, they are displayed double. In the description they look like a single copy. This applies to the icons vac_filter, vac_mbrush, and vac_mop is rotated. Is this a bug or a problem for me?

![2023-12-14 124154](https://github.com/elax46/custom-brand-icons/assets/17631899/b874e7dc-338b-43af-aa15-1c79471b0706)

**Comment by elax46** [comment]
A pre-version has been released to test the icon fix. For the vac_mop icon some correction needs to be applied to the icon, so I ask @rchiileea

**Comment by rchiileea** [comment]
this was instensional so Icon fills a space, if they were not made this way they would show as very very small due to their ultrawide retangular proportions.
