### ISSUE TITLE
Custom Icon request [Analogue Brand Icons]

### ISSUE THREAD

**Issue by notmayo** [elax46/custom-brand-icons#518]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**
Analogue Logo
https://svgur.com/s/10tD
Analogue 3D
https://svgur.com/s/10rz

Can't find other logos for their other products yet but if I do I will submit!

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/ef9cd735-0297-4268-aee6-58b74ae6b54b)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/f08a526c-2924-4d01-8136-cf83c379ae51)
