### ISSUE TITLE
Custom Icon request for 'Nextcloud'

### ISSUE THREAD

**Issue by JHubi1** [elax46/custom-brand-icons#519]
![nextcloud-logo-icon](https://github.com/elax46/custom-brand-icons/assets/61345690/03d63138-a2b4-42b7-8058-8b939e89845e)

Or use other icon from:
[https://nextcloud.com/de/trademarks/](https://nextcloud.com/de/trademarks/)

**Comment by elax46** [comment]
the icon is already available
