### ISSUE TITLE
Custom Icon request for Amazon fireTV

### ISSUE THREAD

**Issue by bcutter** [elax46/custom-brand-icons#52]
_If there is a specific hue fixture or bulb that you want an icon for, let me know and I will try to create it for you and add it to this pack._

**What is the specific model of hue fixture/bulb that you want an icon for**

Amazon fireTV

**Provide a URL that points to an image of this fixture/bulb**

https://icon-sets.iconify.design/simple-icons/amazonfiretv/

**Additional context**

- Icon name proposal: `firetv`
- There´s an Apple TV icon already, and finally there will an Amazon fireTV :-)

**Comment by elax46** [comment]
integrated! in the newly released version
