### ISSUE TITLE
Custom Icon request Octopus Energy

### ISSUE THREAD

**Issue by abbottcam** [elax46/custom-brand-icons#520]
Hi there, 

I was wondering if it's possible to include an icon for Octopus Energy? Which is an energy company in the UK. Ive attached the PNG file, also an SVG file. 

![bitmap](https://github.com/elax46/custom-brand-icons/assets/63968948/b151b7ee-d7eb-4759-8240-925cff607d24)
![icon](https://github.com/elax46/custom-brand-icons/assets/63968948/7b93b2a4-8a1b-459e-8a0e-ef12e4324927)
![icon](https://github.com/elax46/custom-brand-icons/assets/63968948/341cbb07-5278-4eae-abbd-fbd749c1655c)
![icon@2x](https://github.com/elax46/custom-brand-icons/assets/63968948/0aa234e5-1211-45a2-82c6-de7aa00d3afa)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/f04ec208-c9d7-454c-8035-827a9d5b5ba7)
