### ISSUE TITLE
Custom Icon request tp-link

### ISSUE THREAD

**Issue by Reibeiro2017** [elax46/custom-brand-icons#521]

**Comment by rchiileea** [comment]
image not found when i try to save it

**Comment by Reibeiro2017** [comment]
https://i.imgur.com/DBrytPr.png
<a href="https://imgur.com/DBrytPr"><img src="https://i.imgur.com/DBrytPr.png" title="source: imgur.com" /></a>

**Comment by Reibeiro2017** [comment]
https://i.imgur.com/DBrytPr.png

**Comment by Reibeiro2017** [comment]
![Archer_AX73](https://github.com/elax46/custom-brand-icons/assets/109174594/a49a052d-f70c-4fd5-92af-6b73eb6efeea)
![WDSN750](https://github.com/elax46/custom-brand-icons/assets/109174594/bcac79b6-0c36-4290-b4dc-a38a25e527c6)
![PGSE](https://github.com/elax46/custom-brand-icons/assets/109174594/e639f837-14d0-41e9-b43c-526b8e480674)

**Comment by mateuszdrab** [comment]
Hey @Reibeiro2017 

Those image links have token protection - it will be better if you download the SVGs and attach them to your comment.

**Comment by Reibeiro2017** [comment]
![Archer_AX73](https://github.com/elax46/custom-brand-icons/assets/109174594/7dde4908-399a-473a-b3a7-9018ecc63045)
![PGSE](https://github.com/elax46/custom-brand-icons/assets/109174594/942712a4-7602-421b-95a7-ac30b5886bbf)
![WDSN750](https://github.com/elax46/custom-brand-icons/assets/109174594/f0bf1cc9-58b0-44fb-9e11-7ba0cd9a5d77)

**Comment by Reibeiro2017** [comment]
I believe this is now correct?
[https://svgshare.com/s/11oB](url)
[https://svgshare.com/s/11oC](url)
[https://svgshare.com/s/11nG](url)

**Comment by Reibeiro2017** [comment]
I believe this is now correct?
[https://svgshare.com/i/11oB.svg](url)
[https://svgshare.com/i/11nG.svg](url)
[https://svgshare.com/i/11oC.svg](url)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/dcaeff3b-51b9-454c-b8d8-8d6fbdd6ca40)
This will be added on the next update.

**Comment by Reibeiro2017** [comment]
thanks! I had given up trying, I appreciate the effort on your part.
