### ISSUE TITLE
Custom Icon request [Bambu Lab]

### ISSUE THREAD

**Issue by mateuszdrab** [elax46/custom-brand-icons#522]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

https://www.printables.com/model/367329-bambu-lab-logos-svg

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/8da74666-1d49-4ae2-8cd4-05419b527d19)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/24c56216-3f33-4ee6-9247-475a36b586cc)

**Comment by mateuszdrab** [comment]
Thank you so much @rchiileea
