### ISSUE TITLE
Custom Icon request (Dutch) TV/Internet Providors

### ISSUE THREAD

**Issue by Dominic-070** [elax46/custom-brand-icons#525]
Ziggo:
https://origin.ziggo.nl/content/dam/ziggo/klantenservice/internet-en-wifi/apps/70x70-MijnZiggo1.svg

Odido:
https://ampgroep.nl/wp-content/uploads/2022/12/Logo_Odido_Tekengebied-1.svg

KPN:
https://www.glasvezel-vergelijken.nl/uploads/providers/kpn/logo/2ad231418827a0a8deeb35169e70d126/logo-kpn.svg

Caiway:
https://www.glasvezel-vergelijken.nl/uploads/providers/caiway/logo/9eee1f3c62dee96908d9ee26de36bd56/logo-caiway.svg

Delta:
https://www.glasvezel-vergelijken.nl/uploads/providers/delta/logo/3d60080677c8aba3597bb7e376834093/delta.svg

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/26f83eec-a45f-40a2-bec7-4ddb22c2022e)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/733a67d8-d628-49dc-bd32-6774d3e40695)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/3727d484-80e8-4e9e-a2fc-0efb0d520257)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/93c2bb5b-91bd-4514-a607-6f20c9ea611c)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/91623e89-1a97-4834-8cfc-cc2ce57eab58)

**Comment by Dominic-070** [comment]
Thnx!
