### ISSUE TITLE
Custom Icon request [octopus energy]

### ISSUE THREAD

**Issue by mateuszdrab** [elax46/custom-brand-icons#528]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

I couldn't find the svg for the octopus icon but I found this SVG which I think you can cut it out from:

https://static.octopuscdn.com/logos/works-with-octopus-dark.svg

Would that work?

**Comment by elax46** [comment]
add in dev branch
