### ISSUE TITLE
sonos  bookshelf speaker

### ISSUE THREAD

**Issue by jrspowers** [elax46/custom-brand-icons#53]
Hallo ,
could you make an icon for the sonos bookshelf speaker that would be great ?

[sonos  bookshelf speaker](https://www.ikea.com/nl/nl/p/symfonisk-wifi-boekenplankspeaker-zwart-50357554/)

**Comment by elax46** [comment]
hello thanks for your request to make the icon in svg I would need a photo of the product (without backgrounds) horizontally if you find share them here thanks I only found horizontal renderings with background

**Comment by elax46** [comment]
![main_5ape](https://user-images.githubusercontent.com/55278049/137644658-93a487d1-efb2-402b-8b18-4a8b172b64d9.jpg)

More something like this I'll try to draw from this one

**Comment by elax46** [comment]
do you prefer vertically or horizontally?

**Comment by jrspowers** [comment]
Too bad there's no good icon out

**Comment by elax46** [comment]
If you are able to reproduce it in svg I can insert it

**Comment by jrspowers** [comment]
i will try if i succeed

**Comment by jrspowers** [comment]
hello I was able to convert it to svg but I don't know if it's that good ?

**Comment by jrspowers** [comment]
can't send it so can't you deliver it?

**Comment by elax46** [comment]
post me the svg here

**Comment by jrspowers** [comment]
I can't upload svg files here in github so can't deliver it from here

**Comment by elax46** [comment]
usa mega e posta il link qui

**Comment by jrspowers** [comment]
https://mega.nz/file/3gRCgLhA#QA_vIknVFCtz0WQ0VkH53YSwI5LmOBvI0KffJIThqhA

**Comment by elax46** [comment]
it is unusable

**Comment by elax46** [comment]
Integrated icon will be available in the next update

**Comment by jrspowers** [comment]
Thanks man
