### ISSUE TITLE
Please add TuenAero Windows Airplay receiver icon

### ISSUE THREAD

**Issue by iVolt1** [elax46/custom-brand-icons#531]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
![tuneaero_67390](https://github.com/elax46/custom-brand-icons/assets/71899823/556f733b-d67c-415c-81f7-a23da365aa2e)

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

Thanks!

**Comment by rchiileea** [comment]
just checking  on this, is not airplay in windows this icon, it is on my 11 machine 

![image](https://github.com/elax46/custom-brand-icons/assets/87599807/7a00921a-c1c9-4af1-b296-254cc565aeaa)

**Comment by iVolt1** [comment]
Hi Richard,

I wasn't sure if the TuneAero icon was in the pipeline here or not as it assigned to you but Emanuele has put it on the Roadmap

TuneAero is an excellent Airplay 1 receiver that runs on Windows.  I suggested as it would be nice to distinguish it this in long my list Airplay 1 receivers that I connect to using OwnTone via the Home Assistant HopePod Connect addon.

There is a limited free version and an inexpensive license to run it on multiple machines.

http://www.tuneaero.com/

Thanks for your consideration,

iVolt1

**Comment by rchiileea** [comment]
I can make this no problem, I just wanted to make sure

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/8e5828e2-6b50-47ad-8d11-4c81f79e28bd)

**Comment by iVolt1** [comment]
That looks great.. Thanks!
