### ISSUE TITLE
FR - add set to Iconfy

### ISSUE THREAD

**Issue by schmierlappe** [elax46/custom-brand-icons#533]
**Describe the bug**

There is a new project by @matt8707 which called ha-fusion and here is his answer to make it possible to use this cool set of icons. Would that be possible?

  _"I've looked into it. The file is very large, and I would need to write custom code to parse just this set._ 
 _Therefore, it's better if you ask elax46/custom-brand-icons to publish the icon set on Iconify_ 
 _https://iconify.design/docs/articles/add-icon-set/"_

**Comment by elax46** [comment]
@schmierlappe I have opened a request for inclusion

**Comment by elax46** [comment]
In the next few hours the icons will be available and the readme will also be updated to indicate references on how all the icons can be used via the framework
