### ISSUE TITLE
Custom Icon request [Google]

### ISSUE THREAD

**Issue by kknishev** [elax46/custom-brand-icons#536]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

nest-display-max
![nest_display_max_FILL0_wght400_GRAD0_opsz24](https://github.com/elax46/custom-brand-icons/assets/22073966/222564ad-3e78-48c1-a30b-e592a0f6e687)

home-max
![home_max_dots_FILL0_wght400_GRAD0_opsz24](https://github.com/elax46/custom-brand-icons/assets/22073966/c33180ce-50bd-414f-ba5b-9f1e9f54f9ed)

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/07b74c9d-2229-477b-9db0-71046834aa2f)

I changed the max hub though as we have a nice one for the largest alexa so only right one for the google one

![image](https://github.com/elax46/custom-brand-icons/assets/87599807/89f784e6-f1d6-4c18-bf17-c2cddc12c55b)

**Comment by kknishev** [comment]
Ohh, it's okey for nest-hub-max - it's a device with display,
but Google Home Max (home-max) - it's the greatest AUDIO SPEAKER with Google Assistant ever!!
https://www.dxomark.com/google-home-max-speaker-review-powerful-and-well-balanced/
add it please ))

**Comment by romanr** [comment]
> @rchiileea @romanr Ohh, it's okey for nest-hub-max - it's a device with display, but Google Home Max (home-max) - it's the greatest AUDIO SPEAKER with Google Assistant ever!! https://www.dxomark.com/google-home-max-speaker-review-powerful-and-well-balanced/ https://fonts.google.com/icons?icon.query=home+max add it please ))

Add request in Discussions. This ticket is closed.

**Comment by rchiileea** [comment]
@romanr its the same logo, just in the uk the device is call the nest hub lol the icon he says is not it, if you click his link its the home max.
