### ISSUE TITLE
fronius-inverter-gen24.svg

### ISSUE THREAD

**Issue by Federico83-hassio** [elax46/custom-brand-icons#537]
**Describe the bug**
fronius-inverter-gen24.svg icon no longer visible shown only a dot

## Don't see the icon?

Hi, it's been about two of weeks that fronius-inverter-gen24.svg is no longer displayed, instead a dot appears in the upper left corner as if it was accidentally deleted, can it be restored?

**Comment by elax46** [comment]
could you check this icon? Thank you @rchiileea

**Comment by Federico83-hassio** [comment]
if you need it i have original fronius icon taken from my inverter

**Comment by rchiileea** [comment]
not 100% sure as copying the code from the .js shows the icon, but it does not show in HA, although one thing is strange the icon in .js file has starts with M 8 were most icons have no space after the M, I tested the code out with and without the space and they show up on the system so it is very strange. try removing the space in the js between m and 8 and see if that fixes it., its also not in the svg folder either so I can download it to check saved boundries.

**Comment by rchiileea** [comment]
view box is out for some reason, its 0,0,254,254 when it should be 0,0,32,32

**Comment by Federico83-hassio** [comment]
I tried as suggested but the I do not display anything by changing from M 8 M8
![inverter_gen24](https://github.com/elax46/custom-brand-icons/assets/58251354/5373eaeb-713b-4f5d-9195-0d2ea8e38092)
if it comes in handy i will attach the original fronius icon

**Comment by elax46** [comment]
Dimensional problem solved, will be updated in next version

**Comment by Federico83-hassio** [comment]
sorry for the big svg image, anyway if you need more fronius icons please contact me I will download them from my inverter.
Ciao Emanuele & Richard, grazie per il supporto :) thanks for the support!

**Comment by elax46** [comment]
> sorry for the big svg image, anyway if you need more fronius icons please contact me I will download them from my inverter. Ciao Emanuele & Richard, grazie per il supporto :) thanks for the support!

grazie a te per la segnalazione 😃😃
