### ISSUE TITLE
Custom Icon request [amc+]

### ISSUE THREAD

**Issue by lmendezr** [elax46/custom-brand-icons#539]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

https://logowik.com/amc-plus-vector-logo-13416.html

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/da4e65ac-490e-4765-9a1b-eb0f4785e049)
I thickened up the lines to make it more eligable

**Comment by lmendezr** [comment]
Nice! love it - thanks so much @rchiileea!
