### ISSUE TITLE
homepod & homepodmini 

### ISSUE THREAD

**Issue by jrspowers** [elax46/custom-brand-icons#54]
hallo,

could you make an icon for the homepod & homepod mini that would be very nice ?

[homepod](https://www.google.be/search?q=homepod&tbm=isch&ved=2ahUKEwjJ9NmF4tHzAhVOiv0HHczEDwkQ2-cCegQIABAA&oq=homepod&gs_lcp=CgNpbWcQAzIHCCMQ7wMQJzIHCCMQ7wMQJzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgQIABBDMgUIABCABDIFCAAQgAQ6BAgAEBM6CAgAEAcQHhATOggIABAIEB4QEzoICAAQBRAeEBM6CAgAEIAEELEDOggIABCxAxCDAVCm0xRY29oUYJn1GmgDcAB4AIABaogBgQaSAQM4LjGYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=6UFsYYncA86U9u8PzIm_SA&bih=929&biw=1920#imgrc=TYAwcVyKCAIoeM)
[homepod-mini](CgNpbWcQAzIHCCMQ7wMQJzIHCCMQ7wMQJzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgQIABBDMgUIABCABDIFCAAQgAQ6BAgAEBM6CAgAEAcQHhATOggIABAIEB4QEzoICAAQBRAeEBM6CAgAEIAEELEDOggIABCxAxCDAVCm0xRY29oUYJn1GmgDcAB4AIABaogBgQaSAQM4LjGYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ)

**Comment by elax46** [comment]
integrated in the newly released version

**Comment by jrspowers** [comment]
when is this version coming?

**Comment by elax46** [comment]
> when is this version coming?

released now [1.0.30](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.30)

**Comment by jrspowers** [comment]
Thanks man

**Comment by elax46** [comment]
> Thanks man

thank you for the request

**Comment by elax46** [comment]
> Now probleem

what is the problem?

**Comment by jrspowers** [comment]
I mean no problem to send it in
