### ISSUE TITLE
Custom Icon request Globoplay

### ISSUE THREAD

**Issue by damiaorocha** [elax46/custom-brand-icons#541]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

https://pt.wikipedia.org/wiki/Ficheiro:Globoplay_logo.svg#/media/Ficheiro:Globoplay_logo_2020.svg

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
Provide a svg file and jpg logo of your request and a image along with your request.
(links to SVG's or Images will be ignored you must upload the files into your request, ignoring this will result in request being ignored).

**Comment by damiaorocha** [comment]
![images](https://github.com/elax46/custom-brand-icons/assets/72225762/a68796c4-3d6e-47f3-88b8-98b52249cead)
![globoplay](https://github.com/elax46/custom-brand-icons/assets/72225762/49a49f99-e76a-45c6-9632-7ae4cd08b5a0)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/ad9cf364-df8f-4812-9d86-2cca826de0dd)
