### ISSUE TITLE
icon is not showing

### ISSUE THREAD

**Issue by Reibeiro2017** [elax46/custom-brand-icons#545]
**Describe the bug**
phu:tim-logo-alt
This is not the only one appearing, the others are correct
_______________________________________________________________________________________
## Don't see the icon?

doesn't appear, I don't see
________________________________________________________________________________________
It probably depends on the cache. Open Home assistant from an incognito window and check that the icon loads if yes then it depends on the cache, otherwise double check the installation

I did the procedure and it still doesn't appear

**Comment by elax46** [comment]
[read here](https://github.com/elax46/custom-brand-icons?tab=readme-ov-file#dont-see-the-icon)

**Comment by Reibeiro2017** [comment]
I did the above procedures, but the icon still doesn't appear:  phu:tim-logo-alt

**Comment by elax46** [comment]
> I did the above procedures, but the icon still doesn't appear: phu:tim-logo-alt


![Cattura](https://github.com/elax46/custom-brand-icons/assets/55278049/007582c1-d054-48cc-b0cf-303db3696f80)

I have already run the test and as you can see the icon is displayed without problems, I think it is a problem with your instance, try uninstalling and reinstalling

**Comment by schpuntik** [comment]
Hello. I can only confirm, I have the same problem. When I go into edit mode I see icon! As soon as editing mode is switched off, the icon can no longer be seen! Exactly the same thing with CTRL+F5 changes.                  
https://youtube.com/shorts/QjxoHILXUPY

**Comment by mpepping** [comment]
Same thing here. It's a hit or miss. Initially, on an empty cache, the icons show but on a page reload the icon disappears. Only affect `phu:` icons. The [short](https://github.com/elax46/custom-brand-icons/issues/545#issuecomment-1933023367) that @schpuntik posted shows the issue perfectly.

Tried to remove as much (unused) HACS modules, to keep `/config/lovelace/resources` clean as possible. Doesn't seem to make a difference. Different browsers/platforms doesn't make a difference.

**Comment by rchiileea** [comment]
ctl and f5 does not clear cache only settings/clear history and only leaving clear cached images and files will work, I presume most of the issue is around chrome based browsers, why chrome is convienient its not the best browser for image caching.

**Comment by Reibeiro2017** [comment]
Now it's resolved! When I typed 'phu: tim-alt', it appeared exactly as in the image you can see, not as it was before in the 'Miscellany of Icons', where it was 'phi: tim-logo-alt'. In my case, I found out the correct way to write it.

![image](https://github.com/elax46/custom-brand-icons/assets/109174594/98de1950-29f5-4f3b-b2bf-033dca74ca57)
