### ISSUE TITLE
Custom Icon request [Google Home Max]

### ISSUE THREAD

**Issue by kknishev** [elax46/custom-brand-icons#546]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://fonts.google.com/icons?icon.query=home+max

Google Home Max (home-max) - the greatest AUDIO SPEAKER with Google Assistant ever!!
please add it!!

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
You do realise your basically asking for the icon just type phu:nest-hub and it will show, all google devices here in the uk were rebrand next (the mini speaker is called nest-mini here now.).

**Comment by kknishev** [comment]
@rchiileea yes but no
of course I know that "home" has become "nest"

but a nest-hub (nest-hub-max with a camera) is completely different from a home-max

nest-hub (nest-hub-max on picture) - speaker with display
![rtg34h3fan6x3sxp1b7dyg7yhkrmkd3j](https://github.com/elax46/custom-brand-icons/assets/22073966/8affedfc-bec5-4ff8-a9d9-9a19bedf4ade)

home-max - speaker without display
![home-max_1-1000x1000](https://github.com/elax46/custom-brand-icons/assets/22073966/ae3e710e-604b-42ea-82d9-58a4483878e4)

also we have two the same nest-hub now ??
![image](https://github.com/elax46/custom-brand-icons/assets/22073966/f6f58827-426a-457c-a3f4-c53ddec1c15a)

**Comment by rchiileea** [comment]
forget that as it has not been updated yet, I asked you if you would type phu:nest-hub to get the icon you linked, you obviously did not try, as I knew it was their as I made it!...

![image](https://github.com/elax46/custom-brand-icons/assets/87599807/0c42a853-754d-4196-b6fe-7ce057654043)

**Comment by kknishev** [comment]
Wow yep, phu:nest-hub - show the correct icon
thanks a lot!!
