### ISSUE TITLE
2-spot & 4-spot ceiling

### ISSUE THREAD

**Issue by sanderlv** [elax46/custom-brand-icons#549]
removed

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/b0302029-b933-4fd2-94be-f53937d10e89)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/6ecb8944-2267-4c1e-b9cb-ce1f8b468189)

**Comment by sanderlv** [comment]
I love them

**Comment by rchiileea** [comment]
@elax46 please dont add the 2 and 4 spot icons to next release.
