### ISSUE TITLE
Icons not visible in Android app 2/3 times

### ISSUE THREAD

**Issue by sanderlv** [elax46/custom-brand-icons#551]
A lot of times opening the homeassistant companion app results in no visible icons. Cleared cache (in app settings).

I need to force close 2 or 3 times before they show...

My wife has the same issue. 

Then when they show and after 1 minute renter the app, gone again...

**Comment by rchiileea** [comment]
if you followed the links in that post

Add the following to the frontend section of your configuration.yaml

frontend:
extra_module_url:
- /local/custom-brand-icons.js

**Comment by sanderlv** [comment]
I did that, despite still problems. As well via PC and 2 mobile phones.

**Comment by rchiileea** [comment]
> I did that, despite still problems. As well via PC and 2 mobile phones.

first go to settings, dashboard and 3 dots click resorces, add resource
```
/hacsfiles/custom-brand-icons/custom-brand-icons.js?hacstag=366862031202420
```
javascript.

reboot home assistant this should sort the android and cache issue out, if not.

log out and log in on mobile app to fix (seems to be a issue with android), on PC if in browser go to settings, search cache, click clear history and untick all except image cache.

**Comment by ArikShemesh** [comment]
Tried all, still not showing in the Android app.
After editing the view it does show, but closing the app and open again and it gone.

**Comment by sanderlv** [comment]
Am very sorry but I abandoned the ship of custom icons...

**Comment by elax46** [comment]
problem solved, I'm done

**Comment by rchiileea** [comment]
> Tried all, still not showing in the Android app. After editing the view it does show, but closing the app and open again and it gone.

So its just the android app it happens in?

**Comment by ArikShemesh** [comment]
> > Tried all, still not showing in the Android app. After editing the view it does show, but closing the app and open again and it gone.
> 
> So its just the android app it happens in? if yes go to app settings on both phones,
> 
> select the homeassistant app and clear cache.

Only in the app.
Already said that I tried all, including app cache clearing.

**Comment by rchiileea** [comment]
> > > Tried all, still not showing in the Android app. After editing the view it does show, but closing the app and open again and it gone.
> > 
> > 
> > So its just the android app it happens in? if yes go to app settings on both phones,
> > select the homeassistant app and clear cache.
> 
> Only in the app. Already said that I tried all, including app cache clearing.

What theme are you running and I presume you have custom button card, there have been some reported issues with custom components, not just icons with 2024.1.3 onwards, normally though only accoated with the minimanlist theme.
