### ISSUE TITLE
Icons not showing at times

### ISSUE THREAD

**Issue by mpepping** [elax46/custom-brand-icons#553]
**Describe the bug**

Icons don't show at times.

It's a hit or miss. Initially, on an empty cache, the icons show but on a page reload the icon disappears. Only affect `phu:` icons. The [short](https://github.com/elax46/custom-brand-icons/issues/545#issuecomment-1933023367) that @schpuntik posted in #545  shows the issue perfectly.

## Don't see the icon?

> It probably depends on the cache. Open Home assistant from an incognito window and check that the icon loads if yes then it depends on the cache, otherwise double check the installation

Doubt these can be waved as cache issues. Tried to remove as much (unused) HACS modules, to keep `/config/lovelace/resources` clean as possible. Doesn't seem to make a difference. The behaviour is the same on different browsers/platforms.

**Comment by enricofranke** [comment]
I have the same problem when I toggle reload icon is gone when I press the button again its starting loading back in.

**Comment by rchiileea** [comment]
first go to settings, dashboard and 3 dots click resorces, add resource

/hacsfiles/custom-brand-icons/custom-brand-icons.js?hacstag=366862031202420
javascript.

reboot home assistant this should sort the android and cache issue out, if not.

log out and log in on mobile app to fix (seems to be a issue with android), on PC if in browser go to settings, search cache, click clear history and untick all except image cache.

chrome based browsers are horrible, I have to do the cache delete every time I am experimenting in chrome, but does not happen in edge, or firefox for some reason, chrome is getting more of a pain, for example in chrome you can view frigate recordings from within home assistant, but you can view the from within home asssistant in firefox and edge.
