### ISSUE TITLE
How about the badge for Tesla?

### ISSUE THREAD

**Issue by rnadeau77** [elax46/custom-brand-icons#557]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by elax46** [comment]
![Screenshot 2024-02-17 131700](https://github.com/elax46/custom-brand-icons/assets/55278049/56c5e0f3-ef8b-46f0-a8f5-7c6b577e0f59)

is already available
