### ISSUE TITLE
No Icon Picker

### ISSUE THREAD

**Issue by gbomacfly** [elax46/custom-brand-icons#560]
**Describe the bug**
In the iconpicker there are no phu: icons
But icons works directly defined in yaml.

<img width="495" alt="image" src="https://github.com/elax46/custom-brand-icons/assets/1981547/d8f2a417-1186-4d9e-a491-8197d6c22cae">

I installed in HACS and have this in my configuration.yaml:
```
frontend:
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
```

Homeassistand was restartet and the browser cache was cleared.
I don't know where to look for my error, can somebody give me a hint?

Thx a lot :)

**Comment by rchiileea** [comment]
some addons (including official) have had some cache issues since 2024.1.1, here are a few work arounds to try

first go to settings, dashboard and 3 dots click resorces, add resource
```
/hacsfiles/custom-brand-icons/custom-brand-icons.js?hacstag=366862031202420
```
and

```
/local/community/custom-brand-icons/custom-brand-icons.js
```

and let me know if this work around fixes the issue

**Comment by gbomacfly** [comment]
Thanks for your fast reply. The second entry in ressources was missing. Now it works.

Thanky you!
