### ISSUE TITLE
Custom Icon request [Atari]

### ISSUE THREAD

**Issue by cynster** [elax46/custom-brand-icons#566]
I have connected my game consoles to smart plugs and this is one of the icons I'd love to be added:
![noun-atari-console-900657](https://github.com/elax46/custom-brand-icons/assets/26958839/15d5257b-b9bb-4db8-8f8f-ddaf6e6b48cd)
Source: [https://thenounproject.com/icon/atari-console-900657/](https://thenounproject.com/icon/atari-console-900657/)

Alternatively, the Atari controller would be nice:

![noun-atari-joystick-900662](https://github.com/elax46/custom-brand-icons/assets/26958839/7cbd1fcd-46c6-4bf8-9099-c5a4af415b46)
Source: [https://thenounproject.com/icon/atari-joystick-900662/](https://thenounproject.com/icon/atari-joystick-900662/)

**Comment by cynster** [comment]
Extra alt as brand icon:
![Atari_logo_alt](https://github.com/elax46/custom-brand-icons/assets/26958839/9e4dbd8f-5077-44d3-9ab5-25b58475080b)

[https://upload.wikimedia.org/wikipedia/commons/3/3e/Atari_logo_alt.svg](https://upload.wikimedia.org/wikipedia/commons/3/3e/Atari_logo_alt.svg)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/35ee0e66-8f32-4602-9e4a-674c653da792)

only done one but as with the nes my own creation

**Comment by cynster** [comment]
Looks great!
