### ISSUE TITLE
Custom Icon request [NES]

### ISSUE THREAD

**Issue by cynster** [elax46/custom-brand-icons#567]
I have connected my game consoles to smart plugs and this is one of the icons I'd love to be added:
![noun-nes-900664](https://github.com/elax46/custom-brand-icons/assets/26958839/bfb37a35-7543-4589-993c-9dcb18d9c2c4)
Source: [https://thenounproject.com/icon/nes-900664/](https://thenounproject.com/icon/nes-900664/)

An alternative could be the NES controller:
![noun-nes-controller-900661](https://github.com/elax46/custom-brand-icons/assets/26958839/64d5d703-5e95-4777-8a31-226f94c73f54)
Source: [https://thenounproject.com/icon/nes-controller-900661/](https://thenounproject.com/icon/nes-controller-900661/)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/879b0e9a-fb84-4076-bdcf-116c4160540c)

**Comment by cynster** [comment]
That looks amazing :)
