### ISSUE TITLE
Custom Icon request [Scart]

### ISSUE THREAD

**Issue by cynster** [elax46/custom-brand-icons#568]
I have connected my game consoles to smart plugs and this is one of the icons I'd love to be added (scart connection):
![noun-scart-2757808](https://github.com/elax46/custom-brand-icons/assets/26958839/2f4f452e-cd3f-49ba-a746-1147ee882566)
Source: [https://thenounproject.com/icon/scart-2757808/](https://thenounproject.com/icon/scart-2757808/)

**Comment by rchiileea** [comment]
no on scart, ill have to redo this will look teribble in a button on dash (but I will do it)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/c82da7dd-6e28-4f71-9875-5be072d01d7d)
