### ISSUE TITLE
Custom Icon request [Suzuki]

### ISSUE THREAD

**Issue by a-r-j-a-n** [elax46/custom-brand-icons#570]
Can this be implemented? Would help me tremendous! Thanks!

![suzuki](https://github.com/elax46/custom-brand-icons/assets/1314906/75e9bf58-ef33-4f7f-8751-673fe7d413ec)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/659689c2-55a2-4318-9641-428fbc1968b6)
