### ISSUE TITLE
Custom Icon request [Hobby]

### ISSUE THREAD

**Issue by a-r-j-a-n** [elax46/custom-brand-icons#571]
I would like to use this icon in my home assistant for my mobile home, branded [Hobby](https://www.hobby-caravan.de/). Thanks!

![hobby-caravan](https://github.com/elax46/custom-brand-icons/assets/1314906/484381bf-cabe-4c5a-a2df-2984db08eccf)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/c06e24f0-2e63-4514-b8c0-1f48355707c1)
