### ISSUE TITLE
Custom Icon request [Govee-H6046]

### ISSUE THREAD

**Issue by nstyqz** [elax46/custom-brand-icons#575]
![20240225_144254_0000.png](https://github.com/elax46/custom-brand-icons/assets/146044172/849e1121-2670-41e7-a7e2-d2bcd4b62291)

**Comment by elax46** [comment]
you should provide an image/svg of the icon

**Comment by nstyqz** [comment]
![20240225_140831_0000_adobe_express.png](https://github.com/elax46/custom-brand-icons/assets/146044172/ebb8d3bb-006e-4f9a-ba75-3e69943a2fe6)

**Comment by nstyqz** [comment]
![20240225_141115_0000_adobe_express.png](https://github.com/elax46/custom-brand-icons/assets/146044172/0371f4bc-ee69-474c-8e54-befcbf516287)

Yeyieh

**Comment by nstyqz** [comment]
![20240225_141115_0000.png](https://github.com/elax46/custom-brand-icons/assets/146044172/fd5cefdb-ab34-4cbf-bef1-502f11bbaf3b)

**Comment by nstyqz** [comment]
[](https://www.canva.com/design/DAF9zQE5Je0/wkoYOoMA1clDHYiG-lYLMQ/view?utm_content=DAF9zQE5Je0&utm_campaign=share_your_design&utm_medium=link&utm_source=shareyourdesignpanel)

**Comment by nstyqz** [comment]
https://github.com/nstyqz/Home-Set-Up/blob/c05c4f58734dc14016e857b7ab367810f432a333/Govee-H6046_20240225_145638_0000.svg

**Comment by nstyqz** [comment]
Yeyieh

**Comment by elax46** [comment]
will take care of it @rchiileea  as soon as it is available

**Comment by nstyqz** [comment]
"It's great, but I think it would be better if they looked towards the center."

**Comment by rchiileea** [comment]
why centre does look the std, I am covering all bases with these as people that use glows via card mod will apreciate having these

**Comment by nstyqz** [comment]
In practice, I don't think many people connect this model as shown in the icon... However, I still like it. Thanks for the info.
