### ISSUE TITLE
Custom Icon request [Sonos Ray]

### ISSUE THREAD

**Issue by tioan** [elax46/custom-brand-icons#578]
![image](https://github.com/elax46/custom-brand-icons/assets/259990/686f2565-73b8-476a-8872-aa07d6213e42)

Unfortunately I could not find an SVG icon

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/63444565-0ef1-4104-b0e7-6d1c3a81d7ac)
will be added soon still have a few icons to do
