### ISSUE TITLE
icon do not work on wear os 

### ISSUE THREAD

**Issue by Shiroe93** [elax46/custom-brand-icons#580]
icons do not seem to work on wear os home assistant app

**Comment by Shiroe93** [comment]
I think you are right because I checked another custom icon pack and it doesn't work either 
It's a shame because because your icon are really beautiful and useful in the wear os context 
Unfortunately I don't know if there's a solution to this 
In any case thank you for the response and sorry to have bothered you without checking frist

**Comment by rchiileea** [comment]
My wear os watch has been in cupboard for over 2 years lol.... so would need to find it to check.

**Comment by elax46** [comment]
I looked into the issue a bit. HA does not have a native project for the war os app but it is an extension of the android application which is very limited by the structure of the project, it does not seem to support additional components at all. If @rchiileea  has a Wear OS let's see if something can be done

**Comment by rchiileea** [comment]
Ok I have found the watch, lets  hope it charges to full (also @Shiroe93 have you both lines needed in resoarces))?

**Comment by Shiroe93** [comment]
yes the but i have a different hacstag 
it could be a problem?
![immagine](https://github.com/elax46/custom-brand-icons/assets/56954468/0f1d4709-ee1d-4359-a6a5-f4fb61fa635e)

**Comment by rchiileea** [comment]
yep its a wear os thing, please drop a request in the wear os support

**Comment by elax46** [comment]
I am closing the request as the question of the Android package, if it is implemented, will be at a later stage
