### ISSUE TITLE
Icons sometimes showing on Andriod Home assistant companion app

### ISSUE THREAD

**Issue by gurrasv** [elax46/custom-brand-icons#585]
-On desktop i can see the icons at all times no problems.
-On my gfs Iphone, she can see them all time no problems.
However on my Android phone i can sometimes see them sometimes i can't. Seems to sometimes disappear/reappear once app is ''reloaded'' (closed, ''swiped'' away, then reopened) at random times. 

I've tried: 
-To erase the cache on the app. 
-Tried reinstalling the app.
-Tried adding the repositories suggested
-Tried reinstalling the integration

Not i'm at a lost, Im thinking this is a phone problem not a integration problem?

Phone where i'm experiencing the problem:
Oneplus 10t, with OxygenOS 14.0
Home assistant companion app version 2024.1.5-full

**Comment by gurrasv** [comment]
Noticed something new.

When i click to access another of my pages on my mobile dashboard, I seem to have no problem.

Seem to only affect the very front page

**Comment by elax46** [comment]
first go to settings, dashboard and 3 dots click resorces, add resource
```
/hacsfiles/custom-brand-icons/custom-brand-icons.js?hacstag=366862031202420
```
and

```
/local/community/custom-brand-icons/custom-brand-icons.js
```

**Comment by gurrasv** [comment]
I already tried that, thats what i meant by "adding repositorys suggested"

**Comment by hesspoint** [comment]
I have the same issue on the iOS / iPadOS companion app. Sometimes the PHU icons just disappear. Also when I want to change an entity icon and type phu: then nothing appears.

Sometimes a restart of HA fixes it but often it does not

**Comment by woempiej** [comment]
Hi,

I don't use this frontend integration yet, but I've noticed that I have the same challange on my Android walltab with HA standard icons. Maybe a HA issue since an HA update?

**Comment by hesspoint** [comment]
For me it actually got worse. At first I had the issue that I could not assign any phu icons in my companion app on my iPad. But when I used Safari on the iPad it was working fine. Now it also stopped working on Safari. I reset the caches on the companion app and safari and nothing helps. Needless to say I rebooted HA multiple times.

Only place it works fine is in Safari on my Mac.

Stange thing is also that it looks like some icons in the dashboard are shown correctly while others are not and as said when assigning an icon to an entity typing phu nothing comes up.

**Comment by rchiileea** [comment]
stop app, delete cache, delete app-files and at last uninstall app.
restart mobile
reinstalled ha-app

can someone try this

**Comment by paulsgale** [comment]
I’m also using the HACS hass hue icons and they work flawlessly. I’ve tried all the possible fixes and these icons still don’t work 80% maybe of the time. 20% they do but no idea what happens to get them to show up. Very frustrating.

**Comment by rchiileea** [comment]
just checking do you all have this in your config

frontend:
  extra_module_url:
    - /hacsfiles/custom-brand-icons/custom-brand-icons.js

**Comment by rchiileea** [comment]
I am also wondering if those having issues are only experiancing this when accessing remotely with one of the free options?

**Comment by pgale** [comment]
> just checking do you all have this in your config
> 
> frontend: extra_module_url: - /hacsfiles/custom-brand-icons/custom-brand-icons.js

Ahhhhhh! now I feel really dumb! I didn't have that and didn't realise it was needed, installing via HACS. In my defence, that instruction was at the end of a very long list of icons on the github page  - although it was also mentioned with a (non working?) link at the top. That will teach me to not read instructions carefully!

I've made the change and will see what happens - they have all loaded ok so far but I've seen this before where they load and then over time, they disappear. This is only on my Android based screens. PC and iOS are all fine.

Thanks for pointing that out to a dullard! ;)

**Comment by hesspoint** [comment]
Ahhh same here. I also had not added these lines. Have done it now and will see if that fixes it.

However one thing I am a bit confused about:

In the read me it says add this

frontend:
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
    
    However in your post above you use the location
    - /hacsfiles/custom-brand-icons/custom-brand-icons.js
    
    Which one is the correct one to use?

**Comment by pgale** [comment]
I have the second and it still seems to be working :)

**Comment by rchiileea** [comment]
I am just trying to get to the bottom of this really and see  due to changes in the way home assistant is aggressively forcing cache is causing the issues so try both, I personally have never had a issue with mine, but I have had the files set up like this since the start.

**Comment by elax46** [comment]
I'm closing the discussion as it seems the matter is resolved
