### ISSUE TITLE
Custom Icon request: Google Home icon

### ISSUE THREAD

**Issue by ronschaeffer** [elax46/custom-brand-icons#59]
**What is the specific model of hue fixture/bulb that you want an icon for**
Not a hue icon, but rather a Google Home app icon

**Provide a URL that points to an image of this fixture/bulb**
https://play-lh.googleusercontent.com/vr1isZKzTtlok9P81H6cR98iqpPhkuQHJp19Z5kPej3QlhNTnLohXpqcgMqrQpyegA

Here is a monochrome SVG that I created, but I can't figure out how to simplify it appropriate for use as an icon in Home Assistant:  https://1drv.ms/u/s!AtYGFztGDGYlkqAbVeSsZL4GAEZxBQ?e=756bON

Preferably icon photography, as they use a consistent angle.

Thanks!

**Comment by elax46** [comment]
Integrated icon will be available in the next update

**Comment by ronschaeffer** [comment]
Thanks!
