### ISSUE TITLE
Custom Icon request [Mealie icon]

### ISSUE THREAD

**Issue by nickrout** [elax46/custom-brand-icons#590]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

https://iconduck.com/icons/252964/mealie#

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
@nickrout you no the submition rules by now :P

**Comment by nickrout** [comment]
I thought that link took me to a svg file. Sorry if I got it wrong.

**Comment by rchiileea** [comment]
Want an icon? Open a [custom icon request](https://github.com/elax46/custom-brand-icons/issues/new?assignees=elax46&labels=icon-request&template=insertion-of-new-icons.md&title=Custom+Icon+request) or [contribute to the project](https://github.com/elax46/custom-brand-icons#developer-workflow).

Provide a svg file and jpg logo of your request and a image along with your request.
(links to SVG's or Images will be ignored you must upload the files into your request, ignoring this will result in request being ignored).

**Comment by nickrout** [comment]
OK sorry, I'll try again :)
