### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by xion92** [elax46/custom-brand-icons#591]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

![arcticons--mytelenor](https://github.com/elax46/custom-brand-icons/assets/45775002/35491498-5c2a-4b5d-89d5-9c1104807e7f)
[https://icon-sets.iconify.design/arcticons/mytelenor/](url)

![arcticons--svt-play](https://github.com/elax46/custom-brand-icons/assets/45775002/506c4e8f-5a35-486c-849f-36bbb3e42c8e)
[https://icon-sets.iconify.design/arcticons/svt-play/](url)

![tv4-play_logotype_rg_65f361d163d02](https://github.com/elax46/custom-brand-icons/assets/45775002/e3826a42-fc5b-46c3-b396-397875fab9f6)
[https://s3-eu-west-1.amazonaws.com/cwsassets/bon-5c349dceab90f/2023/08/08/64d1f4856e106_thumbnail.png?version=1691481222](url)

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
so what are we supposed to do with some of these, name them bon [bon-64d1f4856e106_thumbnail.svg lol

**Comment by rchiileea** [comment]
@xion92 I will close this request soon if you dont reply within 5 days
