### ISSUE TITLE
Custom Icon request [Meta]

### ISSUE THREAD

**Issue by GewoonJaap** [elax46/custom-brand-icons#595]
Link: https://companieslogo.com/de/meta-platforms/logo/

**Comment by rchiileea** [comment]
read the logo request rules.

**Comment by GewoonJaap** [comment]
![META D](https://github.com/elax46/custom-brand-icons/assets/33700526/1e9c73f8-d2e3-44bb-ae69-7ee1e8cc8b02)
![META D](https://github.com/elax46/custom-brand-icons/assets/33700526/c510cdb8-4133-45f3-80fe-e03a140466ee)
There you go
