### ISSUE TITLE
Icons on website and in home assistant not loading regular 

### ISSUE THREAD

**Issue by skycryer** [elax46/custom-brand-icons#596]
**Describe the bug**
When I check the website here on GitHub to see all available icons not all are loading. Sometimes more sometimes less but never all. I tried on Safari and Chrome with latest updates on OSX.

Similar problem in side Home Assistant, when opened as Website or from IOS companion app on iPhone and iPad (both latest updates for system and app), sometimes icons are loading sometimes not. The home assistant icons are loading fine. Only custom brands are sometimes not loading.

Caching is not the problem, tried different systems, browsers, apps with cleared cache and without. Maybe the package is to large for some systems?

## Don't see the icon?

It probably depends on the cache. Open Home assistant from an incognito window and check that the icon loads if yes then it depends on the cache, otherwise double check the installation

**Comment by rchiileea** [comment]
add this to your config
```
frontend:
  extra_module_url:
    - /hacsfiles/custom-brand-icons/custom-brand-icons.js 
```

**Comment by rchiileea** [comment]
@skycryer did this fix it for you?

**Comment by skycryer** [comment]
Looks like that worked for inside home assistant. Just the preview on GitHub is still a problem most of the times.

**Comment by elax46** [comment]
Since you have communicated the resolution of the problem, I will close
