### ISSUE TITLE
Custom Icon request Mealie (try 2)

### ISSUE THREAD

**Issue by nickrout** [elax46/custom-brand-icons#599]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

![mealie](https://github.com/elax46/custom-brand-icons/assets/5105631/0d9bcf16-8975-43db-a19d-b375e713de6f)

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

The message I got on the last thread said to upload a jpg as well. I have a png to here goes.

![mealie 1024x976](https://github.com/elax46/custom-brand-icons/assets/5105631/5eedb122-3c30-47b8-91fa-d2f793956fd4)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/a8b71ee0-fafe-4cb0-a958-e3c407aeaecc)

**Comment by nickrout** [comment]
Looks good, but mealie, not melie. :+1:
