### ISSUE TITLE
Icon naming convention

### ISSUE THREAD

**Issue by silvanverschuur** [elax46/custom-brand-icons#6]
Is there a reason why not all icons use the same naming convention? Some icons start with a lowercase character others with an uppercase character (e.g. `PendantRound`, `go`). Because the icon names are case sensitive this is quite annoying. 

Another suggestion is to use hyphens between multiple words like 
* `bulb-group`
* `pendant-round`
* `double-spot`

**Comment by elax46** [comment]
Hi I just used the name officially used by philips in the svg files, in later versions I will settle the matter better by setting a basic nomenclature. I'm trying to find new icon packs to add
