### ISSUE TITLE
Custom Icon request [Sonos Sub Mini]

### ISSUE THREAD

**Issue by tioan** [elax46/custom-brand-icons#600]
![image](https://github.com/elax46/custom-brand-icons/assets/259990/8847640e-8eb1-4e2a-b4fe-3b87dd211d52)

Unfortunately I could not find an SVG icon

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/3e2f6506-c83c-4637-8d15-2cdd2e20bf4d)
