### ISSUE TITLE
Github Sponsor monthly minimum amount

### ISSUE THREAD

**Issue by tioan** [elax46/custom-brand-icons#601]
@elax46  
Unfortunately, you have currently set a minimum monthly amount of $3 for the Github Sponsor function.
Could you please deactivate this minimum amount?
I really like to use the Github Sponsor option to say thank you to volunteer open source developers like you. 
[I therefore sponsor quite a lot of people](https://github.com/tioan?tab=sponsoring) with a symbolic $1 / 1€ per month instead of having to split a fixed amount every month.
I would also like to sponsor you, but just like everyone else with a standardized amount.

**Comment by elax46** [comment]
thanks for your support I changed the import I didn't even know it was set to $3

**Comment by elax46** [comment]
@tioan I am closing the request as I have made the change, thanks in advance

**Comment by rchiileea** [comment]
thanks for your sponsoship btw, I appreciate it.
