### ISSUE TITLE
Custom Icon request [authentik]

### ISSUE THREAD

**Issue by RoboMagus** [elax46/custom-brand-icons#603]
Would be nice to have an icono for [Authentik](https://goauthentik.io/) in my Home Assistant dashboard.
Here's a link to the SVG in their github repo: [link](https://github.com/goauthentik/authentik/blob/main/website/static/img/icon.svg).

![image](https://raw.githubusercontent.com/goauthentik/authentik/main/website/static/img/icon.svg)

**Comment by rchiileea** [comment]
Please read the request rules for sumbiting a request before we will look at anything.

**Comment by RoboMagus** [comment]
> Please read the request rules for sumbiting a request before we will look at anything.

In that case please update the Icon Request template, as it literally requests a **link** to an SVG icon:
`**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**`

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/f73fc3c4-f134-4cb1-835f-916cf75af4df)

**Comment by rchiileea** [comment]
Icon Requests
Want an icon? Open a [custom icon request](https://github.com/elax46/custom-brand-icons/issues/new?assignees=elax46&labels=icon-request&template=insertion-of-new-icons.md&title=Custom+Icon+request) or [contribute to the project](https://github.com/elax46/custom-brand-icons#developer-workflow).

Provide a svg file and jpg logo of your request (we also are not mind readers and dont know every icon globaly so if no name is present please add it and a image along with your request.
links to SVG's or Images will be ignored you must upload the files into your request, ignoring this will result in request being ignored. (if you can not be bothered to spend a few minutes doing this, why should we spend time making it).
For those who [made their own icons](https://github.com/elax46/custom-brand-icons#developer-workflow), open pull requests on the [dev branch](https://github.com/elax46/custom-brand-icons/pulls).

**Comment by tioan** [comment]
_svg **and** jpg?_

svg **or** jpg sounds more sensible to me
