### ISSUE TITLE
Custom Icon request [IKEA VIDJA]

### ISSUE THREAD

**Issue by tioan** [elax46/custom-brand-icons#605]
![image](https://github.com/elax46/custom-brand-icons/assets/259990/a0a8d932-654a-49bf-8a69-7e54523cafcb)

Unfortunately I could not find an SVG icon

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/24c985fc-f288-4d08-9fa6-2cc148ceadc9)
I took the liberty of squashing this product for the icon so it would fill the screen more
