### ISSUE TITLE
Custom Icon request [IKEA GUNNARP panel]

### ISSUE THREAD

**Issue by tioan** [elax46/custom-brand-icons#606]
![image](https://github.com/elax46/custom-brand-icons/assets/259990/b8973681-5f90-4a7e-b0fd-efd22e507d75)

Unfortunately I could not find an SVG icon

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/c742c0c9-cc78-4332-955f-1d9435a02a5e)

**Comment by rchiileea** [comment]
You can do that with custom button card and card mod
