### ISSUE TITLE
Custom Icon request [IKEA GUNNARP panel round]

### ISSUE THREAD

**Issue by tioan** [elax46/custom-brand-icons#607]
![image](https://github.com/elax46/custom-brand-icons/assets/259990/c2ae3b4f-2e74-444c-ab8b-8a6a0fdfe9bd)

Unfortunately I could not find an SVG icon

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/cac0cc65-0524-4ed3-bec1-d3e6ce572802)
