### ISSUE TITLE
Custom Icon request [IKEA FLOALT panel]

### ISSUE THREAD

**Issue by tioan** [elax46/custom-brand-icons#608]
![image](https://github.com/elax46/custom-brand-icons/assets/259990/112f8783-97eb-40ae-bf50-d6020a042753)

Unfortunately I could not find an SVG icon

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/80782715-4049-4990-93a0-637bf08bd42e)

**Comment by tioan** [comment]
Looks generally good, but my template was stupid because it shows the panel sideways / vertically, can you tilt the icon 90 degrees to the left so that it is horizontal?
Or would it be possible to upload this icon and the [GUNNARP PANEL](https://github.com/elax46/custom-brand-icons/issues/606) as horizontal and vertical versions?
Sorry for the extra work.
