### ISSUE TITLE
Tesla App Icons

### ISSUE THREAD

**Issue by drjjr2** [elax46/custom-brand-icons#613]
I do not have SVG versions of these icons, just a screen shot. Was directed to post this here. Looking to get these icons added.

![49779](https://github.com/elax46/custom-brand-icons/assets/69729977/3268b80d-fa6c-4ddb-8841-26c267337253)

**Comment by rchiileea** [comment]
ill make them, apart from the flash, there is a flash icon in the mdi libary as well as a lighting (open ) there is even the honk (bugle) but that would need to be rotated, so ill make that and the rest.

**Comment by drjjr2** [comment]
> ill make them, apart from the flash, there is a flash icon in the mdi libary as well as a lighting (open ) there is even the honk (bugle) but that would need to be rotated, so ill make that and the rest.

Right, that makes sense not to re-do them if they already exist. I did not check first.

Thank you for your hard work.

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/28867e87-a743-4020-b085-982e8f691c1c)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/aaaaa588-da35-4eee-ae2e-ebf864895db2)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/9741262d-6af1-42f7-a11e-e8ff45b0c736)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/9dc176dc-b647-4490-944f-6adf2af7e1f6)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/d8661990-89e7-41e9-830b-746ef9997ba4)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/bead42f1-f67a-4f4b-9500-9f1d4b9e35e9)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/bc18dbf3-547e-48d3-a565-abeb77f15fa6)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/b1ffed3b-de7e-4f30-a0ad-6cd5772f5c2f)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/718d079d-0e76-43cb-b068-a3b825d850f9)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/1d303301-a440-45b7-a324-f9df3d8be091)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/ba34dfa5-31cc-433d-9e74-84b598b86ece)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/6a9f2548-1712-4649-ac82-bb77e328abae)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/912f23bd-9bd4-4f6a-8d55-b6c1513e23ce)

all done as some were different to standard icons ;)

**Comment by drjjr2** [comment]
Looks great! Thank you.
