### ISSUE TITLE
Custom Icon request [Peugeot]

### ISSUE THREAD

**Issue by iendicott** [elax46/custom-brand-icons#616]
Is it possible to incorporate these Peugeot Icons please?

Thanks

https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Peugeot_Logo.svg/1865px-Peugeot_Logo.svg.png

https://www.svgrepo.com/vectors/peugeot/

**Comment by elax46** [comment]
the icon is already available

- `phu:peugeot-alt`
- `phu:peugeot`
