### ISSUE TITLE
Custom Icon request Keenetic, Trakt, Speedtest, Plex, SSD M.2, SSD SATA

### ISSUE THREAD

**Issue by avenom** [elax46/custom-brand-icons#619]
Speedtest:

https://icon-icons.com/icon/speedtest-logo/249551

![speedtest_logo_icon_249551](https://github.com/elax46/custom-brand-icons/assets/17644125/9b59bb25-ef73-4bae-9d92-0b367d14fda0)

Trakt

https://icon-icons.com/icon/trakt-logo/144793

![trakt_logo_icon_144793](https://github.com/elax46/custom-brand-icons/assets/17644125/f645e06b-9556-4aa4-9ae6-f57e26bab6de)

Keenetic

https://disk.yandex.ru/d/0SthsE_Qh7H8wA

![keenetic-dark-theme](https://github.com/elax46/custom-brand-icons/assets/17644125/c8f5bc53-e3d0-420f-b436-ef21f1427058)

![keenetic-light-theme](https://github.com/elax46/custom-brand-icons/assets/17644125/7abb44fb-3678-4d77-9594-1a472df4a17b)

SSD M.2 NVMe

https://uxwing.com/nvme-ssd-icon/

![nvme-ssd-icon](https://github.com/elax46/custom-brand-icons/assets/17644125/9fcbc43e-5c46-41f6-bf4c-e2491169f99d)

SSD SATA, solid icon

https://icon-icons.com/icon/ssd-solid/236169

![ssd_solid_icon_236169](https://github.com/elax46/custom-brand-icons/assets/17644125/7c33c0e8-fc80-4605-bf3b-645c527bc7fc)

SSD SATA, line Icon

https://icon-icons.com/icon/ssd-line/235985

![ssd_line_icon_235985](https://github.com/elax46/custom-brand-icons/assets/17644125/3cf57abd-6bfb-41e5-9fe8-5d3643df6a0f)

Plex

https://icon-icons.com/icon/plex/137292

![plex_icon_137292](https://github.com/elax46/custom-brand-icons/assets/17644125/cf530386-a792-436c-922d-97fd62daee47)

Plex Circle

https://icon-icons.com/icon/plex-logo/181311

![plex_logo_icon_181311](https://github.com/elax46/custom-brand-icons/assets/17644125/2eab1781-04d1-4cde-83ed-7f50b8859848)

**Comment by avenom** [comment]
https://icon-icons.com/icon/plex/137292

**Comment by rchiileea** [comment]
pleas read the rules

**Comment by avenom** [comment]
> pleas read the rules

like this?

**Comment by rchiileea** [comment]
yes, ill do them, but not the ssd and the m.2 as we already have

seagate-ssd-m2 |   | seagate-ssd

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/332642a2-19b2-430c-bb66-487b470eb9e7)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/b598b80a-93ea-49a2-ae60-0b1933a5a33c)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/c37ed680-35a7-4ae5-af76-ead25fa251cb)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/15476103-3f31-4413-9d48-032e23a85996)
