### ISSUE TITLE
Custom Icon request Tower Fan

### ISSUE THREAD

**Issue by BenJamesAndo** [elax46/custom-brand-icons#620]
Generic Tower Fan icon.

A few examples.
Sorry, I couldn't find any decent SVGs, only PNGs.
![image](https://github.com/elax46/custom-brand-icons/assets/44917135/cc35304f-6056-4c24-ae67-4caa8504ab7c)
![image](https://github.com/elax46/custom-brand-icons/assets/44917135/89c91660-5ad0-4765-b428-8a16bf77284a)

**Comment by rchiileea** [comment]
Read request rules please I don’t click links

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by BenJamesAndo** [comment]
My sincere apologies for that. I've updated it now.

**Comment by rchiileea** [comment]
added to do list

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/e049aa4c-8c1b-4657-8ba9-6f03b0c77ab6)
