### ISSUE TITLE
Custom Icon reques [3D printer filament]

### ISSUE THREAD

**Issue by SylentButDedly** [elax46/custom-brand-icons#622]
3D printer filament icon! 

https://www.flaticon.com/free-icon/filament_926945
![filament(2)](https://github.com/elax46/custom-brand-icons/assets/13735575/31069e03-67c7-4886-a9c7-af7690178714)

**Comment by rchiileea** [comment]
added to do list

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/f73372e5-c879-48c9-a69d-e643bac36a8d)
