### ISSUE TITLE
ewelink

### ISSUE THREAD

**Issue by Reibeiro2017** [elax46/custom-brand-icons#623]
![ewelink](https://github.com/elax46/custom-brand-icons/assets/109174594/41ea7e84-810d-4538-a079-6e1e13f97913)
![Tuya](https://github.com/elax46/custom-brand-icons/assets/109174594/41866535-49fd-41c1-b5a2-72bda8745b96)

**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
added to do list

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/e68e86c7-0367-4034-aa53-07ffe04bde1d)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/b1230d59-7244-4563-8569-e9d752b2c43c)
