### ISSUE TITLE
Custom Icon requests: retropie and various retrocomputers

### ISSUE THREAD

**Issue by theclue** [elax46/custom-brand-icons#624]
Useful for any universal remote control project in Home Assistant :)

If I can be of any help, I'll glad to! tnx allot for your effort!

[super_nintendo.zip](https://github.com/elax46/custom-brand-icons/files/14972159/super_nintendo.zip)
[RetroPieSplashscreenBlue2.svg_.zip](https://github.com/elax46/custom-brand-icons/files/14972160/RetroPieSplashscreenBlue2.svg_.zip)
[atari.zip](https://github.com/elax46/custom-brand-icons/files/14972161/atari.zip)

**Comment by rchiileea** [comment]
Please read the rules for requests
