### ISSUE TITLE
Custom Icon request Intex Pool Light

### ISSUE THREAD

**Issue by FancyNerd92** [elax46/custom-brand-icons#625]
https://imgur.com/a/L1T5Yjy

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
Please read the rules for requests

**Comment by FancyNerd92** [comment]
I made this icon as png, i don't know how to make it as svg. I saw other requests as siple jpeg from shutterstock and you made it. What's the wrong here?

**Comment by rchiileea** [comment]
as Stated in the request rules, I wont click links (because sometimes I am an work machine) upload the picture

**Comment by FancyNerd92** [comment]
Here it is:
![intexpoollight](https://github.com/elax46/custom-brand-icons/assets/76796004/236bc0ff-95e3-4bb0-9521-3e8d06d5d69b)

**Comment by FancyNerd92** [comment]
Here it is:
![intexpoollight](https://github.com/elax46/custom-brand-icons/assets/76796004/0ec4518c-33cb-4f31-9d87-d90c7c482526)

Thanks

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/d0a089ed-29b6-4e8a-ae2b-53a8778b68dd)

**Comment by FancyNerd92** [comment]
Nice! When you will give the new update?
