### ISSUE TITLE
Custom Icon request OVH Cloud

### ISSUE THREAD

**Issue by WarC0zes** [elax46/custom-brand-icons#631]
Hi,
an icon request for OVH Cloud ( https://www.ovhcloud.com/ ).

icon svg:
![ovh](https://github.com/elax46/custom-brand-icons/assets/91471397/e298d547-4e41-4c71-9a19-a860b6c7e9f8)

Full logo png:
![image](https://github.com/elax46/custom-brand-icons/assets/91471397/c8416214-fa4c-47ed-8dfc-9f082d8072a1)

Thank in advance.

**Comment by rchiileea** [comment]
added to do list

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/c5862970-c6bf-4772-ba42-2b7f03f8635c)
