### ISSUE TITLE
Custom Icon request No-IP

### ISSUE THREAD

**Issue by WarC0zes** [elax46/custom-brand-icons#632]
Hi,
a request for an icon for NO-IP ( https://www.noip.com/ ) , but I don't have an SVG file and I'm bad at photo editing.
If you can make an icon from the png, that would be great, but if you can't, it doesn't matter.

icon png:
![image](https://github.com/elax46/custom-brand-icons/assets/91471397/9053336c-3631-4445-bbaa-9e80877203cd)

![image](https://github.com/elax46/custom-brand-icons/assets/91471397/a2312966-37fa-4a9f-bed9-0dbd6ccb33a9)

**Comment by rchiileea** [comment]
added to do list

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/79e2f74a-18cd-4cce-99b8-5c0bddc40b49)

**Comment by WarC0zes** [comment]
Thanks :thumbsup:
