### ISSUE TITLE
Custom Icon request [Aqara FP2]

### ISSUE THREAD

**Issue by LZXCorp** [elax46/custom-brand-icons#633]
Similar to the `aqara-fp1` icon except it is a complete circle and thinner.
<div>
<img src='https://github.com/elax46/custom-brand-icons/assets/107389832/a62aff78-bd0b-43d7-aafd-663998aa48b8' height=200>
<img src='https://github.com/elax46/custom-brand-icons/assets/107389832/a01daa48-0592-4b12-bf8f-6093e210197e' height=200>
</div>

<br/>

Here is the `aqara-fp1` you created as reference.
<img src='https://raw.githubusercontent.com/elax46/custom-brand-icons/main/icon-svg/aqara-fp1.svg' height=200>

**Comment by rchiileea** [comment]
added todo list

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/576179a7-8cc8-467b-a041-30f69984a48b)
