### ISSUE TITLE
Custom Icon request [Ulanzi TC001]

### ISSUE THREAD

**Issue by LZXCorp** [elax46/custom-brand-icons#634]
Here is an image of the Ulanzi TC001 below.
<div>
<img src='https://github.com/elax46/custom-brand-icons/assets/107389832/4882de2d-86b6-44ab-b855-5238e94d56c6' height=150>
<img src='https://github.com/elax46/custom-brand-icons/assets/107389832/19236501-3331-41ad-9de6-3f0d2ae6d0a1' height=150>
<div>

**Comment by rchiileea** [comment]
added to the to do list

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/fd6441c2-c07b-46c0-a2fc-5ff03b7aac70)
