### ISSUE TITLE
Lutron Request

### ISSUE THREAD

**Issue by DDomnick** [elax46/custom-brand-icons#638]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
[https://logowik.com/lutron-logo-vector-svg-pdf-ai-eps-cdr-free-download-17183.html](url)
**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
Read submition rules

**Comment by rchiileea** [comment]
closing due to no response
