### ISSUE TITLE
Custom Icon request [Samsung The Serif TV]

### ISSUE THREAD

**Issue by tinwetari** [elax46/custom-brand-icons#639]
I do not have an SVG of it but there are a few pretty attractive in Samsung The Serif TV website, like this one: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTV08ohg9QX-RDxyZ_1KsGkN6tIlQ9Dckd-fjrGUy4OhQ&s

**Comment by rchiileea** [comment]
Read the submission rules please

**Comment by rchiileea** [comment]
closing as no response
