### ISSUE TITLE
Custom Icon request - Alarm.com

### ISSUE THREAD

**Issue by ggonmar** [elax46/custom-brand-icons#641]
Alarm.com 
https://companieslogo.com/img/orig/ALRM-b60ff442.svg?t=1690181726

There is an outline option which could be useful or nice as well: 
https://companieslogo.com/img/orig/ALRM.D-223cb328.svg?t=1690181726

**Comment by rchiileea** [comment]
please read the submition rules

**Comment by ggonmar** [comment]
My bad, here are the svgs:

alarm.com
![alarm-dot-com](https://github.com/elax46/custom-brand-icons/assets/11583288/97d554ea-15d1-4871-b816-ad197c03a3f0)

alarm.com-outline
![alarm-dot-com-outline](https://github.com/elax46/custom-brand-icons/assets/11583288/c368bbc7-1803-4188-8dd6-fa7466885414)

**Comment by rchiileea** [comment]
added to do list, will start on current requests at the begining of next week

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/97124a0d-0a91-4196-8184-8273c035d439)
