### ISSUE TITLE
Bambulab alt icon doesn't show

### ISSUE THREAD

**Issue by BlueNickDev** [elax46/custom-brand-icons#644]
**Describe the bug**
bambu-lab-alt icon doesn't work; only this, the other icons works.

![image](https://github.com/elax46/custom-brand-icons/assets/44233682/bbcd29a9-8db5-434f-965e-ef721a3ce745)

![image](https://github.com/elax46/custom-brand-icons/assets/44233682/e6ccb025-04ca-4c99-b248-e6abb0e99a89)

## Don't see the icon?

_It probably depends on the cache. Open Home assistant from an incognito window and check that the icon loads if yes then it depends on the cache, otherwise double check the installation_

Done it, but without success.

Thanks in advance for the help!

**Comment by elax46** [comment]
Hi, thanks for reporting, the correct name is `bambulab-alt`
