### ISSUE TITLE
phu:intel-nuc is missing in 2024.5

### ISSUE THREAD

**Issue by AlexKusnezov** [elax46/custom-brand-icons#647]
**Describe the bug**
phu:intel-nuc is missing in version 204.5
<img width="572" alt="Screenshot 2024-05-16 at 12 43 32" src="https://github.com/elax46/custom-brand-icons/assets/33514406/75b93d97-0254-4cf0-9d95-ec82e3b9113b">

## Don't see the icon?

It probably depends on the cache. Open Home assistant from an incognito window and check that the icon loads if yes then it depends on the cache, otherwise double check the installation

**Comment by elax46** [comment]
which Intel icon are you talking about? `intel-nuc`?

**Comment by elax46** [comment]
new version with fix released, thanks for reporting
