### ISSUE TITLE
Icon Picker support

### ISSUE THREAD

**Issue by elax46** [elax46/custom-brand-icons#65]
Hi @piitaya totally random I found your [pull 10161](https://github.com/home-assistant/frontend/pull/10161) request related to icon Picker it seems to me a very useful tool for users! Is it possible to integrate it also for custom icons?

**Comment by piitaya** [comment]
Hi!
The support for custom icons is already merged 🙂
You can find more info in this PR https://github.com/home-assistant/frontend/pull/10399#issuecomment-953301513 (with an example)

The `customIconsets` is replaced by `customIcons`. You can now provide two functions :
- `getIcon` return the icon path
- `getIconList` return the list of available icons

Note : do not delete the `customIconsets` variable for backward compatibility 😅

**Comment by elax46** [comment]
What do you think? [change](https://github.com/elax46/custom-brand-icons/blob/dev/dist/custom-brand-icons.js) @piitaya

**Comment by piitaya** [comment]
```js
window.customIconsets = window.customIconsets || {};
window.customIconsets["phu"] = getIcon;

window.customIcons = window.customIcons || {};
window.customIcons["phu"] = { getIcon, getIconList };
```

You need to expose the helpers like this.

**Comment by elax46** [comment]
Thanks for the support [change](https://github.com/elax46/custom-brand-icons/blob/dev/dist/custom-brand-icons.js) @piitaya

**Comment by elax46** [comment]
@piitaya I tested the Icon Picker with the beta version of the core, really good idea!

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/LSr-Fj3X36c/0.jpg)](https://www.youtube.com/watch?v=LSr-Fj3X36c)
