### ISSUE TITLE
Custom Icon request "Tasmota Nous A1T & A5T"

### ISSUE THREAD

**Issue by Doom666DE** [elax46/custom-brand-icons#650]
Hello,

Initially, I wanted to ask if you could create and add two more icons. Then I remembered that I have the Adobe programs and can create the icons myself.

However, I need to ask now because I have little experience with GitHub: How can I add my created icons to this repository?

![A1T](https://github.com/elax46/custom-brand-icons/assets/98554600/0fcbdc93-a10d-43eb-a60b-5852f7c414c0)
![А5Т](https://github.com/elax46/custom-brand-icons/assets/98554600/ff85a0e1-11a9-4afd-8cd7-0bfdf2eff4d0)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/30e27c53-75dc-41a8-a9a0-a2a4c1fbad64)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/10e3fb18-00ea-4458-842b-d9b653bb1a99)
plus do we really need more plugs, we have uk, us, eu singles, and the same for extension cords
