### ISSUE TITLE
Custom Icon request [Xiaomi Smart Pet Water Fountain]

### ISSUE THREAD

**Issue by tioan** [elax46/custom-brand-icons#651]
![Xiaomi Smart Pet Water Fountain](https://github.com/elax46/custom-brand-icons/assets/259990/ab8648f7-274d-4bec-a4a3-36530ce7d954)

**Comment by rchiileea** [comment]
added to list

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/f14fc1cd-89c9-4262-a55c-1a7b30526a39)
