### ISSUE TITLE
Custom Icon request [Xiaomi Smart Pet Food Feeder]

### ISSUE THREAD

**Issue by tioan** [elax46/custom-brand-icons#652]
![Xiaomi Smart Pet Food Feeder](https://github.com/elax46/custom-brand-icons/assets/259990/1d763278-76f5-471f-8eeb-ec54bbbdda0f)

**Comment by rchiileea** [comment]
there is the aqara one which is simular shape but with upper panel clear to show food

**Comment by zalmael** [comment]
Hi, I can't find the info, maybe I missed it, but the aqara pet feeder has disappeared. Is there a reason? Thx.
