### ISSUE TITLE
Custom Icon request [Bambu Lab X1 Carbon Combo]

### ISSUE THREAD

**Issue by tioan** [elax46/custom-brand-icons#653]
![Bambu Lab X1 Carbon Combo](https://github.com/elax46/custom-brand-icons/assets/259990/bf4e0ff1-f688-414a-93d7-2831fe1fba10)

**Comment by rchiileea** [comment]
this should already be in the repo @elax46

**Comment by elax46** [comment]
It's the p1s not the x1c @rchiileea

**Comment by rchiileea** [comment]
https://private-user-images.githubusercontent.com/87599807/317646673-0d9545b0-edef-4024-abf6-8926fcc915ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzg1NjEsIm5iZiI6MTcxNjI3ODI2MSwicGF0aCI6Ii84NzU5OTgwNy8zMTc2NDY2NzMtMGQ5NTQ1YjAtZWRlZi00MDI0LWFiZjYtODkyNmZjYzkxNWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA3NTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZTA4YmUzOTYyMDIyMTQyZTQ2MTlkM2JkMWY2ZTEzOTJlZWNlYTBhZWIwNGYzY2Q4MzRlMGRiYWQ1M2RkNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M-OfDYyHglP04EBy78DZ1CnofSWtUNsLIC86uYHWCl0 looks the same to me

**Comment by elax46** [comment]
> ![image](https://private-user-images.githubusercontent.com/87599807/332335713-c0ccd59e-be60-441e-8c20-34a0b03baa37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzg2NDMsIm5iZiI6MTcxNjI3ODM0MywicGF0aCI6Ii84NzU5OTgwNy8zMzIzMzU3MTMtYzBjY2Q1OWUtYmU2MC00NDFlLThjMjAtMzRhMGIwM2JhYTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA3NTkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ZDBiNGM3ODJhMjE3MzE3MWZhYTgxOWIwOTQ1YzFiYjc0MTZjZmZlNDI2YjMyYzlmOWEyOGY3NjBiMTk2OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xouW3MpZ5bmFn_LamdrK7mfl5XL1RcR4qj-8u9ws09k)
> 
> looks the same to me

the difference is the display

**Comment by rchiileea** [comment]
I am not seeming to be a bit critical here, but are you you really going to notice the display size as a icon on a ha dashboard?

**Comment by elax46** [comment]
> I am not seeming to be a bit critical here, but are you you really going to notice the display size as a icon on a ha dashboard?

no you are right about that

**Comment by rchiileea** [comment]
i mean, either I need new glases but 
![Screenshot 2024-05-21 091723](https://github.com/elax46/custom-brand-icons/assets/87599807/23b9ebca-6751-4480-a522-4208fc02c0f1)
![Screenshot 2024-05-21 091703](https://github.com/elax46/custom-brand-icons/assets/87599807/61808dfd-8d8c-4ea0-ab01-d7046ec7605d)

I can do it, but really its just adding weight for something you wont notice
