### ISSUE TITLE
Custom Icon request Doors and French Windows

### ISSUE THREAD

**Issue by hesspoint** [elax46/custom-brand-icons#655]
Hi,

Here in Germany we have these full glass windows and floor to ceiling glass doors (to the balcony, garden or patio). Not only these look different than the US versions but also have a 3rd status (next to open and closed) that is tilted.

Unfortunately all the Door and Window icons in MDI and mostly in this project are US type and don't reflect the tilting accurately.

Therefore here a kind request for 6 new icons

- Door closed
- Door open
- Door tilted
- Window closed
- Window open
- Window tilted

Essential Door and Windows would be almost the same with the difference that doors are longer and windows are more towards squared.

Here are some images that illustrate this. Not sure which is the best way to depict as a small icon so I attached a few different examples

![dkf-mit-stulp-4](https://github.com/elax46/custom-brand-icons/assets/67288231/cc391dfe-3644-491d-8565-1ea659b1e11c)

![balkontuer-einstellen-600x400-Dreh-Kipp-Funktion](https://github.com/elax46/custom-brand-icons/assets/67288231/76cabbc4-4672-47bb-b887-f6eb5d2619a2)

![dreh-kipp-fenster-2](https://github.com/elax46/custom-brand-icons/assets/67288231/03d3c339-085c-4eef-8ac1-16db17598380)

![100566-211014_fenster_kippfenster](https://github.com/elax46/custom-brand-icons/assets/67288231/623977cd-4ae9-4f2e-8d89-3ce5785baa3d)

Thanks you very much!

**Comment by tioan** [comment]
i use 
lift-in-window-closed
lift-in-window-open1
lift-in-window-open2
for my Windows in Germany

**Comment by hesspoint** [comment]
Thanks @tioan somehow I missed these. Then I guess windows is covered but would be nice to have an elongated version as doors 😊

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/b7555f59-64b0-4b90-ba00-279fa91df00d)
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/4d9603c9-e3d5-492e-a990-a80d00098f29)
will add patio doors on next release, Just been busy with sons activities and tournaments as well as fixing 150 odd icons in the repo.

**Comment by rchiileea** [comment]
@hesspoint
