### ISSUE TITLE
Custom Icon request: Update of Kika.svg icon

### ISSUE THREAD

**Issue by hctom** [elax46/custom-brand-icons#657]
The current KiKA icon is not really readable due to its solid background. What do you think about this one instead?

![kika](https://github.com/elax46/custom-brand-icons/assets/8543951/83095566-064a-4704-a980-42dcb236edf0)

Thanks for all your hard work!

**Comment by rchiileea** [comment]
not a fan of outlined icons, especially names, they never read well on dashboard, so I took the solid parts

![image](https://github.com/elax46/custom-brand-icons/assets/87599807/af46403c-7c89-40cc-9b11-36deb06fe295)

**Comment by hctom** [comment]
Fine for me ;) This also makes it much more readable than the current icon. I'm looking forward to the new icon. Thanks!
