### ISSUE TITLE
Custom Icon request [ikea uppatvind]

### ISSUE THREAD

**Issue by jrspowers** [elax46/custom-brand-icons#658]
Hello, could you make this into an icon? Thanks in advance.
![ikea_uppatvind](https://github.com/elax46/custom-brand-icons/assets/60328474/6629b000-10cd-4b0b-98f5-167a23b21848)
![filter](https://github.com/elax46/custom-brand-icons/assets/60328474/dced4cde-2d87-4805-9d29-bd586e37b224)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/a3b082e5-a6a9-4820-a8ad-b81a8ea5b395)

**Comment by jrspowers** [comment]
Can you make filter or this device for icon ?

**Comment by jrspowers** [comment]
Why is this not included in the new release yet? And can you also create the filter as an icon?

**Comment by rchiileea** [comment]
I added a generic air purifier filter, update has take some time, becuase I have been fixing over 150 icons that were oversized in the repo

**Comment by jrspowers** [comment]
Is this now included in the release or not?
