### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by Lycan-Sys-Net** [elax46/custom-brand-icons#659]
Hello,
I would like a custom icon for the following:

Sling TV
https://vignette.wikia.nocookie.net/logopedia/images/b/b1/Sling_Television-logo.svg

Dish TV
https://companieslogo.com/img/orig/DISH-1619a80a.svg?t=1660587592&download=true
https://companieslogo.com/img/orig/DISH_BIG-3aa2e61e.svg?t=1660587592&download=true

**Comment by rchiileea** [comment]
read submition rules
