### ISSUE TITLE
Custom Icon request [Dune-HD]

### ISSUE THREAD

**Issue by pierinho** [elax46/custom-brand-icons#66]
Dune-HD SVG file...
[https://mega.nz/file/OIhlFCrK#FIJg4cMsNjJQDnefq5GN50g-HIT0XjsKtQN-bzJ_sb0](url)

**Comment by elax46** [comment]
the icon does not meet the [requirements described](https://github.com/elax46/custom-brand-icons#make-icon) for this time I was able to integrate it for the next requests do not forget when written

**Comment by elax46** [comment]
usa mega e posta il link qui
