### ISSUE TITLE
Custom Icon request [dish-network-logo]

### ISSUE THREAD

**Issue by LycanrocIsMySpiritAnimal** [elax46/custom-brand-icons#668]
Sorry for the incorrect submission earlier.

Attached are the requested icons, in the requested format.  The name I would suggest using for this one is dish-network-logo.
![dish_network_logo](https://github.com/elax46/custom-brand-icons/assets/77985806/a9bcdaa4-3446-4c49-974a-814a8e139961)
![dish_network_logo](https://github.com/elax46/custom-brand-icons/assets/77985806/500e49a0-a429-492f-8200-c6eb037b86e2)

**Comment by rchiileea** [comment]
I know the dish network I is like this, but I will stump it a little to make it fill more (take a 2 pixel gap from each section so its larger on screen).

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/01c82b5c-d108-4fbf-a146-cb8df2f6031a)
