### ISSUE TITLE
Custom Icon request [dish-network-logo-name]

### ISSUE THREAD

**Issue by LycanrocIsMySpiritAnimal** [elax46/custom-brand-icons#669]
Suggested name is dish-network-logo-name.
![dish_network_logo_name](https://github.com/elax46/custom-brand-icons/assets/77985806/c185f96a-5d0e-4bec-9b73-5413cb6badc7)
![dish_network_logo_name](https://github.com/elax46/custom-brand-icons/assets/77985806/7e3e9fd0-c647-4936-af69-8a7a557a71ac)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/603ae99b-67a0-448f-9bd4-e1fd99cf0429)
