### ISSUE TITLE
Custom Icon request [sling-tv-logo]

### ISSUE THREAD

**Issue by LycanrocIsMySpiritAnimal** [elax46/custom-brand-icons#670]
Suggested Name:  sling-tv-logo

![sling-tv-logo](https://github.com/elax46/custom-brand-icons/assets/77985806/6c9841f4-3e2a-4aad-9f2d-61c0193602d1)
![sling-tv-logo](https://github.com/elax46/custom-brand-icons/assets/77985806/c13f9180-af7b-4ccb-8f5d-27ecdc48b591)

**Comment by rchiileea** [comment]
![image](https://github.com/elax46/custom-brand-icons/assets/87599807/1ee2c93a-56e4-4da3-afc0-ead53633cd74)
