### ISSUE TITLE
Icons not visible in the Header bar

### ISSUE THREAD

**Issue by Jonny-T-cyber** [elax46/custom-brand-icons#681]
Hi,
the icons are not visible in the header bar:

![image](https://github.com/elax46/custom-brand-icons/assets/33354144/18316422-7ae4-4d6e-8e88-3a4b4f4c6b91)

However I noticed that they are visible in 'edit' mode:

![image](https://github.com/elax46/custom-brand-icons/assets/33354144/df3cd3ab-6901-4b49-86bb-dbe67e455aec)

Is there a valid reason?
Can I use the icons in the header bar?
Thanks

**Comment by elax46** [comment]
Hi, sorry for the late reply, I invite you to [read on](https://github.com/elax46/custom-brand-icons?tab=readme-ov-file#dont-see-the-icon)

I remind you to add to your configuration.yaml

```
frontend:
extra_module_url
-/local/community/custom-brand-icons/custom-brand-icons.js
```

**Comment by rchiileea** [comment]
can you try this and let me know if it works?

make sure you have both of these under resources.

/hacsfiles/custom-brand-icons/custom-brand-icons.js?hacstag=366862031202420
and

/local/community/custom-brand-icons/custom-brand-icons.js

**Comment by Maddin1684** [comment]
Same here.
I added the ressources and the url in config.yaml
No Icon loaded in the header bar.
