### ISSUE TITLE
Custom Icon request
Please can I have a custom Icon for a EcoFlow River 2 as per below link

### ISSUE THREAD

**Issue by Dirkster22** [elax46/custom-brand-icons#684]
https://drive.google.com/file/d/1LPPALiFA94LDTvFIcFNgVxuRfceaHVMa/view?usp=drivesdk

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
read submition rules

**Comment by Dirkster22** [comment]
Apologies, very newbie...LOL
Icon for:
EcoFlow River 2 Power Station
![Ecoflow jpg](https://github.com/elax46/custom-brand-icons/assets/168953574/76c37ffc-8080-4cda-a411-ab39aeb97a16)

SVG file can be found at:
https://drive.google.com/file/d/1LPPALiFA94LDTvFIcFNgVxuRfceaHVMa/view?usp=drivesdk

It does not want to upload to github?
