### ISSUE TITLE
Bug report: Frigate icon not shown

### ISSUE THREAD

**Issue by cvc90** [elax46/custom-brand-icons#689]
Hi @elax46,

The Frigate icon (phu:frigate) in the new version 2024.6.0 is not displayed, in previous versions it worked correctly.

![image](https://github.com/elax46/custom-brand-icons/assets/76731844/5f56d4f0-b42e-4826-8262-5c5de9540526)

As you can see in the image all the other icons work correctly

![image](https://github.com/elax46/custom-brand-icons/assets/76731844/0b3aa6bc-5b25-44a9-b0c4-d9a6a4bf39e4)

- It has been verified that it is not a cache error
- It has been verified that the "custom component" is not a permissions error
- No errors displayed in Chrome "DevTools"

**Comment by elax46** [comment]
fixed
