### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by ross9103** [elax46/custom-brand-icons#691]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**
I would like to have a litterbox icon made please.  

I am not sure if I am doing this correctly.

![cbi--litterbox](https://github.com/elax46/custom-brand-icons/assets/78512150/4cd0081c-5d91-435f-9c52-d454fd65b5b0)

above is svg

**Comment by elax46** [comment]
Kindly provide a sample image

**Comment by rchiileea** [comment]
closing as no response
