### ISSUE TITLE
Pinball icon

### ISSUE THREAD

**Issue by Naviato** [elax46/custom-brand-icons#694]
Icon for indicating a pinball machine, set of machines, or application. 

https://drive.google.com/file/d/1R2L46fVzQFwRrVQ8OkDE5FEWslJPLDew/view?usp=share_link
![image](https://github.com/user-attachments/assets/f3d8bdf5-88e7-4588-8330-45b5e980c2de)

**Comment by rchiileea** [comment]
yep I will do a single pinball icon, but read the submition rules

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/a5b08cf2-cea7-4eff-9cfc-eb236b4aacbc)
