### ISSUE TITLE
Pinball Manufacturers

### ISSUE THREAD

**Issue by Naviato** [elax46/custom-brand-icons#695]
Icons to indicate pinball machines by major manufacturers. If a limited number are selected for inclusion, please prioritize the first three shown below. Thank you for considering adding these to the set. 

[Williams](https://drive.google.com/file/d/17VY8J7SmGhlgZmd3zVyXkSZEBHV-s7UJ/view?usp=share_link)
[Stern](https://drive.google.com/file/d/1ZSvDRvDW-u0gQp4eHyOrr7y2s3yqN4LQ/view?usp=share_link)
[Jersey Jack](https://drive.google.com/file/d/126Ks7pltF2S-1R5A6g9cPcb6Lf_lTEC9/view?usp=share_link)
[Bally](https://drive.google.com/file/d/1W7bwdGtMN9KlUr71P5rSOsQWRvr7f0IE/view?usp=share_link)
[Gottlieb](https://drive.google.com/file/d/1J_SC8vfpx1YWAx7VyBO68aWJSnaM48vu/view?usp=share_link)
[Chicago Coin](https://drive.google.com/file/d/1R-H6JniaPyFgCKZx1sZVZaP8kvGBm8HE/view?usp=share_link)

**Comment by rchiileea** [comment]
I dont think this has any realtion to home assistant really
