### ISSUE TITLE
Custom Icon request New ESPHome Icon

### ISSUE THREAD

**Issue by bjoernmayer** [elax46/custom-brand-icons#696]
ESPHome changed their logo.

https://raw.githubusercontent.com/esphome/home-assistant-addon/main/esphome-dev/icon.png

https://esphome.io/_images/logo.png
![image](https://github.com/user-attachments/assets/8d034cd7-02bd-4509-b66f-96ab04ed18f7)

**Comment by rchiileea** [comment]
please read submistion rules,

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/e0f67977-4a57-47ee-808a-d314cc65af0f)
