### ISSUE TITLE
Tesla Car Without Defrost

### ISSUE THREAD

**Issue by Tillsy** [elax46/custom-brand-icons#698]
Hey guys

Is there any chance of getting just a plain Tesla model 3?  Basically phu:tesla-defrost without the defrost :)

Kind regards
Chris

**Comment by rchiileea** [comment]
added to do list

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/9fc1a899-6380-4737-9790-0b15bc7c8ae0)

**Comment by Tillsy** [comment]
Love it thank you!
