### ISSUE TITLE
VRT Radio1, Klara and Studio Brussel

### ISSUE THREAD

**Issue by thomasdg** [elax46/custom-brand-icons#699]
As I don't really know how to contribute through github, I am hereby adding the logos I created for some of the flemish VRT radio stations.

![vrt-radio1](https://github.com/elax46/custom-brand-icons/assets/5465002/6acd5f7f-21f8-4036-bcd1-f83dbead095c)
![vrt-stubru](https://github.com/elax46/custom-brand-icons/assets/5465002/5c7f87f1-fcc6-4147-bf09-dddb152fc4d5)
![vrt-klara](https://github.com/elax46/custom-brand-icons/assets/5465002/329c3cab-6147-4b44-802d-7804bc0582bf)

Lines I added to the javascript file:
` "vrt-stubru":[0,0,24,24, "m 21.96,10.402c0,1.742 -0.494,5.26 -1.142,6.878c-1.776,4.546 -5.204,6.72 -8.837,6.72c-3.634,0 -7.061,-2.174 -8.837,-6.72c-0.61,-1.618 -1.104,-5.136 -1.104,-6.878c-0,-6.308 4.277,-10.402 9.96,-10.402c5.702,0 9.974,4.094 9.96,10.402 zm -2.823,1.886c-0.014,1.05 -0.033,2.099 -0.095,3.149c0.528,-0.063 1.075,-0.173 1.603,-0.303c0.005,-0.067 0.014,-0.139 0.019,-0.206c0.014,-0.149 0.029,-0.298 0.029,-0.437c-0.317,0.082 -0.653,0.144 -0.975,0.192c0.005,-0.201 0.015,-0.398 0.024,-0.6c0.024,-0.619 0.053,-1.248 0.053,-1.862c-0.11,0.009 -0.216,0.019 -0.326,0.033c-0.106,0.015 -0.216,0.024 -0.327,0.034l-0.005,-0 zm -4.161,-3.586l-0,0.768l0.802,0l-0,-0.768l-0.802,0 zm 0.034,1.076l0.019,0.014l-0,2.438c0.254,-0.019 0.513,-0.033 0.768,-0.033c-0,-0.403 -0.005,-0.807 -0.01,-1.21c-0.005,-0.408 -0.009,-0.811 -0.009,-1.209l-0.768,-0 zm -1.776,-0.02c-0.706,0 -1.124,0.591 -1.124,1.263l0.034,-0.015c-0.014,0.672 0.432,1.282 1.138,1.248c0.24,0 0.446,-0.081 0.609,-0.254l0,0.206l0.783,0c-0,-1.166 -0,-2.337 -0.034,-3.504l-0.782,0l-0,1.282c-0.178,-0.158 -0.384,-0.226 -0.624,-0.226 zm 0.369,1.796c-0.129,0.062 -0.288,0.062 -0.417,-0l0.014,-0c-0.192,-0.096 -0.302,-0.288 -0.302,-0.528c-0,-0.24 0.11,-0.466 0.321,-0.543c0.111,-0.048 0.24,-0.048 0.351,0c0.225,0.082 0.336,0.288 0.336,0.543c-0,0.24 -0.111,0.432 -0.303,0.528 zm -4.901,-2.448l0.015,-0l-0.015,-0.015l0,0.015 zm -0.744,-0l0,0.686l-0.417,0l-0,0.643l0.417,0l0,0.831c-0.014,0.561 0.404,0.96 0.946,0.96l0.398,-0l0,-0.658l-0.288,0c-0.076,0 -0.206,-0.062 -0.206,-0.062l-0.048,-0.048c-0.048,-0.068 -0.062,-0.226 -0.062,-0.226l-0,-0.797l0.59,0l-0,-0.657l-0.59,-0l-0,-0.672l-0.74,-0 zm -4.286,2.99c-0.038,-0.005 -0.072,-0.01 -0.11,-0.014c0.033,1.022 0.081,2.03 0.158,3.057c0.302,0.063 0.61,0.13 0.926,0.192c0.192,0.034 0.399,0.015 0.576,-0.081c0.24,-0.159 0.336,-0.418 0.322,-0.706c-0.014,-0.336 -0.178,-0.638 -0.466,-0.816c0.192,-0.144 0.274,-0.35 0.274,-0.59c-0,-0.495 -0.37,-0.864 -0.85,-0.927c-0.278,-0.033 -0.552,-0.072 -0.83,-0.115 zm 0.816,1.282l-0,-0.015l-0.336,-0.048c-0.014,-0.177 -0.014,-0.35 -0.014,-0.528l0.086,0.015c0.072,0.014 0.154,0.033 0.235,0.033c0.192,0.015 0.303,0.13 0.303,0.303c-0,0.062 -0.015,0.129 -0.048,0.177l-0.034,0.063l-0.192,-0 zm 0.336,1.262c-0.082,0.014 -0.178,0.034 -0.254,0.014l-0.015,0.015c-0.057,-0.01 -0.115,-0.019 -0.177,-0.034c-0.063,-0.014 -0.12,-0.024 -0.178,-0.033c-0.014,-0.207 -0.034,-0.418 -0.034,-0.624c0.13,0.033 0.24,0.048 0.37,0.062c0.226,0.014 0.35,0.158 0.384,0.37c-0,0.048 -0.014,0.144 -0.014,0.144l-0.034,0.048l-0.048,0.038 zm 2.194,-2.242c-0.432,-0.014 -0.864,-0.048 -1.296,-0.081l0.014,0.033c-0,1.056 0.014,2.127 0.082,3.183c0.12,0.014 0.24,0.029 0.36,0.038c0.12,0.015 0.24,0.024 0.36,0.039l-0,-0.044c-0.015,-0.35 -0.029,-0.691 -0.029,-1.041c0.081,-0 0.158,0.009 0.24,0.014c0.081,0.01 0.158,0.015 0.24,0.015c0.177,0.033 0.288,0.144 0.321,0.321c0.015,0.135 0.034,0.269 0.058,0.399c0.019,0.134 0.038,0.264 0.058,0.398l0.043,0.005c0.254,0.029 0.499,0.057 0.758,0.057c-0.014,-0.153 -0.038,-0.307 -0.057,-0.465c-0.02,-0.159 -0.039,-0.312 -0.058,-0.466c-0.034,-0.254 -0.158,-0.48 -0.35,-0.638c0.24,-0.144 0.35,-0.37 0.35,-0.639c-0.005,-0.614 -0.466,-1.094 -1.094,-1.128 zm 0.211,1.392c-0.063,0.063 -0.144,0.063 -0.24,0.063l-0.015,-0c-0.081,-0 -0.163,-0.01 -0.249,-0.015c-0.087,-0.009 -0.168,-0.014 -0.25,-0.014l0,-0.754c0.159,0.015 0.336,0.034 0.495,0.034c0.225,0.034 0.369,0.178 0.369,0.398c0,0.116 -0.029,0.212 -0.11,0.288 zm 1.089,0.74l0.015,-0.015c-0,0.768 0.576,1.33 1.344,1.33c0.768,0.033 1.344,-0.432 1.344,-1.248l-0,-2.064l-0.783,-0l0,2.064c0,0.144 -0.048,0.288 -0.129,0.398c-0.125,0.111 -0.269,0.159 -0.447,0.159c-0.35,-0 -0.576,-0.255 -0.576,-0.591l0,-2.049c-0.254,-0.02 -0.513,-0.034 -0.768,-0.034l0,2.05 zm 10.426,-2.204c-0.662,0.044 -1.31,0.092 -1.973,0.12l0.048,0c0,1.09 -0.014,2.175 -0.048,3.264l0.087,-0.009c0.662,-0.063 1.334,-0.125 1.992,-0.216c0.014,-0.226 0.033,-0.447 0.033,-0.672c-0.446,0.062 -0.878,0.11 -1.329,0.144l-0,-0.591c0.168,-0.014 0.34,-0.033 0.508,-0.048l0.005,0c0.173,-0.014 0.346,-0.033 0.509,-0.048c0.014,-0.225 0.014,-0.465 0.014,-0.686c-0.336,0.034 -0.686,0.062 -1.022,0.082l-0,-0.543c0.432,-0.014 0.864,-0.048 1.296,-0.096l0,-0.705l-0.12,0.004 zm -6.456,1.388c-0.11,-0.048 -0.144,-0.144 -0.144,-0.144c-0,-0 -0.067,-0.125 0.062,-0.255c0.13,-0.115 0.336,-0.081 0.336,-0.081c0.207,0.014 0.336,0.144 0.384,0.35l0.816,-0c0,-0.686 -0.628,-1.07 -1.267,-1.07c-0.576,-0 -1.171,0.336 -1.185,0.974c-0,0.158 0.033,0.322 0.096,0.48c0.216,0.394 0.595,0.49 0.974,0.586c0.072,0.019 0.139,0.038 0.211,0.057l0.034,0c0.096,0.029 0.225,0.077 0.273,0.111c0.068,0.048 0.13,0.172 0.034,0.302c-0.029,0.034 -0.062,0.062 -0.11,0.096c-0,-0 -0.02,-0 -0.034,0.014c-0,0 -0.144,0.048 -0.226,0.048c-0.288,0 -0.46,-0.172 -0.494,-0.446l-0.816,-0c0.034,0.72 0.624,1.181 1.33,1.166c0.643,0 1.267,-0.355 1.281,-1.041c0.024,-0.701 -0.489,-0.835 -1.013,-0.97c-0.086,-0.019 -0.172,-0.043 -0.254,-0.067l-0.034,-0.014c0,-0 -0.158,-0.063 -0.254,-0.096 zm 2.885,-0l-0.096,-0.034c-0.082,-0.034 -0.13,-0.082 -0.159,-0.158c-0.014,-0.048 0,-0.111 0.034,-0.178c0.062,-0.096 0.178,-0.13 0.254,-0.144l0.063,0c0.225,0 0.384,0.11 0.417,0.336c0.255,-0 0.514,-0.014 0.768,-0.034c0,-0.672 -0.576,-1.056 -1.2,-1.022c-0.576,0 -1.152,0.384 -1.171,1.008c0,0.158 0.034,0.322 0.096,0.48c0.211,0.379 0.581,0.47 0.955,0.562c0.082,0.019 0.164,0.038 0.245,0.062c0,0 0.207,0.048 0.274,0.144c0.048,0.062 0.062,0.192 -0.034,0.288c-0.096,0.096 -0.206,0.144 -0.336,0.144c-0.273,0 -0.446,-0.158 -0.48,-0.432c-0.273,0 -0.542,0 -0.801,0.014c0.014,0.706 0.59,1.152 1.281,1.119c0.624,-0.034 1.219,-0.399 1.234,-1.071c0.038,-0.676 -0.461,-0.801 -0.965,-0.931c-0.13,-0.033 -0.259,-0.067 -0.379,-0.11l-0,-0.043 zm -3.283,-1.474l-0.02,-0.019l0,-2.448l-0.801,-0l-0,1.344c-0.019,0.24 -0.163,0.384 -0.418,0.417c-0.24,-0.033 -0.398,-0.177 -0.398,-0.432l-0,-1.344l-0.783,0l0,1.536c0,0.514 0.37,0.96 0.898,0.96c0.288,0.02 0.542,-0.096 0.72,-0.302l-0,0.288l0.802,0 zm 5.313,-2.544c-0.686,0.034 -1.2,0.59 -1.2,1.282l0.015,-0c-0,0.672 0.528,1.233 1.219,1.185c0.672,-0.048 1.137,-0.638 1.137,-1.296c0,-0.657 -0.513,-1.171 -1.171,-1.171 zm 0.259,1.714c-0.144,0.096 -0.321,0.096 -0.465,0.014c-0.159,-0.096 -0.24,-0.274 -0.24,-0.48c-0,-0.302 0.206,-0.562 0.465,-0.562c0.336,0 0.466,0.303 0.466,0.528c-0.005,0.212 -0.067,0.384 -0.226,0.5 zm -10.089,-0.37c-0.063,-0.144 -0.192,-0.254 -0.351,-0.322c-0.144,-0.052 -0.302,-0.096 -0.451,-0.134c-0.033,-0.01 -0.062,-0.019 -0.091,-0.024c-0,0 -0.192,-0.048 -0.178,-0.206c0.015,-0.178 0.255,-0.13 0.255,-0.13c0.144,0.034 0.225,0.13 0.254,0.274c0.106,-0 0.211,0.004 0.317,0.009c0.101,0.005 0.197,0.01 0.293,0.01c-0.015,-0.495 -0.447,-0.816 -0.927,-0.831c-0.417,0 -0.753,0.288 -0.768,0.706c-0.028,0.552 0.394,0.691 0.812,0.83c0.019,0.005 0.038,0.01 0.052,0.02c0,-0 0.159,0.048 0.207,0.096c0.048,0.048 0.033,0.158 -0.082,0.206c-0.048,0.034 -0.11,0.034 -0.158,0.034c-0.178,-0.015 -0.288,-0.13 -0.322,-0.303c-0.192,0 -0.384,-0.014 -0.576,-0.033c0,0.494 0.399,0.878 0.898,0.912c0.446,0.033 0.878,-0.255 0.878,-0.735c0,-0.139 -0.014,-0.269 -0.062,-0.379 z"],
  "vrt-radio1":[0,0,24,24, "m 24,7.947c0,5.266 -5.373,15.422 -12,15.422c-6.627,0 -12,-10.156 -12,-15.422c0,-5.266 5.373,-7.316 12,-7.316c6.627,-0 12,2.05 12,7.316 z m -13.669,0.854l0.495,-0.346l0.647,-0.456c0.608,-0.427 0.711,-1.042 0.369,-1.53c-0.343,-0.492 -0.942,-0.595 -1.547,-0.171l-0.646,0.462l1.174,1.676l-1.896,-1.187l-0.456,0.323l0.466,2.161l-0.76,-0.285c0.164,-0.232 0.157,-0.545 -0.016,-0.77c-0.096,-0.152 -0.251,-0.257 -0.427,-0.291c-0.246,-0.025 -0.492,0.049 -0.683,0.207l-0.802,0.563l1.19,1.698l0.473,-0.323l-0.363,-0.515l0.211,-0.145l0.701,0.275l0.544,-0.379l0.443,-0.323l-0.11,-0.405l0.647,-0.462l0.346,0.223 z m 0.256,-2.096c0.094,-0.084 0.216,-0.131 0.343,-0.131c0.173,-0 0.335,0.087 0.43,0.231c0.067,0.089 0.103,0.198 0.103,0.309c0,0.189 -0.105,0.363 -0.272,0.451l-0.19,0.133l-0.605,-0.857l0.191,-0.136 z m -3.002,2.698l-0.324,0.22l-0.287,-0.411l0.323,-0.217c0.155,-0.107 0.304,-0.11 0.398,0.026c0.09,0.129 0.052,0.275 -0.107,0.385l-0.003,-0.003 z m 1.617,-0.828l-0.145,-0.615l0.527,0.349l-0.382,0.266 z m 3.39,-2.614c0.201,0.286 0.53,0.457 0.881,0.457c0.234,0 0.462,-0.076 0.649,-0.217c0.306,-0.201 0.49,-0.543 0.49,-0.909c0,-0.221 -0.067,-0.437 -0.193,-0.618c-0.201,-0.286 -0.53,-0.457 -0.88,-0.457c-0.235,-0 -0.463,0.076 -0.65,0.218c-0.307,0.2 -0.492,0.543 -0.492,0.91c-0,0.22 0.067,0.435 0.192,0.616l0.003,0 z m 0.589,-1.103c0.089,-0.062 0.195,-0.095 0.304,-0.095c0.184,-0 0.355,0.095 0.452,0.25c0.072,0.093 0.111,0.207 0.111,0.324c-0,0.17 -0.082,0.33 -0.221,0.43c-0.09,0.062 -0.196,0.095 -0.306,0.095c-0.183,0 -0.354,-0.093 -0.454,-0.247c-0.071,-0.093 -0.11,-0.207 -0.11,-0.324c-0,-0.172 0.083,-0.333 0.224,-0.433 z m -1.796,0.672l1.191,1.701l0.472,-0.331l-1.191,-1.701l-0.472,0.331 z m -1.077,12.936l4.305,-0l0,-11.897l-4.305,3.015l0,8.882 z"],
  "vrt-klara":[0,0,24,24, "m 17.397,0c1.534,0 3.069,0.585 4.241,1.757c1.171,1.171 1.756,2.706 1.756,4.241c0,1.534 -0.585,3.069 -1.756,4.24l-0,0l-0.001,0.001l-1.756,1.756l0.557,0.558l1.199,1.199l0.001,-0l-0,0c1.171,1.171 1.756,2.706 1.756,4.241c0,1.535 -0.585,3.07 -1.756,4.241c-1.172,1.171 -2.707,1.757 -4.241,1.757c-1.535,-0 -3.07,-0.586 -4.241,-1.757l-0,-0l-1.2,-1.199l-0.077,-0.078l-0.102,-0.102c-0.269,0.502 -0.614,0.973 -1.038,1.396c-0.761,0.761 -1.677,1.271 -2.646,1.532c-0.288,0.078 -0.579,0.134 -0.874,0.167c-0.226,0.026 -0.452,0.039 -0.68,0.039c-1.519,0 -3.038,-0.578 -4.197,-1.738c-1.159,-1.159 -1.739,-2.678 -1.739,-4.198l0,-18.053l11.276,0l-0,3.033l1.277,-1.276l-0,-0c1.171,-1.172 2.706,-1.757 4.241,-1.757 z m -9.086,17.173l-0,-2.889l-0.529,0l0,3.358l1.409,-0l0.201,-0.469l-1.081,-0 z m 1.973,0.469l0.193,-0.469l1.501,-0l0.192,0.469l0.558,-0l-1.476,-3.427l-0.03,0l-1.471,3.427l0.533,-0 z m 0.948,-2.267l0.548,1.329l-1.106,-0l0.558,-1.329 z m -4.769,-1.091l-1.343,1.876l-0,-1.876l-0.528,0l-0,3.358l0.528,-0l-0,-1.19l1.269,1.19l0.735,-0l-1.486,-1.393l1.407,-1.965l-0.582,0 z m 9.171,3.358l-0.682,-0.953c0.44,-0.203 0.672,-0.603 0.672,-1.121c-0,-0.775 -0.509,-1.284 -1.432,-1.284l-0.859,0l-0,3.358l0.528,-0l0,-0.8l0.331,-0c0.084,-0 0.168,-0.005 0.242,-0.015l0.573,0.815l0.627,-0 z m -1.462,-1.254l-0.311,-0l0,-1.635l0.311,0c0.642,0 0.909,0.306 0.909,0.815c-0,0.513 -0.262,0.82 -0.909,0.82 z m 2.43,1.254l0.193,-0.469l1.5,-0l0.193,0.469l0.558,-0l-1.476,-3.427l-0.03,0l-1.471,3.427l0.533,-0 z m 0.948,-2.267l0.548,1.329l-1.106,-0l0.558,-1.329 `z"]`

**Comment by thomasdg** [comment]
Just tried to add a pull request - first time ;)

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/90ef1b55-5844-4922-b99d-29aa9b343d46)
![image](https://github.com/user-attachments/assets/d6ef969a-1a06-4957-99d7-74a191b4c90d)
![image](https://github.com/user-attachments/assets/c19a2c71-8f96-4463-8c76-dbdb420717e1)

**Comment by thomasdg** [comment]
I think elax46 just added them from my trial to make a pull request... If this one did work, I will try to support development of this library from now on...
