### ISSUE TITLE
bulbsSpot group ison

### ISSUE THREAD

**Issue by SAOPP** [elax46/custom-brand-icons#7]
Hi!

Thanks for pack, awesome!

I really miss the icon with the image of several bulbsSpot. Thanks in advance.

**Comment by SAOPP** [comment]
It would also be nice to have copies of these icons, only in a 180 degree rotation.

**Comment by elax46** [comment]
The bulbsSpot is present as long as you read [README.md.](https://github.com/elax46/custom-brand-icons) If you mean the group one, the manufacturer has not made it available. The svg images are those provided by philips you should apply a` transform = "rotate"` to each element if it has this need you can create your fork and make the necessary customizations
