### ISSUE TITLE
Custom Icon request [custom tilt blind open and close and custom attic window open and close icons]

### ISSUE THREAD

**Issue by rchiileea** [elax46/custom-brand-icons#70]
tilt blind
![140479154-c355780d-81d5-46bd-9aaf-fe9a484bd439](https://user-images.githubusercontent.com/87599807/140516724-5928ee96-a7e7-42b6-a4f0-473327d8da00.png)
![140479991-eacba007-faef-468d-9167-5fc575294f54](https://user-images.githubusercontent.com/87599807/140516749-d0832654-c438-445b-bfa9-8dfffba36adc.png)

[tiltblind.zip](https://github.com/elax46/custom-brand-icons/files/7486236/tiltblind.zip)

attic window
![140513559-8a653014-9a0a-48cc-b852-87f4b014de86](https://user-images.githubusercontent.com/87599807/140516937-d17ec6d1-d6a1-4f9a-a5f5-f7f26e8b3768.png)
![140513583-528d69db-8c69-438f-983d-e7b3b8eb1405](https://user-images.githubusercontent.com/87599807/140516979-fa0f3844-5f1b-47be-8af6-dea40f0cf467.png)

[TiltWindowRoof.zip](https://github.com/elax46/custom-brand-icons/files/7486264/TiltWindowRoof.zip)

SVG files in the zip and d= code is correct for icons

**Comment by elax46** [comment]
Thanks for your icons they are really well done! it would be nice if you could also insert a single and double non-angled window. The icons will be available in the next update

**Comment by rchiileea** [comment]
you mean like this 

![image](https://user-images.githubusercontent.com/87599807/140563358-7e7231c2-d2d8-4b3d-b9bc-88a5fbe538f0.png)
![image](https://user-images.githubusercontent.com/87599807/140563374-ef509eea-6461-4863-9114-c818b950e7a8.png)
[double-window.zip](https://github.com/elax46/custom-brand-icons/files/7488296/double-window.zip)

**Comment by elax46** [comment]
Very nice icon! also integrate these

**Comment by jrspowers** [comment]
@rchiileea can you also make this in vertical it's for me lammel zouw nice if this can be made and added by @elax46 thanks alvast ?

**Comment by elax46** [comment]
> @rchiileea can you also make tilt blind in vertical it's lame for me would be nice if this can be made and added by @elax46 thanks alvast ?

repost [here](https://github.com/elax46/custom-brand-icons/issues/79)
