### ISSUE TITLE
Custom Icon request [washing machine open / closed door]

### ISSUE THREAD

**Issue by tioan** [elax46/custom-brand-icons#700]
Something like this

![image](https://github.com/elax46/custom-brand-icons/assets/259990/126fd2b3-d837-4d2d-a1a0-104bc59a0750)

but with less details like

![image](https://github.com/elax46/custom-brand-icons/assets/259990/37eb739b-cfe3-4e27-8bc3-2f863dc78f55)

**Comment by rchiileea** [comment]
this would be simple, but in reality I dont think its needed, just washing machine finished is used in most smart homes and people generally leave the door slightly ajar to allow a machine to dry out.
