### ISSUE TITLE
Custom Icon request : Salt TV Provider

### ISSUE THREAD

**Issue by mphp** [elax46/custom-brand-icons#702]
https://commons.wikimedia.org/wiki/File:Salt_Logo_2015.svg
![image](https://github.com/user-attachments/assets/13de74ff-543a-43d0-9aad-f9cc920e6a98)

This is a very common Internet & TV provider in Switzerland...
Thank you !

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/6aefbbe7-3ddb-40cd-ba9c-9b27a87b8df1)
