### ISSUE TITLE
Custom Icon request : Monzo Bank

### ISSUE THREAD

**Issue by beecho01** [elax46/custom-brand-icons#703]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

https://www.iconarchive.com/download/i150356/simpleicons-team/simple/monzo.svg
https://www.iconarchive.com/show/simple-icons-by-simpleicons-team/monzo-icon.html

[Monzo bank](https://en.wikipedia.org/wiki/Monzo) in the UK.

**Comment by rchiileea** [comment]
read request rules
