### ISSUE TITLE
Custom Icon request: Virgin Media

### ISSUE THREAD

**Issue by skinnypope** [elax46/custom-brand-icons#705]
Virgin Media icon request

A very large UK / Irish internet and TV provider.

[https://www.virginmedia.com/](url)

[https://logos.fandom.com/wiki/Virgin_Media?file=Vm-logo-small.svg](url)

![Vm-logo-small](https://github.com/elax46/custom-brand-icons/assets/168759853/c6052b77-7955-4dd3-895c-a1b22e84a850)

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/44479150-07bf-4997-bcfa-25a8d7c2785a)

**Comment by skinnypope** [comment]
Perfect, thank you so much
