### ISSUE TITLE
Generic smoke-detector icon missing in latest update

### ISSUE THREAD

**Issue by P3TACCO** [elax46/custom-brand-icons#706]
The phu:smoke-detector icon is missing in the latest update.

It's still displayed here:
https://icon-sets.iconify.design/cbi/

It's not in the search tool here:
https://elax46.github.io/custom-brand-icons/

It's no longer in my HA instance after update to 2024.6.1

Was this intentional?

Thanks

**Comment by elax46** [comment]
Hi, thanks for the report, it wasn't intentional but a bug, already fixed, it will be released in the next version

**Comment by P3TACCO** [comment]
Thanks!
