### ISSUE TITLE
check on these windows as done them to the full 28x28 size

### ISSUE THREAD

**Issue by rchiileea** [elax46/custom-brand-icons#71]
Closed
![image](https://user-images.githubusercontent.com/87599807/140640552-0d646ec0-0845-4089-9398-8e9553ff9bc2.png)

Open
![image](https://user-images.githubusercontent.com/87599807/140640559-a5dd3b07-662f-4460-8f71-962124130082.png)
[Lift-Out.zip](https://github.com/elax46/custom-brand-icons/files/7492054/Lift-Out.zip)

**Comment by elax46** [comment]
@rchiileea do the other icons also have a maximum size of 28x28?
