### ISSUE TITLE
Custom Icon request S0tool

### ISSUE THREAD

**Issue by huizebruin** [elax46/custom-brand-icons#713]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

S0tool ( jpeg)

![s0tool-2024](https://github.com/user-attachments/assets/f26c5fda-5ec2-4819-aa63-7a26cc0baf81)

S0tool ( svg)

![s0tool-2024](https://github.com/user-attachments/assets/7339547a-a866-45ff-b833-8c1825731604)

![s0tool-2024 44739e](https://github.com/user-attachments/assets/efb356cd-2803-4f28-baa2-4c9305cb1f15)

**Comment by scns** [comment]
This icon would be a great addition.

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/3153da4a-4833-420b-954d-fe88b65bc25b)

**Comment by huizebruin** [comment]
> ![image](https://github.com/user-attachments/assets/3153da4a-4833-420b-954d-fe88b65bc25b)
> 

That's looking good 👍
