### ISSUE TITLE
Custom Icon request Christmas Tree, Wreath and Lights

### ISSUE THREAD

**Issue by broyuken** [elax46/custom-brand-icons#72]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://www.svgrepo.com/svg/222397/christmas-wreath-wreath
https://www.svgrepo.com/svg/55849/christmas-tree
https://www.svgrepo.com/svg/38327/christmas-lights

**Additional context**
There don't seem to be any/many christmas icons for christmas decorations anywhere for HA, so why not here?

**Comment by rchiileea** [comment]
I like this idea, although I think the tree should be solid that way you can add using custom button card and card mod a glow through the bobbles and around edge

**Comment by elax46** [comment]
the christmas tree icon does not meet the [requirements](https://github.com/elax46/custom-brand-icons#help-me-insert-more-icons)

**Comment by broyuken** [comment]
Do you mean the wreath? It looks like you can just go in and delete one of these lines and the accompanying <g> tag and it still renders fine. 

<g transform="translate(1 1)">

**Comment by rchiileea** [comment]
> Do you mean the wreath? It looks like you can just go in and delete one of these lines and the accompanying tag and it still renders fine.

they will,  but what elax is refering too is the code part, its not suitable for home assistant, there are some things I have planned to add if elax is ok as my xmas lights and tree are plugged into a smart switch.

**Comment by elax46** [comment]
> Do you mean the wreath? It looks like you can just go in and delete one of these lines and the accompanying tag and it still renders fine.

the wreath is insertable the problem is the tree

**Comment by broyuken** [comment]
I’m sorry, I don’t know that much about vector icons. What part is the issue? I can see if I can pull it into illustrator and save it in a more compatible format.

**Comment by elax46** [comment]
problem solved, integrated icon

**Comment by rchiileea** [comment]
sorry to keep closed thread going but this was a tree I was working on, not sure if it would work though as code is long, (still single under path, but long).

![image](https://user-images.githubusercontent.com/87599807/140798913-59170617-e552-45c0-a4d5-34ad2673866d.png)

**Comment by elax46** [comment]
> sorry to keep closed thread going but this was a tree I was working on, not sure if it would work though as code is long, (still single under path, but long).
> 
> ![image](https://user-images.githubusercontent.com/87599807/140798913-59170617-e552-45c0-a4d5-34ad2673866d.png)
> 
> I was going for real tree look :P

wow nice I add this too! the length of the code is not a problem

**Comment by rchiileea** [comment]
[christmas-real-tree.zip](https://github.com/elax46/custom-brand-icons/files/7499336/christmas-real-tree.zip)

**Comment by rchiileea** [comment]
> > I’m sorry, I don’t know that much about vector icons. What part is the issue? I can see if I can pull it into illustrator and save it in a more compatible format.
> 
> it is not possible, it is a question of code

no need to be sorry, its a svg thing, you need to basically do a combine on anything created in photoshop (28px X 28px in size) but I find it best to export as svg after and load in inkscape as this will show potential problem as allow you to run the combine under paths (which will turn it into a single line of code rather than multiple paths).

**Comment by broyuken** [comment]
so the issue was the multiple paths because of the ornaments?

**Comment by elax46** [comment]
> so the issue was the multiple paths because of the ornaments?

yes because in the script I can only load a single path per icon

**Comment by broyuken** [comment]
gotcha, good to know for future icon requests. thanks for replying so quickly!

**Comment by elax46** [comment]
> gotcha, good to know for future icon requests. thanks for replying so quickly!

Not at all

**Comment by rchiileea** [comment]
forgot to ask when will the update be released, or is that down to hacs? I have some fancy rainbow effect css code to test with tree icon :P

**Comment by elax46** [comment]
> forgot to ask when will the update be released, or is that down to hacs? I have some fancy rainbow effect css code to test with tree icon :P

release now!

**Comment by elax46** [comment]
> forgot to ask when will the update be released, or is that down to hacs? I have some fancy rainbow effect css code to test with tree icon :P

I'm sorry you don't get on the contributor list on the first page of the repo, but for that you should open pull requests

**Comment by rchiileea** [comment]
> > forgot to ask when will the update be released, or is that down to hacs? I have some fancy rainbow effect css code to test with tree icon :P
> 
> I'm sorry you don't get on the contributor list on the first page of the repo, but for that you should open pull requests

I dont mean that, I meant I have not seen update in hacs for 3 days, so was wondering when that was going to happen (no rush just curious)

**Comment by elax46** [comment]
I prefer to release versions when there are at least a few new icons, [1.0.37](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.37) is out now

**Comment by rchiileea** [comment]
> I prefer to release versions when there are at least a few new icons, [1.0.37](https://github.com/elax46/custom-brand-icons/releases/tag/1.0.37) is out now

time is not issue, i just was curious :) see it now

**Comment by rchiileea** [comment]
![tree](https://user-images.githubusercontent.com/87599807/140897550-3c022470-310a-4c2a-9c7d-f5e0453be02e.gif)
looks like my code works for when device would be on :)

**Comment by AndyVRD** [comment]
> ![tree](https://user-images.githubusercontent.com/87599807/140897550-3c022470-310a-4c2a-9c7d-f5e0453be02e.gif)
> looks like my code works for when device would be on :)

Is there any change you can share the glowing code/template behind the Christmas three. :)
