### ISSUE TITLE
Custom Icon request Fortaleza

### ISSUE THREAD

**Issue by damiaorocha** [elax46/custom-brand-icons#720]
![fortaleza](https://github.com/user-attachments/assets/1a84ffcf-cdf6-445b-8be6-171b3b24839b)
![fortaleza](https://github.com/user-attachments/assets/f010aad8-071a-4c90-99b4-2e655531b900)

**Comment by damiaorocha** [comment]
![fortaleza](https://github.com/user-attachments/assets/49993f4f-2c81-40f7-9519-5252562bd90e)

**Comment by rchiileea** [comment]
I will be back from holiday next week to start making icons for next update

**Comment by Gtt1229** [comment]
@damiaorocha How is this?

![image](https://github.com/user-attachments/assets/561453c2-5697-4af5-bf2e-485ea30f0c82)

@rchiileea I started this right when you began to comment on the open issues.

**Comment by damiaorocha** [comment]
this is a football club shield

**Comment by Gtt1229** [comment]
> this is a football club shield

So is the icon sufficient?

**Comment by damiaorocha** [comment]
Yes

**Comment by Gtt1229** [comment]
@rchiileea Created Pull Request: https://github.com/elax46/custom-brand-icons/pull/743

**Comment by elax46** [comment]
> @elax46 @Gtt1229 this icon is incorrect and is what caused issues in the past, the icons why they have to be 24x24 the hight of the icons images should be 20x20 inside a 24x24 box... this icons goes over that there needs to be a 2 pixel gap around the whole image of the icon to not cause issues. ![image](https://private-user-images.githubusercontent.com/87599807/363910600-876e7d6e-4755-4b5e-ba47-9a58f9f0ff72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTU2MjMsIm5iZiI6MTcyNTM1NTMyMywicGF0aCI6Ii84NzU5OTgwNy8zNjM5MTA2MDAtODc2ZTdkNmUtNDc1NS00YjVlLWJhNDctOWE1OGY5ZjBmZjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA5MjIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMzVmN2RhZTg2NmYwZWRjMTE3MjA4MWViOWQ1MjMxODJkYWYwOTk2NzY2YTdmYTQyYzI1ODU4MDIyYTYxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yEX3FdLxszrdwBIOy4CKONwLPmP-gr2fVNdhVn6paKw) and ill have to redo it to fit in with the rules @elax46 change to new one I upload sometime today

The pull request has been revert

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/afe0efea-fd84-4aaf-b47a-67786fdfa1e5)
