### ISSUE TITLE
Custom Icon request Stremio

### ISSUE THREAD

**Issue by EF01** [elax46/custom-brand-icons#723]
Stremio 

Png:
![stremio-purple-small-758151493](https://github.com/user-attachments/assets/0cd9cae6-d7a1-4c50-977b-d54d2e88bfe5)

Svg:
![th-4018464638](https://github.com/user-attachments/assets/aa20ee8b-d190-462c-aea2-7cb5c8be8ac9)

**Comment by rchiileea** [comment]
I will be back from holiday next week to start making icons for next update

**Comment by Gtt1229** [comment]
How is this one?

![image](https://github.com/user-attachments/assets/695e9f7e-16b5-4e45-b589-327954e5fdc5)

**Comment by EF01** [comment]
Perfect! Thank you 💪

**Comment by Gtt1229** [comment]
> I will be back from holiday next week to start making icons for next update

We literally commented at the same time haha. I can add this one to the dev.

**Comment by Gtt1229** [comment]
@rchiileea This can be marked as completed:

https://github.com/elax46/custom-brand-icons/pull/740
