### ISSUE TITLE
Lyrion music server 

### ISSUE THREAD

**Issue by nickrout** [elax46/custom-brand-icons#724]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

https://github.com/LMS-Community/lms-community.github.io/blob/main/assets/icon/Lyrion%20-%20logo%20-%20black.svg

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

![Lyrion - logo - black](https://github.com/user-attachments/assets/3b2b44da-47b7-437b-b4e8-6a1d92b1497f)

Hope I got it right this time. Sorry about last time.

**Comment by rchiileea** [comment]
I will be back from holiday next week to start making icons for next update

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/a8ac146f-46c4-4aab-83a1-545c37256ad5)
