### ISSUE TITLE
Custom Icon request Mikrotik

### ISSUE THREAD

**Issue by anhnvme** [elax46/custom-brand-icons#725]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://icon-sets.iconify.design/simple-icons/mikrotik/
**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**
![simple-icons--mikrotik](https://github.com/user-attachments/assets/50cb8c63-1a62-496b-bbc1-d83577d33609)
Please add this icon. Thank you

**Comment by rchiileea** [comment]
I will be back from holiday next week to start making icons for next update

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/159be10b-2545-47ef-8edf-43a8ad271190)

**Comment by anhnvme** [comment]
thank you so much !
