### ISSUE TITLE
Custom Icon request - ITVX

### ISSUE THREAD

**Issue by JackO-C** [elax46/custom-brand-icons#727]
Hey there, first time logo request, just found your HACS mod and it's awesome! Thank you

![ITVX_logo](https://github.com/user-attachments/assets/cc179593-6e8f-480d-add4-ff36ba0f34ea)

This is the ITVX UK streaming service logo

**Comment by rchiileea** [comment]
I will be back from holiday next week to start making icons for next update

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/394eae89-a592-4caf-aacf-57a6a8f7890d)

**Comment by visjack** [comment]
perfect!
