### ISSUE TITLE
Custom Icon request [Lidl Curved floor lamp]

### ISSUE THREAD

**Issue by tioan** [elax46/custom-brand-icons#728]
![image](https://github.com/user-attachments/assets/c9b17fa4-c5fc-4ffc-b694-50fe4e7596bf)

**Comment by rchiileea** [comment]
I will be back from holiday next week to start making icons for next update

**Comment by rchiileea** [comment]
@tioan I have added a rule to the template just because of this request, I mean come on you expect me to make a icon from a low poly 150x150 px image

**Comment by rchiileea** [comment]
@tioan you may have noticed the icon is in the repo, I just wanted to shock you for a better picture next time :P
