### ISSUE TITLE
Icon don't show in the new badges on HA app

### ISSUE THREAD

**Issue by WazoAkaRapace** [elax46/custom-brand-icons#729]
**Describe the bug**
The icons does not show up in the badges until I open the edit mode and try to edit the badge. It then show up in the frontend after.

Icons are working correctly in other cards.

## Don't see the icon?

I've followed all the instructions to add the frontend resources in the configuration or the two resources, but icons doesn't show up.

Thanks for your help 🙏

**Comment by elax46** [comment]
Hi, sorry for the late reply, I checked on my instance that the icons are visible from the web interface while the invisibility problem is always there with the Android application, @rchiileea  are there similar problems in your instance?

**Comment by rchiileea** [comment]
ok in my ios app, but I must say I am using testflight ios app, but their have been bugs happening left right and centre lately in that not even related to our repor (lock screen widgets etc).
