### ISSUE TITLE
Custom Icon request - World Scout Organisation

### ISSUE THREAD

**Issue by hen-hick** [elax46/custom-brand-icons#730]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
![image2vector](https://github.com/user-attachments/assets/d7b1465a-d64f-428a-bcc5-97c3c9b634ea)

![WSCT_EMBLEM_RGB_MONO](https://github.com/user-attachments/assets/f7ea7fc8-9efd-4d23-a1b0-85c182af6e72)

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by hen-hick** [comment]
https://brand.scout.org/d/HHhYcPGXUAWQ/visual-identity#/logo-shorthand/the-shorthand

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/f37d1484-1dea-486c-bee0-3f693dd39ed2)
