### ISSUE TITLE
Custom Icon request - World Scout Emblem

### ISSUE THREAD

**Issue by hen-hick** [elax46/custom-brand-icons#731]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
![image2vector (1)](https://github.com/user-attachments/assets/26c4bf70-4245-4c48-a3b1-6654d2ce5e76)

![Master_WSCT_EMBLEM_RGB_MONO](https://github.com/user-attachments/assets/67015040-c145-4139-8fd7-c34b1b1f7a8a)

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
this is the old scout logo new one is 
![image](https://github.com/user-attachments/assets/55773766-9b62-46d0-a26c-7d84914857ed)

**Comment by hen-hick** [comment]
The one posted by @rchiileea is the UK scout associations logo. The one I have requested is the World Scout Emblem which is the new branding from the World Organisation of the Scouting Movement (WOSM).

https://brand.scout.org/d/HHhYcPGXUAWQ/visual-identity#/master-world-scout-emblem/our-emblem

**Comment by rchiileea** [comment]
I will be back from holiday next week to start making icons for next update

**Comment by hen-hick** [comment]
Thanks, Sea Explorer Leader here. Thought it would be best to include the WOSM ones for more general use than the UK specific ones.

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/e4d07485-54ba-4164-ba98-4a4264c032ac)
