### ISSUE TITLE
Custom Icon request - Aqara E1 RSD-M01

### ISSUE THREAD

**Issue by plotzwi-eq** [elax46/custom-brand-icons#733]
![image](https://www.elektrogrosshandel.ch/thumbor/YVWPysbPG_U23PFS3_gQlwQnM_Q=/fit-in/3600x2700/filters:cachevalid(2023-12-04T16:54:23):strip_icc():strip_exif()/eldas/myassets/0458/0387_P_0458828.jpg)

Sorry guys, I couldn't find svg image of this.

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/dac0530c-f660-49f9-9a5f-009144138e84)
