### ISSUE TITLE
Icon not on android app

### ISSUE THREAD

**Issue by wout-junius** [elax46/custom-brand-icons#735]
## Description

I do not see the Icons on my dashboard in the andoird app.

### Steps I tried
1. Check Issues for same issue
2. restarted app (Force quit)
3. clear app cashe

**Comment by rchiileea** [comment]
I can test this when I get back from holiday next week, not a issue in ios app though

**Comment by elax46** [comment]
Three weeks have passed without a response, we are closing the request
