### ISSUE TITLE
Custom Icon request FaceTime

### ISSUE THREAD

**Issue by GitHubGoody** [elax46/custom-brand-icons#736]
https://logowik.com/down?file=eyJpdiI6IkdKa05kckliUWk2YUNiN0t0SW9xYUE9PSIsInZhbHVlIjoiYXlzdHNCaFIvMVZkYy9UNmtNa2FKZz09IiwibWFjIjoiZDEwMjk2ODRlZjgxNmFjYjcwNzM2MGFhMjdiZDQ3NWFjYjBjODJhOWQ4NjJkMWY3ZjhjZTQyMmU3N2E3NmMyMCIsInRhZyI6IiJ9

or

https://logowik.com/apple-facetime-vector-logo-12303.html

**Comment by rchiileea** [comment]
read rules,
