### ISSUE TITLE
Custom Icon request Apple Photos

### ISSUE THREAD

**Issue by GitHubGoody** [elax46/custom-brand-icons#737]
https://icons8.com/icons/set/apple-photos

**Comment by rchiileea** [comment]
read rules

**Comment by GitHubGoody** [comment]
> read rules

@rchiileea Sorry about that, but I just noticed the issue template (requests a link) and README (provide the svg and links will be ignored) have different instructions:

ISSUE TEMPLATE
`**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**`

README
- Provide a svg file and jpg logo of your request (we also are not mind readers and dont know every icon globaly so if no name is present please add it and a image along with your request.
- links to SVG's or Images will be ignored you must upload the files into your requestand they must be visible in post IGNORING THIS SIMPLE REQUEST WILL RESULT IN YOUR REQUEST BEING IGNORED AND CLOSED (if you can not be bothered to spend a few minutes doing this, why should we spend time making it).

Maybe update to align with your intent?

**Comment by rchiileea** [comment]
yes, but do as new requests please

**Comment by GitHubGoody** [comment]
I don't understand
