### ISSUE TITLE
Custom Icon request [Numbered Bedroom Icons]

### ISSUE THREAD

**Issue by PlasmaPod** [elax46/custom-brand-icons#742]
## Bedroom No. Icons

Customised icons by "PlasmaPod"

Bed Icon with Room No. s to distinguish between Bedrooms. e.g. Master Bedroom, Bed 2, Bed 3, Bed 4.

[//]: # (Start Custom Icons)

| Icon | Name |
| :--- | :--- |
| ![bedroom-1](https://github.com/user-attachments/assets/a275be29-a86e-4705-9c2b-79ee66e05b71)| Bedroom 1 |
| ![bedroom-2](https://github.com/user-attachments/assets/3d464689-10df-4472-a3fb-7f71f64d8df8)| Bedroom 2 |
| ![bedroom-3](https://github.com/user-attachments/assets/09952154-a94f-47a2-a913-1a662f5dcadf)| Bedroom 3 |
| ![bedroom-4](https://github.com/user-attachments/assets/6af64e98-1d11-43bf-aac7-1eea67875d61)| Bedroom 4 |
| ![bedroom-5](https://github.com/user-attachments/assets/bde0ea9d-a85e-4adb-b45b-ee0139a0e065)| Bedroom 5 |
| ![bedroom-6](https://github.com/user-attachments/assets/6ad6d936-ec42-4230-9291-8e808a6b6eff)| Bedroom 6 |
| ![bedroom-7](https://github.com/user-attachments/assets/83516b8d-1d92-4d9b-946b-1f0bf75272e2)| Bedroom 7 |
| ![bedroom-8](https://github.com/user-attachments/assets/54705973-61cb-4294-9ce9-c416819a8533)| Bedroom 8 |
| ![bedroom-9](https://github.com/user-attachments/assets/4c7b8f80-bcd1-4cb7-b9fa-03dfc5df95e6)| Bedroom 9 |
|![master-bedroom](https://github.com/user-attachments/assets/02dd3bb8-e9d1-4d82-a9a0-3cee16091be0)| Master Bedroom |

[//]: # (End Custom Icons)

**Comment by rchiileea** [comment]
why I like the idea, this still does not really achieve anything you cant do with card mod, having 1-9 and a m listed its just crazy, maybe just a bedroom icon with gap for the number.

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/ff38fdcb-afda-4bc4-9cf2-6a194d8579d5)

**Comment by PlasmaPod** [comment]
<img width="1437" alt="Screenshot 2024-09-03 at 8 41 58 PM" src="https://github.com/user-attachments/assets/ab958925-74be-4987-ace0-d9bf19a596f9">
This is what I was aiming to achieve. I probably only needed todo Bed1 - Bed5

Thanks for adding bedroom-alt-numbered
