### ISSUE TITLE
Icons Positionning 

### ISSUE THREAD

**Issue by Titou84240** [elax46/custom-brand-icons#747]
**Describe the bug**
Hi ;-)  , Really sorry if its already discussed or fixed , i have search i hope fully and never found it. 
Is it possible to have the icons on the top bar positionned differently , for example i have them on the left and i would like to have them centered : 

![2024-09-03 14_55_11-UI Lovelace Minimalist – Home Assistant – Brave](https://github.com/user-attachments/assets/fff8c63a-aa49-4fea-ad52-16d1b234bc98)

Just taking my chance here :-)

**Comment by elax46** [comment]
Hi this is not a bug of the icon set but it is the HA dashboard toolbar which is aligned to the left I don't think it is a customizable thing unless you install some custom integration but if there are any I also tag @rchiileea  maybe he knows something about it

**Comment by rchiileea** [comment]
Not going to happen, the only way to get around this at the moment is to use kiosk mode to hide the top bar and use badges on your actual pages.

**Comment by Titou84240** [comment]
Ok ok understood thanks for the info !
