### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by DaWacko87** [elax46/custom-brand-icons#749]
Hi elax46,

Thank you already for the great work! These icons make my Home Assistant so much more customizable. However I would also love to have the Onkyo logo added to the custom brand icons.

![Onkyo_(logo)](https://github.com/user-attachments/assets/45f62398-a833-48f7-b53e-b0434b1a9460)
![Onkyo_(logo)](https://github.com/user-attachments/assets/e06eadd0-07da-4e4f-a343-1fc13aad759e)

Kind regards,

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/8e7ca3a8-0f20-422f-9441-27ec61ba683b)

**Comment by DaWacko87** [comment]
Thank you that's great!
