### ISSUE TITLE
Custom Icon request: Panasonic

### ISSUE THREAD

**Issue by Eigeplackter** [elax46/custom-brand-icons#750]
I hope the image quality is okay, this is my first request.

![panasonic-logo](https://github.com/user-attachments/assets/f1fca600-1eee-4366-9244-3a0c4e73c428)
![panasonic-logo](https://github.com/user-attachments/assets/9b007bab-eef7-484f-9c84-0a28aca3bdcc)

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/71905911-b926-461e-a56d-3a49e4eb6277)
