### ISSUE TITLE
Custom Icon request Epson

### ISSUE THREAD

**Issue by Eigeplackter** [elax46/custom-brand-icons#751]
Hi, would really like to see the correct icon for my pj.
Thanks in advance. The "Exceed your vision" is absolutely not necessary.

![epson-logo](https://github.com/user-attachments/assets/56965a0e-7394-4c44-8c40-5916d2eff1dc)
![epson](https://github.com/user-attachments/assets/ca05ac6c-8fae-4a4c-8d42-8167374f1c6d)

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/ebbd6e17-f0db-4ea5-9925-ddc9c0b19bfc)
