### ISSUE TITLE
Custom Icon request Denon

### ISSUE THREAD

**Issue by Eigeplackter** [elax46/custom-brand-icons#752]
Again, would be grateful to replace the boring mdi:amplifier with the brand.

![DENON](https://github.com/user-attachments/assets/6fe05033-e6cb-4fa0-8c46-8c942850e233)
![denon-logo-svg-vector](https://github.com/user-attachments/assets/54d1c000-32c6-4492-a16e-bf79ea00c866)

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/2f0affa9-f02e-43b1-bab5-adbbdc91ba39)
