### ISSUE TITLE
No Icons after update to 2024.9.1

### ISSUE THREAD

**Issue by c0nt4x** [elax46/custom-brand-icons#755]
**Describe the bug**
I have updated to v.2024.9.1 and there are no icons to be found when I try to add one to an entity. I enter phu: and no list of icons appear.

Cache has been cleared, browser refreshed and HA restarted but still no Custom Brand icons to be found.

**Comment by elax46** [comment]
Hi in my HA instance everything is ok the icons are visible without problems I suggest you redownload the latest version
![Cattura](https://github.com/user-attachments/assets/91944c40-ba58-44e7-81d1-f4da3cbe6012)

**Comment by elax46** [comment]
Two weeks have passed without a response, we are closing the request
