### ISSUE TITLE
Custom Icon request Linksys

### ISSUE THREAD

**Issue by anhnvme** [elax46/custom-brand-icons#756]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**
https://icon-sets.iconify.design/simple-icons/linksys/
**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**
![simple-icons--linksys (1)](https://github.com/user-attachments/assets/1cd623ec-f143-4db6-af27-47b93f6a5a4e)

Please add this icon. Thank you

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/4042696b-e0b2-4d4a-8d15-498b124a5cb9)
