### ISSUE TITLE
Custom Icon request [Herman Miller Aeron]

### ISSUE THREAD

**Issue by conorlap** [elax46/custom-brand-icons#76]
https://drive.google.com/file/d/1XmJcZCup5nVNmoCcWeyaJdGDOBVEb1PU/view?usp=sharing

Herman Miller Aeron chair, for office room icon. 
Thanks!

**Comment by elax46** [comment]
the file is not accessible

**Comment by conorlap** [comment]
whoops, my bad! Should be public now :)

**Comment by elax46** [comment]
the icon will be available in the next update

**Comment by conorlap** [comment]
Hey @elax46 / @rchiileea is there any way to make this icon solid black? The icon isn't all that clear when it's small on my HA dashboard! I'm not sure how to do this for SVG files!

**Comment by elax46** [comment]
it could be something like this but it depends on where you implement it
`<ha-icon icon="phu:herman-miller-aeron" style=" color: black;"></ha-icon>`

**Comment by rchiileea** [comment]
in your card via editor in ui make sure it under

icon: phu:herman-miller-aeron
color: black

or if icon icon is white  add this under card (must  be using card mod and custom button card from hacs)

entity: your entity 
icon: phu:herman-miller-aeron
color: white
name: yourname
tap_action:
  action: toggle
  haptic: light
hold_action:
  action: more-info
  haptic: medium
styles: 
   icon:
     - '-webkit-filter': contrast(96%) drop-shadow(3px 3px 3px rgba(0,0,0,1)
  
or if icon is black in your config change to - '-webkit-filter': contrast(96%) drop-shadow(3px 3px 3px rgba(255,255,255,1)

first one is to add a black drop shardow around the icone and will define it more, second one will be a white drop shadow to define it more (it all depends on your card/icon color combo on which one will work for you
