### ISSUE TITLE
Custom Icon request Apple Photos

### ISSUE THREAD

**Issue by GitHubGoody** [elax46/custom-brand-icons#761]
![ApplePhotos](https://github.com/user-attachments/assets/ecc3e3de-f7ae-4369-a174-c49969a9ba99)

**Comment by rchiileea** [comment]
looking at this, not going to be easy with them over laps, will end up looking like a square with a flower lol

**Comment by GitHubGoody** [comment]
Yeah, I may be better off going through Font Awesome on this one.

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/61a436b0-6d7f-4634-879c-25def908e829)
