### ISSUE TITLE
Custom Brand Icons Not Loading - 404 Error for custom-brand-icons.js

### ISSUE THREAD

**Issue by cloudbr34k84** [elax46/custom-brand-icons#769]
Describe the bug: The custom-brand-icons.js file is not being loaded, resulting in a 404 error. This issue occurs when accessing the resource from the following URL: https://ha.cloudbr34k.xyz/local/custom-brand-icons.js.

Steps to reproduce:

Open Home Assistant and navigate to the Lovelace resources page.
Check the browser's developer tools for network requests.
Notice that the request for custom-brand-icons.js returns a 404 error.
Expected behavior: The custom-brand-icons.js file should load successfully, allowing the custom brand icons to be displayed.

Error Details:

Request URL: https://ha.cloudbr34k.xyz/local/custom-brand-icons.js
Request Method: GET
Status Code: 404 Not Found
Referrer Policy: same-origin
Cache Consideration: I have attempted to load the page using an incognito window to rule out cache issues, but the issue persists. Double-checked the installation, and the file still cannot be located.

rowser Information:

Browser: Chrome Version 128.0.6613.120 (Official Build) (64-bit)
Operating System: Windows 11

**Comment by elax46** [comment]
Hi how did you integrate CBI into your instance? I suggest you add it using HACS

**Comment by cloudbr34k84** [comment]
> Hi how did you integrate CBI into your instance? I suggest you add it using HACS

I added it via hacs followed the guide, i have added it based on the below

frontend:
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
    
first go to settings, dashboard and 3 dots click resorces, add resource

/hacsfiles/custom-brand-icons/custom-brand-icons.js?hacstag=366862031202420
Add this second resource too

/local/community/custom-brand-icons/custom-brand-icons.js

**Comment by elax46** [comment]
> > Hi how did you integrate CBI into your instance? I suggest you add it using HACS
> > @elax46
> > I added it via hacs followed the guide, i have added it based on the below
> 
> this is also the download path www/community/custom-brand-icons/custom-brand-icons.js frontend: extra_module_url: - /local/community/custom-brand-icons/custom-brand-icons.js
> 
> first go to settings, dashboard and 3 dots click resorces, add resource
> 
> /hacsfiles/custom-brand-icons/custom-brand-icons.js?hacstag=366862031202420 Add this second resource too
> 
> /local/community/custom-brand-icons/custom-brand-icons.js

can you check if there is a js file in the specified path /local/community?

**Comment by cloudbr34k84** [comment]
> > > Hi how did you integrate CBI into your instance? I suggest you add it using HACS
> > > @elax46
> > > I added it via hacs followed the guide, i have added it based on the below
> > 
> > this is also the download path www/community/custom-brand-icons/custom-brand-icons.js frontend: extra_module_url: - /local/community/custom-brand-icons/custom-brand-icons.js
> > 
> > first go to settings, dashboard and 3 dots click resorces, add resource
> > 
> > /hacsfiles/custom-brand-icons/custom-brand-icons.js?hacstag=366862031202420 Add this second resource too
> > 
> > /local/community/custom-brand-icons/custom-brand-icons.js
> 
> can you check if there is a js file in the specified path /local/community?

@elax46 
This is where the js file is located
www/community/custom-brand-icons/custom-brand-icons.js

**Comment by elax46** [comment]
the position is correct there shouldn't be any problem

**Comment by cloudbr34k84** [comment]
Hmmmm
Btw this error is from the Dev console screen under the network tab.

It's not that only hacs integration that is 404

**Comment by elax46** [comment]
I checked in my HA instance and I don't have these errors. I suggest you remove all the paths related to CBI and check what happens.

**Comment by cloudbr34k84** [comment]
> I checked in my HA instance and I don't have these errors. I suggest you remove all the paths related to CBI and check what happens.

Paths?? All resource address?

**Comment by cloudbr34k84** [comment]
that seems to have worked :)

**Comment by elax46** [comment]
I don't know what it could depend on, honestly I recommend removing CBI and reinstalling it using this [link](https://my.home-assistant.io/redirect/_change/?redirect=hacs_repository%2F%3Fowner%3Delax46%26repository%3Dcustom-brand-icons%26category%3Dfrontend)
