### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by kraroed** [elax46/custom-brand-icons#77]
I created another icon based on the Google Home app icon for the Google hello doorbell if you would like to use it.

Google Hello Doorbell:
https://drive.google.com/file/d/1WKiYkYiSyYQKZh8fkvQch6xnNZ8vP0rm/view?usp=drivesdk

**Comment by elax46** [comment]
the icon does not meet the [requirements](https://github.com/elax46/custom-brand-icons#make-icon)

**Comment by rchiileea** [comment]
tbh this almost the same as arlo bell use that

**Comment by rchiileea** [comment]
> I created another icon based on the Google Home app icon for the Google hello doorbell if you would like to use it.
> 
> Google Hello Doorbell: https://drive.google.com/file/d/1WKiYkYiSyYQKZh8fkvQch6xnNZ8vP0rm/view?usp=drivesdk

use phu:arlo-video-doorbell

**Comment by elax46** [comment]
I close this request as you have not answered us anymore
