### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by computergreek** [elax46/custom-brand-icons#776]
**links will be ignnored please upload icon/image**

**Again read main rules, Also I will point out low quality images of products will be ignored, if you can not be bothered to search we wont either**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

![fixture 1 1 (1)](https://github.com/user-attachments/assets/e4774220-cac2-44a6-8ca8-62f9375b32bd)
![fixture 1 1](https://github.com/user-attachments/assets/a66a79d1-2406-45c1-a848-286c79fff28e)

Hi, and thank you for looking at this request. 
I'm requesting that an icon be made of the Ikea FELSISK light fixture (ikea article number 404.895.26) with four Ikea 'TRÅDFRI LED bulb E26 450 lumen, smart wireless dimmable/white spectrum globe' light bulbs (article number 304.413.37). I've attached two images of what it looks like in my living room, but the fixture is a pretty popular one. i also attached a picture of it from its instructional manual in case that's helpful. 

![felsisk](https://github.com/user-attachments/assets/e9a7ef07-316a-49a5-8235-42ad91127add)

thanks again in advance and if there's anything else i can provide to make this easier for you, please let me know.

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/a22eaa88-ace5-42c8-93b3-0d4d84a11792)
