### ISSUE TITLE
Robot Vacuum Rotary Mop Icon

### ISSUE THREAD

**Issue by roblombardo** [elax46/custom-brand-icons#780]
An icon to represent the ever more popular rotary mop vacuums. Currently only a vibratory mop icon exists.
![image](https://github.com/user-attachments/assets/35b6ad09-5131-4a17-be88-fecb51ef31c7)

**Comment by rchiileea** [comment]
we have a roborok icon that suits most people, are you on about having the rotary mop pads added? 

phu:vac_mop
![image](https://github.com/user-attachments/assets/1551af18-a251-4246-ab4c-88ae85e683a6)

but round ones for rotary mops

**Comment by roblombardo** [comment]
Yes, that is my suggestion. I believe rotary mops are going to supplant the vibratory options, Therefore the existing graphic will not be recognizable to users eventually..Rob ***@***.*** Sep 27, 2024, at 12:06 AM, Richard Bowzer ***@***.***> wrote:﻿
we have a roborok icon that suits most people, are you on about having the rotary mop pads added?
phu:vac_mop
image.png (view on web)
but round ones for rotary mops

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/bf59b4d0-6c22-45ac-86d6-41a2ff44df6f)
