### ISSUE TITLE
Custom Icon request Rai Play

### ISSUE THREAD

**Issue by TheSgrash** [elax46/custom-brand-icons#783]
![image](https://github.com/user-attachments/assets/b6b0c9a0-fa15-47c9-9e89-6aa21ac35a1b) - taken from https://it.m.wikipedia.org/wiki/File:RaiPlay.svg

OnLine Platform for RAI - National Italian public broadcaster

this icon can be useful into MediaPlayer and TV remotes

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/ec5070b5-b5be-4e11-8443-5489149254ab)
