### ISSUE TITLE
Custom Icon request Mediaset Infinity

### ISSUE THREAD

**Issue by TheSgrash** [elax46/custom-brand-icons#784]
![image](https://github.com/user-attachments/assets/b112ff9d-2cfe-4ed7-83fa-0e119f02764e)

OnLine Platform for Mediaset - 2nd Italian public broadcaster

this icon can be useful into MediaPlayer and TV remotes

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/c0bafcc9-6f29-4db8-9dda-414ed8aabc1b)
