### ISSUE TITLE
Custom Icon request Synology DSM

### ISSUE THREAD

**Issue by SpaceEnergy** [elax46/custom-brand-icons#786]
![download-icon-synology+dsm-1330289860771959921_512](https://github.com/user-attachments/assets/d9f22b49-3432-4b1d-8f3f-7daf1b3c7d1f)

- taken from https://icons-for-free.com/synology+dsm-1330289860771959921/

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/ef1a2f9d-64a6-493a-a28f-8fe99d8ec6c4)
