### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by not-chees** [elax46/custom-brand-icons#787]
**links will be ignnored please upload icon/image**

**Again read main rules, Also I will point out low quality images of products will be ignored, if you can not be bothered to search we wont either**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

Hi, I would like to use the logo of "pathé". Pathé is a cinemabranch in The Netherlands but you can also rent and buy movies on their streaming service. I have atatched their logo as a png and as a svg.
![pathe--5](https://github.com/user-attachments/assets/d78d22f5-5ca2-4aa3-9e56-7c3666287503)
![imke2-tekengebied1](https://github.com/user-attachments/assets/21f5fef9-e0ef-4df8-95fb-2f020f6ca6c1)
Thank you!

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/7b45e41e-5fe3-44fb-9d7a-b7fab1b75874)
