### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by ivoargirov** [elax46/custom-brand-icons#789]
Hello,
Please add the Starlink logo icon.

Thanks
Ivo
![StarlinklogoPNGimage](https://github.com/user-attachments/assets/53475930-fea0-4ea3-8503-51aa1bda8c89)

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/46960526-01ba-4b1b-8bab-4a03401db63d)
