### ISSUE TITLE
Custom Icon request [Work in progress on more windows and doors]

### ISSUE THREAD

**Issue by rchiileea** [elax46/custom-brand-icons#79]
**Doors with glass**
1-panel-glass
![image](https://user-images.githubusercontent.com/87599807/141778546-428a9fe1-7560-4059-8cae-058d1aa9ba4d.png)
![image](https://user-images.githubusercontent.com/87599807/141778583-651835fd-1dbe-49dc-ae7d-e5faf2e74cfb.png)

2-panel-glass
![image](https://user-images.githubusercontent.com/87599807/141778703-24bc9d95-1e3c-43c2-8d6e-b3001ebafc07.png)
![image](https://user-images.githubusercontent.com/87599807/141778744-b280d048-6ba8-4e65-bae6-59cfbff99069.png)

3-panel-glass
![image](https://user-images.githubusercontent.com/87599807/141778815-752d038e-e8d8-4db4-a008-baff213f0be3.png)
![image](https://user-images.githubusercontent.com/87599807/141778845-e6b7673e-27ff-4ae6-b0a1-7913c4bbb097.png)

4-side-glassdoor
![image](https://user-images.githubusercontent.com/87599807/141778908-2a8e43eb-585f-40eb-9824-85b9141e54b2.png)
![image](https://user-images.githubusercontent.com/87599807/141778956-24016e84-9d38-4f52-82fe-1af344c13401.png)

6-panel-glassdoor
![image](https://user-images.githubusercontent.com/87599807/141779637-0fe82366-8821-4dfd-ac9f-261f7ac72ccd.png)
![image](https://user-images.githubusercontent.com/87599807/141779684-dedcf247-b46e-4676-be1c-2a8654e44907.png)

6-panel-frontdoor
![image](https://user-images.githubusercontent.com/87599807/141779143-e1a662f5-5c6f-435b-b986-db7241889a9b.png)
![image](https://user-images.githubusercontent.com/87599807/141779251-fb1dc654-ba54-4c60-8cca-b9aa16408ab0.png)

**Non-glass door**
![image](https://user-images.githubusercontent.com/87599807/141779788-7940096a-d40e-4eba-a795-3405d8d6f7fe.png)
![image](https://user-images.githubusercontent.com/87599807/141779828-071ced88-67e9-4c0f-8f3b-e420eb268576.png)

**Windows**
top-window
![image](https://user-images.githubusercontent.com/87599807/141779923-8d3a6ff1-691d-41a5-b5bb-8405e5d987ce.png)
![image](https://user-images.githubusercontent.com/87599807/141779959-a6414fd6-4377-4c41-a33f-9d4e53ac39c1.png)

sliding-window (and sliding back door)
![image](https://user-images.githubusercontent.com/87599807/141780092-95c5668e-93d4-4980-a84f-bdb5bf4e4321.png)
![image](https://user-images.githubusercontent.com/87599807/141780123-715476f4-f915-4db9-a424-361ee79436c2.png)

**More ring item**
Ring floodlight standalone
![image](https://user-images.githubusercontent.com/87599807/141781755-52e6e06b-8dd9-4bed-9b5f-bc7a33cabd20.png)

**Vert-blind**
![image](https://user-images.githubusercontent.com/87599807/141782115-2a864eb0-aa62-4599-8c08-a70a00bf28e0.png)
![image](https://user-images.githubusercontent.com/87599807/141782164-af544ec6-b4c6-424e-a9fe-00b5673968ef.png)

files to be added
[new items.zip](https://github.com/elax46/custom-brand-icons/files/7538649/new.items.zip)

**Comment by elax46** [comment]
wonderful work

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/141682481-1b4b0cf4-609b-495e-9328-657978f4982b.png)
![image](https://user-images.githubusercontent.com/87599807/141682490-f92540b3-96b3-49fd-a920-ea9cbecf996e.png)
![image](https://user-images.githubusercontent.com/87599807/141682705-81defe1c-99eb-45ca-8ef3-cd9143c1e76d.png)
![image](https://user-images.githubusercontent.com/87599807/141682744-42908e4d-e7b4-4fc0-a1a7-3c00779259e9.png)
a few more done yesterday, have a few more doors to do and windows then will upload

**Comment by jrspowers** [comment]
@rchiileea can you also make tilt blind in vertical it's lame for me would be nice if this can be made and added by @elax46 thanks alvast ?

**Comment by rchiileea** [comment]
> @rchiileea can you also make tilt blind in vertical it's lame for me would be nice if this can be made and added by @elax46 thanks alvast ?

its already in the folder waiting for me to finish the others (I had done this allready)

![image](https://user-images.githubusercontent.com/87599807/141696160-ea32ddc3-5245-40c3-bb10-1818aa0f6efd.png)

![image](https://user-images.githubusercontent.com/87599807/141696189-225bd747-430e-4909-8c75-f1460c85b9e2.png)

**Comment by jrspowers** [comment]
thanks man this makes my dashboard still beautiful

**Comment by rchiileea** [comment]
It’s not fun not shed jet as I need to create the gap at bottom between the slat uprights as to me it looks like prison bars still I have a coupe of doors and windows to finish and the upload all for road to add

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jrspowers** [comment]
I think they are also very good and understand you think wise & I can not open your link?

**Comment by rchiileea** [comment]
BUMP - SEE 1ST POST

**Comment by elax46** [comment]
@rchiileea new version released!

**Comment by rchiileea** [comment]
Nice, but I did forget one icon, ill add it when I done some more (double garage/ double door shed) one

________________________________

**Comment by jrspowers** [comment]
hello the latest update of icons doesn't work don't see any icons 2 times reboot doesn't work ?

**Comment by rchiileea** [comment]
> hello the latest update of icons doesn't work don't see any icons 2 times reboot doesn't work ?

Works fine me for me, have you tried alt/f5 for your browser or if  that does not work clear your cache and if using fully kiosk clear your cache
