### ISSUE TITLE
Custom Brand Icons not working for Mobile App Notifications?

### ISSUE THREAD

**Issue by tmason818** [elax46/custom-brand-icons#791]
**Describe the bug**
I can't seem to get any of the _Custom Brand Icons_ to work for Mobile App Notification. Are they able to be used or are they strictly for Lovelace?

For example this will display the PlayStation logo for a Notification icon from the Mobile App:
`notification_icon: mdi:sony-playstation`

However calling a phu icon will default the Notification icon to the Home Assistant Icon
`notification_icon: phu:playstation`

Is there perhaps some additional code that needs to be added to .yaml to call these icons through the Mobile App?

**Comment by Christianbouchard2** [comment]
Hi, I see the issue is closed, what is the command for notification_icon with "phu:"
THank!
