### ISSUE TITLE
Custom Icon request Sonos Logo

### ISSUE THREAD

**Issue by dworkin74** [elax46/custom-brand-icons#792]
Please add the Sonos Logo
![arcticons--sonos](https://github.com/user-attachments/assets/5d85a46c-4bad-496f-87dc-ee078655157e)

**Comment by rchiileea** [comment]
this ill pass on typing the normal thing as its a easy logo to fine, but for future referance please read rules and follow otherwise request will be ignored!

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/82058b84-db6e-49ab-b117-807a53188fe0)
