### ISSUE TITLE
Custom Icon request Snapcast

### ISSUE THREAD

**Issue by chicco-carone** [elax46/custom-brand-icons#793]
Since i wasn't sure which one would be adequate I uploaded 3 images and hopefully one of them can be added
![Snapcast](https://github.com/user-attachments/assets/d6ea7e08-4d4c-4a6d-bef1-08e59a5ea415)
![snapcast-svgrepo-com](https://github.com/user-attachments/assets/69f85a95-f2f5-4412-9d1f-cd415d9103ec)
![Snapcast](https://github.com/user-attachments/assets/38f02c07-8676-4601-a35d-dc7d8b5cfafb)
![snapcast_icon](https://github.com/user-attachments/assets/9fb20351-c0dc-43b3-90b2-685321193f3c)

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/4d3b3af2-6041-4861-aa07-3cf0ef980a78)
