### ISSUE TITLE
Poorly visible icons on github page

### ISSUE THREAD

**Issue by KrizzeOne** [elax46/custom-brand-icons#8]
**Describe the bug**
Since I'm using the dark background in github, I'm not able so see the provided brand icons clearly.

<img width="488" alt="Bildschirmfoto 2021-06-10 um 18 11 05" src="https://user-images.githubusercontent.com/65257000/121560016-6a374e00-ca17-11eb-820e-428907af3c49.png">

**Comment by elax46** [comment]
Thanks for your suggestion I already know about it. In the next update it will be corrected

**Comment by elax46** [comment]
Correct now! @KrizzeOne

**Comment by jimbob1001** [comment]
Can't see icons on white background now 😬
![Screenshot_20210611-073602](https://user-images.githubusercontent.com/10485852/121641987-ccc83280-ca87-11eb-92a7-af8409d7ff24.png)
