### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by capandcamera** [elax46/custom-brand-icons#80]
Streaming services: 
discovery-plus
disney-plus

[Archive.zip](https://github.com/elax46/custom-brand-icons/files/7532891/Archive.zip)

I attempted to test this with:
`"discovery-plus":[0,0,24,24,"M6.924,7.834l0,0.337l-0.331,0.049l-0.009,0.002c-3.151,0.548 -5.549,3.299 -5.549,6.606c-0,3.31 2.402,6.063 5.558,6.607l0.331,0.049l0,0.365l-0.331,-0.042l-0.005,-0.001c-3.37,-0.528 -5.95,-3.447 -5.95,-6.965c-0,-3.518 2.583,-6.439 5.955,-6.965l0.331,-0.042Zm0.766,1.091c3.262,-0 5.91,2.648 5.91,5.91c0,3.262 -2.648,5.911 -5.91,5.911c-3.262,-0 -5.911,-2.649 -5.911,-5.911c0,-3.262 2.649,-5.91 5.911,-5.91Zm4.141,11.613l-0.113,0.083c-0,0 0.113,-0.083 0.113,-0.083Zm0.189,-0.139l-0.189,0.139c0,0 0.189,-0.139 0.189,-0.139l0.042,-0.034l-0.042,0.034Zm0.171,-0.14l-0.129,0.106c0,-0 0.129,-0.106 0.129,-0.106Zm0.139,-0.115l-0.139,0.115c-0,-0 0.139,-0.115 0.139,-0.115l0.061,-0.056c-0,-0 -0.061,0.056 -0.061,0.056Zm0.19,-0.176l-0.129,0.12c-0,-0 0.129,-0.12 0.129,-0.12Zm0.105,-0.097l-0.105,0.097c-0,0 0.105,-0.097 0.105,-0.097l0.077,-0.081c0,0 -0.077,0.081 -0.077,0.081Zm0.201,-0.209l-0.124,0.128c0,0 0.124,-0.128 0.124,-0.128Zm0.078,-0.08l-0.078,0.08c0,0 0.078,-0.08 0.078,-0.08l0.093,-0.109c0,0 -0.093,0.109 -0.093,0.109Zm0.208,-0.242l-0.115,0.133c0,0 0.115,-0.133 0.115,-0.133Zm0.054,-0.063l-0.054,0.063c0,-0 0.054,-0.063 0.054,-0.063l0.11,-0.143c-0,-0 -0.11,0.143 -0.11,0.143Zm0.211,-0.276l-0.101,0.133c-0,-0 0.101,-0.133 0.101,-0.133Zm0.033,-0.043l-0.033,0.043l0.033,-0.043l0.132,-0.194c0,-0 -0.132,0.194 -0.132,0.194Zm0.212,-0.311l-0.08,0.117c0,-0 0.08,-0.117 0.08,-0.117Zm0.222,-0.369l-0.207,0.347l-0.015,0.022c0.078,-0.12 0.152,-0.243 0.222,-0.369Zm0.177,-0.338l-0.177,0.338c0,0 0.177,-0.338 0.177,-0.338Zm-0.177,0.338c0,0 0,0 0,0Zm0.188,-0.359l-0.011,0.021l0.011,-0.021l0.042,-0.092c-0,0 -0.042,0.092 -0.042,0.092Zm0.148,-0.328l-0.106,0.236c-0,0 0.106,-0.236 0.106,-0.236Zm0.019,-0.042l-0.019,0.042l0.019,-0.042l0.037,-0.095c-0,-0 -0.037,0.095 -0.037,0.095Zm0.122,-0.318l-0.085,0.223c-0,-0 0.085,-0.223 0.085,-0.223Zm0.025,-0.064l-0.025,0.064c0,-0 0.025,-0.064 0.025,-0.064l0.026,-0.084c0,0 -0.026,0.084 -0.026,0.084Zm0.097,-0.308l-0.071,0.224c0,0 0.071,-0.224 0.071,-0.224Zm0.027,-0.084l-0.027,0.084c0,0 0.027,-0.084 0.027,-0.084l0.017,-0.066c-0,-0 -0.017,0.066 -0.017,0.066Zm0.076,-0.301l-0.059,0.235c-0,-0 0.059,-0.235 0.059,-0.235Zm0.026,-0.1l-0.026,0.1c0,0 0.026,-0.1 0.026,-0.1l0.008,-0.047c0,0 -0.008,0.047 -0.008,0.047Zm0.058,-0.307l-0.05,0.26c0,0 0.05,-0.26 0.05,-0.26Zm0.02,-0.104l-0.02,0.104c0,-0 0.02,-0.104 0.02,-0.104l0.003,-0.024l-0.003,0.024Zm0.003,-0.024l0.051,-0.394l-0.051,0.394Zm-2.957,4.698l-0.338,0.22l0.36,-0.236l-0.022,0.016Zm0.041,-0.028l-0.019,0.012l0.113,-0.083l-0.094,0.071Zm0.283,-0.21l-0.189,0.139l0.231,-0.173l-0.042,0.034Zm0.079,-0.062l-0.037,0.028l0.129,-0.106l-0.092,0.078Zm0.231,-0.193l-0.139,0.115l0.2,-0.171l-0.061,0.056Zm0.113,-0.101l-0.052,0.045l0.129,-0.12l-0.077,0.075Zm0.182,-0.172l-0.105,0.097l0.182,-0.178l-0.077,0.081Zm0.141,-0.143l-0.064,0.062l0.124,-0.128l-0.06,0.066Zm0.138,-0.146l-0.078,0.08l0.171,-0.189l-0.093,0.109Zm0.166,-0.189l-0.073,0.08l0.115,-0.133l-0.042,0.053Zm0.096,-0.116l-0.054,0.063l0.164,-0.206l-0.11,0.143Zm0.185,-0.238l-0.075,0.095l0.101,-0.133l-0.026,0.038Zm0.059,-0.081l-0.033,0.043l0.165,-0.237l-0.132,0.194Zm0.2,-0.291l-0.068,0.097l0.08,-0.117l-0.012,0.02Zm0.027,-0.042l-0.015,0.022l0.222,-0.369l-0.207,0.347Zm0.373,-0.66l-0.166,0.313l0.177,-0.338l-0.011,0.025Zm0.022,-0.046l-0.011,0.021l0.053,-0.113l-0.042,0.092Zm0.128,-0.277l-0.086,0.185l0.106,-0.236l-0.02,0.051Zm0.039,-0.093l-0.019,0.042l0.056,-0.137l-0.037,0.095Zm0.094,-0.238l-0.057,0.143l0.085,-0.223l-0.028,0.08Zm0.053,-0.144l-0.025,0.064l0.051,-0.148l-0.026,0.084Zm0.065,-0.195l-0.039,0.111l0.071,-0.224l-0.032,0.113Zm0.059,-0.197l-0.027,0.084l0.044,-0.15l-0.017,0.066Zm0.041,-0.149l-0.024,0.083l0.059,-0.235l-0.035,0.152Zm0.061,-0.252l-0.026,0.1l0.034,-0.147l-0.008,0.047Zm0.021,-0.102l-0.013,0.055l0.05,-0.26l-0.037,0.205Zm0.057,-0.309l-0.02,0.104l0.023,-0.128l-0.003,0.024Zm0.078,-0.735l-0.002,0.046l-0.003,0.046c0.002,-0.031 0.004,-0.061 0.005,-0.092Zm0.002,-0.745l0.004,0.085l0.002,0.087c-0.001,-0.058 -0.003,-0.115 -0.006,-0.172Zm-0.047,-0.534l0.023,0.205l0.017,0.207c-0.01,-0.138 -0.023,-0.276 -0.04,-0.412Zm-0.046,-0.306l0.007,0.043c-0.002,-0.015 -0.004,-0.029 -0.007,-0.043Zm-0.032,-0.173l0.009,0.043l0.008,0.043c-0.003,-0.014 -0.006,-0.029 -0.008,-0.043l-0.009,-0.043Zm-7.681,-5.636l0,-4.901l7.081,-0c5.023,-0 9.1,4.092 9.1,9.132l0,0.554c0,5.108 -4.132,9.255 -9.223,9.255l-5.747,0c0.639,-0.036 1.255,-0.161 1.835,-0.362l0.155,-0.058l3.803,0c4.867,0 8.819,-3.965 8.819,-8.85l-0,-0.528c-0,-4.82 -3.9,-8.733 -8.702,-8.733l-6.77,0l-0,4.461l-0.276,0.021l-0.075,0.009Zm1.088,13.696l-0.27,0.005l0.27,-0.005Zm-0.955,-0.03l0.149,0.012l-0.207,-0l-0,-0.019l0.058,0.007Zm3.068,-0.046l-0.155,0.058l-1.692,-0c0.163,-0.013 0.324,-0.032 0.483,-0.058l1.364,0Zm-2.85,-13.65l-0,0.334l-0.276,0.024l-0,-0.337l0.276,-0.021Zm0.737,13.726c0.089,-0.004 0.178,-0.01 0.266,-0.018l1.692,-0c-0.58,0.201 -1.196,0.326 -1.835,0.362l-0.907,0l-0.257,-0.019l-0.047,-0.006l0,-0.365l0.075,0.009l-0,0.019l0.207,-0c0.088,0.008 0.177,0.014 0.267,0.018c0.089,0.003 0.179,0.005 0.269,0.005l0.27,-0.005Zm-0.539,-0c0.089,0.003 0.179,0.005 0.269,0.005l-0.269,-0.005Zm0.539,-0l0.266,-0.018l-0.266,0.018Zm-1.088,-13.696l0.075,-0.009l-0,0.337l-0.075,0.009l0,-0.337Zm1.022,-3.938l5.789,-0c4.694,-0 8.505,3.811 8.505,8.505c0,4.521 -3.555,8.218 -8.02,8.445l-0.435,0.011l-2.427,-0c0.122,-0.075 0.243,-0.153 0.36,-0.236l0.019,-0.012l0.094,-0.071l0.189,-0.139l0.042,-0.034l0.037,-0.028l0.092,-0.078l0.139,-0.115l0.061,-0.056l0.052,-0.045l0.077,-0.075l0.105,-0.097l0.077,-0.081l0.064,-0.062l0.06,-0.066l0.078,-0.08l0.093,-0.109l0.073,-0.08l0.042,-0.053l0.054,-0.063l0.11,-0.143l0.075,-0.095l0.026,-0.038l0.033,-0.043l0.132,-0.194l0.068,-0.097l0.012,-0.02c0.077,-0.12 0.151,-0.243 0.222,-0.369l0.166,-0.313l0.011,-0.025l0.011,-0.021l0.042,-0.092l0.086,-0.185l0.02,-0.051l0.019,-0.042l0.037,-0.095l0.057,-0.143l0.028,-0.08l0.025,-0.064l0.026,-0.084l0.039,-0.111l0.032,-0.113l0.027,-0.084l0.017,-0.066l0.024,-0.083l0.035,-0.152l0.026,-0.1l0.008,-0.047l0.013,-0.055l0.037,-0.205l0.02,-0.104l0.003,-0.024c0.019,-0.117 0.035,-0.235 0.047,-0.354l0.004,-0.04l-0.004,0.04c-0.012,0.119 -0.028,0.237 -0.047,0.354l0.051,-0.394l-0.051,0.394l-0.023,0.128l-0.05,0.26l-0.034,0.147l-0.059,0.235l-0.044,0.15l-0.071,0.224l-0.051,0.148l-0.085,0.223l-0.056,0.137l-0.106,0.236l-0.053,0.113l-0.177,0.338l-0.222,0.369l-0.08,0.117l-0.165,0.237l-0.101,0.133l-0.164,0.206l-0.115,0.133l-0.171,0.189l-0.124,0.128l-0.182,0.178l-0.129,0.12l-0.2,0.171l-0.129,0.106l-0.231,0.173l-0.113,0.083l-0.36,0.236l-0.678,-0c2.231,-1.088 3.77,-3.381 3.77,-6.029c-0,-3.587 -2.821,-6.519 -6.363,-6.699l-0.141,-0.004l-0,-4.229Z"]`

but it did not work, if you're able to see what I've done wrong i would appreciate the feedback so I'm able to create / test future icons 

Thanks!

**Comment by elax46** [comment]
from the tests done it seems to me that both icons are working

**Comment by elax46** [comment]
the icon will be available in the next update
