### ISSUE TITLE
Custom Icon request - neophos washing tabs

### ISSUE THREAD

**Issue by zurwaq** [elax46/custom-brand-icons#800]
if possible please make this, otherwise, i will try to make one next week.

**Comment by rchiileea** [comment]
Well I hope if you do make one you read the guidelines for doing this, but washing tabs is a bit out of the smart home related world though is it... please read rules anyway.

**Comment by zurwaq** [comment]
I have an automation that count the tabs and give me a notifikation when im about to run out of them. :)
