### ISSUE TITLE
Custom Icon request - Mi Bedside Lamp 2

### ISSUE THREAD

**Issue by MStankiewiczOfficial** [elax46/custom-brand-icons#801]
![obraz](https://mi-home.pl/cdn/shop/products/2691_mibedsidelamp2-800px-hero_4fb17125-e19e-4251-a754-7135047a94e2.png)

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/b9d5796d-4a0e-4a93-8fc3-e43bc65bb226)
