### ISSUE TITLE
Custom Icon request [Bulb Refresh]

### ISSUE THREAD

**Issue by AshGSmith** [elax46/custom-brand-icons#803]
![reload](https://github.com/user-attachments/assets/89395327-9d05-4504-a50d-3413a36a5710)
**links will be ignnored please upload icon/image**

**Again read main rules, Also I will point out low quality images of products will be ignored, if you can not be bothered to search we wont either**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/b2d15ae5-de88-4d88-a837-d1f431ee00f5)
