### ISSUE TITLE
Custom Icon request Avito without title

### ISSUE THREAD

**Issue by alxpk91** [elax46/custom-brand-icons#804]
![368703765-4c4d68a2-12e9-4d8c-b88d-303b0602e920](https://github.com/user-attachments/assets/ad71b6f9-7238-4a7d-9556-3ddcab926dba)

**Comment by rchiileea** [comment]
well you should of really said that in your first request.

**Comment by alxpk91** [comment]
I added comment in first request, but it was closed

**Comment by rchiileea** [comment]
yes you added the comment after logo was created bud, next time you submit a logo please be more specific as this is done in our spare time.

**Comment by alxpk91** [comment]
Hi, okay, I'll keep that in mind for the future.
