### ISSUE TITLE
Custom Icon request Plexamp

### ISSUE THREAD

**Issue by chicco-carone** [elax46/custom-brand-icons#805]
![Plexamp](https://github.com/user-attachments/assets/5f2e60a5-fabd-4c49-90c1-bc4f3311682e)

**Comment by chicco-carone** [comment]
Are there any issues that are preventing this from getting added?

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/14880db3-6759-40d8-87d1-385232d551c0)
