### ISSUE TITLE
icon sometimes not visable on google hub

### ISSUE THREAD

**Issue by EyeVisionsNL** [elax46/custom-brand-icons#807]
Good day everyone,
I'm having something strange with the custom icons when I play a dashboard on my Google Hub. The strange thing is I have a dashboard with mushroom cards and other things that works just fine and shows all the icons. But on my dashboard with a map and using the normal card picture with elements they don't show.? This only happens on teh google hub al other devices show the icons correctly.

anybody any ideas?

**Comment by rchiileea** [comment]
its the cache of google hub I believe, it does not update often enough.
