### ISSUE TITLE
Custom Icon request: Fox ESS

### ISSUE THREAD

**Issue by adamlc** [elax46/custom-brand-icons#808]
I'd like to request a logo for Fox ESS please!

SVG:

![FOX_ESS_Logo](https://github.com/user-attachments/assets/d279123e-a34f-45f4-8926-e94725296c3b)

JPG:

![FoxESS](https://github.com/user-attachments/assets/9de283e3-270c-4566-9237-63889acaf323)

Edit: Sorry it includes the text. Ideally just the logo please.

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/dd0a67f4-0b20-4c30-aea0-223f943dad91)
