### ISSUE TITLE
Custom Icon request - Deezer new logo

### ISSUE THREAD

**Issue by Suelis** [elax46/custom-brand-icons#809]
Hi,
There is a Deezer logo in the libraray but they changed it. Could you please add the new one :

![DEEZR PA](https://github.com/user-attachments/assets/2d61e9b1-81b3-4900-973c-0b7776e6878a)

Thanks for your amazing work 👍

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/00b67ca0-e90d-486b-8af6-4c7774d5e172)

**Comment by Suelis** [comment]
Thanks !
