### ISSUE TITLE
Update to Jellyseer icon

### ISSUE THREAD

**Issue by Bretterteig** [elax46/custom-brand-icons#810]
Jellyseerr updated their logo a while ago. Here you go:

![logo_full](https://github.com/user-attachments/assets/2faa2aac-3701-4635-98e5-e91cbddeafbd)

Thank you

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/d1b944ab-6992-4acc-9000-3f2da394aaba)
