### ISSUE TITLE
Custom Icon request - Systemair SAVE

### ISSUE THREAD

**Issue by ricmik** [elax46/custom-brand-icons#813]
These icons are used for showing state for a Systemair SAVE ventilation unit.

From left to right: 
- Free cooling
- Heater
- Heat Exchanger
- Moisture Transfer
- Cooker Hood

![ezgif-1-4db0ddf193](https://github.com/user-attachments/assets/05b6e0d6-affa-4235-95bf-8800d0ed2e9a)

**Comment by rchiileea** [comment]
when i get round to have the time ill do this but one icon of the unit, you can use color of icon to change what its doing in  home assistant.

**Comment by ricmik** [comment]
Thanks!

While changing the color would work for some functions, some functions can be active at the same time. 

For example heat exchanger and cooker hood can be active at the same time.

**Comment by rchiileea** [comment]
secondry info in a custom button card will work for two examples, I would be quite happy to share the code.

![image](https://github.com/user-attachments/assets/7f2b1be8-ed3d-47f2-9264-52a4ecde1ba2)
![image](https://github.com/user-attachments/assets/71d2c173-f69f-419c-b51d-88f8ac920caf)
![image](https://github.com/user-attachments/assets/c8cc64fc-3fc1-4d9d-94c9-719bcf90bd5e)

many options availible

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/2bd2d326-e117-4d03-a179-2a0f82daa905)

**Comment by ricmik** [comment]
Hi! I was hoping to get the state icons from the first post (not the Systemair logo)🙂
