### ISSUE TITLE
Litter Robot Icon

### ISSUE THREAD

**Issue by Waank1** [elax46/custom-brand-icons#814]
![LR](https://github.com/user-attachments/assets/5f2731cb-cb14-4925-9702-d01d2cdff6c7)
![LR](https://github.com/user-attachments/assets/f010af9f-fa5c-4981-b6d3-4829a4346c48)

I hope I have done this correctly, I have the litter robot app installed in my home assistant, but can't seem to pull the icon out of the file.

**links will be ignnored please upload icon/image**

**Again read main rules, Also I will point out low quality images of products will be ignored, if you can not be bothered to search we wont either**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/9d76c90f-fec0-487d-8b4c-4bf3c780a0c7)

**Comment by Waank1** [comment]
Awesome! TYVM!
