### ISSUE TITLE
Icons not appearing when using a shortcut created in companion app

### ISSUE THREAD

**Issue by ukmgranger** [elax46/custom-brand-icons#815]
**Describe the bug**
I'm using the icons in the Custom Remote Card.  I have created a shortcut in the Companion App, and when I launch the shortcut that takes me directly to the remote card, all the PHU icons are missing.  I have added two screenshots.  I have circled the missing icons.

Also - when I access the card by opening the companion app and navigating to the card, the icons show as normal.

![image](https://github.com/user-attachments/assets/3aaa53d6-ea7e-4f68-a3bf-f2f18dd8ac7c)
![image](https://github.com/user-attachments/assets/f6968a99-a773-422d-958c-443d24718db7)

I'm using HA 2024.11.0b1
Android 15
Latest version of the companion app

## Don't see the icon?

It probably depends on the cache. Open Home assistant from an incognito window and check that the icon loads if yes then it depends on the cache, otherwise double check the installation

**Comment by elax46** [comment]
Unfortunately these problems that arise with companion applications or even with the HA itself and HA iOS and Android application depend on the cache management
