### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by Pr3mut05** [elax46/custom-brand-icons#816]
IKEA FÖRNUFTIG
Luftreiniger/air purifier

![foernuftig-luftreiniger-weiss__0832294_pe777645_s5](https://github.com/user-attachments/assets/778a7a33-1499-449d-91dc-d5380dd53452)

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/6ffc020c-03ff-4f75-b5dd-3b8fe0a5f3a0)
