### ISSUE TITLE
Custom Icon request Ikea HÖGVIND 

### ISSUE THREAD

**Issue by ArthFink** [elax46/custom-brand-icons#817]
Ikea HÖGVIND 
Tischleuchte, vernickelt/grau Glas

![hoegvind-tischleuchte-vernickelt-grau-glas__1300598_pe937151_s5](https://github.com/user-attachments/assets/0b47c787-69fb-4090-b33b-183c9c8fb1c7)

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/4010add7-7fb9-4e6f-a597-cfbb36b52cdd)

**Comment by ArthFink** [comment]
Thanks, great work!
