### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by ArthFink** [elax46/custom-brand-icons#818]
Ikea HADDEBO
Ceiling Lamp

![haddebo-aufhaengung-3-fach-schwarz__0988567_pe818162_s5 (1)](https://github.com/user-attachments/assets/899a7d9a-616c-4d93-9c5e-a74804bb5af1)

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/56c71313-82fe-49e3-b097-f2d73649f1d0)

**Comment by ArthFink** [comment]
Thanks, great work!
