### ISSUE TITLE
Custom Icon request - IKEA Kallax

### ISSUE THREAD

**Issue by c0nt4x** [elax46/custom-brand-icons#819]
Whilst not a 'smart' device I have a few of these about the house and they have multiple smart lights on each. Each unit is set up as a light group so it would be good to have this icon to represent the light group.

<img width="440" alt="Screenshot 2024-11-06 at 13 03 27" src="https://github.com/user-attachments/assets/12f5c86c-7693-4873-a6bb-5a2196824ab3">

<img width="359" alt="Screenshot 2024-11-06 at 13 02 51" src="https://github.com/user-attachments/assets/d3a8d94c-2ba8-4160-9381-02c2783859c2">

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/d5e480ac-05fc-4f59-9374-1086f2186d60)
![image](https://github.com/user-attachments/assets/f47026c0-fece-420a-8d14-9c4a4e054c7b)
![image](https://github.com/user-attachments/assets/b8ef2fd9-fe57-407b-ac78-d286111bee98)
![image](https://github.com/user-attachments/assets/1526dae4-7fc3-4a91-9cc8-b5ccd290b377)
![image](https://github.com/user-attachments/assets/d1bca74f-456b-4ffd-b2aa-f360c3b45516)
![image](https://github.com/user-attachments/assets/5351303d-30d8-443c-ad5c-92185a866d65)

**Comment by c0nt4x** [comment]
@elax46  The icon ikea-kallax8 was not included with the latest integration update.

Thanks for your work on these.

**Comment by elax46** [comment]
> @elax46 The icon ikea-kallax8 was not included with the latest integration update.
> 
> Thanks for your work on these.

yes we know there was a problem with the code
