### ISSUE TITLE
Custom Icon request - Litter Robot

### ISSUE THREAD

**Issue by dejatesting2** [elax46/custom-brand-icons#821]
Any chance to get an icon for the Litter Robot 4? The integration has one for Firmware entity but its not settable for the actual "vacuum" entity.

**Comment by dejatesting2** [comment]
![5348052](https://github.com/user-attachments/assets/47931f0f-4b4f-4ea3-82ca-8fd7925f3cbd)
Image

**Comment by rchiileea** [comment]
Vacuum????

**Comment by dejatesting2** [comment]
It's purrfect
