### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by ElPapiMango** [elax46/custom-brand-icons#824]
Hi

I made an icon for a Moes 4 gang wall switch. SKU: ZT-SY-EU1S-WH-MS

I used affinity designer and its kind of large file size and not sure how to optimize it. Its based on icon-svg/moes-switch-dual.svg but without logo (couldnt fit it).
![moes-switch-quad](https://github.com/user-attachments/assets/34b47428-7def-4dac-8f68-e45c4ef3a9b1)

**Comment by rchiileea** [comment]
you need to re upload this its showing as txt

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/a5fee172-6ad8-43bd-bbdb-bc6ecf91a655)
