### ISSUE TITLE
Robinhood

### ISSUE THREAD

**Issue by sourpatchdad** [elax46/custom-brand-icons#826]
The Similarweb rank is 1,603. Please see https://www.similarweb.com/website/robinhood.com/

(New) Branding - https://newsroom.aboutrobinhood.com/a-new-visual-identity/
Color - #CCFF00

![robinhood](https://github.com/user-attachments/assets/5a7a296a-3714-4ba4-b8a8-b482823adb13)
![robinhood](https://github.com/user-attachments/assets/2e660753-81df-4514-8e1e-352446b61f62)

**Comment by rchiileea** [comment]
![image](https://github.com/user-attachments/assets/5b8eb877-52ca-4c97-8445-990c50e300d1)
