### ISSUE TITLE
Sonos and otherS done

### ISSUE THREAD

**Issue by rchiileea** [elax46/custom-brand-icons#83]
**Sonos**

![image](https://user-images.githubusercontent.com/87599807/142921414-e8c7f094-9023-4471-9758-a5112bb55043.png)
![image](https://user-images.githubusercontent.com/87599807/142921518-72c8bc90-a974-45fa-830b-51c1697fcc52.png)
![image](https://user-images.githubusercontent.com/87599807/142921552-96bd7040-957d-43d3-a8e5-5dc18bebdb77.png)
![image](https://user-images.githubusercontent.com/87599807/142921579-37f5e56a-f7f1-4c73-adfc-82537f4a2915.png)
![image](https://user-images.githubusercontent.com/87599807/142921609-35ef74fb-a2f3-4882-9958-3c8fb5c2f504.png)

[sonos.zip](https://github.com/elax46/custom-brand-icons/files/7583782/sonos.zip)

**Others**

echo dot clock
![image](https://user-images.githubusercontent.com/87599807/142921749-8d2f8f08-ac66-4b08-86df-609e412d7890.png)
(just added clock face to your one)

ikea 5 spot ceiling
![image](https://user-images.githubusercontent.com/87599807/142921802-3874ffc6-843b-4da3-8574-e3209da4cfa7.png)

ikea blind
![image](https://user-images.githubusercontent.com/87599807/142921950-5797fd04-da05-4628-adbd-e0818b20c23d.png)
![image](https://user-images.githubusercontent.com/87599807/142921921-d03ac0d6-c567-4a48-a136-ebd928dcb4db.png)

shed/Garage open and close

![image](https://user-images.githubusercontent.com/87599807/142922036-6f02978b-089c-4eb1-b2e9-202fef650d76.png)
![image](https://user-images.githubusercontent.com/87599807/142922060-93b54833-f6d5-48fc-9f64-5d032962398d.png)

Light shade, ones i have in my own home
![image](https://user-images.githubusercontent.com/87599807/142922131-ab462329-c8bb-4fae-be57-e4c8ebc873e1.png)

[new none sonos.zip](https://github.com/elax46/custom-brand-icons/files/7583800/new.none.sonos.zip)

**Comment by elax46** [comment]
The sonos playbar was not present in previous packages

**Comment by rchiileea** [comment]
> 

![image](https://user-images.githubusercontent.com/87599807/143016591-04fa3f7c-4314-4305-ad73-4181a5be245f.png)
 
i saw it there thats why I done it

**Comment by elax46** [comment]
I meant that you have not loaded the icons of the shelf or the playbar

**Comment by rchiileea** [comment]
there are two zips above sonos.zip and none sonos.zip

inside sonos.zip i download again and i see

![image](https://user-images.githubusercontent.com/87599807/143019195-1b9a73d8-84d1-46b8-8fb0-f48e02e0db66.png)

**Comment by elax46** [comment]
I'm sorry I didn't see it
