### ISSUE TITLE
Updated BBC icon

### ISSUE THREAD

**Issue by scottcawley** [elax46/custom-brand-icons#832]
Would it be possible to update the BBC logo please?

The typeface has slightly changed in the last few years, but also the existing image you use is slightly the wrong proportions and the “blocks” are stretched to the wrong shape.

Attached is the current logo. Many thanks. 
![IMG_4561](https://github.com/user-attachments/assets/9cfd8671-621f-4dc3-80b4-6aa32cb26c21)

**Comment by rchiileea** [comment]
it was in last release

**Comment by scottcawley** [comment]
Forgive me if I am being stupid, but I think that's incorrect.  [A quick look at the library shows the old logo](https://elax46.github.io/custom-brand-icons/?search=bbc) (the squashed one), but not the new one included in my post above.

I think there may be a misunderstanding and confusion with the other BBC logo that was recently added - one also shown on the library page - for BBC Radio 2.

As well as the generic BBC logo above which may be useful, it would also be good to add the logos for the separate BBC streaming services for video and audio, which may be helpful icons for people like myself who are trying to set up buttons on remotes etc.

Thank you.

![BBC_iPlayer_Stacked_White_RGB_HR](https://github.com/user-attachments/assets/3a7080e4-3a90-4964-83bf-4abb799343e3)
![BBC_Sounds_Stacked_White_RGB_HR](https://github.com/user-attachments/assets/f73e85e1-464a-404e-b0bc-cc882b7aa0b2)
