### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by Audielite** [elax46/custom-brand-icons#840]
**links will be ignnored please upload icon/image**

**Again read main rules, Also I will point out low quality images of products will be ignored, if you can not be bothered to search we wont either**

**off-type icons will not be accepted, Home Assistant makes it visible when an entity is on or off, it is useless to weigh down the library**

![6F59D498-6F0E-466F-ADC2-3FCC04F5484D](https://github.com/user-attachments/assets/82882e51-0167-49c3-a0b6-a98592005adb)

Thank you!

**Comment by rchiileea** [comment]
We already have the disney icon in the repo as a D with the + sign, as we had this ocon before and it did not suit well in cards etc due to size

**Comment by Audielite** [comment]
Hi @rchiileea, when I search for it I cannot find it.
