### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by alasdairnott** [elax46/custom-brand-icons#85]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

**Additional context**

Can you please create an icon from the attached? 

It's for Proxmox Virtual Environment

[proxmox.zip](https://github.com/elax46/custom-brand-icons/files/7595665/proxmox.zip)

**Comment by elax46** [comment]
the icon does not have any kind of viewBox

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/143301160-a6d235cc-07ce-4867-b527-5f9549ca06e6.png)
 
wont be ready for a little while I have my other hardware branding ones to do before handing over the list, this one was a quick conversion for me. (like 5 secs)

**Comment by elax46** [comment]
when you are ready we will add it

**Comment by alasdairnott** [comment]
Thanks so much!

**Comment by elax46** [comment]
the icon will be available
