### ISSUE TITLE
Custom Icon request

### ISSUE THREAD

**Issue by rchiileea** [elax46/custom-brand-icons#86]
**New icons**

**### Replacement for nvidia sheild**
![image](https://user-images.githubusercontent.com/87599807/143681782-cda205fd-8170-48b5-ab62-7d4fcaa8e555.png)
updated nvidia-shield

**### Replacement for ikea ones**
![image](https://user-images.githubusercontent.com/87599807/143681672-7a6b4a3d-64a1-42cd-afaf-b796e9bc930e.png)
updated ikea 5 spot

![image](https://user-images.githubusercontent.com/87599807/143681699-5aff6283-ad03-49b5-8276-62d1a37519d4.png)
updated ikea blind open

![image](https://user-images.githubusercontent.com/87599807/143681715-828c4160-6505-4266-99a8-febcb11a6728.png)
updated ikea blind closed

**added icons**

![image](https://user-images.githubusercontent.com/87599807/143681767-b50dabfc-8e5e-4b68-b837-cf212a3da25c.png)
raspberry

![image](https://user-images.githubusercontent.com/87599807/143681746-889c9a80-cb92-46cd-b5e3-d0dda9871e3c.png)
ha-blue

![image](https://user-images.githubusercontent.com/87599807/143681832-7ac0bfe4-200e-461a-9432-fdd763952eeb.png)
intel nuc

![image](https://user-images.githubusercontent.com/87599807/143681730-bbe54f3c-2852-4d5e-abf3-b0ec72255d27.png)
computer

![image](https://user-images.githubusercontent.com/87599807/143682308-bf74b2fa-ba0e-440b-974c-78309df9d608.png)
proxmax
[updates.zip](https://github.com/elax46/custom-brand-icons/files/7611741/updates.zip)

**Comment by rchiileea** [comment]
added proxmax one nearly forgot lol

**Comment by elax46** [comment]
the icon will be available
