### ISSUE TITLE
spot-bulb-top icon is off-center

### ISSUE THREAD

**Issue by SAOPP** [elax46/custom-brand-icons#9]
spot-bulb-top icon is off-center in light card, example below:

![image](https://user-images.githubusercontent.com/5647009/121604150-b0f66980-ca52-11eb-8a22-8bd9ab3b283f.png)

**Comment by elax46** [comment]
I just released a corrective version

**Comment by SAOPP** [comment]
By the way, pay attention, several new icons had a similar problem there ...

**Comment by SAOPP** [comment]
![Uploading image.png…]()

**Comment by SAOPP** [comment]
Actually, NAS too

**Comment by elax46** [comment]
I fixed them all, clear your browser cache

**Comment by SAOPP** [comment]
Well, I just told you, I was sure that you fixed it. :)
