### ISSUE TITLE
Please, add any UPS icon

### ISSUE THREAD

**Issue by Spirituss** [elax46/custom-brand-icons#90]
It would be great to have some UPS icons, such as “classic” ups, like this

![image](https://user-images.githubusercontent.com/47206760/143779072-8bcd23e6-9383-4f65-a6ae-729d906a7d91.jpeg)

and “home appliance”, like this

![](https://static.onlinetrade.ru/img/items/b/apc_back_ups_es_400va_be400_rs__6.jpg)

**Comment by rchiileea** [comment]
Started a Schneider electric brand which covers a lot of things including apc ups 

![image](https://user-images.githubusercontent.com/87599807/144042760-6e47d12a-6ed0-4a97-915f-7d2ae639c1aa.png)
![image](https://user-images.githubusercontent.com/87599807/144042835-6e814c85-aa48-48ae-921f-b2fa70c05df8.png)

also will include wiser heating items too
![image](https://user-images.githubusercontent.com/87599807/144043093-5cc4e5c3-d371-4ed6-a793-2667df78b08d.png)
![image](https://user-images.githubusercontent.com/87599807/144043148-db582473-0c63-46dc-b0eb-09671b125ca7.png)

![image](https://user-images.githubusercontent.com/87599807/144043202-aad40374-5985-42f5-9c46-84c4dc8ab641.png)
![image](https://user-images.githubusercontent.com/87599807/144043258-2fa93204-ca5f-4f80-b1af-45be22477d7a.png)
