### ISSUE TITLE
Custom Icon request [tapo-p100-tplink]

### ISSUE THREAD

**Issue by Knot83** [elax46/custom-brand-icons#94]
[**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**](https://www.amazon.it/gp/product/B07Z5JD3T4/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&th=1)

**Additional context**

**Comment by Knot83** [comment]
Sorry but I don't have enough time right now to work on making an SVG. That's why I added the Amazon link of the Smart Plug request.

Thanks for understanding

**Comment by rchiileea** [comment]
this will have to wait until I move onto the brand to be honest as there are many tp link items and I just would not want to make 1 icon :) but I will get to the brand some time.

**Comment by rchiileea** [comment]
![image](https://user-images.githubusercontent.com/87599807/147657910-a97d918a-cc19-4686-9bc7-ac9a6a7046a0.png)
will be added soon
