### ISSUE TITLE
Cyberpower UPS - PowerPanel Software Logo

### ISSUE THREAD

**Issue by myopenflixr** [elax46/custom-brand-icons#96]
https://drive.google.com/file/d/1mYaDqkxYtqFfoTvbEyOcL5C4Sr9FpYTB/view?usp=sharing

Hi, this is a logo that I would like to see integrated. It's the logo for the PowerPanel software used to manage Cyberpower UPS units.

Hopefully the logo will work for you. I tried creating this myself in inkscape with no luck. I have almost zero experienced with image editors.

Thank You for your consideration!

**Comment by elax46** [comment]
Thanks for your request the icon has been integrated into the dev branch and will be available in the next release

**Comment by myopenflixr** [comment]
@elax46 I manually added the new line to my `custom-brand-icons.js` file and the icon is not showing as available in Home Assistant. I've refreshed browser, cleared cookies, and restarted Home Assistant with no luck.

Here's the line I added right below `reolink-go`

`"power-panel-logo":[0,0,24,24,"M98,100c-2.609.741-3.207,1.57-5,3v1H91v1H89v1H86v1H83v1c-3.535,1.11-9.97-.383-12-1H66c-10.044-3.854-22.067-18.389-17-34V69h1l2-6,2-1,3-4,3-2V54l2-1V34c-1.139-1.139-.4,0-1-2H60c-2.671,3.042-7.629,3.616-11,6L34,54l-1,4H32l-1,4H30v3H29v2H28l-1,70c-4.962-1.316-7.326-6.276-10-10l-4-3v-2l-2-1-1-4-2-1-3-9H4C0.661,98.548,0,89.777,0,78V62H1V58H2V54H3V51H4V48H5V45l2-1V42H8V40H9V38h1V36l3-2V32l3-2V28l4-3,7-8h2l2-3h2l2-3h2V10h2V9h2V8h2V7h2V6h2V5l6-1V3h3V2c3.97-1.393,25.016-3.745,31-2V1h5V2h5V3h2V4h3V5h3V6h2V7l9,3,1,2h2v1l3,1,1,2h2l16,17v2l2,1q0.5,2,1,4h1v2h1q1,3,2,6h1v3h1v2h1v5c3.121,9.875,4.578,26.062,1,37v4h-1v2h-1v4l-2,1v3h-1q-0.5,2.5-1,5c-14.6,23.75-37.513,42.149-76,42a13.307,13.307,0,0,0-3-4V129c4.537-1.689,12.853-1.05,19-1v-1l7-1v-1h3v-1l6-2q0.5-1,1-2h2q0.5-1,1-2h2l3-4,2-1v-2l4-3,7-14c0.9-2.55,2.1-20.258,1-24h-1V65h-1V63h-1V60h-1q-1-3-2-6h-1V52l-4-3V47l-2-1-4-5h-2l-1-2L92,32v2c-1.619,1.69-1.594,17.294,0,19,0.968,3.459,3.808,5.674,6,8l2,1v2l2,1q0.5,2,1,4h1v3h1v5h1q-0.5,5-1,10h-1v4l-2,1v3h-1C99.605,96.863,98.733,97.34,98,100ZM86,18H67c-1.77,4.827-1,13.55-1,20V77c4.537,1.689,12.853,1.049,19,1,1.77-4.827,1-13.55,1-20V18Z"],`

Any suggestions?

Thank you.

**Comment by myopenflixr** [comment]
I actually got this to work. I had to make a slight change as follows:
Original = `"power-panel-logo":[0,0,24,24`
Corrected = `"power-panel-logo":[0,0,157,162`

**Comment by elax46** [comment]
thanks for letting me know the value to insert depends on the viewBox of the icon

**Comment by elax46** [comment]
@myopenflixr i released a pre-version you can install it from HACS

**Comment by myopenflixr** [comment]
Just downloaded 1.0.45b and seems to be working well! Cleared cache and cookies and icon is working
