### ISSUE TITLE
Custom Icon request - Tesla

### ISSUE THREAD

**Issue by chester512** [elax46/custom-brand-icons#99]
**Insert a link to an SVG icon the integrable icons are ONLY in SVG format**

https://iconscout.com/icon/tesla-14

**Additional context**

**Comment by rchiileea** [comment]
Actually just finishing up on some tesla ones so your timing is good 

![image](https://user-images.githubusercontent.com/87599807/145705671-f37d691e-cb04-4e04-80e9-beeda25de960.png)
![image](https://user-images.githubusercontent.com/87599807/145705673-3d658f77-c72a-4b66-a007-59a287049b29.png)
![image](https://user-images.githubusercontent.com/87599807/145705677-53cf8e6e-80d6-48ba-8740-06c58a0f3e65.png)
![image](https://user-images.githubusercontent.com/87599807/145705681-d8fcf2db-29d9-47b5-9e21-67ff052b152b.png)
![image](https://user-images.githubusercontent.com/87599807/145705683-1305177e-3bfe-4e2f-aab7-40033d23dee5.png)
![image](https://user-images.githubusercontent.com/87599807/145705686-8c3600e3-5121-409f-aef3-a5125254ab91.png)
![image](https://user-images.githubusercontent.com/87599807/145705692-2cb0c263-1721-4825-8b91-300f57074e0e.png)
